import { getPersistedLanguage } from './tr';

const az = {
  loginTitle: 'Reytinqə qoşul', loginDescription: 'Oyunçu adlarını görmək və xalını reytinqə yazmaq üçün hesabına daxil ol.',
  login: 'Hesaba daxil ol', loadingError: 'Reytinq yüklənmədi', loadingDescription: 'Şəbəkəni və giriş sessiyanı yoxlayıb yenidən cəhd et.',
  retry: 'Yenidən yoxla', localOnly: 'Xal bu cihazda saxlanıldı. Reytinq üçün hesabına daxil ol.',
  failed: 'Xal cihazda saxlanıldı, amma reytinqə göndərilmədi.', accountChanged: 'Hesab dəyişib. Bu nəticə başqa hesaba göndərilmədi.',
  saved: 'Xal reytinqə yazıldı', serverUpdate: 'Reytinq xidməti yenilənməlidir. Xal cihazda saxlanılıb.',
};
type Copy = Record<keyof typeof az,string>;
const copies: Record<string,Copy> = {
  az,
  en: { loginTitle:'Join the leaderboard',loginDescription:'Sign in to see player names and add your score to the leaderboard.',login:'Sign in',loadingError:'Leaderboard could not load',loadingDescription:'Check your connection and sign-in session, then try again.',retry:'Try again',localOnly:'Your score is saved on this device. Sign in to join the leaderboard.',failed:'Your score is saved locally, but was not sent to the leaderboard.',accountChanged:'The account changed. This result was not sent to another account.',saved:'Score added to the leaderboard',serverUpdate:'The leaderboard service needs an update. Your score is saved locally.' },
  tr: { loginTitle:'Sıralamaya katıl',loginDescription:'Oyuncu adlarını görmek ve puanını sıralamaya eklemek için hesabına giriş yap.',login:'Giriş yap',loadingError:'Sıralama yüklenemedi',loadingDescription:'Bağlantını ve giriş oturumunu kontrol edip tekrar dene.',retry:'Tekrar dene',localOnly:'Puanın bu cihazda kaydedildi. Sıralama için giriş yap.',failed:'Puanın cihazda kaydedildi ancak sıralamaya gönderilemedi.',accountChanged:'Hesap değişti. Bu sonuç başka hesaba gönderilmedi.',saved:'Puan sıralamaya eklendi',serverUpdate:'Sıralama hizmeti güncellenmeli. Puanın cihazda kayıtlı.' },
  ru: { loginTitle:'Присоединиться к рейтингу',loginDescription:'Войдите в аккаунт, чтобы видеть имена игроков и добавлять свои очки в рейтинг.',login:'Войти',loadingError:'Рейтинг не загрузился',loadingDescription:'Проверьте подключение и вход в аккаунт, затем повторите попытку.',retry:'Повторить',localOnly:'Очки сохранены на устройстве. Войдите, чтобы добавить их в рейтинг.',failed:'Очки сохранены на устройстве, но не отправлены в рейтинг.',accountChanged:'Аккаунт изменился. Результат не отправлен в другой аккаунт.',saved:'Очки добавлены в рейтинг',serverUpdate:'Сервис рейтинга требует обновления. Очки сохранены на устройстве.' },
  de: { loginTitle:'An der Rangliste teilnehmen',loginDescription:'Melde dich an, um Spielernamen zu sehen und deine Punkte in die Rangliste einzutragen.',login:'Anmelden',loadingError:'Rangliste nicht geladen',loadingDescription:'Prüfe deine Verbindung und Anmeldung und versuche es erneut.',retry:'Erneut versuchen',localOnly:'Deine Punkte sind auf diesem Gerät gespeichert. Melde dich für die Rangliste an.',failed:'Deine Punkte sind lokal gespeichert, wurden aber nicht an die Rangliste gesendet.',accountChanged:'Das Konto hat sich geändert. Dieses Ergebnis wurde nicht an ein anderes Konto gesendet.',saved:'Punkte zur Rangliste hinzugefügt',serverUpdate:'Der Ranglistendienst muss aktualisiert werden. Deine Punkte sind lokal gespeichert.' },
  ar: { loginTitle:'انضم إلى لوحة الترتيب',loginDescription:'سجّل الدخول لرؤية أسماء اللاعبين وإضافة نقاطك إلى لوحة الترتيب.',login:'تسجيل الدخول',loadingError:'تعذّر تحميل الترتيب',loadingDescription:'تحقق من الاتصال وجلسة تسجيل الدخول ثم حاول مرة أخرى.',retry:'حاول مرة أخرى',localOnly:'حُفظت نقاطك على هذا الجهاز. سجّل الدخول للانضمام إلى الترتيب.',failed:'حُفظت النقاط على الجهاز، لكن لم تُرسل إلى الترتيب.',accountChanged:'تغيّر الحساب. لم تُرسل هذه النتيجة إلى حساب آخر.',saved:'أُضيفت النقاط إلى الترتيب',serverUpdate:'تحتاج خدمة الترتيب إلى تحديث. نقاطك محفوظة على الجهاز.' },
  kk: { loginTitle:'Рейтингке қосылу',loginDescription:'Ойыншылардың аттарын көру және ұпайыңызды рейтингке қосу үшін аккаунтыңызға кіріңіз.',login:'Кіру',loadingError:'Рейтинг жүктелмеді',loadingDescription:'Байланыс пен аккаунтқа кіру күйін тексеріп, қайталап көріңіз.',retry:'Қайталау',localOnly:'Ұпайыңыз осы құрылғыда сақталды. Рейтингке қосылу үшін кіріңіз.',failed:'Ұпай құрылғыда сақталды, бірақ рейтингке жіберілмеді.',accountChanged:'Аккаунт өзгерді. Бұл нәтиже басқа аккаунтқа жіберілмеді.',saved:'Ұпай рейтингке қосылды',serverUpdate:'Рейтинг қызметін жаңарту қажет. Ұпайыңыз құрылғыда сақталған.' },
  uz: { loginTitle:'Reytingga qo‘shilish',loginDescription:'O‘yinchilar ismlarini ko‘rish va ballingizni reytingga qo‘shish uchun hisobingizga kiring.',login:'Hisobga kirish',loadingError:'Reyting yuklanmadi',loadingDescription:'Ulanish va kirish seansini tekshirib, yana urinib ko‘ring.',retry:'Qayta urinish',localOnly:'Ballingiz shu qurilmada saqlandi. Reyting uchun hisobga kiring.',failed:'Ball qurilmada saqlandi, ammo reytingga yuborilmadi.',accountChanged:'Hisob o‘zgardi. Bu natija boshqa hisobga yuborilmadi.',saved:'Ball reytingga qo‘shildi',serverUpdate:'Reyting xizmati yangilanishi kerak. Ballingiz qurilmada saqlangan.' },
  ka: { loginTitle:'შეუერთდი რეიტინგს',loginDescription:'მოთამაშეთა სახელების სანახავად და ქულის რეიტინგში დასამატებლად შედი ანგარიშში.',login:'ანგარიშში შესვლა',loadingError:'რეიტინგი ვერ ჩაიტვირთა',loadingDescription:'შეამოწმე კავშირი და ანგარიშში შესვლა, შემდეგ სცადე ხელახლა.',retry:'ხელახლა ცდა',localOnly:'ქულა ამ მოწყობილობაზე შეინახა. რეიტინგისთვის შედი ანგარიშში.',failed:'ქულა მოწყობილობაზე შეინახა, მაგრამ რეიტინგში ვერ გაიგზავნა.',accountChanged:'ანგარიში შეიცვალა. შედეგი სხვა ანგარიშზე არ გაგზავნილა.',saved:'ქულა რეიტინგს დაემატა',serverUpdate:'რეიტინგის სერვისს განახლება სჭირდება. ქულა მოწყობილობაზე შენახულია.' },
};
export function gameScoreMessage(key: keyof Copy) { return (copies[getPersistedLanguage()] ?? copies.az)[key]; }
