-- ============================================================
-- GurcuFix5 — baby_names_db: gürcü adları dəsti (lang='ka')
-- PROBLEM: ka dilində ad siyahısı YOX idi — KA istifadəçilər ya AZ
-- adlarını (köhnə build) ya da boş siyahı görürdü.
-- Format OzbekFix5 (uz seed) ilə eynidir: WHERE NOT EXISTS (name+lang) — idempotent.
-- 80 ad: 40 qız + 40 oğlan, adlar Mxedruli qrafikası ilə, mənalar gürcü dilində.
-- Sütunlar: origin_ka/meaning_ka Gurcu1-də əlavə olunub.
-- ============================================================

-- ── Qız adları (40) ──
INSERT INTO public.baby_names_db (name, gender, origin, meaning, origin_ka, meaning_ka, popularity, is_active, lang) SELECT 'ნინო', 'girl', 'ქართული', 'ქართველთა განმანათლებლის, წმინდა ნინოს სახელი', 'ქართული', 'ქართველთა განმანათლებლის, წმინდა ნინოს სახელი', 99, true, 'ka' WHERE NOT EXISTS (SELECT 1 FROM public.baby_names_db WHERE name = 'ნინო' AND lang = 'ka');
INSERT INTO public.baby_names_db (name, gender, origin, meaning, origin_ka, meaning_ka, popularity, is_active, lang) SELECT 'მარიამი', 'girl', 'ებრაული', 'ღვთისმშობლის სახელი; საყვარელი და სანატრელი', 'ებრაული', 'ღვთისმშობლის სახელი; საყვარელი და სანატრელი', 98, true, 'ka' WHERE NOT EXISTS (SELECT 1 FROM public.baby_names_db WHERE name = 'მარიამი' AND lang = 'ka');
INSERT INTO public.baby_names_db (name, gender, origin, meaning, origin_ka, meaning_ka, popularity, is_active, lang) SELECT 'ანა', 'girl', 'ებრაული', 'მადლი, წყალობა', 'ებრაული', 'მადლი, წყალობა', 96, true, 'ka' WHERE NOT EXISTS (SELECT 1 FROM public.baby_names_db WHERE name = 'ანა' AND lang = 'ka');
INSERT INTO public.baby_names_db (name, gender, origin, meaning, origin_ka, meaning_ka, popularity, is_active, lang) SELECT 'ელენე', 'girl', 'ბერძნული', 'ნათელი, მანათობელი', 'ბერძნული', 'ნათელი, მანათობელი', 95, true, 'ka' WHERE NOT EXISTS (SELECT 1 FROM public.baby_names_db WHERE name = 'ელენე' AND lang = 'ka');
INSERT INTO public.baby_names_db (name, gender, origin, meaning, origin_ka, meaning_ka, popularity, is_active, lang) SELECT 'თამარი', 'girl', 'ებრაული', 'ფინიკის პალმა; თამარ მეფის სახელი', 'ებრაული', 'ფინიკის პალმა; თამარ მეფის სახელი', 94, true, 'ka' WHERE NOT EXISTS (SELECT 1 FROM public.baby_names_db WHERE name = 'თამარი' AND lang = 'ka');
INSERT INTO public.baby_names_db (name, gender, origin, meaning, origin_ka, meaning_ka, popularity, is_active, lang) SELECT 'სალომე', 'girl', 'ებრაული', 'მშვიდობა, სიმშვიდე', 'ებრაული', 'მშვიდობა, სიმშვიდე', 93, true, 'ka' WHERE NOT EXISTS (SELECT 1 FROM public.baby_names_db WHERE name = 'სალომე' AND lang = 'ka');
INSERT INTO public.baby_names_db (name, gender, origin, meaning, origin_ka, meaning_ka, popularity, is_active, lang) SELECT 'ლიზი', 'girl', 'ებრაული', 'ელისაბედის მოფერებითი ფორმა — ღმერთი ჩემი ფიცია', 'ებრაული', 'ელისაბედის მოფერებითი ფორმა — ღმერთი ჩემი ფიცია', 92, true, 'ka' WHERE NOT EXISTS (SELECT 1 FROM public.baby_names_db WHERE name = 'ლიზი' AND lang = 'ka');
INSERT INTO public.baby_names_db (name, gender, origin, meaning, origin_ka, meaning_ka, popularity, is_active, lang) SELECT 'ბარბარე', 'girl', 'ბერძნული', 'წმინდა ბარბარეს სახელი; უცხო მიწიდან მოსული', 'ბერძნული', 'წმინდა ბარბარეს სახელი; უცხო მიწიდან მოსული', 91, true, 'ka' WHERE NOT EXISTS (SELECT 1 FROM public.baby_names_db WHERE name = 'ბარბარე' AND lang = 'ka');
INSERT INTO public.baby_names_db (name, gender, origin, meaning, origin_ka, meaning_ka, popularity, is_active, lang) SELECT 'ნატა', 'girl', 'ლათინური', 'ნატალიას შემოკლებული ფორმა — შობის დღეს დაბადებული', 'ლათინური', 'ნატალიას შემოკლებული ფორმა — შობის დღეს დაბადებული', 90, true, 'ka' WHERE NOT EXISTS (SELECT 1 FROM public.baby_names_db WHERE name = 'ნატა' AND lang = 'ka');
INSERT INTO public.baby_names_db (name, gender, origin, meaning, origin_ka, meaning_ka, popularity, is_active, lang) SELECT 'ანასტასია', 'girl', 'ბერძნული', 'აღდგომა, ხელახლა დაბადებული', 'ბერძნული', 'აღდგომა, ხელახლა დაბადებული', 89, true, 'ka' WHERE NOT EXISTS (SELECT 1 FROM public.baby_names_db WHERE name = 'ანასტასია' AND lang = 'ka');
INSERT INTO public.baby_names_db (name, gender, origin, meaning, origin_ka, meaning_ka, popularity, is_active, lang) SELECT 'ქეთევანი', 'girl', 'ქართული', 'ქეთევან წმინდა დედოფლის სახელი; ერთგულების სიმბოლო', 'ქართული', 'ქეთევან წმინდა დედოფლის სახელი; ერთგულების სიმბოლო', 88, true, 'ka' WHERE NOT EXISTS (SELECT 1 FROM public.baby_names_db WHERE name = 'ქეთევანი' AND lang = 'ka');
INSERT INTO public.baby_names_db (name, gender, origin, meaning, origin_ka, meaning_ka, popularity, is_active, lang) SELECT 'ნია', 'girl', 'ქართული', 'თანამედროვე ქართული სახელი; მოფერებითი წარმოშობის', 'ქართული', 'თანამედროვე ქართული სახელი; მოფერებითი წარმოშობის', 88, true, 'ka' WHERE NOT EXISTS (SELECT 1 FROM public.baby_names_db WHERE name = 'ნია' AND lang = 'ka');
INSERT INTO public.baby_names_db (name, gender, origin, meaning, origin_ka, meaning_ka, popularity, is_active, lang) SELECT 'სოფიო', 'girl', 'ბერძნული', 'სიბრძნე', 'ბერძნული', 'სიბრძნე', 87, true, 'ka' WHERE NOT EXISTS (SELECT 1 FROM public.baby_names_db WHERE name = 'სოფიო' AND lang = 'ka');
INSERT INTO public.baby_names_db (name, gender, origin, meaning, origin_ka, meaning_ka, popularity, is_active, lang) SELECT 'ელისაბედი', 'girl', 'ებრაული', 'ღმერთი ჩემი ფიცია', 'ებრაული', 'ღმერთი ჩემი ფიცია', 86, true, 'ka' WHERE NOT EXISTS (SELECT 1 FROM public.baby_names_db WHERE name = 'ელისაბედი' AND lang = 'ka');
INSERT INTO public.baby_names_db (name, gender, origin, meaning, origin_ka, meaning_ka, popularity, is_active, lang) SELECT 'თეკლა', 'girl', 'ბერძნული', 'ღვთის დიდება', 'ბერძნული', 'ღვთის დიდება', 85, true, 'ka' WHERE NOT EXISTS (SELECT 1 FROM public.baby_names_db WHERE name = 'თეკლა' AND lang = 'ka');
INSERT INTO public.baby_names_db (name, gender, origin, meaning, origin_ka, meaning_ka, popularity, is_active, lang) SELECT 'ხატია', 'girl', 'ქართული', 'ხატივით ლამაზი', 'ქართული', 'ხატივით ლამაზი', 85, true, 'ka' WHERE NOT EXISTS (SELECT 1 FROM public.baby_names_db WHERE name = 'ხატია' AND lang = 'ka');
INSERT INTO public.baby_names_db (name, gender, origin, meaning, origin_ka, meaning_ka, popularity, is_active, lang) SELECT 'მია', 'girl', 'ებრაული', 'მარიამის შემოკლებული ფორმა', 'ებრაული', 'მარიამის შემოკლებული ფორმა', 84, true, 'ka' WHERE NOT EXISTS (SELECT 1 FROM public.baby_names_db WHERE name = 'მია' AND lang = 'ka');
INSERT INTO public.baby_names_db (name, gender, origin, meaning, origin_ka, meaning_ka, popularity, is_active, lang) SELECT 'ნინი', 'girl', 'ქართული', 'ნინოს მოფერებითი ფორმა', 'ქართული', 'ნინოს მოფერებითი ფორმა', 84, true, 'ka' WHERE NOT EXISTS (SELECT 1 FROM public.baby_names_db WHERE name = 'ნინი' AND lang = 'ka');
INSERT INTO public.baby_names_db (name, gender, origin, meaning, origin_ka, meaning_ka, popularity, is_active, lang) SELECT 'ემა', 'girl', 'გერმანული', 'მთლიანი, ყოვლისმომცველი', 'გერმანული', 'მთლიანი, ყოვლისმომცველი', 83, true, 'ka' WHERE NOT EXISTS (SELECT 1 FROM public.baby_names_db WHERE name = 'ემა' AND lang = 'ka');
INSERT INTO public.baby_names_db (name, gender, origin, meaning, origin_ka, meaning_ka, popularity, is_active, lang) SELECT 'ნიცა', 'girl', 'ქართული', 'მოფერებითი წარმოშობის ქართული სახელი', 'ქართული', 'მოფერებითი წარმოშობის ქართული სახელი', 83, true, 'ka' WHERE NOT EXISTS (SELECT 1 FROM public.baby_names_db WHERE name = 'ნიცა' AND lang = 'ka');
INSERT INTO public.baby_names_db (name, gender, origin, meaning, origin_ka, meaning_ka, popularity, is_active, lang) SELECT 'ემილია', 'girl', 'ლათინური', 'გულმოდგინე, მონდომებული', 'ლათინური', 'გულმოდგინე, მონდომებული', 82, true, 'ka' WHERE NOT EXISTS (SELECT 1 FROM public.baby_names_db WHERE name = 'ემილია' AND lang = 'ka');
INSERT INTO public.baby_names_db (name, gender, origin, meaning, origin_ka, meaning_ka, popularity, is_active, lang) SELECT 'თინათინი', 'girl', 'ქართული', 'მზის სხივის ანარეკლი; „ვეფხისტყაოსნის" გმირი', 'ქართული', 'მზის სხივის ანარეკლი; „ვეფხისტყაოსნის" გმირი', 82, true, 'ka' WHERE NOT EXISTS (SELECT 1 FROM public.baby_names_db WHERE name = 'თინათინი' AND lang = 'ka');
INSERT INTO public.baby_names_db (name, gender, origin, meaning, origin_ka, meaning_ka, popularity, is_active, lang) SELECT 'გაბრიელა', 'girl', 'ებრაული', 'ღმერთი ჩემი ძალაა', 'ებრაული', 'ღმერთი ჩემი ძალაა', 81, true, 'ka' WHERE NOT EXISTS (SELECT 1 FROM public.baby_names_db WHERE name = 'გაბრიელა' AND lang = 'ka');
INSERT INTO public.baby_names_db (name, gender, origin, meaning, origin_ka, meaning_ka, popularity, is_active, lang) SELECT 'თაკო', 'girl', 'ქართული', 'თამარის მოფერებითი ფორმა', 'ქართული', 'თამარის მოფერებითი ფორმა', 81, true, 'ka' WHERE NOT EXISTS (SELECT 1 FROM public.baby_names_db WHERE name = 'თაკო' AND lang = 'ka');
INSERT INTO public.baby_names_db (name, gender, origin, meaning, origin_ka, meaning_ka, popularity, is_active, lang) SELECT 'ვერონიკა', 'girl', 'ბერძნული', 'გამარჯვების მომტანი', 'ბერძნული', 'გამარჯვების მომტანი', 80, true, 'ka' WHERE NOT EXISTS (SELECT 1 FROM public.baby_names_db WHERE name = 'ვერონიკა' AND lang = 'ka');
INSERT INTO public.baby_names_db (name, gender, origin, meaning, origin_ka, meaning_ka, popularity, is_active, lang) SELECT 'ნუცა', 'girl', 'ქართული', 'ძველი ქართული მოფერებითი სახელი; საყვარელი', 'ქართული', 'ძველი ქართული მოფერებითი სახელი; საყვარელი', 80, true, 'ka' WHERE NOT EXISTS (SELECT 1 FROM public.baby_names_db WHERE name = 'ნუცა' AND lang = 'ka');
INSERT INTO public.baby_names_db (name, gender, origin, meaning, origin_ka, meaning_ka, popularity, is_active, lang) SELECT 'დეა', 'girl', 'ლათინური', 'ქალღმერთი', 'ლათინური', 'ქალღმერთი', 79, true, 'ka' WHERE NOT EXISTS (SELECT 1 FROM public.baby_names_db WHERE name = 'დეა' AND lang = 'ka');
INSERT INTO public.baby_names_db (name, gender, origin, meaning, origin_ka, meaning_ka, popularity, is_active, lang) SELECT 'მაია', 'girl', 'ბერძნული', 'გაზაფხულის ქალღმერთი; მაისის თვე', 'ბერძნული', 'გაზაფხულის ქალღმერთი; მაისის თვე', 79, true, 'ka' WHERE NOT EXISTS (SELECT 1 FROM public.baby_names_db WHERE name = 'მაია' AND lang = 'ka');
INSERT INTO public.baby_names_db (name, gender, origin, meaning, origin_ka, meaning_ka, popularity, is_active, lang) SELECT 'თეა', 'girl', 'ბერძნული', 'ქალღმერთი; ნათების ქალღმერთის სახელი', 'ბერძნული', 'ქალღმერთი; ნათების ქალღმერთის სახელი', 78, true, 'ka' WHERE NOT EXISTS (SELECT 1 FROM public.baby_names_db WHERE name = 'თეა' AND lang = 'ka');
INSERT INTO public.baby_names_db (name, gender, origin, meaning, origin_ka, meaning_ka, popularity, is_active, lang) SELECT 'ნანა', 'girl', 'ქართული', 'ნანა დედოფლის სახელი; იავნანას სითბო', 'ქართული', 'ნანა დედოფლის სახელი; იავნანას სითბო', 78, true, 'ka' WHERE NOT EXISTS (SELECT 1 FROM public.baby_names_db WHERE name = 'ნანა' AND lang = 'ka');
INSERT INTO public.baby_names_db (name, gender, origin, meaning, origin_ka, meaning_ka, popularity, is_active, lang) SELECT 'ნესტანი', 'girl', 'ქართული', '„ვეფხისტყაოსნის" გმირის, ნესტან-დარეჯანის სახელი', 'ქართული', '„ვეფხისტყაოსნის" გმირის, ნესტან-დარეჯანის სახელი', 78, true, 'ka' WHERE NOT EXISTS (SELECT 1 FROM public.baby_names_db WHERE name = 'ნესტანი' AND lang = 'ka');
INSERT INTO public.baby_names_db (name, gender, origin, meaning, origin_ka, meaning_ka, popularity, is_active, lang) SELECT 'თეონა', 'girl', 'ბერძნული', 'ღვთის სიბრძნის მქონე', 'ბერძნული', 'ღვთის სიბრძნის მქონე', 77, true, 'ka' WHERE NOT EXISTS (SELECT 1 FROM public.baby_names_db WHERE name = 'თეონა' AND lang = 'ka');
INSERT INTO public.baby_names_db (name, gender, origin, meaning, origin_ka, meaning_ka, popularity, is_active, lang) SELECT 'გვანცა', 'girl', 'ქართული', 'სვანური წარმოშობის სახელი; სიცოცხლით სავსე', 'ქართული', 'სვანური წარმოშობის სახელი; სიცოცხლით სავსე', 77, true, 'ka' WHERE NOT EXISTS (SELECT 1 FROM public.baby_names_db WHERE name = 'გვანცა' AND lang = 'ka');
INSERT INTO public.baby_names_db (name, gender, origin, meaning, origin_ka, meaning_ka, popularity, is_active, lang) SELECT 'ლალი', 'girl', 'ქართული', 'ლალი — ძვირფასი ქვა', 'ქართული', 'ლალი — ძვირფასი ქვა', 77, true, 'ka' WHERE NOT EXISTS (SELECT 1 FROM public.baby_names_db WHERE name = 'ლალი' AND lang = 'ka');
INSERT INTO public.baby_names_db (name, gender, origin, meaning, origin_ka, meaning_ka, popularity, is_active, lang) SELECT 'ეკატერინე', 'girl', 'ბერძნული', 'წმინდა, უმწიკვლო', 'ბერძნული', 'წმინდა, უმწიკვლო', 76, true, 'ka' WHERE NOT EXISTS (SELECT 1 FROM public.baby_names_db WHERE name = 'ეკატერინე' AND lang = 'ka');
INSERT INTO public.baby_names_db (name, gender, origin, meaning, origin_ka, meaning_ka, popularity, is_active, lang) SELECT 'ლიკა', 'girl', 'ქართული', 'თანამედროვე მოფერებითი სახელი', 'ქართული', 'თანამედროვე მოფერებითი სახელი', 76, true, 'ka' WHERE NOT EXISTS (SELECT 1 FROM public.baby_names_db WHERE name = 'ლიკა' AND lang = 'ka');
INSERT INTO public.baby_names_db (name, gender, origin, meaning, origin_ka, meaning_ka, popularity, is_active, lang) SELECT 'ანუკი', 'girl', 'ქართული', 'ანას მოფერებითი ფორმა', 'ქართული', 'ანას მოფერებითი ფორმა', 76, true, 'ka' WHERE NOT EXISTS (SELECT 1 FROM public.baby_names_db WHERE name = 'ანუკი' AND lang = 'ka');
INSERT INTO public.baby_names_db (name, gender, origin, meaning, origin_ka, meaning_ka, popularity, is_active, lang) SELECT 'ირინე', 'girl', 'ბერძნული', 'მშვიდობა', 'ბერძნული', 'მშვიდობა', 75, true, 'ka' WHERE NOT EXISTS (SELECT 1 FROM public.baby_names_db WHERE name = 'ირინე' AND lang = 'ka');
INSERT INTO public.baby_names_db (name, gender, origin, meaning, origin_ka, meaning_ka, popularity, is_active, lang) SELECT 'მეგი', 'girl', 'ბერძნული', 'მარგარიტას მოფერებითი ფორმა — მარგალიტი', 'ბერძნული', 'მარგარიტას მოფერებითი ფორმა — მარგალიტი', 75, true, 'ka' WHERE NOT EXISTS (SELECT 1 FROM public.baby_names_db WHERE name = 'მეგი' AND lang = 'ka');
INSERT INTO public.baby_names_db (name, gender, origin, meaning, origin_ka, meaning_ka, popularity, is_active, lang) SELECT 'მართა', 'girl', 'არამეული', 'დიასახლისი, ქალბატონი', 'არამეული', 'დიასახლისი, ქალბატონი', 74, true, 'ka' WHERE NOT EXISTS (SELECT 1 FROM public.baby_names_db WHERE name = 'მართა' AND lang = 'ka');

-- ── Oğlan adları (40) ──
INSERT INTO public.baby_names_db (name, gender, origin, meaning, origin_ka, meaning_ka, popularity, is_active, lang) SELECT 'გიორგი', 'boy', 'ბერძნული', 'მიწის მუშაკი; საქართველოს მფარველი წმინდანის სახელი', 'ბერძნული', 'მიწის მუშაკი; საქართველოს მფარველი წმინდანის სახელი', 99, true, 'ka' WHERE NOT EXISTS (SELECT 1 FROM public.baby_names_db WHERE name = 'გიორგი' AND lang = 'ka');
INSERT INTO public.baby_names_db (name, gender, origin, meaning, origin_ka, meaning_ka, popularity, is_active, lang) SELECT 'დავითი', 'boy', 'ებრაული', 'საყვარელი; დავით აღმაშენებლის სახელი', 'ებრაული', 'საყვარელი; დავით აღმაშენებლის სახელი', 97, true, 'ka' WHERE NOT EXISTS (SELECT 1 FROM public.baby_names_db WHERE name = 'დავითი' AND lang = 'ka');
INSERT INTO public.baby_names_db (name, gender, origin, meaning, origin_ka, meaning_ka, popularity, is_active, lang) SELECT 'ლუკა', 'boy', 'ლათინური', 'ნათლის მომტანი', 'ლათინური', 'ნათლის მომტანი', 96, true, 'ka' WHERE NOT EXISTS (SELECT 1 FROM public.baby_names_db WHERE name = 'ლუკა' AND lang = 'ka');
INSERT INTO public.baby_names_db (name, gender, origin, meaning, origin_ka, meaning_ka, popularity, is_active, lang) SELECT 'ნიკოლოზი', 'boy', 'ბერძნული', 'ხალხის გამარჯვება', 'ბერძნული', 'ხალხის გამარჯვება', 95, true, 'ka' WHERE NOT EXISTS (SELECT 1 FROM public.baby_names_db WHERE name = 'ნიკოლოზი' AND lang = 'ka');
INSERT INTO public.baby_names_db (name, gender, origin, meaning, origin_ka, meaning_ka, popularity, is_active, lang) SELECT 'ალექსანდრე', 'boy', 'ბერძნული', 'ხალხის დამცველი', 'ბერძნული', 'ხალხის დამცველი', 94, true, 'ka' WHERE NOT EXISTS (SELECT 1 FROM public.baby_names_db WHERE name = 'ალექსანდრე' AND lang = 'ka');
INSERT INTO public.baby_names_db (name, gender, origin, meaning, origin_ka, meaning_ka, popularity, is_active, lang) SELECT 'ირაკლი', 'boy', 'ბერძნული', 'ჰერაკლეს სახელიდან — გმირი, ძლიერი', 'ბერძნული', 'ჰერაკლეს სახელიდან — გმირი, ძლიერი', 93, true, 'ka' WHERE NOT EXISTS (SELECT 1 FROM public.baby_names_db WHERE name = 'ირაკლი' AND lang = 'ka');
INSERT INTO public.baby_names_db (name, gender, origin, meaning, origin_ka, meaning_ka, popularity, is_active, lang) SELECT 'ლევანი', 'boy', 'ბერძნული', 'ლომი', 'ბერძნული', 'ლომი', 92, true, 'ka' WHERE NOT EXISTS (SELECT 1 FROM public.baby_names_db WHERE name = 'ლევანი' AND lang = 'ka');
INSERT INTO public.baby_names_db (name, gender, origin, meaning, origin_ka, meaning_ka, popularity, is_active, lang) SELECT 'სანდრო', 'boy', 'ქართული', 'ალექსანდრეს შემოკლებული ფორმა', 'ქართული', 'ალექსანდრეს შემოკლებული ფორმა', 91, true, 'ka' WHERE NOT EXISTS (SELECT 1 FROM public.baby_names_db WHERE name = 'სანდრო' AND lang = 'ka');
INSERT INTO public.baby_names_db (name, gender, origin, meaning, origin_ka, meaning_ka, popularity, is_active, lang) SELECT 'ანდრია', 'boy', 'ბერძნული', 'მამაცი, ვაჟკაცი', 'ბერძნული', 'მამაცი, ვაჟკაცი', 90, true, 'ka' WHERE NOT EXISTS (SELECT 1 FROM public.baby_names_db WHERE name = 'ანდრია' AND lang = 'ka');
INSERT INTO public.baby_names_db (name, gender, origin, meaning, origin_ka, meaning_ka, popularity, is_active, lang) SELECT 'ილია', 'boy', 'ებრაული', 'ჩემი ღმერთი უფალია; ილია ჭავჭავაძის სახელი', 'ებრაული', 'ჩემი ღმერთი უფალია; ილია ჭავჭავაძის სახელი', 89, true, 'ka' WHERE NOT EXISTS (SELECT 1 FROM public.baby_names_db WHERE name = 'ილია' AND lang = 'ka');
INSERT INTO public.baby_names_db (name, gender, origin, meaning, origin_ka, meaning_ka, popularity, is_active, lang) SELECT 'საბა', 'boy', 'არამეული', 'წმინდა საბა განწმენდილის სახელი', 'არამეული', 'წმინდა საბა განწმენდილის სახელი', 88, true, 'ka' WHERE NOT EXISTS (SELECT 1 FROM public.baby_names_db WHERE name = 'საბა' AND lang = 'ka');
INSERT INTO public.baby_names_db (name, gender, origin, meaning, origin_ka, meaning_ka, popularity, is_active, lang) SELECT 'ბექა', 'boy', 'ქართული', 'ბექა ჯაყელის სახელი; მთავარი, ბატონი', 'ქართული', 'ბექა ჯაყელის სახელი; მთავარი, ბატონი', 88, true, 'ka' WHERE NOT EXISTS (SELECT 1 FROM public.baby_names_db WHERE name = 'ბექა' AND lang = 'ka');
INSERT INTO public.baby_names_db (name, gender, origin, meaning, origin_ka, meaning_ka, popularity, is_active, lang) SELECT 'დემეტრე', 'boy', 'ბერძნული', 'მიწის ნაყოფიერების მფარველი; დემეტრე თავდადებულის სახელი', 'ბერძნული', 'მიწის ნაყოფიერების მფარველი; დემეტრე თავდადებულის სახელი', 87, true, 'ka' WHERE NOT EXISTS (SELECT 1 FROM public.baby_names_db WHERE name = 'დემეტრე' AND lang = 'ka');
INSERT INTO public.baby_names_db (name, gender, origin, meaning, origin_ka, meaning_ka, popularity, is_active, lang) SELECT 'ნიკა', 'boy', 'ქართული', 'ნიკოლოზის მოფერებითი ფორმა; გამარჯვება', 'ქართული', 'ნიკოლოზის მოფერებითი ფორმა; გამარჯვება', 87, true, 'ka' WHERE NOT EXISTS (SELECT 1 FROM public.baby_names_db WHERE name = 'ნიკა' AND lang = 'ka');
INSERT INTO public.baby_names_db (name, gender, origin, meaning, origin_ka, meaning_ka, popularity, is_active, lang) SELECT 'დანიელი', 'boy', 'ებრაული', 'ღმერთია ჩემი მსაჯული', 'ებრაული', 'ღმერთია ჩემი მსაჯული', 86, true, 'ka' WHERE NOT EXISTS (SELECT 1 FROM public.baby_names_db WHERE name = 'დანიელი' AND lang = 'ka');
INSERT INTO public.baby_names_db (name, gender, origin, meaning, origin_ka, meaning_ka, popularity, is_active, lang) SELECT 'თორნიკე', 'boy', 'ქართული', 'ძველი ქართული სახელი; თორნიკე ერისთავის სახელით ცნობილი', 'ქართული', 'ძველი ქართული სახელი; თორნიკე ერისთავის სახელით ცნობილი', 86, true, 'ka' WHERE NOT EXISTS (SELECT 1 FROM public.baby_names_db WHERE name = 'თორნიკე' AND lang = 'ka');
INSERT INTO public.baby_names_db (name, gender, origin, meaning, origin_ka, meaning_ka, popularity, is_active, lang) SELECT 'გაბრიელი', 'boy', 'ებრაული', 'ღმერთი ჩემი ძალაა; მთავარანგელოზის სახელი', 'ებრაული', 'ღმერთი ჩემი ძალაა; მთავარანგელოზის სახელი', 85, true, 'ka' WHERE NOT EXISTS (SELECT 1 FROM public.baby_names_db WHERE name = 'გაბრიელი' AND lang = 'ka');
INSERT INTO public.baby_names_db (name, gender, origin, meaning, origin_ka, meaning_ka, popularity, is_active, lang) SELECT 'ვახტანგი', 'boy', 'ქართული', 'ვახტანგ გორგასლის სახელი; მგლის ტანის მქონე — ძლიერი', 'ქართული', 'ვახტანგ გორგასლის სახელი; მგლის ტანის მქონე — ძლიერი', 85, true, 'ka' WHERE NOT EXISTS (SELECT 1 FROM public.baby_names_db WHERE name = 'ვახტანგი' AND lang = 'ka');
INSERT INTO public.baby_names_db (name, gender, origin, meaning, origin_ka, meaning_ka, popularity, is_active, lang) SELECT 'ლაშა', 'boy', 'ქართული', 'ნათელი, მანათობელი; ლაშა-გიორგის სახელი', 'ქართული', 'ნათელი, მანათობელი; ლაშა-გიორგის სახელი', 85, true, 'ka' WHERE NOT EXISTS (SELECT 1 FROM public.baby_names_db WHERE name = 'ლაშა' AND lang = 'ka');
INSERT INTO public.baby_names_db (name, gender, origin, meaning, origin_ka, meaning_ka, popularity, is_active, lang) SELECT 'ლაზარე', 'boy', 'ებრაული', 'ღმერთი შემწეა', 'ებრაული', 'ღმერთი შემწეა', 84, true, 'ka' WHERE NOT EXISTS (SELECT 1 FROM public.baby_names_db WHERE name = 'ლაზარე' AND lang = 'ka');
INSERT INTO public.baby_names_db (name, gender, origin, meaning, origin_ka, meaning_ka, popularity, is_active, lang) SELECT 'გიგა', 'boy', 'ქართული', 'გიორგის მოფერებითი ფორმა', 'ქართული', 'გიორგის მოფერებითი ფორმა', 84, true, 'ka' WHERE NOT EXISTS (SELECT 1 FROM public.baby_names_db WHERE name = 'გიგა' AND lang = 'ka');
INSERT INTO public.baby_names_db (name, gender, origin, meaning, origin_ka, meaning_ka, popularity, is_active, lang) SELECT 'მათე', 'boy', 'ებრაული', 'ღვთის საჩუქარი', 'ებრაული', 'ღვთის საჩუქარი', 83, true, 'ka' WHERE NOT EXISTS (SELECT 1 FROM public.baby_names_db WHERE name = 'მათე' AND lang = 'ka');
INSERT INTO public.baby_names_db (name, gender, origin, meaning, origin_ka, meaning_ka, popularity, is_active, lang) SELECT 'დაჩი', 'boy', 'ქართული', 'ძველი ქართული სახელი; მეფე დაჩის სახელი', 'ქართული', 'ძველი ქართული სახელი; მეფე დაჩის სახელი', 83, true, 'ka' WHERE NOT EXISTS (SELECT 1 FROM public.baby_names_db WHERE name = 'დაჩი' AND lang = 'ka');
INSERT INTO public.baby_names_db (name, gender, origin, meaning, origin_ka, meaning_ka, popularity, is_active, lang) SELECT 'მიხეილი', 'boy', 'ებრაული', 'ვინ არის როგორც ღმერთი; მთავარანგელოზ მიქაელის სახელი', 'ებრაული', 'ვინ არის როგორც ღმერთი; მთავარანგელოზ მიქაელის სახელი', 82, true, 'ka' WHERE NOT EXISTS (SELECT 1 FROM public.baby_names_db WHERE name = 'მიხეილი' AND lang = 'ka');
INSERT INTO public.baby_names_db (name, gender, origin, meaning, origin_ka, meaning_ka, popularity, is_active, lang) SELECT 'შოთა', 'boy', 'ქართული', 'შოთა რუსთაველის სახელით უკვდავქმნილი ძველი ქართული სახელი', 'ქართული', 'შოთა რუსთაველის სახელით უკვდავქმნილი ძველი ქართული სახელი', 82, true, 'ka' WHERE NOT EXISTS (SELECT 1 FROM public.baby_names_db WHERE name = 'შოთა' AND lang = 'ka');
INSERT INTO public.baby_names_db (name, gender, origin, meaning, origin_ka, meaning_ka, popularity, is_active, lang) SELECT 'რატი', 'boy', 'ქართული', 'ძველი ქართული სახელი, ერისთავთა ტრადიციიდან', 'ქართული', 'ძველი ქართული სახელი, ერისთავთა ტრადიციიდან', 81, true, 'ka' WHERE NOT EXISTS (SELECT 1 FROM public.baby_names_db WHERE name = 'რატი' AND lang = 'ka');
INSERT INTO public.baby_names_db (name, gender, origin, meaning, origin_ka, meaning_ka, popularity, is_active, lang) SELECT 'ნოე', 'boy', 'ებრაული', 'სიმშვიდე, ნუგეში', 'ებრაული', 'სიმშვიდე, ნუგეში', 80, true, 'ka' WHERE NOT EXISTS (SELECT 1 FROM public.baby_names_db WHERE name = 'ნოე' AND lang = 'ka');
INSERT INTO public.baby_names_db (name, gender, origin, meaning, origin_ka, meaning_ka, popularity, is_active, lang) SELECT 'იოანე', 'boy', 'ებრაული', 'ღმერთი მოწყალეა', 'ებრაული', 'ღმერთი მოწყალეა', 79, true, 'ka' WHERE NOT EXISTS (SELECT 1 FROM public.baby_names_db WHERE name = 'იოანე' AND lang = 'ka');
INSERT INTO public.baby_names_db (name, gender, origin, meaning, origin_ka, meaning_ka, popularity, is_active, lang) SELECT 'ზურაბი', 'boy', 'სპარსული', 'ბრწყინვალე, ღირსეული', 'სპარსული', 'ბრწყინვალე, ღირსეული', 78, true, 'ka' WHERE NOT EXISTS (SELECT 1 FROM public.baby_names_db WHERE name = 'ზურაბი' AND lang = 'ka');
INSERT INTO public.baby_names_db (name, gender, origin, meaning, origin_ka, meaning_ka, popularity, is_active, lang) SELECT 'თედო', 'boy', 'ქართული', 'თევდორეს შემოკლებული ფორმა — ღვთის საჩუქარი', 'ქართული', 'თევდორეს შემოკლებული ფორმა — ღვთის საჩუქარი', 78, true, 'ka' WHERE NOT EXISTS (SELECT 1 FROM public.baby_names_db WHERE name = 'თედო' AND lang = 'ka');
INSERT INTO public.baby_names_db (name, gender, origin, meaning, origin_ka, meaning_ka, popularity, is_active, lang) SELECT 'პაატა', 'boy', 'ქართული', 'უმცროსი, პატარა', 'ქართული', 'უმცროსი, პატარა', 77, true, 'ka' WHERE NOT EXISTS (SELECT 1 FROM public.baby_names_db WHERE name = 'პაატა' AND lang = 'ka');
INSERT INTO public.baby_names_db (name, gender, origin, meaning, origin_ka, meaning_ka, popularity, is_active, lang) SELECT 'გურამი', 'boy', 'ქართული', 'ძველი ქართული სახელი; სპარსული წარმოშობის', 'ქართული', 'ძველი ქართული სახელი; სპარსული წარმოშობის', 77, true, 'ka' WHERE NOT EXISTS (SELECT 1 FROM public.baby_names_db WHERE name = 'გურამი' AND lang = 'ka');
INSERT INTO public.baby_names_db (name, gender, origin, meaning, origin_ka, meaning_ka, popularity, is_active, lang) SELECT 'თემური', 'boy', 'თურქული', 'რკინა; მტკიცე, შეუდრეკელი', 'თურქული', 'რკინა; მტკიცე, შეუდრეკელი', 76, true, 'ka' WHERE NOT EXISTS (SELECT 1 FROM public.baby_names_db WHERE name = 'თემური' AND lang = 'ka');
INSERT INTO public.baby_names_db (name, gender, origin, meaning, origin_ka, meaning_ka, popularity, is_active, lang) SELECT 'ვანო', 'boy', 'ქართული', 'იოანეს (ივანეს) მოფერებითი ფორმა', 'ქართული', 'იოანეს (ივანეს) მოფერებითი ფორმა', 76, true, 'ka' WHERE NOT EXISTS (SELECT 1 FROM public.baby_names_db WHERE name = 'ვანო' AND lang = 'ka');
INSERT INTO public.baby_names_db (name, gender, origin, meaning, origin_ka, meaning_ka, popularity, is_active, lang) SELECT 'აკაკი', 'boy', 'ბერძნული', 'უბოროტო, კეთილი; აკაკი წერეთლის სახელი', 'ბერძნული', 'უბოროტო, კეთილი; აკაკი წერეთლის სახელი', 76, true, 'ka' WHERE NOT EXISTS (SELECT 1 FROM public.baby_names_db WHERE name = 'აკაკი' AND lang = 'ka');
INSERT INTO public.baby_names_db (name, gender, origin, meaning, origin_ka, meaning_ka, popularity, is_active, lang) SELECT 'ამირანი', 'boy', 'ქართული', 'ქართული მითოსის გმირი; შეუპოვარი', 'ქართული', 'ქართული მითოსის გმირი; შეუპოვარი', 75, true, 'ka' WHERE NOT EXISTS (SELECT 1 FROM public.baby_names_db WHERE name = 'ამირანი' AND lang = 'ka');
INSERT INTO public.baby_names_db (name, gender, origin, meaning, origin_ka, meaning_ka, popularity, is_active, lang) SELECT 'ტიმოთე', 'boy', 'ბერძნული', 'ღვთის პატივისმცემელი', 'ბერძნული', 'ღვთის პატივისმცემელი', 75, true, 'ka' WHERE NOT EXISTS (SELECT 1 FROM public.baby_names_db WHERE name = 'ტიმოთე' AND lang = 'ka');
INSERT INTO public.baby_names_db (name, gender, origin, meaning, origin_ka, meaning_ka, popularity, is_active, lang) SELECT 'იაკობი', 'boy', 'ებრაული', 'ქუსლზე მპყრობელი; შემცვლელი', 'ებრაული', 'ქუსლზე მპყრობელი; შემცვლელი', 74, true, 'ka' WHERE NOT EXISTS (SELECT 1 FROM public.baby_names_db WHERE name = 'იაკობი' AND lang = 'ka');
INSERT INTO public.baby_names_db (name, gender, origin, meaning, origin_ka, meaning_ka, popularity, is_active, lang) SELECT 'ზაზა', 'boy', 'ქართული', 'ძველი ქართული სახელი', 'ქართული', 'ძველი ქართული სახელი', 74, true, 'ka' WHERE NOT EXISTS (SELECT 1 FROM public.baby_names_db WHERE name = 'ზაზა' AND lang = 'ka');
INSERT INTO public.baby_names_db (name, gender, origin, meaning, origin_ka, meaning_ka, popularity, is_active, lang) SELECT 'გივი', 'boy', 'ქართული', '„შაჰნამეს" გმირის სახელიდან; მამაცი', 'ქართული', '„შაჰნამეს" გმირის სახელიდან; მამაცი', 73, true, 'ka' WHERE NOT EXISTS (SELECT 1 FROM public.baby_names_db WHERE name = 'გივი' AND lang = 'ka');
