-- ============================================================
-- Alman6 — Hardcoded-audit açarları (BÜTÜN dillər: en/ru/tr/kk/de)
-- Mənbə: kodda tr() olmadan qalmış istifadəçi-tərəfli mətnlər
-- (vaksin placeholder-ləri, maternity etiketləri, dashboard/nutrition
--  placeholder-ləri, oyun leaderboard fallback). İdempotent.
-- ============================================================

INSERT INTO public.translations (key, lang, value, namespace) VALUES
  ('vaccinecalendar_yer_ph', 'en', 'e.g. London Children''s Hospital', 'common'),
  ('vaccinecalendar_sebeb_ph', 'en', 'e.g. Medical contraindication', 'common'),
  ('maternity_is_staji_telebi', 'en', 'Employment Requirement', 'common'),
  ('maternity_staj_metni', 'en', 'To receive maternity pay, you must have worked at your current workplace for at least {n} months.', 'common'),
  ('maternity_usaga_qulluq_mezuniyyeti', 'en', 'Childcare Leave', 'common'),
  ('maternity_muddet', 'en', 'Duration', 'common'),
  ('common_ay_unit', 'en', 'months', 'common'),
  ('dashboard_diger_ml_ph', 'en', 'Other (ml)', 'common'),
  ('dashboard_qida_ph', 'en', 'e.g. pumpkin purée', 'common'),
  ('nutrition_kcal_ph', 'en', 'e.g. 350', 'common'),
  ('games_user_fallback', 'en', 'Anacan user', 'common'),
  ('vaccinecalendar_yer_ph', 'ru', 'напр., Детская городская клиническая больница', 'common'),
  ('vaccinecalendar_sebeb_ph', 'ru', 'напр., медицинское противопоказание', 'common'),
  ('maternity_is_staji_telebi', 'ru', 'Требование к трудовому стажу', 'common'),
  ('maternity_staj_metni', 'ru', 'Чтобы получить отпускные выплаты, ваш трудовой стаж на последнем месте работы должен составлять не менее {n} месяцев.', 'common'),
  ('maternity_usaga_qulluq_mezuniyyeti', 'ru', 'Отпуск по уходу за ребёнком', 'common'),
  ('maternity_muddet', 'ru', 'Продолжительность', 'common'),
  ('common_ay_unit', 'ru', 'месяц', 'common'),
  ('dashboard_diger_ml_ph', 'ru', 'Другое (мл)', 'common'),
  ('dashboard_qida_ph', 'ru', 'Напр.: тыквенное пюре', 'common'),
  ('nutrition_kcal_ph', 'ru', 'напр., 350', 'common'),
  ('games_user_fallback', 'ru', 'Пользователь Anacan', 'common'),
  ('vaccinecalendar_yer_ph', 'tr', 'örn. İstanbul Çocuk Kliniği', 'common'),
  ('vaccinecalendar_sebeb_ph', 'tr', 'örn. Tıbbi kontrendikasyon', 'common'),
  ('maternity_is_staji_telebi', 'tr', 'Çalışma Süresi Şartı', 'common'),
  ('maternity_staj_metni', 'tr', 'İzin ödemesi alabilmeniz için son iş yerinizde en az {n} ay çalışmış olmanız gerekir.', 'common'),
  ('maternity_usaga_qulluq_mezuniyyeti', 'tr', 'Çocuk Bakım İzni', 'common'),
  ('maternity_muddet', 'tr', 'Süre', 'common'),
  ('common_ay_unit', 'tr', 'ay', 'common'),
  ('dashboard_diger_ml_ph', 'tr', 'Diğer (ml)', 'common'),
  ('dashboard_qida_ph', 'tr', 'Örn. balkabaklı püre', 'common'),
  ('nutrition_kcal_ph', 'tr', 'örn. 350', 'common'),
  ('games_user_fallback', 'tr', 'Anacan kullanıcısı', 'common'),
  ('vaccinecalendar_yer_ph', 'kk', 'мыс. Алматы қалалық балалар клиникалық ауруханасы', 'common'),
  ('vaccinecalendar_sebeb_ph', 'kk', 'мыс. Медициналық қарсы көрсетілім', 'common'),
  ('maternity_is_staji_telebi', 'kk', 'Еңбек өтіліне қойылатын талап', 'common'),
  ('maternity_staj_metni', 'kk', 'Демалыс төлемін алу үшін соңғы жұмыс орныңызда кемінде {n} ай еңбек өтіліңіз болуы тиіс.', 'common'),
  ('maternity_usaga_qulluq_mezuniyyeti', 'kk', 'Бала күтіміне байланысты демалыс', 'common'),
  ('maternity_muddet', 'kk', 'Ұзақтығы', 'common'),
  ('common_ay_unit', 'kk', 'ай', 'common'),
  ('dashboard_diger_ml_ph', 'kk', 'Басқа (мл)', 'common'),
  ('dashboard_qida_ph', 'kk', 'Мыс.: асқабақ езбесі', 'common'),
  ('nutrition_kcal_ph', 'kk', 'мыс. 350', 'common'),
  ('games_user_fallback', 'kk', 'Anacan пайдаланушысы', 'common'),
  ('vaccinecalendar_yer_ph', 'de', 'z. B. Kinderklinik München', 'common'),
  ('vaccinecalendar_sebeb_ph', 'de', 'z. B. medizinische Kontraindikation', 'common'),
  ('maternity_is_staji_telebi', 'de', 'Erforderliche Beschäftigungsdauer', 'common'),
  ('maternity_staj_metni', 'de', 'Um Urlaubsgeld zu erhalten, musst du bei deinem letzten Arbeitgeber mindestens {n} Monate beschäftigt gewesen sein.', 'common'),
  ('maternity_usaga_qulluq_mezuniyyeti', 'de', 'Elternzeit', 'common'),
  ('maternity_muddet', 'de', 'Dauer', 'common'),
  ('common_ay_unit', 'de', 'Monat', 'common'),
  ('dashboard_diger_ml_ph', 'de', 'Sonstiges (ml)', 'common'),
  ('dashboard_qida_ph', 'de', 'z. B. Kürbispüree', 'common'),
  ('nutrition_kcal_ph', 'de', 'z. B. 350', 'common'),
  ('games_user_fallback', 'de', 'Anacan-Nutzerin', 'common')
ON CONFLICT (key, lang) DO NOTHING;
