import { normalizeAppLanguage } from '@/lib/app-languages';
import { friendsText, type FriendsMessageKey } from '../iki-dost/messages';

const KEYS = ['flightTitle', 'flightCard', 'flightGuide', 'lift', 'release', 'wind', 'narrow', 'moving', 'secret',
  'parkingTitle', 'parkingCard', 'parkingGuide', 'parkingKey', 'exit', 'cars', 'bus', 'flightWon', 'flightLost', 'parkingWon', 'starCount'] as const;
export type CasualMessageKey = typeof KEYS[number];
export type CasualTextKey = FriendsMessageKey | CasualMessageKey;
const COPY: Record<string, string[]> = {
  az: ['Tumurcuğun uçuşu', 'Yarpaq paraşütü ilə uç, ulduzları topla və küləyi keç.', 'Ekranı basıb saxla — yüksəl. Burax — en. Budaqlardan keç, ulduzları topla və sona çat. 3 canın var.', 'Yüksəl', 'Burax · en', 'Külək axınları', 'Dar keçidlər', 'Hərəkətli budaqlar', 'Gizli yollar',
    'Yolunu aç', 'Maşınları sürüşdür, Qucaqın çıxış yolunu aç.', 'Maşını yalnız öz istiqamətində sürüşdür. Qucaqın yaşıl maşınını sağdakı çıxışdan çıxar. Seçilmiş maşını oxlarla da hərəkət etdirə bilərsən.', 'Açar işarəli maşını halqalı yerə gətir, çıxışın kilidi açılsın.', 'Çıxış', 'Maşınlar', 'Avtobus', 'Uçuş tamamlandı!', 'Kiçik bir eniş', 'Qucaq yola çıxdı!', '{count} ulduz toplandı'],
  en: ['Tumurcuq’s Flight', 'Glide with a leaf parachute, collect stars and ride the wind.', 'Hold the screen to rise; release to descend. Pass branches, collect stars and reach the finish. You have 3 hearts.', 'Rise', 'Release · descend', 'Wind currents', 'Narrow passages', 'Moving branches', 'Secret routes',
    'Clear the Way', 'Slide the cars and clear Qucaq’s route out.', 'Slide each car along its own direction. Move Qucaq’s green car through the right exit. You can also select a car and use arrows.', 'Move the key-marked car to its ringed bay to unlock the exit.', 'Exit', 'Cars', 'Bus', 'Flight complete!', 'A little landing', 'Qucaq is on the way!', '{count} stars collected'],
  tr: ['Tumurcuq’un Uçuşu', 'Yaprak paraşütle uç, yıldızları topla ve rüzgârı aş.', 'Ekrana basılı tutarak yüksel, bırakarak alçal. Dalları geç, yıldızları topla ve sona ulaş. 3 canın var.', 'Yüksel', 'Bırak · alçal', 'Rüzgâr akımları', 'Dar geçitler', 'Hareketli dallar', 'Gizli yollar',
    'Yolu Aç', 'Arabaları kaydır, Qucaq’ın çıkış yolunu aç.', 'Her arabayı kendi yönünde kaydır. Qucaq’ın yeşil arabasını sağdaki çıkıştan çıkar. Arabayı seçip okları da kullanabilirsin.', 'Anahtarlı arabayı halkalı yere getirerek çıkışı aç.', 'Çıkış', 'Arabalar', 'Otobüs', 'Uçuş tamamlandı!', 'Küçük bir iniş', 'Qucaq yola çıktı!', '{count} yıldız toplandı'],
  ru: ['Полёт Tumurcuq', 'Лети на парашюте-листе, собирай звёзды и проходи потоки ветра.', 'Удерживай экран, чтобы подняться, отпусти, чтобы снизиться. Облетай ветви, собирай звёзды и долети до финиша. У тебя 3 жизни.', 'Подняться', 'Отпусти · снижайся', 'Потоки ветра', 'Узкие проходы', 'Движущиеся ветви', 'Тайные пути',
    'Освободи путь', 'Сдвигай машины и освободи выезд для Qucaq.', 'Каждая машина движется только вдоль своей оси. Выведи зелёную машину Qucaq через выход справа. Можно выбрать машину и пользоваться стрелками.', 'Поставь машину с ключом на место с кольцом, чтобы открыть выезд.', 'Выезд', 'Машины', 'Автобус', 'Полёт завершён!', 'Небольшая посадка', 'Qucaq отправился в путь!', 'Собрано звёзд: {count}'],
  de: ['Tumurcuqs Flug', 'Gleite mit einem Blattfallschirm, sammle Sterne und nutze den Wind.', 'Halte den Bildschirm zum Steigen, lasse ihn zum Sinken los. Weiche Ästen aus, sammle Sterne und erreiche das Ziel. Du hast 3 Herzen.', 'Steigen', 'Loslassen · sinken', 'Windströme', 'Enge Passagen', 'Bewegliche Äste', 'Geheime Wege',
    'Mach den Weg frei', 'Verschiebe Autos und öffne Qucaq den Ausweg.', 'Schiebe jedes Auto nur in seiner Richtung. Fahre Qucaqs grünes Auto rechts hinaus. Du kannst ein Auto wählen und Pfeile verwenden.', 'Bringe das Auto mit dem Schlüssel auf den markierten Platz, um die Ausfahrt zu öffnen.', 'Ausfahrt', 'Autos', 'Bus', 'Flug geschafft!', 'Eine kleine Landung', 'Qucaq ist unterwegs!', '{count} Sterne gesammelt'],
  ar: ['رحلة Tumurcuq', 'طر بمظلة من ورقة، واجمع النجوم واعبر تيارات الريح.', 'اضغط باستمرار لترتفع، واترك الشاشة لتنخفض. تجاوز الأغصان واجمع النجوم وصل إلى النهاية. لديك ٣ قلوب.', 'ارتفع', 'اترك · انخفض', 'تيارات الريح', 'ممرات ضيقة', 'أغصان متحركة', 'طرق سرية',
    'افتح الطريق', 'حرّك السيارات وافتح مخرج Qucaq.', 'حرّك كل سيارة في اتجاهها فقط. أخرج سيارة Qucaq الخضراء من المخرج الأيمن. يمكنك اختيار سيارة واستخدام الأسهم أيضًا.', 'ضع السيارة ذات المفتاح في المكان المحاط بحلقة لفتح المخرج.', 'المخرج', 'السيارات', 'حافلة', 'اكتملت الرحلة!', 'هبوط صغير', 'انطلق Qucaq!', 'جُمعت {count} نجوم'],
  ka: ['Tumurcuq-ის ფრენა', 'იფრინე ფოთლის პარაშუტით, შეაგროვე ვარსკვლავები და გადალახე ქარი.', 'დააჭირე ეკრანს ასასვლელად, აუშვი დასაშვებად. გაიარე ტოტები, შეაგროვე ვარსკვლავები და მიაღწიე ფინიშს. გაქვს 3 სიცოცხლე.', 'ასვლა', 'აუშვი · დაშვება', 'ქარის ნაკადები', 'ვიწრო გასასვლელები', 'მოძრავი ტოტები', 'საიდუმლო გზები',
    'გახსენი გზა', 'გაასრიალე მანქანები და გაუხსენი Qucaq-ს გასასვლელი.', 'მანქანა მხოლოდ თავისი მიმართულებით გაასრიალე. Qucaq-ის მწვანე მანქანა მარჯვენა გასასვლელში გაიყვანე. შეგიძლია მანქანა აირჩიო და ისრები გამოიყენო.', 'გასაღებიანი მანქანა რგოლიან ადგილზე მიიყვანე გასასვლელის გასახსნელად.', 'გასასვლელი', 'მანქანები', 'ავტობუსი', 'ფრენა დასრულდა!', 'პატარა დაშვება', 'Qucaq გზას გაუდგა!', 'შეგროვებულია {count} ვარსკვლავი'],
  kk: ['Tumurcuq ұшуы', 'Жапырақ парашютпен ұш, жұлдыз жинап, желден өт.', 'Экранды ұстап тұрсаң көтеріледі, жіберсең төмендейді. Бұтақтардан өтіп, жұлдыз жинап мәреге жет. 3 жаның бар.', 'Көтерілу', 'Жібер · төменде', 'Жел ағындары', 'Тар өткелдер', 'Қозғалатын бұтақтар', 'Жасырын жолдар',
    'Жолды аш', 'Көліктерді жылжытып, Qucaq-тың шығу жолын аш.', 'Әр көлікті өз бағытымен жылжыт. Qucaq-тың жасыл көлігін оң жақтан шығар. Көлікті таңдап, көрсеткілерді де қолдануға болады.', 'Кілт белгісі бар көлікті сақиналы орынға жеткізіп, шығуды аш.', 'Шығу', 'Көліктер', 'Автобус', 'Ұшу аяқталды!', 'Шағын қону', 'Qucaq жолға шықты!', '{count} жұлдыз жиналды'],
  uz: ['Tumurcuq parvozi', 'Barg parashyutida uch, yulduzlarni yig‘ib shamoldan o‘t.', 'Ekranni bosib tursang ko‘taril, qo‘yib yuborsang tush. Shoxlardan o‘t, yulduzlarni yig‘ib marraga yet. 3 joning bor.', 'Ko‘taril', 'Qo‘yib yubor · tush', 'Shamol oqimlari', 'Tor yo‘laklar', 'Harakatlanuvchi shoxlar', 'Yashirin yo‘llar',
    'Yo‘lni och', 'Mashinalarni surib, Qucaqning chiqish yo‘lini och.', 'Har mashinani faqat o‘z yo‘nalishida sur. Qucaqning yashil mashinasini o‘ng chiqishdan olib chiq. Mashinani tanlab o‘qlardan ham foydalanish mumkin.', 'Kalit belgili mashinani halqali joyga olib borib chiqishni och.', 'Chiqish', 'Mashinalar', 'Avtobus', 'Parvoz tugadi!', 'Kichik qo‘nish', 'Qucaq yo‘lga chiqdi!', '{count} yulduz yig‘ildi'],
  zh: ['Tumurcuq 的飞行', '乘叶子降落伞飞行，收集星星，穿过风流。', '按住屏幕上升，松开下降。避开树枝，收集星星，到达终点。你有3颗心。', '上升', '松开 · 下降', '风流', '狭窄通道', '移动树枝', '秘密路线',
    '让出道路', '滑动车辆，为 Qucaq 打开出口。', '车辆只能沿自身方向移动。把 Qucaq 的绿色汽车从右侧出口开出去。也可选择车辆后使用方向键。', '把带钥匙标记的车辆停到圆环车位，解锁出口。', '出口', '车辆', '巴士', '飞行完成！', '小小的降落', 'Qucaq 出发了！', '收集了 {count} 颗星星'],
  id: ['Penerbangan Tumurcuq', 'Terbang dengan parasut daun, kumpulkan bintang dan lewati angin.', 'Tahan layar untuk naik; lepaskan untuk turun. Hindari cabang, kumpulkan bintang dan capai akhir. Kamu punya 3 nyawa.', 'Naik', 'Lepas · turun', 'Arus angin', 'Jalur sempit', 'Cabang bergerak', 'Jalur rahasia',
    'Buka Jalan', 'Geser mobil dan buka jalan keluar Qucaq.', 'Geser tiap mobil hanya sesuai arahnya. Keluarkan mobil hijau Qucaq lewat pintu kanan. Kamu juga bisa memilih mobil lalu memakai panah.', 'Pindahkan mobil bertanda kunci ke tempat bercincin untuk membuka pintu keluar.', 'Keluar', 'Mobil', 'Bus', 'Penerbangan selesai!', 'Pendaratan kecil', 'Qucaq berangkat!', '{count} bintang terkumpul'],
  fr: ['Le vol de Tumurcuq', 'Vole avec un parachute-feuille, ramasse des étoiles et traverse le vent.', 'Maintiens l’écran pour monter, relâche pour descendre. Évite les branches, ramasse les étoiles et atteins l’arrivée. Tu as 3 vies.', 'Monter', 'Relâcher · descendre', 'Courants de vent', 'Passages étroits', 'Branches mobiles', 'Chemins secrets',
    'Libère le passage', 'Fais glisser les voitures pour laisser sortir Qucaq.', 'Chaque voiture glisse dans son propre sens. Fais sortir la voiture verte de Qucaq par la droite. Tu peux aussi sélectionner une voiture et utiliser les flèches.', 'Place la voiture marquée d’une clé sur l’emplacement cerclé pour ouvrir la sortie.', 'Sortie', 'Voitures', 'Bus', 'Vol terminé !', 'Un petit atterrissage', 'Qucaq prend la route !', '{count} étoiles ramassées'],
  es: ['El vuelo de Tumurcuq', 'Vuela con un paracaídas de hoja, recoge estrellas y cruza el viento.', 'Mantén pulsada la pantalla para subir; suelta para bajar. Evita ramas, recoge estrellas y llega a la meta. Tienes 3 vidas.', 'Subir', 'Soltar · bajar', 'Corrientes de viento', 'Pasos estrechos', 'Ramas móviles', 'Rutas secretas',
    'Abre el camino', 'Desliza los coches y deja salir a Qucaq.', 'Cada coche se mueve solo en su dirección. Saca el coche verde de Qucaq por la derecha. También puedes elegir un coche y usar las flechas.', 'Lleva el coche con llave a la plaza con un círculo para abrir la salida.', 'Salida', 'Coches', 'Autobús', '¡Vuelo completado!', 'Un pequeño aterrizaje', '¡Qucaq sale de viaje!', '{count} estrellas recogidas'],
  pt: ['O voo de Tumurcuq', 'Voa com um paraquedas de folha, recolhe estrelas e atravessa o vento.', 'Mantém o ecrã premido para subir; solta para descer. Evita ramos, recolhe estrelas e chega à meta. Tens 3 vidas.', 'Subir', 'Soltar · descer', 'Correntes de vento', 'Passagens estreitas', 'Ramos móveis', 'Caminhos secretos',
    'Abre o caminho', 'Desliza os carros e abre a saída de Qucaq.', 'Move cada carro apenas na sua direção. Leva o carro verde de Qucaq à saída da direita. Também podes selecionar um carro e usar as setas.', 'Leva o carro com a chave ao lugar com um círculo para abrir a saída.', 'Saída', 'Carros', 'Autocarro', 'Voo concluído!', 'Uma pequena aterragem', 'Qucaq está a caminho!', '{count} estrelas recolhidas'],
  vi: ['Chuyến bay của Tumurcuq', 'Bay bằng dù lá, thu thập sao và vượt luồng gió.', 'Giữ màn hình để bay lên, thả để hạ xuống. Tránh cành cây, nhặt sao và đến đích. Bạn có 3 mạng.', 'Bay lên', 'Thả · hạ xuống', 'Luồng gió', 'Lối đi hẹp', 'Cành cây di chuyển', 'Đường bí mật',
    'Mở lối đi', 'Trượt các xe để mở đường ra cho Qucaq.', 'Chỉ trượt xe theo hướng của nó. Đưa xe xanh của Qucaq qua lối ra bên phải. Bạn cũng có thể chọn xe rồi dùng mũi tên.', 'Đưa xe có chìa khóa đến ô có vòng tròn để mở lối ra.', 'Lối ra', 'Xe', 'Xe buýt', 'Hoàn thành chuyến bay!', 'Hạ cánh nhẹ nhàng', 'Qucaq lên đường!', 'Đã thu thập {count} sao'],
  hi: ['Tumurcuq की उड़ान', 'पत्ते के पैराशूट से उड़ें, सितारे चुनें और हवा पार करें।', 'ऊपर उठने के लिए स्क्रीन दबाए रखें, नीचे आने के लिए छोड़ें। शाखाओं से बचें, सितारे चुनें और अंत तक पहुँचें। आपके पास 3 जीवन हैं।', 'ऊपर उठें', 'छोड़ें · नीचे आएँ', 'हवा की धाराएँ', 'संकरे रास्ते', 'चलती शाखाएँ', 'गुप्त रास्ते',
    'रास्ता खोलें', 'गाड़ियों को सरकाएँ और Qucaq का रास्ता खोलें।', 'गाड़ी को केवल उसकी दिशा में सरकाएँ। Qucaq की हरी गाड़ी को दाएँ निकास से बाहर निकालें। गाड़ी चुनकर तीरों से भी चला सकते हैं।', 'चाबी वाली गाड़ी को घेरे वाली जगह पर लाकर निकास खोलें।', 'निकास', 'गाड़ियाँ', 'बस', 'उड़ान पूरी!', 'हल्की लैंडिंग', 'Qucaq चल पड़ा!', '{count} सितारे मिले'],
  ja: ['Tumurcuq の飛行', '葉っぱのパラシュートで飛び、星を集めて風を乗り越えよう。', '画面を押し続けると上昇、離すと下降。枝を避け、星を集めてゴールへ。ライフは3つです。', '上昇', '離す · 下降', '風の流れ', '狭い通路', '動く枝', '秘密の道',
    '道を開こう', '車をスライドして Qucaq の出口を開こう。', '車は向いている方向にだけ動かせます。Qucaq の緑の車を右の出口へ。車を選んで矢印でも操作できます。', '鍵マークの車を丸印の駐車位置へ動かし、出口を開こう。', '出口', '車', 'バス', '飛行成功！', '小さな着陸', 'Qucaq が出発！', '星を {count} 個集めた'],
  ko: ['Tumurcuq의 비행', '나뭇잎 낙하산으로 날며 별을 모으고 바람을 통과하세요.', '화면을 누르고 있으면 올라가고 놓으면 내려가요. 가지를 피하고 별을 모아 도착하세요. 목숨은 3개예요.', '상승', '놓기 · 하강', '바람 흐름', '좁은 통로', '움직이는 가지', '비밀 길',
    '길을 열어요', '차를 밀어 Qucaq의 출구를 열어요.', '차는 자신의 방향으로만 움직여요. Qucaq의 초록 차를 오른쪽 출구로 내보내세요. 차를 선택하고 화살표도 쓸 수 있어요.', '열쇠 표시 차를 원이 있는 주차칸으로 옮겨 출구를 여세요.', '출구', '자동차', '버스', '비행 완료!', '작은 착륙', 'Qucaq가 출발했어요!', '별 {count}개 수집'],
  pl: ['Lot Tumurcuq', 'Leć na liściowym spadochronie, zbieraj gwiazdy i pokonuj wiatr.', 'Przytrzymaj ekran, by wzlecieć; puść, by opaść. Omijaj gałęzie, zbieraj gwiazdy i dotrzyj do mety. Masz 3 życia.', 'Wzleć', 'Puść · opadnij', 'Prądy powietrza', 'Wąskie przejścia', 'Ruchome gałęzie', 'Sekretne trasy',
    'Otwórz drogę', 'Przesuwaj auta, by Qucaq mógł wyjechać.', 'Każde auto przesuwa się tylko w swoim kierunku. Wyprowadź zielone auto Qucaq przez prawy wyjazd. Możesz wybrać auto i używać strzałek.', 'Przesuń auto z kluczem na miejsce z kółkiem, aby otworzyć wyjazd.', 'Wyjazd', 'Auta', 'Autobus', 'Lot ukończony!', 'Małe lądowanie', 'Qucaq rusza w drogę!', 'Zebrano {count} gwiazd'],
  nl: ['Tumurcuqs vlucht', 'Vlieg met een bladparachute, verzamel sterren en trotseer de wind.', 'Houd het scherm vast om te stijgen; laat los om te dalen. Ontwijk takken, pak sterren en bereik de finish. Je hebt 3 levens.', 'Stijgen', 'Loslaten · dalen', 'Windstromen', 'Smalle doorgangen', 'Bewegende takken', 'Geheime routes',
    'Maak de weg vrij', 'Schuif auto’s en maak Qucaqs uitweg vrij.', 'Schuif elke auto alleen in zijn eigen richting. Rijd Qucaqs groene auto rechts naar buiten. Je kunt ook een auto selecteren en pijlen gebruiken.', 'Zet de auto met de sleutel op het omcirkelde vak om de uitgang te openen.', 'Uitgang', 'Auto’s', 'Bus', 'Vlucht voltooid!', 'Een kleine landing', 'Qucaq gaat op pad!', '{count} sterren verzameld'],
  sv: ['Tumurcuqs flygtur', 'Flyg med en lövfallskärm, samla stjärnor och ta dig genom vinden.', 'Håll skärmen för att stiga, släpp för att sjunka. Undvik grenar, samla stjärnor och nå målet. Du har 3 liv.', 'Stig', 'Släpp · sjunk', 'Vindströmmar', 'Smala passager', 'Rörliga grenar', 'Hemliga vägar',
    'Öppna vägen', 'Skjut bilarna och öppna Qucaqs utfart.', 'Varje bil rör sig bara i sin riktning. Kör Qucaqs gröna bil genom högra utfarten. Du kan välja en bil och använda pilar.', 'Flytta bilen med nyckeln till den ringade platsen för att öppna utfarten.', 'Utfart', 'Bilar', 'Buss', 'Flygturen klar!', 'En liten landning', 'Qucaq är på väg!', '{count} stjärnor samlade'],
};
export const CASUAL_MESSAGES = Object.fromEntries(Object.entries(COPY).map(([language, values]) => {
  if (values.length !== KEYS.length) throw new Error(`CASUAL_COPY_LENGTH_${language}`);
  return [language, Object.fromEntries(KEYS.map((key, index) => [key, values[index]]))];
})) as Record<string, Record<CasualMessageKey, string>>;
export function casualText(language: string, key: CasualTextKey, values: Record<string, string | number> = {}): string {
  const messages = CASUAL_MESSAGES[normalizeAppLanguage(language)];
  return Object.prototype.hasOwnProperty.call(messages, key) ? messages[key as CasualMessageKey].replace(/\{(\w+)\}/g, (placeholder, name) => values[name] === undefined ? placeholder : String(values[name]))
    : friendsText(language, key as FriendsMessageKey, values);
}
