-- ============================================================
-- Xəstəxana/Klinika Seed: Saudi Arabia (10 provider)
-- Mənbə: AI-əsaslı "bot" (generate-healthcare-providers.cjs) — YALNIZ məşhur/sabit
-- flaqman xəstəxanalar; əmin olunmayan telefon/veb-sayt sahələri NULL saxlanılıb.
-- ⚠️ Canlıya keçirmədən əvvəl bir neçə sətri əl ilə yoxlamaq tövsiyə olunur.
-- İdempotent: name+country_code üzrə WHERE NOT EXISTS.
-- ============================================================

INSERT INTO public.healthcare_providers (id, name, name_en, provider_type, specialty, specialty_en, city, country_code, phone, website, is_featured, is_active) SELECT '576bedd5-7189-4870-afd2-da3b89dab9ec', 'مستشفى النساء التخصصي بمدينة الملك فهد الطبية', 'Women''s Specialized Hospital, King Fahad Medical City', 'hospital', 'أمراض النساء والولادة وطب الأم والجنين', 'Obstetrics, Gynecology & Maternal-Fetal Medicine', 'Riyadh', 'SA', NULL, 'https://www.kfmc.med.sa/', true, true WHERE NOT EXISTS (SELECT 1 FROM public.healthcare_providers WHERE name = 'مستشفى النساء التخصصي بمدينة الملك فهد الطبية' AND country_code = 'SA');
INSERT INTO public.healthcare_providers (id, name, name_en, provider_type, specialty, specialty_en, city, country_code, phone, website, is_featured, is_active) SELECT '33fe4051-c0f6-4521-98f6-7323f3ee5b07', 'مستشفى الملك خالد الجامعي', 'King Khalid University Hospital', 'hospital', 'مستشفى جامعي عام وأمراض النساء والولادة', 'University Hospital, Obstetrics & Gynecology', 'Riyadh', 'SA', NULL, 'https://medicalcity.ksu.edu.sa/', true, true WHERE NOT EXISTS (SELECT 1 FROM public.healthcare_providers WHERE name = 'مستشفى الملك خالد الجامعي' AND country_code = 'SA');
INSERT INTO public.healthcare_providers (id, name, name_en, provider_type, specialty, specialty_en, city, country_code, phone, website, is_featured, is_active) SELECT '00276e40-3d62-4258-8f11-707e82b2c7ef', 'مدينة الملك عبدالعزيز الطبية بالرياض', 'King Abdulaziz Medical City, Riyadh', 'hospital', 'رعاية تخصصية وأمراض النساء والولادة وطب الأطفال', 'Specialist Care, Obstetrics, Gynecology & Pediatrics', 'Riyadh', 'SA', NULL, 'https://ngha.med.sa/', true, true WHERE NOT EXISTS (SELECT 1 FROM public.healthcare_providers WHERE name = 'مدينة الملك عبدالعزيز الطبية بالرياض' AND country_code = 'SA');
INSERT INTO public.healthcare_providers (id, name, name_en, provider_type, specialty, specialty_en, city, country_code, phone, website, is_featured, is_active) SELECT '65393c33-b0e2-4410-bfc9-66ee7c4e298f', 'مستشفى الملك عبدالله التخصصي للأطفال', 'King Abdullah Specialized Children''s Hospital', 'hospital', 'طب الأطفال التخصصي', 'Specialist Pediatric Care', 'Riyadh', 'SA', NULL, 'https://ngha.med.sa/', true, true WHERE NOT EXISTS (SELECT 1 FROM public.healthcare_providers WHERE name = 'مستشفى الملك عبدالله التخصصي للأطفال' AND country_code = 'SA');
INSERT INTO public.healthcare_providers (id, name, name_en, provider_type, specialty, specialty_en, city, country_code, phone, website, is_featured, is_active) SELECT 'd6c8ddca-ce77-4caf-840e-9d34e0dcdb61', 'مستشفى الملك فيصل التخصصي ومركز الأبحاث', 'King Faisal Specialist Hospital and Research Centre', 'hospital', 'الرعاية التخصصية للنساء والأطفال', 'Specialist Women''s and Children''s Care', 'Riyadh', 'SA', '+966 11 464 7272', 'https://www.kfshrc.edu.sa/', true, true WHERE NOT EXISTS (SELECT 1 FROM public.healthcare_providers WHERE name = 'مستشفى الملك فيصل التخصصي ومركز الأبحاث' AND country_code = 'SA');
INSERT INTO public.healthcare_providers (id, name, name_en, provider_type, specialty, specialty_en, city, country_code, phone, website, is_featured, is_active) SELECT 'ffe87830-e9dd-4b0f-a1d6-1ba0956f211a', 'مدينة الملك سعود الطبية', 'King Saud Medical City', 'hospital', 'الرعاية العامة وأمراض النساء والولادة وطب الأطفال', 'General Care, Obstetrics, Gynecology & Pediatrics', 'Riyadh', 'SA', NULL, 'https://www.ksmc.med.sa/', true, true WHERE NOT EXISTS (SELECT 1 FROM public.healthcare_providers WHERE name = 'مدينة الملك سعود الطبية' AND country_code = 'SA');
INSERT INTO public.healthcare_providers (id, name, name_en, provider_type, specialty, specialty_en, city, country_code, phone, website, is_featured, is_active) SELECT 'fadb3f27-48fe-4447-9371-f8fa1249c34a', 'مستشفى الولادة والأطفال بجدة', 'Maternity and Children''s Hospital, Jeddah', 'hospital', 'النساء والولادة وطب الأطفال', 'Obstetrics, Gynecology & Pediatrics', 'Jeddah', 'SA', NULL, NULL, true, true WHERE NOT EXISTS (SELECT 1 FROM public.healthcare_providers WHERE name = 'مستشفى الولادة والأطفال بجدة' AND country_code = 'SA');
INSERT INTO public.healthcare_providers (id, name, name_en, provider_type, specialty, specialty_en, city, country_code, phone, website, is_featured, is_active) SELECT '3da21ace-ebdf-433b-8a09-650397a72af2', 'مستشفى الولادة والأطفال بالدمام', 'Maternity and Children''s Hospital, Dammam', 'hospital', 'النساء والولادة وطب الأطفال', 'Obstetrics, Gynecology & Pediatrics', 'Dammam', 'SA', NULL, NULL, true, true WHERE NOT EXISTS (SELECT 1 FROM public.healthcare_providers WHERE name = 'مستشفى الولادة والأطفال بالدمام' AND country_code = 'SA');
INSERT INTO public.healthcare_providers (id, name, name_en, provider_type, specialty, specialty_en, city, country_code, phone, website, is_featured, is_active) SELECT '946d27b7-b94b-4188-a073-a8836a74e583', 'مستشفى الدكتور سليمان فقيه', 'Dr. Soliman Fakeeh Hospital', 'hospital', 'الرعاية العامة وأمراض النساء والولادة وطب الأطفال', 'General Care, Obstetrics, Gynecology & Pediatrics', 'Jeddah', 'SA', NULL, 'https://www.fakeeh.care/', true, true WHERE NOT EXISTS (SELECT 1 FROM public.healthcare_providers WHERE name = 'مستشفى الدكتور سليمان فقيه' AND country_code = 'SA');
INSERT INTO public.healthcare_providers (id, name, name_en, provider_type, specialty, specialty_en, city, country_code, phone, website, is_featured, is_active) SELECT 'a04e6f65-b8ca-4ab5-9519-e4a996dc78ad', 'المركز الطبي الدولي', 'International Medical Center', 'hospital', 'الرعاية العامة وأمراض النساء والولادة وطب الأطفال', 'General Care, Obstetrics, Gynecology & Pediatrics', 'Jeddah', 'SA', NULL, 'https://www.imc.med.sa/', true, true WHERE NOT EXISTS (SELECT 1 FROM public.healthcare_providers WHERE name = 'المركز الطبي الدولي' AND country_code = 'SA');
