-- ============================================================
-- Xəstəxana/Klinika: United Arab Emirates — mövcud 8 sətirdən 4-ü üçün
-- telefon/veb-sayt doğrulaması + 10 YENİ sətir (real veb-tədqiqat).
-- 3 saytın köhnəlmiş/işləməyən URL-i də düzəldildi (Corniche Hospital və
-- Al Jalila Children's Hospital köhnə domenləri artıq parked/defunct-dır —
-- SEHA/Dubai Health-in yeni rəsmi səhifələrinə yönləndirildi).
-- İdempotent: UPDATE-lər zərərsiz təkrar; INSERT-lər name_en+country_code
-- üzrə WHERE NOT EXISTS.
-- ============================================================

-- --- Mövcud sətirlərdə tapılan telefon/veb-sayt düzəlişləri ---
UPDATE public.healthcare_providers SET phone = '02 811 7777', website = 'https://www.seha.ae/hospital-detail/38' WHERE name_en = 'Corniche Hospital' AND country_code = 'AE';
UPDATE public.healthcare_providers SET phone = '800 60', website = 'https://dubaihealth.ae/facility/hospital/latifa-hospital' WHERE name_en = 'Latifa Hospital for Women and Children' AND country_code = 'AE';
UPDATE public.healthcare_providers SET phone = '800 96626' WHERE name_en = 'Danat Al Emarat Hospital for Women & Children' AND country_code = 'AE';
UPDATE public.healthcare_providers SET phone = '800 60', website = 'https://dubaihealth.ae/facility/hospital/al-jalila-childrens-hospital' WHERE name_en = 'Al Jalila Children''s Hospital' AND country_code = 'AE';

-- --- 10 YENİ sətir ---
INSERT INTO public.healthcare_providers (name, name_en, provider_type, specialty, specialty_en, description, description_en, address, address_en, city, country_code, phone, website, is_featured, is_active) SELECT 'مستشفى برجيل - أبوظبي', 'Burjeel Hospital, Abu Dhabi', 'hospital', 'أمراض النساء والتوليد', 'Obstetrics & Gynecology', 'مستشفى معتمد من JCI يضم قسمًا متخصصًا لأمراض النساء والتوليد ومعهد متقدم لطب النساء وعيادة لطب الأجنة.', 'A JCI-accredited multi-specialty hospital with a dedicated Gynecology & Obstetrics department and an Advanced Gynecology Institute.', 'Al Najdah Street, P.O. Box 7400, Abu Dhabi', 'Al Najdah Street, P.O. Box 7400, Abu Dhabi', 'Abu Dhabi', 'AE', '+971 2 508 5555', 'https://burjeel.com/abu-dhabi/', true, true WHERE NOT EXISTS (SELECT 1 FROM public.healthcare_providers WHERE name_en = 'Burjeel Hospital, Abu Dhabi' AND country_code = 'AE');
INSERT INTO public.healthcare_providers (name, name_en, provider_type, specialty, specialty_en, description, description_en, address, address_en, city, country_code, phone, website, is_featured, is_active) SELECT 'المستشفى الأمريكي دبي', 'American Hospital Dubai', 'hospital', 'أمراض النساء والتوليد', 'Obstetrics & Gynecology', 'مستشفى خاص من 252 سريرًا وعضو في شبكة Mayo Clinic، يضم قسمًا شاملاً لأمراض النساء والتوليد يغطي طب الأجنة والولادة الطبيعية والقيصرية.', 'A 252-bed private hospital and Mayo Clinic Care Network member, with a comprehensive OB-GYN department covering fetal medicine, water birth, and C-sections.', '19th St, Oud Metha, P.O. Box 5566, Dubai', '19th St, Oud Metha, P.O. Box 5566, Dubai', 'Dubai', 'AE', '+971 4 377 5500', 'https://www.ahdubai.com/', true, true WHERE NOT EXISTS (SELECT 1 FROM public.healthcare_providers WHERE name_en = 'American Hospital Dubai' AND country_code = 'AE');
INSERT INTO public.healthcare_providers (name, name_en, provider_type, specialty, specialty_en, description, description_en, address, address_en, city, country_code, phone, website, is_featured, is_active) SELECT 'مستشفى زليخة - دبي', 'Zulekha Hospital, Dubai', 'hospital', 'أمراض النساء والتوليد', 'Obstetrics & Gynecology', 'مستشفى متعدد التخصصات تأسس عام 1964، يقدم باقات ولادة وأقسام توليد ونساء وحديثي ولادة.', 'A multi-specialty hospital founded in 1964, offering maternity packages alongside Obstetrics, Gynaecology, and Neonatology departments.', 'Doha Street, Al Nahda 2, Al Qusais, Dubai', 'Doha Street, Al Nahda 2, Al Qusais, Dubai', 'Dubai', 'AE', '600 52 4442', 'https://www.zulekhahospitals.com/', true, true WHERE NOT EXISTS (SELECT 1 FROM public.healthcare_providers WHERE name_en = 'Zulekha Hospital, Dubai' AND country_code = 'AE');
INSERT INTO public.healthcare_providers (name, name_en, provider_type, specialty, specialty_en, description, description_en, address, address_en, city, country_code, phone, website, is_featured, is_active) SELECT 'مستشفى ميدكير للنساء والأطفال', 'Medcare Women & Children Hospital', 'hospital', 'أمراض النساء والتوليد وطب الأطفال', 'Obstetrics, Gynecology & Pediatrics', 'مستشفى متخصص من 93 سريرًا يديره طاقم غالبيته من النساء، يقدم التوليد وأمراض النساء وطب الأجنة وحديثي الولادة.', 'A 93-bed specialty hospital staffed largely by women, offering obstetrics, gynecology, maternal-fetal medicine, and neonatology.', 'Sheikh Zayed Road, beside Manara Service Centre, Dubai', 'Sheikh Zayed Road, beside Manara Service Centre, Dubai', 'Dubai', 'AE', '800 633 2273', 'https://www.medcare.ae/en/branches/view/medcare-women-children-hospital.html', true, true WHERE NOT EXISTS (SELECT 1 FROM public.healthcare_providers WHERE name_en = 'Medcare Women & Children Hospital' AND country_code = 'AE');
INSERT INTO public.healthcare_providers (name, name_en, provider_type, specialty, specialty_en, description, description_en, address, address_en, city, country_code, phone, website, is_featured, is_active) SELECT 'مركز فقيه لأطفال الأنابيب', 'Fakih IVF Fertility Center', 'clinic', 'طب الخصوبة وأطفال الأنابيب وأمراض النساء والتوليد', 'Fertility & IVF, Obstetrics & Gynecology', 'أول مركز خاص لأطفال الأنابيب في دبي (2011)، يقدم خدمات الخصوبة والفحص الجيني وطب النساء والتوليد.', 'The first private IVF center in Dubai (est. 2011), offering fertility/IVF-ICSI, genetic testing, and OB-GYN services across multiple UAE locations.', '37, 65b St. – Al Wasl Road, Jumeirah 1, P.O. Box 72960, Dubai', '37, 65b St. – Al Wasl Road, Jumeirah 1, P.O. Box 72960, Dubai', 'Dubai', 'AE', '+971 4 349 7600', 'https://www.fakihivf.com/', true, true WHERE NOT EXISTS (SELECT 1 FROM public.healthcare_providers WHERE name_en = 'Fakih IVF Fertility Center' AND country_code = 'AE');
INSERT INTO public.healthcare_providers (name, name_en, provider_type, specialty, specialty_en, description, description_en, address, address_en, city, country_code, phone, website, is_featured, is_active) SELECT 'مستشفى NMC رويال - مدينة خليفة', 'NMC Royal Hospital, Khalifa City', 'hospital', 'أمراض النساء والتوليد', 'Obstetrics & Gynecology', 'مستشفى إحالة من 200 سرير مع طوارئ على مدار الساعة، يضم قسمًا كاملاً لأمراض النساء والتوليد وطب الأجنة والقبالة ووحدة عناية مركزة لحديثي الولادة.', 'A 200-bed tertiary referral hospital with 24/7 emergency care, featuring a full Obstetrics & Gynaecology department, foetal medicine, midwifery services, and a NICU.', '16th St., Khalifa City - A, P.O. Box 35233, Abu Dhabi', '16th St., Khalifa City - A, P.O. Box 35233, Abu Dhabi', 'Abu Dhabi', 'AE', '800 1122', 'https://nmc.ae/en/locations/abu-dhabi/nmc-royal-hospital-khalifa-city', true, true WHERE NOT EXISTS (SELECT 1 FROM public.healthcare_providers WHERE name_en = 'NMC Royal Hospital, Khalifa City' AND country_code = 'AE');
INSERT INTO public.healthcare_providers (name, name_en, provider_type, specialty, specialty_en, description, description_en, address, address_en, city, country_code, phone, website, is_featured, is_active) SELECT 'مستشفى رأس الخيمة', 'RAK Hospital', 'hospital', 'أمراض النساء والتوليد', 'Obstetrics & Gynecology', 'مستشفى رأس الخيمة الرائد يقدم باقات ولادة مميزة وقسمًا متخصصًا لأمراض النساء والتوليد وطب الأطفال وحديثي الولادة.', 'Ras Al Khaimah''s leading private hospital, offering premium maternity packages alongside dedicated Obstetrics & Gynaecology and Pediatrics/Neonatology departments.', 'Al Qusaidat, P.O. Box 11393, Ras Al Khaimah', 'Al Qusaidat, P.O. Box 11393, Ras Al Khaimah', 'Ras Al Khaimah', 'AE', '+971 7 207 4444', 'https://rakhospital.com/', true, true WHERE NOT EXISTS (SELECT 1 FROM public.healthcare_providers WHERE name_en = 'RAK Hospital' AND country_code = 'AE');
INSERT INTO public.healthcare_providers (name, name_en, provider_type, specialty, specialty_en, description, description_en, address, address_en, city, country_code, phone, website, is_featured, is_active) SELECT 'مستشفى ثمباي الجامعي', 'Thumbay University Hospital', 'hospital', 'أمراض النساء والتوليد', 'Obstetrics & Gynecology', 'أكبر مستشفى أكاديمي خاص في المنطقة (350 سريرًا)، يضم مركزًا لأمراض النساء والتوليد مع 10 غرف ولادة ووحدة عناية مركزة لحديثي الولادة.', 'The largest private academic hospital in the region (350 beds), with a dedicated Center for Obstetrics & Gynecology, 10 labor/delivery rooms, and a NICU.', 'Thumbay Medicity, Al Jurf, Ajman', 'Thumbay Medicity, Al Jurf, Ajman', 'Ajman', 'AE', '600 515 555', 'https://thumbayuniversityhospital.com/', true, true WHERE NOT EXISTS (SELECT 1 FROM public.healthcare_providers WHERE name_en = 'Thumbay University Hospital' AND country_code = 'AE');
INSERT INTO public.healthcare_providers (name, name_en, provider_type, specialty, specialty_en, description, description_en, address, address_en, city, country_code, phone, website, is_featured, is_active) SELECT 'مستشفى ثمباي - الفجيرة', 'Thumbay Hospital, Fujairah', 'hospital', 'أمراض النساء والتوليد', 'Obstetrics & Gynecology', 'مستشفى متعدد التخصصات من 60 سريرًا (سابقًا مستشفى GMC الفجيرة) معتمد من JCI، يضم قسم أمراض نساء وتوليد وبرنامج "صحة المرأة" المخصص.', 'A JCI-accredited 60-bed multi-specialty hospital (formerly GMC Hospital Fujairah), with an Obstetrics & Gynecology department and a dedicated "Women Wellness" program.', 'Next to Fujairah Football Stadium, Sheikh Khalifa Bin Zayed Street, Fujairah', 'Next to Fujairah Football Stadium, Sheikh Khalifa Bin Zayed Street, Fujairah', 'Fujairah', 'AE', '600 515 555', 'https://thumbayhospital.com/fujairah/', true, true WHERE NOT EXISTS (SELECT 1 FROM public.healthcare_providers WHERE name_en = 'Thumbay Hospital, Fujairah' AND country_code = 'AE');
INSERT INTO public.healthcare_providers (name, name_en, provider_type, specialty, specialty_en, description, description_en, address, address_en, city, country_code, phone, website, is_featured, is_active) SELECT 'مستشفى أستر - دبي', 'Aster Hospital, Dubai', 'hospital', 'أمراض النساء والتوليد', 'Obstetrics & Gynecology', 'مستشفى متعدد التخصصات ضمن مجموعة Aster DM Healthcare، يضم قسمي أمراض النساء والتوليد وجراحة النساء بالمنظار، وبرنامج "Aster Nurture" لباقات الحمل.', 'A multi-specialty hospital under Aster DM Healthcare, with Obstetrics & Gynecology and Laparoscopic Gynaecology departments plus the "Aster Nurture" maternity package program.', 'Al Qusais, Dubai', 'Al Qusais, Dubai', 'Dubai', 'AE', '+971 4 440 0500', 'https://www.asterhospitals.ae/', true, true WHERE NOT EXISTS (SELECT 1 FROM public.healthcare_providers WHERE name_en = 'Aster Hospital, Dubai' AND country_code = 'AE');
