-- ============================================================
-- Xəstəxana/Klinika: Kazakhstan — mövcud 8 sətirin telefon/veb-sayt
-- doğrulaması + 10 YENİ sətir (real veb-tədqiqat + çarpaz-yoxlama, Task
-- agent, webfetch + 2GIS.kz biznes kataloqu ilə). Bəzi rəsmi .kz saytları
-- avtomatlaşdırılmış fetch-i bloklayır (403) — bu hallarda ünvan/telefon
-- 2GIS.kz-də (rəsmi qeydiyyatlı təşkilat kataloqu) çarpaz-yoxlanılıb.
-- UPDATE-lər idempotentdir (hər dəfə eyni dəyəri yazır, zərərsiz təkrar).
-- İdempotent INSERT: name_en+country_code üzrə WHERE NOT EXISTS.
-- ============================================================

-- --- Mövcud 8 sətirdən 7-si üçün telefon/veb-sayt tapıldı (ilk sətir - NCAGIP - artıq Duzelis9-da düzəldilib) ---
UPDATE public.healthcare_providers SET phone = '+7 771 944-45-80' WHERE name_en = 'National Research Center for Maternal and Child Health' AND country_code = 'KZ';
UPDATE public.healthcare_providers SET phone = '+7 727 299-26-87' WHERE name_en = 'Scientific Center of Pediatrics and Pediatric Surgery' AND country_code = 'KZ';
UPDATE public.healthcare_providers SET phone = '+7 727 337-84-74', website = 'https://perinatal-cardio.kz' WHERE name_en = 'Center of Perinatology and Pediatric Cardiac Surgery' AND country_code = 'KZ';
UPDATE public.healthcare_providers SET phone = '+7 727 230-17-91', website = 'https://almaty-perinatal.kz' WHERE name_en = 'Almaty City Perinatal Center' AND country_code = 'KZ';
UPDATE public.healthcare_providers SET phone = '+7 7212 94-04-77', website = 'https://okbkar.kz' WHERE name_en = 'Karaganda Regional Perinatal Center' AND country_code = 'KZ';
UPDATE public.healthcare_providers SET phone = '+7 7252 77-40-59', website = 'https://gpc-shymkent.kz' WHERE name_en = 'Shymkent City Perinatal Center' AND country_code = 'KZ';
UPDATE public.healthcare_providers SET phone = '+7 7132 45-70-78', website = 'https://aktobe-opc.kz' WHERE name_en = 'Aktobe Regional Perinatal Center' AND country_code = 'KZ';

-- --- 10 YENİ sətir ---
INSERT INTO public.healthcare_providers (name, name_en, provider_type, specialty, specialty_en, description, description_en, address, address_en, city, country_code, phone, website, is_featured, is_active) SELECT 'Павлодар облыстық перинаталдық орталығы №1', 'Pavlodar Regional Perinatal Center No. 1', 'hospital', 'Акушерлік-гинекология, перинатология', 'Obstetrics, Gynecology & Perinatology', 'Павлодар облысындағы жүкті әйелдер мен жаңа туған нәрестелерге мамандандырылған көмек көрсететін облыстық перинаталдық орталық.', 'The regional perinatal facility serving Pavlodar region for high-risk maternity and newborn care.', 'ул. Генерала Дюсенова, 4 к2, Павлодар, 140000', 'ул. Генерала Дюсенова, 4 к2, Павлодар, 140000', 'Pavlodar', 'KZ', '+7 7182 20-99-10', NULL, true, true WHERE NOT EXISTS (SELECT 1 FROM public.healthcare_providers WHERE name_en = 'Pavlodar Regional Perinatal Center No. 1' AND country_code = 'KZ');
INSERT INTO public.healthcare_providers (name, name_en, provider_type, specialty, specialty_en, description, description_en, address, address_en, city, country_code, phone, website, is_featured, is_active) SELECT 'Абай облысы "Облыстық перинаталдық орталығы" (Семей)', 'Abai Region Perinatal Center (Semey)', 'hospital', 'Акушерлік-гинекология, неонатология, перинатология', 'Obstetrics, Gynecology, Neonatology & Perinatology', 'Абай облысы денсаулық сақтау басқармасына қарасты, Семей қаласында орналасқан облыстық перинаталдық орталық.', 'The regional perinatal center of Abai Region, located in Semey.', 'Жамакаев көшесі, 100, Семей', 'Жамакаев көшесі, 100, Семей', 'Semey', 'KZ', '+7 7222 32-47-77', 'https://pcsemey.kz', true, true WHERE NOT EXISTS (SELECT 1 FROM public.healthcare_providers WHERE name_en = 'Abai Region Perinatal Center (Semey)' AND country_code = 'KZ');
INSERT INTO public.healthcare_providers (name, name_en, provider_type, specialty, specialty_en, description, description_en, address, address_en, city, country_code, phone, website, is_featured, is_active) SELECT 'Атырау облыстық перинаталдық орталығы', 'Atyrau Regional Perinatal Center', 'hospital', 'Акушерлік-гинекология, перинатология', 'Obstetrics, Gynecology & Perinatology', 'Атырау облысындағы жүктілік пен босануды қадағалайтын және жаңа туған нәрестелерге көмек көрсететін облыстық мекеме.', 'The regional facility overseeing maternity and newborn care for Atyrau region.', 'ул. Адмирала Льва Владимирского, 22а, Атырау', 'ул. Адмирала Льва Владимирского, 22а, Атырау', 'Atyrau', 'KZ', '+7 7122 30-77-95', NULL, true, true WHERE NOT EXISTS (SELECT 1 FROM public.healthcare_providers WHERE name_en = 'Atyrau Regional Perinatal Center' AND country_code = 'KZ');
INSERT INTO public.healthcare_providers (name, name_en, provider_type, specialty, specialty_en, description, description_en, address, address_en, city, country_code, phone, website, is_featured, is_active) SELECT 'Жамбыл облыстық перинаталдық орталығы', 'Zhambyl Regional Perinatal Center', 'hospital', 'Акушерлік-гинекология, перинатология', 'Obstetrics, Gynecology & Perinatology', 'Жамбыл облысы әкімдігінің денсаулық сақтау басқармасына қарасты, Тараз қаласындағы облыстық перинаталдық орталық.', 'The regional perinatal center under the Zhambyl Region Health Department, located in Taraz.', 'ул. Мангилик Ел, 1Б, Тараз, 080000', 'ул. Мангилик Ел, 1Б, Тараз, 080000', 'Taraz', 'KZ', '+7 7262 54-22-30', NULL, true, true WHERE NOT EXISTS (SELECT 1 FROM public.healthcare_providers WHERE name_en = 'Zhambyl Regional Perinatal Center' AND country_code = 'KZ');
INSERT INTO public.healthcare_providers (name, name_en, provider_type, specialty, specialty_en, description, description_en, address, address_en, city, country_code, phone, website, is_featured, is_active) SELECT 'Қостанай перинаталдық орталығы', 'Kostanay Perinatal Center', 'hospital', 'Акушерлік-гинекология, перинатология', 'Obstetrics, Gynecology & Perinatology', 'Қостанай облысы әкімдігінің денсаулық сақтау басқармасына қарасты, жүктілік пен босануға мамандандырылған мекеме.', 'The perinatal facility under the Kostanay Region Health Department, specializing in pregnancy and delivery care.', 'ул. Шаяхметова, 120, Костанай, 110000', 'ул. Шаяхметова, 120, Костанай, 110000', 'Kostanay', 'KZ', '+7 7142 57-47-71', NULL, true, true WHERE NOT EXISTS (SELECT 1 FROM public.healthcare_providers WHERE name_en = 'Kostanay Perinatal Center' AND country_code = 'KZ');
INSERT INTO public.healthcare_providers (name, name_en, provider_type, specialty, specialty_en, description, description_en, address, address_en, city, country_code, phone, website, is_featured, is_active) SELECT 'Батыс Қазақстан облыстық перинаталдық орталығы', 'West Kazakhstan Regional Perinatal Center', 'hospital', 'Акушерлік-гинекология, перинатология, жаңа туған нәрестелер патологиясы', 'Obstetrics, Gynecology, Perinatology & Neonatal Care', 'Батыс Қазақстан облысындағы жүктілік, босану және жаңа туған нәрестелерге арналған облыстық мамандандырылған орталық.', 'The West Kazakhstan region''s specialized center for pregnancy, delivery, and newborn care, located in Uralsk.', 'ул. Героя Советского Союза Ахмирова, 4, Уральск', 'ул. Героя Советского Союза Ахмирова, 4, Уральск', 'Uralsk', 'KZ', '+7 7112 26-64-22', NULL, true, true WHERE NOT EXISTS (SELECT 1 FROM public.healthcare_providers WHERE name_en = 'West Kazakhstan Regional Perinatal Center' AND country_code = 'KZ');
INSERT INTO public.healthcare_providers (name, name_en, provider_type, specialty, specialty_en, description, description_en, address, address_en, city, country_code, phone, website, is_featured, is_active) SELECT 'Солтүстік Қазақстан облыстық перинаталдық орталығы', 'North Kazakhstan Regional Perinatal Center', 'hospital', 'Акушерлік-гинекология, перинатология', 'Obstetrics, Gynecology & Perinatology', 'Солтүстік Қазақстан облысы әкімдігінің денсаулық сақтау басқармасына қарасты облыстық перинаталдық орталық.', 'The regional perinatal center under the North Kazakhstan Region Health Department, located in Petropavlovsk.', 'ул. Казахстанской Правды, 233, Петропавловск, 150009', 'ул. Казахстанской Правды, 233, Петропавловск, 150009', 'Petropavlovsk', 'KZ', '+7 7152 42-18-96', NULL, true, true WHERE NOT EXISTS (SELECT 1 FROM public.healthcare_providers WHERE name_en = 'North Kazakhstan Regional Perinatal Center' AND country_code = 'KZ');
INSERT INTO public.healthcare_providers (name, name_en, provider_type, specialty, specialty_en, description, description_en, address, address_en, city, country_code, phone, website, is_featured, is_active) SELECT 'Қызылорда облыстық перинаталдық орталығы', 'Kyzylorda Regional Perinatal Center', 'hospital', 'Акушерлік-гинекология, перинатология, неонатология', 'Obstetrics, Gynecology, Perinatology & Neonatology', 'Қызылорда облысы денсаулық сақтау басқармасына қарасты, жүктілік пен босануды қадағалайтын облыстық мекеме, 2024 жылы ұлттық аккредитациядан өтті.', 'Kyzylorda region''s perinatal institution, which successfully passed national accreditation in 2024, providing obstetric and neonatal care.', 'ул. Султана Бейбарса, 12, Кызылорда, 120000', 'ул. Султана Бейбарса, 12, Кызылорда, 120000', 'Kyzylorda', 'KZ', '+7 7242 21-48-13', 'https://opc-gov.kz', true, true WHERE NOT EXISTS (SELECT 1 FROM public.healthcare_providers WHERE name_en = 'Kyzylorda Regional Perinatal Center' AND country_code = 'KZ');
INSERT INTO public.healthcare_providers (name, name_en, provider_type, specialty, specialty_en, description, description_en, address, address_en, city, country_code, phone, website, is_featured, is_active) SELECT 'Шығыс Қазақстан облысының "Ана мен бала орталығы"', 'East Kazakhstan Region Center for Mother and Child', 'hospital', 'Акушерлік-гинекология, перинатология, реанимация', 'Obstetrics, Gynecology, Perinatology & ICU', 'Шығыс Қазақстан облысындағы босандыру, гинекология, жүктілік патологиясы және нәрестелер реанимациясы бөлімшелерін біріктірген "Ана мен бала орталығы".', 'East Kazakhstan region''s "Center for Mother and Child," combining maternity, gynecology, high-risk pregnancy, and newborn/adult ICU departments.', 'ул. Оралхан Бокей, 35, Усть-Каменогорск, 070016', 'ул. Оралхан Бокей, 35, Усть-Каменогорск, 070016', 'Ust-Kamenogorsk', 'KZ', '+7 7232 75-55-29', NULL, true, true WHERE NOT EXISTS (SELECT 1 FROM public.healthcare_providers WHERE name_en = 'East Kazakhstan Region Center for Mother and Child' AND country_code = 'KZ');
INSERT INTO public.healthcare_providers (name, name_en, provider_type, specialty, specialty_en, description, description_en, address, address_en, city, country_code, phone, website, is_featured, is_active) SELECT 'Mediker Hospital International', 'Mediker Hospital International', 'clinic', 'Гинекология, акушер-гинеколог дәрігерлер, әйелдерге арналған Check-up', 'Gynecology, Obstetrician-Gynecologists, Women''s Check-up Programs', 'Жеке меншік көпбейінді клиника, оның ішінде арнайы гинекология хирургия бөлімі мен акушер-гинеколог дәрігерлері бар "Әйелдер Check-up" бағдарламасы жұмыс істейді.', 'A private multi-specialty clinic in Almaty with a dedicated Gynecology surgical department, on-staff obstetrician-gynecologists, and a "Women''s Check-up" program.', 'ул. Азербаева, 67, Алматы', 'ул. Азербаева, 67, Алматы', 'Almaty', 'KZ', '+7 727 313-11-13', 'https://mih.kz', true, true WHERE NOT EXISTS (SELECT 1 FROM public.healthcare_providers WHERE name_en = 'Mediker Hospital International' AND country_code = 'KZ');
