-- ============================================================
-- Xəstəxana/Klinika Seed: Saudi Arabia (10 provider)
-- Mənbə: AI-əsaslı "bot" (generate-healthcare-providers.cjs) — YALNIZ məşhur/sabit
-- flaqman xəstəxanalar; əmin olunmayan telefon/veb-sayt sahələri NULL saxlanılıb.
-- ⚠️ Canlıya keçirmədən əvvəl bir neçə sətri əl ilə yoxlamaq tövsiyə olunur.
-- İdempotent: name+country_code üzrə WHERE NOT EXISTS.
-- ============================================================

INSERT INTO public.healthcare_providers (id, name, name_en, provider_type, specialty, specialty_en, city, country_code, phone, website, is_featured, is_active) SELECT 'c39756bb-c065-4f54-9606-b1b746ab8af7', 'مستشفى النساء التخصصي بمدينة الملك فهد الطبية', 'Women''s Specialized Hospital, King Fahad Medical City', 'hospital', 'أمراض النساء والولادة وطب الأم والجنين', 'Obstetrics, Gynecology & Maternal-Fetal Medicine', 'Riyadh', 'SA', NULL, 'https://www.kfmc.med.sa/', true, true WHERE NOT EXISTS (SELECT 1 FROM public.healthcare_providers WHERE name = 'مستشفى النساء التخصصي بمدينة الملك فهد الطبية' AND country_code = 'SA');
INSERT INTO public.healthcare_providers (id, name, name_en, provider_type, specialty, specialty_en, city, country_code, phone, website, is_featured, is_active) SELECT '51649678-0b8f-4fa6-8cba-6f382eb55b18', 'مستشفى الملك خالد الجامعي', 'King Khalid University Hospital', 'hospital', 'مستشفى جامعي عام وأمراض النساء والولادة', 'University Hospital, Obstetrics & Gynecology', 'Riyadh', 'SA', NULL, 'https://medicalcity.ksu.edu.sa/', true, true WHERE NOT EXISTS (SELECT 1 FROM public.healthcare_providers WHERE name = 'مستشفى الملك خالد الجامعي' AND country_code = 'SA');
INSERT INTO public.healthcare_providers (id, name, name_en, provider_type, specialty, specialty_en, city, country_code, phone, website, is_featured, is_active) SELECT '6ac77123-e9d1-4fb8-9636-9eb80fede194', 'مدينة الملك عبدالعزيز الطبية بالرياض', 'King Abdulaziz Medical City, Riyadh', 'hospital', 'رعاية تخصصية وأمراض النساء والولادة وطب الأطفال', 'Specialist Care, Obstetrics, Gynecology & Pediatrics', 'Riyadh', 'SA', NULL, 'https://ngha.med.sa/', true, true WHERE NOT EXISTS (SELECT 1 FROM public.healthcare_providers WHERE name = 'مدينة الملك عبدالعزيز الطبية بالرياض' AND country_code = 'SA');
INSERT INTO public.healthcare_providers (id, name, name_en, provider_type, specialty, specialty_en, city, country_code, phone, website, is_featured, is_active) SELECT 'e1d71baa-8dac-4bcf-b58e-378306e76a1d', 'مستشفى الملك عبدالله التخصصي للأطفال', 'King Abdullah Specialized Children''s Hospital', 'hospital', 'طب الأطفال التخصصي', 'Specialist Pediatric Care', 'Riyadh', 'SA', NULL, 'https://ngha.med.sa/', true, true WHERE NOT EXISTS (SELECT 1 FROM public.healthcare_providers WHERE name = 'مستشفى الملك عبدالله التخصصي للأطفال' AND country_code = 'SA');
INSERT INTO public.healthcare_providers (id, name, name_en, provider_type, specialty, specialty_en, city, country_code, phone, website, is_featured, is_active) SELECT '0fd4fdbf-3248-4417-ae9e-6f71070d7188', 'مستشفى الملك فيصل التخصصي ومركز الأبحاث', 'King Faisal Specialist Hospital and Research Centre', 'hospital', 'الرعاية التخصصية للنساء والأطفال', 'Specialist Women''s and Children''s Care', 'Riyadh', 'SA', NULL, 'https://www.kfshrc.edu.sa/', true, true WHERE NOT EXISTS (SELECT 1 FROM public.healthcare_providers WHERE name = 'مستشفى الملك فيصل التخصصي ومركز الأبحاث' AND country_code = 'SA');
INSERT INTO public.healthcare_providers (id, name, name_en, provider_type, specialty, specialty_en, city, country_code, phone, website, is_featured, is_active) SELECT 'f184e671-08bc-4176-9b1e-be9eb8535945', 'مدينة الملك سعود الطبية', 'King Saud Medical City', 'hospital', 'الرعاية العامة وأمراض النساء والولادة وطب الأطفال', 'General Care, Obstetrics, Gynecology & Pediatrics', 'Riyadh', 'SA', NULL, 'https://www.ksmc.med.sa/', true, true WHERE NOT EXISTS (SELECT 1 FROM public.healthcare_providers WHERE name = 'مدينة الملك سعود الطبية' AND country_code = 'SA');
INSERT INTO public.healthcare_providers (id, name, name_en, provider_type, specialty, specialty_en, city, country_code, phone, website, is_featured, is_active) SELECT '5920a8b2-2d7f-4340-907c-c604b95f9812', 'مستشفى الولادة والأطفال بجدة', 'Maternity and Children''s Hospital, Jeddah', 'hospital', 'النساء والولادة وطب الأطفال', 'Obstetrics, Gynecology & Pediatrics', 'Jeddah', 'SA', NULL, NULL, true, true WHERE NOT EXISTS (SELECT 1 FROM public.healthcare_providers WHERE name = 'مستشفى الولادة والأطفال بجدة' AND country_code = 'SA');
INSERT INTO public.healthcare_providers (id, name, name_en, provider_type, specialty, specialty_en, city, country_code, phone, website, is_featured, is_active) SELECT 'ad738482-4622-43c7-9ec1-f3c24c834d2e', 'مستشفى الولادة والأطفال بالدمام', 'Maternity and Children''s Hospital, Dammam', 'hospital', 'النساء والولادة وطب الأطفال', 'Obstetrics, Gynecology & Pediatrics', 'Dammam', 'SA', NULL, NULL, true, true WHERE NOT EXISTS (SELECT 1 FROM public.healthcare_providers WHERE name = 'مستشفى الولادة والأطفال بالدمام' AND country_code = 'SA');
INSERT INTO public.healthcare_providers (id, name, name_en, provider_type, specialty, specialty_en, city, country_code, phone, website, is_featured, is_active) SELECT 'd942341c-ccfb-426d-a3ef-a891a30c6685', 'مستشفى الدكتور سليمان فقيه', 'Dr. Soliman Fakeeh Hospital', 'hospital', 'الرعاية العامة وأمراض النساء والولادة وطب الأطفال', 'General Care, Obstetrics, Gynecology & Pediatrics', 'Jeddah', 'SA', NULL, 'https://www.fakeeh.care/', true, true WHERE NOT EXISTS (SELECT 1 FROM public.healthcare_providers WHERE name = 'مستشفى الدكتور سليمان فقيه' AND country_code = 'SA');
INSERT INTO public.healthcare_providers (id, name, name_en, provider_type, specialty, specialty_en, city, country_code, phone, website, is_featured, is_active) SELECT '8aa58d08-b5de-4fd2-bb2d-78833c0383cb', 'المركز الطبي الدولي', 'International Medical Center', 'hospital', 'الرعاية العامة وأمراض النساء والولادة وطب الأطفال', 'General Care, Obstetrics, Gynecology & Pediatrics', 'Jeddah', 'SA', NULL, 'https://www.imc.med.sa/', true, true WHERE NOT EXISTS (SELECT 1 FROM public.healthcare_providers WHERE name = 'المركز الطبي الدولي' AND country_code = 'SA');
