-- ============================================================
-- Xəstəxana/Klinika: Saudi Arabia — mövcud 10 sətirdən 7-si üçün telefon
-- doğrulaması (rəsmi sayt / Wayback Machine arxivi) + 6 YENİ sətir.
-- Maternity and Children's Hospital (Jeddah/Dammam) və King Faisal Specialist
-- Hospital üçün telefon TAPILMADI (rəsmi onlayn mövcudluq yoxdur/əvvəlcədən
-- yoxlanılıb) — uydurmaqdansa dəyişməz saxlanılıb (NULL qalır).
-- İdempotent: UPDATE-lər zərərsiz təkrar; INSERT-lər name_en+country_code
-- üzrə WHERE NOT EXISTS.
-- ============================================================

-- --- Mövcud sətirlərdə tapılan telefonlar ---
UPDATE public.healthcare_providers SET phone = '800 127 7000' WHERE name_en = 'Women''s Specialized Hospital, King Fahad Medical City' AND country_code = 'SA';
UPDATE public.healthcare_providers SET phone = '920004071' WHERE name_en = 'King Khalid University Hospital' AND country_code = 'SA';
UPDATE public.healthcare_providers SET phone = '+966-11-801-1111' WHERE name_en = 'King Abdulaziz Medical City, Riyadh' AND country_code = 'SA';
UPDATE public.healthcare_providers SET phone = '+966-11-801-1111' WHERE name_en = 'King Abdullah Specialized Children''s Hospital' AND country_code = 'SA';
UPDATE public.healthcare_providers SET phone = '011-435-5555' WHERE name_en = 'King Saud Medical City' AND country_code = 'SA';
UPDATE public.healthcare_providers SET phone = '+966 9200 12777' WHERE name_en = 'Dr. Soliman Fakeeh Hospital' AND country_code = 'SA';
UPDATE public.healthcare_providers SET phone = '+966 920027778' WHERE name_en = 'International Medical Center' AND country_code = 'SA';

-- --- 6 YENİ sətir ---
INSERT INTO public.healthcare_providers (name, name_en, provider_type, specialty, specialty_en, description, description_en, address, address_en, city, country_code, phone, website, is_featured, is_active) SELECT 'مستشفى الدكتور سليمان فقيه - المدينة المنورة', 'Dr. Soliman Fakeeh Hospital, Madinah', 'hospital', 'أمراض النساء والولادة', 'Obstetrics & Gynecology', 'فرع مستشفى الدكتور سليمان فقيه بالمدينة المنورة، يضم قسمًا متخصصًا لأمراض النساء والولادة وباقات صحية مخصصة للمرأة.', 'The Madinah branch of Dr. Soliman Fakeeh Hospital, featuring a dedicated Obstetrics & Gynecology department and women''s health packages.', 'طريق الملك عبدالله بن عبدالعزيز آل سعود، حي الفتح، المدينة المنورة 42312', 'King Abdullah bin Abdulaziz Al Saud Road, Al Fath District, Madinah 42312', 'Madinah', 'SA', '+966 9200 12777', 'https://dsfhmadinah.fakeeh.care/', true, true WHERE NOT EXISTS (SELECT 1 FROM public.healthcare_providers WHERE name_en = 'Dr. Soliman Fakeeh Hospital, Madinah' AND country_code = 'SA');
INSERT INTO public.healthcare_providers (name, name_en, provider_type, specialty, specialty_en, description, description_en, address, address_en, city, country_code, phone, website, is_featured, is_active) SELECT 'مستشفى المواساة - المدينة المنورة', 'Mouwasat Hospital, Madinah', 'hospital', 'أمراض النساء والولادة', 'Obstetrics & Gynecology', 'أول مستشفى رقمي بالمدينة المنورة (200 سرير)، يضم قسمًا لأمراض النساء والولادة ضمن 36 تخصصًا طبيًا.', 'Madinah''s first fully digital hospital (200 beds), featuring an Obstetrics & Gynecology department among 36 medical specialties.', 'مدينة المعرفة الاقتصادية، المدينة المنورة', 'Knowledge Economic City, Madinah', 'Madinah', 'SA', '+966 920 004 477', 'https://www.mouwasat.com/en/hospital/mouwasat-hospital-madinah', true, true WHERE NOT EXISTS (SELECT 1 FROM public.healthcare_providers WHERE name_en = 'Mouwasat Hospital, Madinah' AND country_code = 'SA');
INSERT INTO public.healthcare_providers (name, name_en, provider_type, specialty, specialty_en, description, description_en, address, address_en, city, country_code, phone, website, is_featured, is_active) SELECT 'مستشفى المواساة - الخبر', 'Mouwasat Hospital, Khobar', 'hospital', 'أمراض النساء والولادة', 'Obstetrics & Gynecology', 'مستشفى رائد في المنطقة الشرقية تأسس عام 2018 (260 سريرًا)، يضم قسمًا لأمراض النساء والولادة وأول مركز جراحة روبوتية في المنطقة.', 'A leading Eastern Province hospital established in 2018 (260 beds), with an OB-GYN department and the region''s first robotic surgery center.', 'حي المروج، الخبر', 'Al Muruj District, Khobar', 'Khobar', 'SA', '+966 920 004 477', 'https://www.mouwasat.com/en/hospital/mouwasat-hospital-khobar', true, true WHERE NOT EXISTS (SELECT 1 FROM public.healthcare_providers WHERE name_en = 'Mouwasat Hospital, Khobar' AND country_code = 'SA');
INSERT INTO public.healthcare_providers (name, name_en, provider_type, specialty, specialty_en, description, description_en, address, address_en, city, country_code, phone, website, is_featured, is_active) SELECT 'المستشفى السعودي الألماني - الدمام', 'Saudi German Hospital, Dammam', 'hospital', 'قسم أمراض النساء والتوليد', 'Obstetrics and Gynecology Department', 'مستشفى متعدد التخصصات في الدمام تابع لمجموعة المستشفيات السعودية الألمانية، ويضم قسمًا لأمراض النساء والتوليد.', 'A multi-specialty hospital in Dammam within the Saudi German Hospitals Group, including an Obstetrics and Gynecology Department.', 'ضمن مدينة باترجي الطبية، الدمام', 'Batterjee Medical City, Dammam', 'Dammam', 'SA', '+966 920 007 997', 'https://dammam.saudigermanhealth.com/en', true, true WHERE NOT EXISTS (SELECT 1 FROM public.healthcare_providers WHERE name_en = 'Saudi German Hospital, Dammam' AND country_code = 'SA');
INSERT INTO public.healthcare_providers (name, name_en, provider_type, specialty, specialty_en, description, description_en, address, address_en, city, country_code, phone, website, is_featured, is_active) SELECT 'المستشفى السعودي الألماني - مكة المكرمة', 'Saudi German Hospital, Makkah', 'hospital', 'قسم أمراض النساء والتوليد', 'Obstetrics and Gynecology Department', 'الفرع الثامن لمجموعة المستشفيات السعودية الألمانية، افتُتح عام 2022 في مكة المكرمة ويضم قسمًا لأمراض النساء والتوليد.', 'The 8th branch of the Saudi German Hospitals Group, opened in 2022 in Makkah, including an Obstetrics and Gynecology Department.', 'مكة المكرمة', 'Makkah', 'Makkah', 'SA', '+966 920 007 997', 'https://saudigermanhealth.com/en/makkah', true, true WHERE NOT EXISTS (SELECT 1 FROM public.healthcare_providers WHERE name_en = 'Saudi German Hospital, Makkah' AND country_code = 'SA');
INSERT INTO public.healthcare_providers (name, name_en, provider_type, specialty, specialty_en, description, description_en, address, address_en, city, country_code, phone, website, is_featured, is_active) SELECT 'مستشفى الملك سلمان التخصصي بالطائف', 'King Salman Specialist Hospital, Taif', 'hospital', 'قسم الولادة وفحص ما قبل الولادة', 'Maternity and Prenatal Check-up Department', 'مستشفى تابع للشؤون الصحية بوزارة الحرس الوطني في الطائف بسعة 300 سرير، يضم قسمًا للولادة وفحص ما قبل الولادة.', 'An NGHA (Ministry of National Guard Health Affairs) hospital in Taif with 300 beds, including a maternity/labor and prenatal check-up department.', 'الطائف', 'Taif', 'Taif', 'SA', NULL, 'https://ngha.med.sa/', true, true WHERE NOT EXISTS (SELECT 1 FROM public.healthcare_providers WHERE name_en = 'King Salman Specialist Hospital, Taif' AND country_code = 'SA');
