-- ============================================================
-- Xəstəxana/Klinika Seed: Kazakhstan (8 provider)
-- Mənbə: AI-əsaslı "bot" (generate-healthcare-providers.cjs) — YALNIZ məşhur/sabit
-- flaqman xəstəxanalar; əmin olunmayan telefon/veb-sayt sahələri NULL saxlanılıb.
-- ⚠️ Canlıya keçirmədən əvvəl bir neçə sətri əl ilə yoxlamaq tövsiyə olunur.
-- İdempotent: name+country_code üzrə WHERE NOT EXISTS.
-- ============================================================

INSERT INTO public.healthcare_providers (id, name, name_en, provider_type, specialty, specialty_en, city, country_code, phone, website, is_featured, is_active) SELECT '00925c64-a6cf-4d12-8e16-a057a979050d', 'Акушерлік, гинекология және перинатология ғылыми орталығы', 'Scientific Center of Obstetrics, Gynecology and Perinatology', 'hospital', 'Акушерлік, гинекология және перинатология', 'Obstetrics, Gynecology & Perinatology', 'Almaty', 'KZ', NULL, 'https://ncagip.kz/', true, true WHERE NOT EXISTS (SELECT 1 FROM public.healthcare_providers WHERE name = 'Акушерлік, гинекология және перинатология ғылыми орталығы' AND country_code = 'KZ');
INSERT INTO public.healthcare_providers (id, name, name_en, provider_type, specialty, specialty_en, city, country_code, phone, website, is_featured, is_active) SELECT '3e3376c8-5a95-42e4-9d35-de4dcd2bb21c', 'Ана мен бала ұлттық ғылыми орталығы', 'National Research Center for Maternal and Child Health', 'hospital', 'Акушерлік, гинекология, перинатология және педиатрия', 'Obstetrics, Gynecology, Perinatology & Pediatrics', 'Astana', 'KZ', NULL, 'https://umc.org.kz/', true, true WHERE NOT EXISTS (SELECT 1 FROM public.healthcare_providers WHERE name = 'Ана мен бала ұлттық ғылыми орталығы' AND country_code = 'KZ');
INSERT INTO public.healthcare_providers (id, name, name_en, provider_type, specialty, specialty_en, city, country_code, phone, website, is_featured, is_active) SELECT 'efcf2663-93d7-40f4-8905-968baf97e646', 'Педиатрия және балалар хирургиясы ғылыми орталығы', 'Scientific Center of Pediatrics and Pediatric Surgery', 'hospital', 'Педиатрия және балалар хирургиясы', 'Pediatrics & Pediatric Surgery', 'Almaty', 'KZ', NULL, 'https://pediatria.kz/', true, true WHERE NOT EXISTS (SELECT 1 FROM public.healthcare_providers WHERE name = 'Педиатрия және балалар хирургиясы ғылыми орталығы' AND country_code = 'KZ');
INSERT INTO public.healthcare_providers (id, name, name_en, provider_type, specialty, specialty_en, city, country_code, phone, website, is_featured, is_active) SELECT '0f02f3f7-c7b0-408c-8d82-1333e8ec321e', 'Перинатология және балалар кардиохирургиясы орталығы', 'Center of Perinatology and Pediatric Cardiac Surgery', 'hospital', 'Перинатология және балалар кардиохирургиясы', 'Perinatology & Pediatric Cardiac Surgery', 'Almaty', 'KZ', NULL, NULL, true, true WHERE NOT EXISTS (SELECT 1 FROM public.healthcare_providers WHERE name = 'Перинатология және балалар кардиохирургиясы орталығы' AND country_code = 'KZ');
INSERT INTO public.healthcare_providers (id, name, name_en, provider_type, specialty, specialty_en, city, country_code, phone, website, is_featured, is_active) SELECT 'bc7d6ec8-d7a7-4ba1-a91d-5faf8294cec1', 'Алматы қалалық перинаталдық орталығы', 'Almaty City Perinatal Center', 'hospital', 'Акушерлік, гинекология және неонатология', 'Obstetrics, Gynecology & Neonatology', 'Almaty', 'KZ', NULL, NULL, true, true WHERE NOT EXISTS (SELECT 1 FROM public.healthcare_providers WHERE name = 'Алматы қалалық перинаталдық орталығы' AND country_code = 'KZ');
INSERT INTO public.healthcare_providers (id, name, name_en, provider_type, specialty, specialty_en, city, country_code, phone, website, is_featured, is_active) SELECT '5b2ca25d-b397-4be0-8491-8bef821940a3', 'Қарағанды облыстық перинаталдық орталығы', 'Karaganda Regional Perinatal Center', 'hospital', 'Акушерлік, перинатология және неонатология', 'Obstetrics, Perinatology & Neonatology', 'Karaganda', 'KZ', NULL, NULL, true, true WHERE NOT EXISTS (SELECT 1 FROM public.healthcare_providers WHERE name = 'Қарағанды облыстық перинаталдық орталығы' AND country_code = 'KZ');
INSERT INTO public.healthcare_providers (id, name, name_en, provider_type, specialty, specialty_en, city, country_code, phone, website, is_featured, is_active) SELECT 'ee5eabd1-4613-4889-a06b-3720ccfd5508', 'Шымкент қалалық перинаталдық орталығы', 'Shymkent City Perinatal Center', 'hospital', 'Акушерлік, перинатология және неонатология', 'Obstetrics, Perinatology & Neonatology', 'Shymkent', 'KZ', NULL, NULL, true, true WHERE NOT EXISTS (SELECT 1 FROM public.healthcare_providers WHERE name = 'Шымкент қалалық перинаталдық орталығы' AND country_code = 'KZ');
INSERT INTO public.healthcare_providers (id, name, name_en, provider_type, specialty, specialty_en, city, country_code, phone, website, is_featured, is_active) SELECT 'be870dcf-eda1-4242-b572-37029a288989', 'Ақтөбе облыстық перинаталдық орталығы', 'Aktobe Regional Perinatal Center', 'hospital', 'Акушерлік, перинатология және неонатология', 'Obstetrics, Perinatology & Neonatology', 'Aktobe', 'KZ', NULL, NULL, true, true WHERE NOT EXISTS (SELECT 1 FROM public.healthcare_providers WHERE name = 'Ақтөбе облыстық перинаталдық орталығы' AND country_code = 'KZ');
