-- ============================================================
-- Xəstəxana/Klinika Seed: United Arab Emirates (8 provider)
-- Mənbə: AI-əsaslı "bot" (generate-healthcare-providers.cjs) — YALNIZ məşhur/sabit
-- flaqman xəstəxanalar; əmin olunmayan telefon/veb-sayt sahələri NULL saxlanılıb.
-- ⚠️ Canlıya keçirmədən əvvəl bir neçə sətri əl ilə yoxlamaq tövsiyə olunur.
-- İdempotent: name+country_code üzrə WHERE NOT EXISTS.
-- ============================================================

INSERT INTO public.healthcare_providers (id, name, name_en, provider_type, specialty, specialty_en, city, country_code, phone, website, is_featured, is_active) SELECT 'aabe6fce-37db-462a-9995-8fdc466e6849', 'مستشفى الكورنيش', 'Corniche Hospital', 'hospital', 'أمراض النساء والتوليد ورعاية حديثي الولادة', 'Obstetrics, Gynecology & Neonatal Care', 'Abu Dhabi', 'AE', NULL, 'https://www.cornichehospital.ae/', true, true WHERE NOT EXISTS (SELECT 1 FROM public.healthcare_providers WHERE name = 'مستشفى الكورنيش' AND country_code = 'AE');
INSERT INTO public.healthcare_providers (id, name, name_en, provider_type, specialty, specialty_en, city, country_code, phone, website, is_featured, is_active) SELECT '171f27c7-6ea6-487f-98f9-7c981a1ba5fc', 'مستشفى لطيفة للنساء والأطفال', 'Latifa Hospital for Women and Children', 'hospital', 'أمراض النساء والتوليد وطب الأطفال', 'Obstetrics, Gynecology & Pediatrics', 'Dubai', 'AE', NULL, 'https://www.dha.gov.ae/en/facilities/hospitals/latifa-hospital', true, true WHERE NOT EXISTS (SELECT 1 FROM public.healthcare_providers WHERE name = 'مستشفى لطيفة للنساء والأطفال' AND country_code = 'AE');
INSERT INTO public.healthcare_providers (id, name, name_en, provider_type, specialty, specialty_en, city, country_code, phone, website, is_featured, is_active) SELECT 'e16cfc34-83be-4a0c-a14d-ace710069b35', 'مستشفى دانة الإمارات للنساء والأطفال', 'Danat Al Emarat Hospital for Women & Children', 'hospital', 'صحة المرأة والولادة وطب الأطفال', 'Women''s Health, Maternity & Pediatrics', 'Abu Dhabi', 'AE', NULL, 'https://danatalemarat.ae/', true, true WHERE NOT EXISTS (SELECT 1 FROM public.healthcare_providers WHERE name = 'مستشفى دانة الإمارات للنساء والأطفال' AND country_code = 'AE');
INSERT INTO public.healthcare_providers (id, name, name_en, provider_type, specialty, specialty_en, city, country_code, phone, website, is_featured, is_active) SELECT 'f4af58f6-41e7-412e-8b2f-d3ad4913e9d9', 'مستشفى توام', 'Tawam Hospital', 'hospital', 'مستشفى تخصصي وتعليمي؛ أمراض النساء والتوليد', 'Specialist Teaching Hospital; Obstetrics & Gynecology', 'Al Ain', 'AE', '800 50', 'https://tawam.seha.ae/', true, true WHERE NOT EXISTS (SELECT 1 FROM public.healthcare_providers WHERE name = 'مستشفى توام' AND country_code = 'AE');
INSERT INTO public.healthcare_providers (id, name, name_en, provider_type, specialty, specialty_en, city, country_code, phone, website, is_featured, is_active) SELECT '4c8a3b46-a4f6-431f-883a-2885d8c6845f', 'مستشفى الجليلة للأطفال', 'Al Jalila Children''s Hospital', 'hospital', 'طب الأطفال التخصصي', 'Specialist Pediatric Care', 'Dubai', 'AE', NULL, 'https://aljalilachildrens.ae/', true, true WHERE NOT EXISTS (SELECT 1 FROM public.healthcare_providers WHERE name = 'مستشفى الجليلة للأطفال' AND country_code = 'AE');
INSERT INTO public.healthcare_providers (id, name, name_en, provider_type, specialty, specialty_en, city, country_code, phone, website, is_featured, is_active) SELECT '6a1c9937-4c12-479f-b145-cc84cd34578c', 'مستشفى كند', 'Kanad Hospital', 'hospital', 'أمراض النساء والتوليد وطب الأطفال', 'Obstetrics, Gynecology & Pediatrics', 'Al Ain', 'AE', '+971 3 713 1111', 'https://kanadhospital.org/', true, true WHERE NOT EXISTS (SELECT 1 FROM public.healthcare_providers WHERE name = 'مستشفى كند' AND country_code = 'AE');
INSERT INTO public.healthcare_providers (id, name, name_en, provider_type, specialty, specialty_en, city, country_code, phone, website, is_featured, is_active) SELECT '1a26f06f-cee5-4985-919e-a4068b9cd61c', 'المستشفى الجامعي بالشارقة', 'University Hospital Sharjah', 'hospital', 'مستشفى جامعي؛ أمراض النساء والتوليد وطب الأطفال', 'University Hospital; Obstetrics, Gynecology & Pediatrics', 'Sharjah', 'AE', '+971 6 505 8555', 'https://www.uhs.ae/', true, true WHERE NOT EXISTS (SELECT 1 FROM public.healthcare_providers WHERE name = 'المستشفى الجامعي بالشارقة' AND country_code = 'AE');
INSERT INTO public.healthcare_providers (id, name, name_en, provider_type, specialty, specialty_en, city, country_code, phone, website, is_featured, is_active) SELECT '5a0eff80-7d3c-44e8-89da-f579603023e4', 'مستشفى ميدكلينك سيتي', 'Mediclinic City Hospital', 'hospital', 'مستشفى متعدد التخصصات؛ أمراض النساء والتوليد', 'Multispecialty Hospital; Obstetrics & Gynecology', 'Dubai', 'AE', '+971 4 4359900', 'https://www.mediclinic.ae/en/city-hospital/home.html', true, true WHERE NOT EXISTS (SELECT 1 FROM public.healthcare_providers WHERE name = 'مستشفى ميدكلينك سيتي' AND country_code = 'AE');
