-- ============================================================
-- Xəstəxana/Klinika: Azerbaijan — mövcud 13 sətir canlı DB-dən birbaşa
-- sorğulanıb (anon key, RLS is_active=true ictimai oxunaqlıdır) və 3-ü
-- spot-check edilib (Caspian International Hospital "*0717" QISA KOD
-- TƏSDİQLƏNDİ — səhv deyil, saytda əsas nömrə kimi göstərilir; Liv Bona Dea
-- Hospital telefonu təsdiqləndi + YENİ ünvan tapıldı; Modern Hospital
-- telefonu təsdiqləndi, qadın sağlamlığı şöbəsi TAPILMADI, "Multidisciplinary"
-- etiketi olduğu kimi düzgün saxlanılıb). + 6 YENİ doğrulanmış sətir
-- (13+6=19). Aşağı etimadlı 7-ci namizəd (Avrasiya Hospital) "mükəmməl
-- doğruluq" tələbinə görə BİLƏRƏKDƏN daxil edilməyib.
-- İdempotent: UPDATE-lər zərərsiz təkrar; INSERT-lər name_en+country_code
-- üzrə WHERE NOT EXISTS.
-- ============================================================

-- --- Spot-check zamanı tapılan yeni ünvan/dəqiqləşmə ---
UPDATE public.healthcare_providers SET address = 'Mehdi Abbasov küç. 2, Bakı 1060', address_en = 'Mehdi Abbasov str. 2, Baku 1060', specialty = 'Mamalıq-ginekologiya, Süni mayalanma (İVF), Neonatologiya (çoxprofilli)', specialty_en = 'Obstetrics-Gynecology, IVF, Neonatology (multidisciplinary)' WHERE name = 'Liv Bona Dea Hospital' AND country_code = 'AZ';

-- --- 6 YENİ sətir ---
INSERT INTO public.healthcare_providers (name, name_en, provider_type, specialty, specialty_en, description, description_en, address, address_en, city, country_code, phone, website, is_featured, is_active) SELECT 'Ege Hospital', 'Ege Hospital', 'hospital', 'Cərrah mama-ginekoloq, Kardiologiya, Nevrologiya, Oftalmologiya, Pediatriya, Endokrinologiya', 'Surgeon OB-GYN, Cardiology, Neurology, Ophthalmology, Pediatrics, Endocrinology', 'Ege Hospital-ın həkim heyətində "Cərrah mama-ginekoloq" daxil olmaqla kardiologiya, nevrologiya, pediatriya və endokrinologiya üzrə mütəxəssislər çalışır.', 'Ege Hospital''s medical staff includes a Surgeon OB-GYN alongside cardiology, neurology, pediatrics, and endocrinology specialists.', 'Akademik Həsən Əliyev küçəsi 38, AZ1078, Bakı', 'Akademik Hasan Aliyev str. 38, AZ1078, Baku', 'Bakı', 'AZ', '(+994 12) 599 11 17', 'https://egehospital.az', true, true WHERE NOT EXISTS (SELECT 1 FROM public.healthcare_providers WHERE name_en = 'Ege Hospital' AND country_code = 'AZ');
INSERT INTO public.healthcare_providers (name, name_en, provider_type, specialty, specialty_en, description, description_en, address, address_en, city, country_code, phone, website, is_featured, is_active) SELECT 'Sağlam Ailə Tibb Mərkəzi', 'Healthy Family Medical Center', 'clinic', 'Ginekologiya (Mamalıq-ginekologiya) — hamiləliyin aparılması, 3D USM, qadın sonsuzluğu, kontrasepsiya', 'Gynecology (Obstetrics-Gynecology) — pregnancy management, 3D ultrasound, female infertility, contraception', 'Bakı (bir neçə filial), Sumqayıt və Gəncədə fəaliyyət göstərən bu tibb mərkəzinin Ginekologiya şöbəsi hamiləliyin aparılması, 3D USM və qadın sonsuzluğu müalicəsi daxil olmaqla geniş qadın sağlamlığı xidmətləri göstərir.', 'Operating in Baku (multiple branches), Sumgayit, and Ganja, this medical center''s Gynecology department offers comprehensive women''s health services including pregnancy management, 3D ultrasound, and female infertility treatment.', 'Əhməd Rəcəbli küçəsi 3/10, Nərimanov r-nu, Bakı', 'Ahmad Rajabli str. 3/10, Narimanov district, Baku', 'Bakı', 'AZ', '012 910', 'https://saglamaile.az', true, true WHERE NOT EXISTS (SELECT 1 FROM public.healthcare_providers WHERE name_en = 'Healthy Family Medical Center' AND country_code = 'AZ');
INSERT INTO public.healthcare_providers (name, name_en, provider_type, specialty, specialty_en, description, description_en, address, address_en, city, country_code, phone, website, is_featured, is_active) SELECT 'Elmi-Tədqiqat Mamalıq və Ginekologiya İnstitutu', 'Scientific-Research Institute of Obstetrics and Gynecology', 'hospital', 'Mamalıq və Ginekologiya (dövlət elmi-müalicə müəssisəsi)', 'Obstetrics and Gynecology (state scientific-treatment institution)', 'Azərbaycan Səhiyyə Nazirliyinin rəsmi tabeliyində olan bu institut ölkənin mamalıq-ginekologiya sahəsində ixtisaslaşmış aparıcı dövlət elmi-müalicə müəssisəsidir.', 'Officially under Azerbaijan''s Ministry of Health, this institute is the country''s leading state research-and-treatment institution specializing specifically in obstetrics and gynecology.', 'Kazım Kazımzadə küçəsi 118, Yasamal r-nu, Bakı', 'Kazim Kazimzade str. 118, Yasamal district, Baku', 'Bakı', 'AZ', '(+994 12) 510 09 51', NULL, true, true WHERE NOT EXISTS (SELECT 1 FROM public.healthcare_providers WHERE name_en = 'Scientific-Research Institute of Obstetrics and Gynecology' AND country_code = 'AZ');
INSERT INTO public.healthcare_providers (name, name_en, provider_type, specialty, specialty_en, description, description_en, address, address_en, city, country_code, phone, website, is_featured, is_active) SELECT 'Ailə Planlanması Məsləhətxanası', 'Family Planning Consultation Center', 'clinic', 'Mama-ginekoloq, Uşaq ginekoloqu, Androloq, Endokrinoloq, Genetik — hamiləlik müayinəsi, sonsuzluq, nigahdan əvvəl müayinə', 'Obstetrics-Gynecology, Pediatric Gynecology, Andrology, Endocrinology, Genetics — pregnancy exams, infertility, pre-marital screening', 'Səhiyyə Nazirliyinin tabeliyində fəaliyyət göstərən bu məsləhətxana mama-ginekoloq və uşaq ginekoloqu mütəxəssisləri ilə hamiləlik müayinəsi, sonsuzluq müalicəsi və nigahdan əvvəl müayinə xidmətləri göstərir.', 'Operating under the Ministry of Health, this center offers pregnancy examinations, infertility treatment, and pre-marital screening with dedicated OB-GYN and pediatric-gynecology specialists.', 'Puşkin küçəsi 12A, Bakı, AZ1000', 'Pushkin str. 12A, Baku, AZ1000', 'Bakı', 'AZ', '(+994 12) 498 62 58', 'https://aileplanlanmasi.az', true, true WHERE NOT EXISTS (SELECT 1 FROM public.healthcare_providers WHERE name_en = 'Family Planning Consultation Center' AND country_code = 'AZ');
INSERT INTO public.healthcare_providers (name, name_en, provider_type, specialty, specialty_en, description, description_en, address, address_en, city, country_code, phone, website, is_featured, is_active) SELECT 'Diamed Medical Group', 'Diamed Medical Group', 'clinic', 'Poliklinika (terapevt, kardioloq, nevroloq, uroloq, ginekoloq, LOR), Laboratoriya, Cərrahiyyə Mərkəzi', 'General Polyclinic (internal medicine, cardiology, neurology, urology, gynecology, ENT), Laboratory, Surgery Center', '1999-cu ildən fəaliyyət göstərən Diamed Medical Group-un poliklinikasında digər mütəxəssislərlə yanaşı ginekoloq həkim də xəstə qəbul edir.', 'Operating since 1999, Diamed Medical Group''s polyclinic includes a gynecologist among its roster of specialists, alongside internal medicine, cardiology, neurology, and urology.', 'Akademik Həsən Əliyev küçəsi 493, Nərimanov r-nu, Bakı', 'Akademik Hasan Aliyev str. 493, Narimanov district, Baku', 'Bakı', 'AZ', '(+994 12) 465 06 06', 'https://diamedhospital.az', true, true WHERE NOT EXISTS (SELECT 1 FROM public.healthcare_providers WHERE name_en = 'Diamed Medical Group' AND country_code = 'AZ');
INSERT INTO public.healthcare_providers (name, name_en, provider_type, specialty, specialty_en, description, description_en, address, address_en, city, country_code, phone, website, is_featured, is_active) SELECT 'Şəfa Müalicəvi Diaqnostika Mərkəzi', 'Shafa Treatment & Diagnostic Center', 'clinic', 'Genetik laboratoriya (NIPT, PGD), reproduktiv sağlamlıq müayinələri, hormonlar', 'Genetic Laboratory (NIPT, PGD), Reproductive Health Testing, Hormones', '1996-cı ildən fəaliyyət göstərən bu mərkəz NIPT (qeyri-invaziv prenatal test) və PGD (İVF üçün preimplantasion genetik diaqnostika) daxil olmaqla reproduktiv sağlamlıq və genetik laborator analizlər təqdim edir.', 'Operating since 1996, this center provides reproductive-health and genetic laboratory testing, including NIPT (non-invasive prenatal testing) and PGD (preimplantation genetic diagnosis used in IVF).', 'Həsən bəy Zərdabi küçəsi 84, Yasamal r-nu, Bakı', 'Hasan bey Zardabi str. 84, Yasamal district, Baku', 'Bakı', 'AZ', '(+994 12) 448 38 11', 'https://www.shafa.az', true, true WHERE NOT EXISTS (SELECT 1 FROM public.healthcare_providers WHERE name_en = 'Shafa Treatment & Diagnostic Center' AND country_code = 'AZ');
