-- ============================================================
-- Xəstəxana/Klinika Seed: Germany (8 provider)
-- Mənbə: AI-əsaslı "bot" (generate-healthcare-providers.cjs) — YALNIZ məşhur/sabit
-- flaqman xəstəxanalar; əmin olunmayan telefon/veb-sayt sahələri NULL saxlanılıb.
-- ⚠️ Canlıya keçirmədən əvvəl bir neçə sətri əl ilə yoxlamaq tövsiyə olunur.
-- İdempotent: name+country_code üzrə WHERE NOT EXISTS.
-- ============================================================

INSERT INTO public.healthcare_providers (id, name, name_en, provider_type, specialty, specialty_en, city, country_code, phone, website, is_featured, is_active) SELECT '2eee6341-96d2-40c6-bc50-37acfd4dc689', 'Charité – Universitätsmedizin Berlin', 'Charité – University Medicine Berlin', 'hospital', 'Frauenheilkunde und Geburtshilfe; Kinder- und Jugendmedizin', 'Obstetrics & Gynecology; Pediatrics and Adolescent Medicine', 'Berlin', 'DE', '+49 30 450-50', 'https://www.charite.de/', true, true WHERE NOT EXISTS (SELECT 1 FROM public.healthcare_providers WHERE name = 'Charité – Universitätsmedizin Berlin' AND country_code = 'DE');
INSERT INTO public.healthcare_providers (id, name, name_en, provider_type, specialty, specialty_en, city, country_code, phone, website, is_featured, is_active) SELECT '4341b67a-7b4f-4176-9a9a-ad93f78d4a23', 'LMU Klinikum', 'LMU University Hospital', 'hospital', 'Frauenheilkunde und Geburtshilfe; Kinder- und Jugendmedizin', 'Obstetrics & Gynecology; Pediatrics and Adolescent Medicine', 'München', 'DE', '+49 89 4400-0', 'https://www.lmu-klinikum.de/', true, true WHERE NOT EXISTS (SELECT 1 FROM public.healthcare_providers WHERE name = 'LMU Klinikum' AND country_code = 'DE');
INSERT INTO public.healthcare_providers (id, name, name_en, provider_type, specialty, specialty_en, city, country_code, phone, website, is_featured, is_active) SELECT '3efd73a3-af3e-4e98-8715-e7a74ac24778', 'Universitätsklinikum Heidelberg', 'Heidelberg University Hospital', 'hospital', 'Frauenheilkunde und Geburtshilfe; Kinder- und Jugendmedizin', 'Obstetrics & Gynecology; Pediatrics and Adolescent Medicine', 'Heidelberg', 'DE', '+49 6221 56-0', 'https://www.klinikum.uni-heidelberg.de/', true, true WHERE NOT EXISTS (SELECT 1 FROM public.healthcare_providers WHERE name = 'Universitätsklinikum Heidelberg' AND country_code = 'DE');
INSERT INTO public.healthcare_providers (id, name, name_en, provider_type, specialty, specialty_en, city, country_code, phone, website, is_featured, is_active) SELECT '00a91c37-45ff-4bf7-97a5-b144c1d4cb8e', 'Universitätsklinikum Hamburg-Eppendorf (UKE)', 'University Medical Center Hamburg-Eppendorf', 'hospital', 'Frauenheilkunde und Geburtshilfe; Kinder- und Jugendmedizin', 'Obstetrics & Gynecology; Pediatrics and Adolescent Medicine', 'Hamburg', 'DE', '+49 40 7410-0', 'https://www.uke.de/', true, true WHERE NOT EXISTS (SELECT 1 FROM public.healthcare_providers WHERE name = 'Universitätsklinikum Hamburg-Eppendorf (UKE)' AND country_code = 'DE');
INSERT INTO public.healthcare_providers (id, name, name_en, provider_type, specialty, specialty_en, city, country_code, phone, website, is_featured, is_active) SELECT 'e27d4341-1e2e-4a3b-a366-18db763a1ae6', 'Medizinische Hochschule Hannover (MHH)', 'Hannover Medical School', 'hospital', 'Frauenheilkunde und Geburtshilfe; Kinder- und Jugendmedizin', 'Obstetrics & Gynecology; Pediatrics and Adolescent Medicine', 'Hannover', 'DE', '+49 511 532-0', 'https://www.mhh.de/', true, true WHERE NOT EXISTS (SELECT 1 FROM public.healthcare_providers WHERE name = 'Medizinische Hochschule Hannover (MHH)' AND country_code = 'DE');
INSERT INTO public.healthcare_providers (id, name, name_en, provider_type, specialty, specialty_en, city, country_code, phone, website, is_featured, is_active) SELECT '3ac45403-6c77-4691-ac2c-6d9780e153e0', 'Uniklinik Köln', 'University Hospital Cologne', 'hospital', 'Frauenheilkunde und Geburtshilfe; Kinder- und Jugendmedizin', 'Obstetrics & Gynecology; Pediatrics and Adolescent Medicine', 'Köln', 'DE', '+49 221 478-0', 'https://www.uk-koeln.de/', true, true WHERE NOT EXISTS (SELECT 1 FROM public.healthcare_providers WHERE name = 'Uniklinik Köln' AND country_code = 'DE');
INSERT INTO public.healthcare_providers (id, name, name_en, provider_type, specialty, specialty_en, city, country_code, phone, website, is_featured, is_active) SELECT 'e1642e37-15d2-4134-b6d1-6223d55dfddd', 'Universitätsklinikum Freiburg', 'University Medical Center Freiburg', 'hospital', 'Frauenheilkunde und Geburtshilfe; Kinder- und Jugendmedizin', 'Obstetrics & Gynecology; Pediatrics and Adolescent Medicine', 'Freiburg im Breisgau', 'DE', '+49 761 270-0', 'https://www.uniklinik-freiburg.de/', true, true WHERE NOT EXISTS (SELECT 1 FROM public.healthcare_providers WHERE name = 'Universitätsklinikum Freiburg' AND country_code = 'DE');
INSERT INTO public.healthcare_providers (id, name, name_en, provider_type, specialty, specialty_en, city, country_code, phone, website, is_featured, is_active) SELECT '0a647ba0-5327-4dda-ae08-3181cdde2a8b', 'Universitätsklinikum Tübingen', 'University Hospital Tübingen', 'hospital', 'Frauenheilkunde und Geburtshilfe; Kinder- und Jugendmedizin', 'Obstetrics & Gynecology; Pediatrics and Adolescent Medicine', 'Tübingen', 'DE', '+49 7071 29-0', 'https://www.medizin.uni-tuebingen.de/', true, true WHERE NOT EXISTS (SELECT 1 FROM public.healthcare_providers WHERE name = 'Universitätsklinikum Tübingen' AND country_code = 'DE');
