-- ============================================================
-- Duzelis1 — teething_symptoms.relief_tips_{ru,tr,kk,de,ar} bug fix
-- Bu sütunlar vergüllə ayrılmış PLAIN STRING kimi saxlanılmışdı (relief_tips_en
-- düzgün JSON-array-string idi) — mapRowTranslation-ın JSON.parse-i fail olub
-- səssizcə əsas (İngilis) massivə geri qayıdırdı (bu, "Wipe drool frequently",
-- "Gentle massage", "Extra cuddles" kimi mətnlərin BÜTÜN dillərdə görünmə bug-udur).
-- Bu fayl mövcud tərcümə MƏZMUNUNU dəyişmir, YALNIZ formatını (comma-string → JSON array).
-- İdempotentdir (artıq düzgün olanlara toxunmur).
-- ============================================================

UPDATE public.teething_symptoms SET relief_tips_ru = '["Надевайте малышу слюнявчик","Чаще вытирайте слюну","Наносите защитный крем"]', relief_tips_tr = '["Bebeğe önlük takın","Salyayı sık sık silin","Bariyer krem sürün"]', relief_tips_kk = '["Бөпеге алжапқыш тағыңыз","Сілекейін жиі сүртіңіз","Қорғаныш кремін жағыңыз"]', relief_tips_de = '["Zieh deinem Baby ein Lätzchen an","Wisch den Speichel regelmäßig ab","Trag eine Schutzcreme auf"]', relief_tips_ar = '["ضعي مريلة لطفلكِ","امسحي اللعاب باستمرار","ضعي كريمًا واقيًا"]' WHERE id = 'da469ca3-dfb2-401a-bc96-10c1f9768175';
UPDATE public.teething_symptoms SET relief_tips_ru = '["Холодное кольцо для прорезывания зубов","Мягкий массаж","Охлаждённая тканевая салфетка"]', relief_tips_tr = '["Soğuk diş kaşıma halkası","Nazik masaj","Soğutulmuş bez"]', relief_tips_kk = '["Салқын тіс шығару сақинасы","Жұмсақ уқалау","Салқындатылған мата"]', relief_tips_de = '["Kalter Beißring","Sanfte Massage","Gekühltes Tuch"]', relief_tips_ar = '["حلقة تسنين باردة","تدليك لطيف","قطعة قماش مبردة"]' WHERE id = '11f5b7df-f534-4677-9297-aff12652de0c';
UPDATE public.teething_symptoms SET relief_tips_ru = '["Чаще обнимайте малыша","Отвлекайте игрушками","Включайте успокаивающие звуки"]', relief_tips_tr = '["Daha fazla kucaklayın","Oyuncaklarla dikkatini dağıtın","Sakinleştirici sesler dinletin"]', relief_tips_kk = '["Көбірек құшақтаңыз","Ойыншықтармен назарын аударыңыз","Тыныштандыратын дыбыстар"]', relief_tips_de = '["Zusätzliche Kuscheleinheiten","Ablenkung mit Spielzeug","Beruhigende Geräusche"]', relief_tips_ar = '["أكثري من احتضانه","شتتي انتباهه بالألعاب","أصوات مهدئة"]' WHERE id = '6dca2abe-b145-4328-aa53-3621d7294068';
UPDATE public.teething_symptoms SET relief_tips_ru = '["Соблюдайте режим","Обезболивающее перед сном","Успокаивающее кормление грудью"]', relief_tips_tr = '["Uyku düzenini koruyun","Yatmadan önce ağrı kesici","Rahatlatıcı emzirme"]', relief_tips_kk = '["Ұйқы режимін сақтаңыз","Ұйықтар алдында ауырсынуды басатын дәрі","Тыныштандыру үшін емізу"]', relief_tips_de = '["Behalte den gewohnten Rhythmus bei","Schmerzmittel vor dem Schlafengehen","Beruhigendes Stillen"]', relief_tips_ar = '["حافظي على الروتين","مسكن للألم قبل النوم","الرضاعة المهدئة"]' WHERE id = '5d314a9d-29c4-4925-a850-549a104c10cc';
UPDATE public.teething_symptoms SET relief_tips_ru = '["Предлагайте прохладную пищу","Попробуйте пищу разной текстуры","Будьте терпеливы"]', relief_tips_tr = '["Soğuk yiyecekler sunun","Farklı dokular deneyin","Sabırlı olun"]', relief_tips_kk = '["Салқын тағамдар ұсыныңыз","Құрылымы әртүрлі тағамдарды қолданып көріңіз","Сабырлы болыңыз"]', relief_tips_de = '["Biete kalte Speisen an","Probiere verschiedene Konsistenzen aus","Hab Geduld"]', relief_tips_ar = '["قدمي له أطعمة باردة","جربي أطعمة بقوامات مختلفة","تحلي بالصبر"]' WHERE id = '8b318d48-e0c5-4e54-9b08-fd79f2a8d46e';
UPDATE public.teething_symptoms SET relief_tips_ru = '["Предлагайте безопасные прорезыватели","Присматривайте за малышом во время игры","Регулярно мойте игрушки"]', relief_tips_tr = '["Güvenli diş kaşıyıcılar verin","Oyun sırasında gözetim altında tutun","Oyuncakları düzenli olarak temizleyin"]', relief_tips_kk = '["Қауіпсіз тіс қышытқыш беріңіз","Ойын кезінде қадағалаңыз","Ойыншықтарды жүйелі түрде тазалаңыз"]', relief_tips_de = '["Biete sichere Beißringe an","Beaufsichtige dein Baby beim Spielen","Reinige das Spielzeug regelmäßig"]', relief_tips_ar = '["قدمي له عضاضات آمنة","راقبيه أثناء اللعب","نظفي الألعاب بانتظام"]' WHERE id = '781c41ff-4633-4c1a-ba59-4e165b56d073';
UPDATE public.teething_symptoms SET relief_tips_ru = '["Убедитесь, что нет ушной инфекции","Массируйте дёсны","Отвлекайте малыша"]', relief_tips_tr = '["Kulak enfeksiyonu açısından kontrol ettirin","Diş eti masajı yapın","Dikkatini dağıtın"]', relief_tips_kk = '["Құлақ инфекциясы бар-жоғын тексеріңіз","Қызыл иекті уқалау","Назарын басқаға аудару"]', relief_tips_de = '["Lass eine Ohrenentzündung ausschließen","Zahnfleischmassage","Ablenkung"]', relief_tips_ar = '["تحققي من وجود التهاب في الأذن","دلكي لثته","شتتي انتباهه"]' WHERE id = 'bb23e53f-eb8b-42a3-8aea-5b43f97b45ef';
UPDATE public.teething_symptoms SET relief_tips_ru = '["Следите за температурой","Давайте малышу достаточно жидкости","Если температура высокая, обратитесь к врачу"]', relief_tips_tr = '["Ateşi takip edin","Bebeğin yeterli sıvı almasını sağlayın","Yüksekse doktora başvurun"]', relief_tips_kk = '["Дене қызуын бақылаңыз","Бөпеге жеткілікті сұйықтық беріңіз","Дене қызуы жоғарыласа, дәрігерге хабарласыңыз"]', relief_tips_de = '["Behalte die Temperatur im Blick","Achte darauf, dass dein Baby ausreichend Flüssigkeit bekommt","Ist die Temperatur höher, wende dich an einen Arzt"]', relief_tips_ar = '["راقبي درجة الحرارة","حافظي على ترطيب طفلكِ","استشيري الطبيب إذا كانت مرتفعة"]' WHERE id = 'f66a15e2-5772-4cf2-9dd9-2fdc2fe21480';
