-- ============================================================
-- Xəstəxana/Klinika Seed: United Arab Emirates (8 provider)
-- Mənbə: AI-əsaslı "bot" (generate-healthcare-providers.cjs) — YALNIZ məşhur/sabit
-- flaqman xəstəxanalar; əmin olunmayan telefon/veb-sayt sahələri NULL saxlanılıb.
-- ⚠️ Canlıya keçirmədən əvvəl bir neçə sətri əl ilə yoxlamaq tövsiyə olunur.
-- İdempotent: name+country_code üzrə WHERE NOT EXISTS.
-- ============================================================

INSERT INTO public.healthcare_providers (id, name, name_en, provider_type, specialty, specialty_en, city, country_code, phone, website, is_featured, is_active) SELECT '589dd289-2b57-4288-865d-a8e7a101c419', 'مستشفى الكورنيش', 'Corniche Hospital', 'hospital', 'أمراض النساء والتوليد ورعاية حديثي الولادة', 'Obstetrics, Gynecology & Neonatal Care', 'Abu Dhabi', 'AE', NULL, 'https://www.cornichehospital.ae/', true, true WHERE NOT EXISTS (SELECT 1 FROM public.healthcare_providers WHERE name = 'مستشفى الكورنيش' AND country_code = 'AE');
INSERT INTO public.healthcare_providers (id, name, name_en, provider_type, specialty, specialty_en, city, country_code, phone, website, is_featured, is_active) SELECT 'b1eef773-30c7-4967-87a5-83c53be45209', 'مستشفى لطيفة للنساء والأطفال', 'Latifa Hospital for Women and Children', 'hospital', 'أمراض النساء والتوليد وطب الأطفال', 'Obstetrics, Gynecology & Pediatrics', 'Dubai', 'AE', NULL, 'https://www.dha.gov.ae/en/facilities/hospitals/latifa-hospital', true, true WHERE NOT EXISTS (SELECT 1 FROM public.healthcare_providers WHERE name = 'مستشفى لطيفة للنساء والأطفال' AND country_code = 'AE');
INSERT INTO public.healthcare_providers (id, name, name_en, provider_type, specialty, specialty_en, city, country_code, phone, website, is_featured, is_active) SELECT '07670197-ca15-4f0e-bb19-a0d2ed0790cb', 'مستشفى دانة الإمارات للنساء والأطفال', 'Danat Al Emarat Hospital for Women & Children', 'hospital', 'صحة المرأة والولادة وطب الأطفال', 'Women''s Health, Maternity & Pediatrics', 'Abu Dhabi', 'AE', NULL, 'https://danatalemarat.ae/', true, true WHERE NOT EXISTS (SELECT 1 FROM public.healthcare_providers WHERE name = 'مستشفى دانة الإمارات للنساء والأطفال' AND country_code = 'AE');
INSERT INTO public.healthcare_providers (id, name, name_en, provider_type, specialty, specialty_en, city, country_code, phone, website, is_featured, is_active) SELECT 'ffc771f9-c0ae-4338-8ea5-1f9e813f23a2', 'مستشفى توام', 'Tawam Hospital', 'hospital', 'مستشفى تخصصي وتعليمي؛ أمراض النساء والتوليد', 'Specialist Teaching Hospital; Obstetrics & Gynecology', 'Al Ain', 'AE', '+971 3 767 7444', 'https://tawam.seha.ae/', true, true WHERE NOT EXISTS (SELECT 1 FROM public.healthcare_providers WHERE name = 'مستشفى توام' AND country_code = 'AE');
INSERT INTO public.healthcare_providers (id, name, name_en, provider_type, specialty, specialty_en, city, country_code, phone, website, is_featured, is_active) SELECT 'df70fb19-5b88-45a1-8105-40b24bb1c006', 'مستشفى الجليلة للأطفال', 'Al Jalila Children''s Hospital', 'hospital', 'طب الأطفال التخصصي', 'Specialist Pediatric Care', 'Dubai', 'AE', NULL, 'https://aljalilachildrens.ae/', true, true WHERE NOT EXISTS (SELECT 1 FROM public.healthcare_providers WHERE name = 'مستشفى الجليلة للأطفال' AND country_code = 'AE');
INSERT INTO public.healthcare_providers (id, name, name_en, provider_type, specialty, specialty_en, city, country_code, phone, website, is_featured, is_active) SELECT 'f5531f70-2889-4181-9356-44a07b1b781a', 'مستشفى كند', 'Kanad Hospital', 'hospital', 'أمراض النساء والتوليد وطب الأطفال', 'Obstetrics, Gynecology & Pediatrics', 'Al Ain', 'AE', '+971 3 713 1111', 'https://kanadhospital.org/', true, true WHERE NOT EXISTS (SELECT 1 FROM public.healthcare_providers WHERE name = 'مستشفى كند' AND country_code = 'AE');
INSERT INTO public.healthcare_providers (id, name, name_en, provider_type, specialty, specialty_en, city, country_code, phone, website, is_featured, is_active) SELECT '818ef412-6d03-4ad6-a307-d6a12ebbe9a4', 'المستشفى الجامعي بالشارقة', 'University Hospital Sharjah', 'hospital', 'مستشفى جامعي؛ أمراض النساء والتوليد وطب الأطفال', 'University Hospital; Obstetrics, Gynecology & Pediatrics', 'Sharjah', 'AE', '+971 6 505 8555', 'https://www.uhs.ae/', true, true WHERE NOT EXISTS (SELECT 1 FROM public.healthcare_providers WHERE name = 'المستشفى الجامعي بالشارقة' AND country_code = 'AE');
INSERT INTO public.healthcare_providers (id, name, name_en, provider_type, specialty, specialty_en, city, country_code, phone, website, is_featured, is_active) SELECT '2bfe306e-4876-4812-95ab-baafc315f471', 'مستشفى ميدكلينك سيتي', 'Mediclinic City Hospital', 'hospital', 'مستشفى متعدد التخصصات؛ أمراض النساء والتوليد', 'Multispecialty Hospital; Obstetrics & Gynecology', 'Dubai', 'AE', '+971 4 435 9999', 'https://www.mediclinic.ae/en/city-hospital/home.html', true, true WHERE NOT EXISTS (SELECT 1 FROM public.healthcare_providers WHERE name = 'مستشفى ميدكلينك سيتي' AND country_code = 'AE');
