-- ============================================================
-- Xəstəxana/Klinika Seed: Kazakhstan (8 provider)
-- Mənbə: AI-əsaslı "bot" (generate-healthcare-providers.cjs) — YALNIZ məşhur/sabit
-- flaqman xəstəxanalar; əmin olunmayan telefon/veb-sayt sahələri NULL saxlanılıb.
-- ⚠️ Canlıya keçirmədən əvvəl bir neçə sətri əl ilə yoxlamaq tövsiyə olunur.
-- İdempotent: name+country_code üzrə WHERE NOT EXISTS.
-- ============================================================

INSERT INTO public.healthcare_providers (id, name, name_en, provider_type, specialty, specialty_en, city, country_code, phone, website, is_featured, is_active) SELECT '0bf34813-52ea-47c3-a03d-d56c236fe9b5', 'Акушерлік, гинекология және перинатология ғылыми орталығы', 'Scientific Center of Obstetrics, Gynecology and Perinatology', 'hospital', 'Акушерлік, гинекология және перинатология', 'Obstetrics, Gynecology & Perinatology', 'Almaty', 'KZ', '+7 727 300-45-99', 'https://ncagip.kz/', true, true WHERE NOT EXISTS (SELECT 1 FROM public.healthcare_providers WHERE name = 'Акушерлік, гинекология және перинатология ғылыми орталығы' AND country_code = 'KZ');
INSERT INTO public.healthcare_providers (id, name, name_en, provider_type, specialty, specialty_en, city, country_code, phone, website, is_featured, is_active) SELECT 'f45ef69f-df86-4255-bdef-cc486080cdbc', 'Ана мен бала ұлттық ғылыми орталығы', 'National Research Center for Maternal and Child Health', 'hospital', 'Акушерлік, гинекология, перинатология және педиатрия', 'Obstetrics, Gynecology, Perinatology & Pediatrics', 'Astana', 'KZ', NULL, 'https://umc.org.kz/', true, true WHERE NOT EXISTS (SELECT 1 FROM public.healthcare_providers WHERE name = 'Ана мен бала ұлттық ғылыми орталығы' AND country_code = 'KZ');
INSERT INTO public.healthcare_providers (id, name, name_en, provider_type, specialty, specialty_en, city, country_code, phone, website, is_featured, is_active) SELECT '8a55062a-9e25-4f1e-997f-e542e3cae011', 'Педиатрия және балалар хирургиясы ғылыми орталығы', 'Scientific Center of Pediatrics and Pediatric Surgery', 'hospital', 'Педиатрия және балалар хирургиясы', 'Pediatrics & Pediatric Surgery', 'Almaty', 'KZ', NULL, 'https://pediatria.kz/', true, true WHERE NOT EXISTS (SELECT 1 FROM public.healthcare_providers WHERE name = 'Педиатрия және балалар хирургиясы ғылыми орталығы' AND country_code = 'KZ');
INSERT INTO public.healthcare_providers (id, name, name_en, provider_type, specialty, specialty_en, city, country_code, phone, website, is_featured, is_active) SELECT '93645040-7d1f-4526-9fa8-b9e52d9cdb2c', 'Перинатология және балалар кардиохирургиясы орталығы', 'Center of Perinatology and Pediatric Cardiac Surgery', 'hospital', 'Перинатология және балалар кардиохирургиясы', 'Perinatology & Pediatric Cardiac Surgery', 'Almaty', 'KZ', NULL, NULL, true, true WHERE NOT EXISTS (SELECT 1 FROM public.healthcare_providers WHERE name = 'Перинатология және балалар кардиохирургиясы орталығы' AND country_code = 'KZ');
INSERT INTO public.healthcare_providers (id, name, name_en, provider_type, specialty, specialty_en, city, country_code, phone, website, is_featured, is_active) SELECT '454c196b-25ee-4c1d-9ed9-9bc0c978ab6e', 'Алматы қалалық перинаталдық орталығы', 'Almaty City Perinatal Center', 'hospital', 'Акушерлік, гинекология және неонатология', 'Obstetrics, Gynecology & Neonatology', 'Almaty', 'KZ', NULL, NULL, true, true WHERE NOT EXISTS (SELECT 1 FROM public.healthcare_providers WHERE name = 'Алматы қалалық перинаталдық орталығы' AND country_code = 'KZ');
INSERT INTO public.healthcare_providers (id, name, name_en, provider_type, specialty, specialty_en, city, country_code, phone, website, is_featured, is_active) SELECT '329e9c41-5f5f-47eb-98a4-1e45f19f267c', 'Қарағанды облыстық перинаталдық орталығы', 'Karaganda Regional Perinatal Center', 'hospital', 'Акушерлік, перинатология және неонатология', 'Obstetrics, Perinatology & Neonatology', 'Karaganda', 'KZ', NULL, NULL, true, true WHERE NOT EXISTS (SELECT 1 FROM public.healthcare_providers WHERE name = 'Қарағанды облыстық перинаталдық орталығы' AND country_code = 'KZ');
INSERT INTO public.healthcare_providers (id, name, name_en, provider_type, specialty, specialty_en, city, country_code, phone, website, is_featured, is_active) SELECT '432f5de5-4624-4de5-bc2e-583d871e529e', 'Шымкент қалалық перинаталдық орталығы', 'Shymkent City Perinatal Center', 'hospital', 'Акушерлік, перинатология және неонатология', 'Obstetrics, Perinatology & Neonatology', 'Shymkent', 'KZ', NULL, NULL, true, true WHERE NOT EXISTS (SELECT 1 FROM public.healthcare_providers WHERE name = 'Шымкент қалалық перинаталдық орталығы' AND country_code = 'KZ');
INSERT INTO public.healthcare_providers (id, name, name_en, provider_type, specialty, specialty_en, city, country_code, phone, website, is_featured, is_active) SELECT 'ef92f0a6-d3b1-4bb5-9f15-cb18c08332e3', 'Ақтөбе облыстық перинаталдық орталығы', 'Aktobe Regional Perinatal Center', 'hospital', 'Акушерлік, перинатология және неонатология', 'Obstetrics, Perinatology & Neonatology', 'Aktobe', 'KZ', NULL, NULL, true, true WHERE NOT EXISTS (SELECT 1 FROM public.healthcare_providers WHERE name = 'Ақтөбе облыстық перинаталдық орталығы' AND country_code = 'KZ');
