-- Duzelis13: Əkiz/üçüz/dördüz hamiləlik funksionallığı — bir neçə əlaqəli hissə:
--   1) profiles.chorionicity — plasenta növü (dixorionik/monoxorionik) — ProfileEditScreen-də
--      redaktə olunur, DangerSignsScreen-də TTTS-spesifik xəbərdarlıq üçün istifadə olunur.
--      (baby_count/multiples_type özü artıq var idi — bu, ONLARA əlavədir, yenisi deyil.)
--   2) fetal_growth_scans — YENİ cədvəl: Fetal Growth Tracker aləti üçün USM-əsaslı
--      təxmini körpə çəkisi (EFW) qeydləri. Doğuşdan ƏVVƏL istifadə olunur, ona görə
--      user_children.child_id əvəzinə sadə baby_label ('A'/'B'/'C'/'D') istifadə edir.
--   3) tool_configs-a 'fetal-growth' alətinin qeydiyyatı (bump mərhələsi).
--   4) Yuxarıdakı + BirthOnboardingModal (çox-uşaqlı) + Danger Signs (TTTS) üçün
--      bütün yeni UI mətnləri — DB overlay bütün 7 dil üçün (lokal seed faylları da
--      birbaşa yeniləndi: src/locales/az.json, en.json, scripts/i18n/{ru,tr,kk,de,ar}.seed.json).
-- Idempotent — safe to re-run.

-- ============================================================
-- 1) Xorionluq
-- ============================================================
ALTER TABLE public.profiles
  ADD COLUMN IF NOT EXISTS chorionicity text;

COMMENT ON COLUMN public.profiles.chorionicity IS 'Əkiz/üçüz hamiləlikdə plasenta növü: dichorionic | monochorionic_diamniotic | monochorionic_monoamniotic | unknown. ProfileEditScreen-də (yalnız multiples_type != single olanda) redaktə olunur, DangerSignsScreen-də TTTS-spesifik xəbərdarlıq göstərmək üçün istifadə olunur.';

-- ============================================================
-- 2) Fetal Growth Tracker cədvəli
-- ============================================================
CREATE TABLE IF NOT EXISTS public.fetal_growth_scans (
  id UUID NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
  user_id UUID NOT NULL,
  baby_label TEXT NOT NULL DEFAULT 'A',
  scan_date DATE NOT NULL DEFAULT CURRENT_DATE,
  efw_grams NUMERIC(6,0) NOT NULL,
  notes TEXT NULL,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()
);

COMMENT ON TABLE public.fetal_growth_scans IS 'USM-əsaslı təxmini körpə çəkisi (EFW) qeydləri — Fetal Growth Tracker. baby_label (A/B/C/D) əkiz/üçüz/dördüz üçündür (user_children hələ doğuşdan əvvəl mövcud deyil).';

CREATE INDEX IF NOT EXISTS idx_fetal_growth_scans_user_date ON public.fetal_growth_scans(user_id, scan_date DESC);

ALTER TABLE public.fetal_growth_scans ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Users can manage own fetal growth scans" ON public.fetal_growth_scans;
CREATE POLICY "Users can manage own fetal growth scans" ON public.fetal_growth_scans
  FOR ALL USING (auth.uid() = user_id);

DROP POLICY IF EXISTS "Partners can view linked fetal growth scans" ON public.fetal_growth_scans;
CREATE POLICY "Partners can view linked fetal growth scans" ON public.fetal_growth_scans
  FOR SELECT USING (user_id IN (
    SELECT p2.user_id FROM public.profiles p1
    JOIN public.profiles p2 ON p1.linked_partner_id = p2.id
    WHERE p1.user_id = auth.uid()
  ));

-- ============================================================
-- 3) tool_configs qeydiyyatı
-- ============================================================
INSERT INTO public.tool_configs
  (tool_id, name, name_az, description, description_az, icon, color, bg_color, life_stages, sort_order, is_active)
VALUES
  ('fetal-growth', 'Fetal Growth Tracker', 'Fetal Böyümə İzləyicisi', 'Track estimated fetal weight from ultrasounds', 'USM-əsaslı təxmini körpə çəkisini izləyin', 'TrendingUp', 'text-emerald-600', 'bg-emerald-50', '{bump}', 20, true)
ON CONFLICT (tool_id) DO UPDATE SET name_az = EXCLUDED.name_az, description_az = EXCLUDED.description_az, icon = EXCLUDED.icon, is_active = EXCLUDED.is_active;

-- ============================================================
-- 4) Yeni UI translation keys (49 açar × 7 dil)
-- ============================================================
INSERT INTO public.translations (key, lang, value, namespace) VALUES
  ('birthonboardingmodal_korpeleriniz_haqqinda_melumat', 'az', 'Körpələriniz haqqında məlumat verin', 'profile'),
  ('birthonboardingmodal_korpeleriniz_haqqinda_melumat', 'en', 'Tell us about your babies', 'profile'),
  ('birthonboardingmodal_korpeleriniz_haqqinda_melumat', 'ru', 'Расскажите нам о ваших детях', 'profile'),
  ('birthonboardingmodal_korpeleriniz_haqqinda_melumat', 'tr', 'Bebekleriniz hakkında bilgi verin', 'profile'),
  ('birthonboardingmodal_korpeleriniz_haqqinda_melumat', 'kk', 'Балаларыңыз туралы мәлімет беріңіз', 'profile'),
  ('birthonboardingmodal_korpeleriniz_haqqinda_melumat', 'de', 'Erzählen Sie uns von Ihren Babys', 'profile'),
  ('birthonboardingmodal_korpeleriniz_haqqinda_melumat', 'ar', 'أخبرينا عن أطفالك', 'profile'),
  ('birthonboardingmodal_korpeleriniz_ne_vaxt_doguldu', 'az', 'Körpələriniz nə vaxt doğuldu?', 'profile'),
  ('birthonboardingmodal_korpeleriniz_ne_vaxt_doguldu', 'en', 'When were your babies born?', 'profile'),
  ('birthonboardingmodal_korpeleriniz_ne_vaxt_doguldu', 'ru', 'Когда родились ваши дети?', 'profile'),
  ('birthonboardingmodal_korpeleriniz_ne_vaxt_doguldu', 'tr', 'Bebekleriniz ne zaman doğdu?', 'profile'),
  ('birthonboardingmodal_korpeleriniz_ne_vaxt_doguldu', 'kk', 'Балаларыңыз қашан туды?', 'profile'),
  ('birthonboardingmodal_korpeleriniz_ne_vaxt_doguldu', 'de', 'Wann wurden Ihre Babys geboren?', 'profile'),
  ('birthonboardingmodal_korpeleriniz_ne_vaxt_doguldu', 'ar', 'متى وُلد أطفالك؟', 'profile'),
  ('birthonboardingmodal_korpelerin_adlari', 'az', 'Körpələrin adları', 'profile'),
  ('birthonboardingmodal_korpelerin_adlari', 'en', 'Babies'' names', 'profile'),
  ('birthonboardingmodal_korpelerin_adlari', 'ru', 'Имена детей', 'profile'),
  ('birthonboardingmodal_korpelerin_adlari', 'tr', 'Bebeklerin isimleri', 'profile'),
  ('birthonboardingmodal_korpelerin_adlari', 'kk', 'Балалардың есімдері', 'profile'),
  ('birthonboardingmodal_korpelerin_adlari', 'de', 'Namen der Babys', 'profile'),
  ('birthonboardingmodal_korpelerin_adlari', 'ar', 'أسماء الأطفال', 'profile'),
  ('birthonboardingmodal_balaca_mocuzelerinizin_adlari_nedir', 'az', 'Balaca möcüzələrinizin adları nədir?', 'profile'),
  ('birthonboardingmodal_balaca_mocuzelerinizin_adlari_nedir', 'en', 'What are your little miracles named?', 'profile'),
  ('birthonboardingmodal_balaca_mocuzelerinizin_adlari_nedir', 'ru', 'Как зовут ваших маленьких чудес?', 'profile'),
  ('birthonboardingmodal_balaca_mocuzelerinizin_adlari_nedir', 'tr', 'Küçük mucizelerinizin isimleri ne?', 'profile'),
  ('birthonboardingmodal_balaca_mocuzelerinizin_adlari_nedir', 'kk', 'Кішкентай кереметтеріңіздің есімдері қандай?', 'profile'),
  ('birthonboardingmodal_balaca_mocuzelerinizin_adlari_nedir', 'de', 'Wie heißen Ihre kleinen Wunder?', 'profile'),
  ('birthonboardingmodal_balaca_mocuzelerinizin_adlari_nedir', 'ar', 'ما أسماء معجزاتك الصغيرة؟', 'profile'),
  ('birthonboardingmodal_n_ci_korpe', 'az', '{n}-ci körpə', 'profile'),
  ('birthonboardingmodal_n_ci_korpe', 'en', 'Baby {n}', 'profile'),
  ('birthonboardingmodal_n_ci_korpe', 'ru', 'Ребёнок {n}', 'profile'),
  ('birthonboardingmodal_n_ci_korpe', 'tr', '{n}. bebek', 'profile'),
  ('birthonboardingmodal_n_ci_korpe', 'kk', '{n}-ші бала', 'profile'),
  ('birthonboardingmodal_n_ci_korpe', 'de', 'Baby {n}', 'profile'),
  ('birthonboardingmodal_n_ci_korpe', 'ar', 'الطفل {n}', 'profile'),
  ('profile_multiples_label', 'az', 'Neçə körpə gözləyirsiniz?', 'profile'),
  ('profile_multiples_label', 'en', 'How many babies are you expecting?', 'profile'),
  ('profile_multiples_label', 'ru', 'Сколько детей вы ожидаете?', 'profile'),
  ('profile_multiples_label', 'tr', 'Kaç bebek bekliyorsunuz?', 'profile'),
  ('profile_multiples_label', 'kk', 'Неше бала күтіп жатырсыз?', 'profile'),
  ('profile_multiples_label', 'de', 'Wie viele Babys erwarten Sie?', 'profile'),
  ('profile_multiples_label', 'ar', 'كم عدد الأطفال الذين تنتظرينهم؟', 'profile'),
  ('profile_multiples_single', 'az', 'Tək körpə', 'profile'),
  ('profile_multiples_single', 'en', 'Single baby', 'profile'),
  ('profile_multiples_single', 'ru', 'Один ребёнок', 'profile'),
  ('profile_multiples_single', 'tr', 'Tek bebek', 'profile'),
  ('profile_multiples_single', 'kk', 'Жалғыз бала', 'profile'),
  ('profile_multiples_single', 'de', 'Einzelkind', 'profile'),
  ('profile_multiples_single', 'ar', 'طفل واحد', 'profile'),
  ('profile_multiples_twins', 'az', 'Əkiz', 'profile'),
  ('profile_multiples_twins', 'en', 'Twins', 'profile'),
  ('profile_multiples_twins', 'ru', 'Близнецы', 'profile'),
  ('profile_multiples_twins', 'tr', 'İkiz', 'profile'),
  ('profile_multiples_twins', 'kk', 'Егіздер', 'profile'),
  ('profile_multiples_twins', 'de', 'Zwillinge', 'profile'),
  ('profile_multiples_twins', 'ar', 'توأم', 'profile'),
  ('profile_multiples_triplets', 'az', 'Üçüz', 'profile'),
  ('profile_multiples_triplets', 'en', 'Triplets', 'profile'),
  ('profile_multiples_triplets', 'ru', 'Тройня', 'profile'),
  ('profile_multiples_triplets', 'tr', 'Üçüz', 'profile'),
  ('profile_multiples_triplets', 'kk', 'Үшемдер', 'profile'),
  ('profile_multiples_triplets', 'de', 'Drillinge', 'profile'),
  ('profile_multiples_triplets', 'ar', 'ثلاثة توائم', 'profile'),
  ('profile_multiples_quadruplets', 'az', 'Dördüz', 'profile'),
  ('profile_multiples_quadruplets', 'en', 'Quadruplets', 'profile'),
  ('profile_multiples_quadruplets', 'ru', 'Четверня', 'profile'),
  ('profile_multiples_quadruplets', 'tr', 'Dördüz', 'profile'),
  ('profile_multiples_quadruplets', 'kk', 'Төртемдер', 'profile'),
  ('profile_multiples_quadruplets', 'de', 'Vierlinge', 'profile'),
  ('profile_multiples_quadruplets', 'ar', 'رباعي التوائم', 'profile'),
  ('chorionicity_label', 'az', 'Plasenta növü (Xorionluq)', 'health'),
  ('chorionicity_label', 'en', 'Placenta type (Chorionicity)', 'health'),
  ('chorionicity_label', 'ru', 'Тип плаценты (Хориальность)', 'health'),
  ('chorionicity_label', 'tr', 'Plasenta türü (Koryonisite)', 'health'),
  ('chorionicity_label', 'kk', 'Плацента түрі (Хорионалдылық)', 'health'),
  ('chorionicity_label', 'de', 'Plazentatyp (Chorionizität)', 'health'),
  ('chorionicity_label', 'ar', 'نوع المشيمة (المشيمية)', 'health'),
  ('chorionicity_placeholder', 'az', 'Seçin (USM-də məlum olur)', 'health'),
  ('chorionicity_placeholder', 'en', 'Select (determined by ultrasound)', 'health'),
  ('chorionicity_placeholder', 'ru', 'Выберите (определяется на УЗИ)', 'health'),
  ('chorionicity_placeholder', 'tr', 'Seçin (USG ile belirlenir)', 'health'),
  ('chorionicity_placeholder', 'kk', 'Таңдаңыз (УДЗ-де анықталады)', 'health'),
  ('chorionicity_placeholder', 'de', 'Auswählen (wird per Ultraschall bestimmt)', 'health'),
  ('chorionicity_placeholder', 'ar', 'اختاري (يتم تحديدها بالموجات فوق الصوتية)', 'health'),
  ('chorionicity_unknown', 'az', 'Hələ bilmirəm / USM gözləyirəm', 'health'),
  ('chorionicity_unknown', 'en', 'Don''t know yet / awaiting ultrasound', 'health'),
  ('chorionicity_unknown', 'ru', 'Пока не знаю / жду УЗИ', 'health'),
  ('chorionicity_unknown', 'tr', 'Henüz bilmiyorum / USG bekliyorum', 'health'),
  ('chorionicity_unknown', 'kk', 'Әлі білмеймін / УДЗ күтудемін', 'health'),
  ('chorionicity_unknown', 'de', 'Weiß ich noch nicht / warte auf Ultraschall', 'health'),
  ('chorionicity_unknown', 'ar', 'لا أعرف بعد / أنتظر الموجات فوق الصوتية', 'health'),
  ('chorionicity_dichorionic', 'az', 'Ayrı-ayrı plasentalar (Dixorionik)', 'health'),
  ('chorionicity_dichorionic', 'en', 'Separate placentas (Dichorionic)', 'health'),
  ('chorionicity_dichorionic', 'ru', 'Отдельные плаценты (Дихориальная)', 'health'),
  ('chorionicity_dichorionic', 'tr', 'Ayrı plasentalar (Dikoryonik)', 'health'),
  ('chorionicity_dichorionic', 'kk', 'Бөлек плацентaлар (Дихорионды)', 'health'),
  ('chorionicity_dichorionic', 'de', 'Getrennte Plazenten (Dichorial)', 'health'),
  ('chorionicity_dichorionic', 'ar', 'مشيمتان منفصلتان (ثنائية المشيمة)', 'health'),
  ('chorionicity_mcda', 'az', 'Ortaq plasenta, ayrı kisələr (Monoxorionik-Diamniotik)', 'health'),
  ('chorionicity_mcda', 'en', 'Shared placenta, separate sacs (Monochorionic-Diamniotic)', 'health'),
  ('chorionicity_mcda', 'ru', 'Общая плацента, отдельные мешки (Монохориальная-Диамниотическая)', 'health'),
  ('chorionicity_mcda', 'tr', 'Ortak plasenta, ayrı keseler (Monokoryonik-Diamniyotik)', 'health'),
  ('chorionicity_mcda', 'kk', 'Ортақ плацента, бөлек қапшықтар (Монохорионды-Диамниотикалық)', 'health'),
  ('chorionicity_mcda', 'de', 'Gemeinsame Plazenta, getrennte Fruchtblasen (Monochorial-Diamniotisch)', 'health'),
  ('chorionicity_mcda', 'ar', 'مشيمة مشتركة، أكياس منفصلة (وحيدة المشيمة ثنائية السلى)', 'health'),
  ('chorionicity_mcma', 'az', 'Ortaq plasenta və ortaq kisə (Monoxorionik-Monoamniotik)', 'health'),
  ('chorionicity_mcma', 'en', 'Shared placenta and shared sac (Monochorionic-Monoamniotic)', 'health'),
  ('chorionicity_mcma', 'ru', 'Общая плацента и общий мешок (Монохориальная-Моноамниотическая)', 'health'),
  ('chorionicity_mcma', 'tr', 'Ortak plasenta ve ortak kese (Monokoryonik-Monoamniyotik)', 'health'),
  ('chorionicity_mcma', 'kk', 'Ортақ плацента және ортақ қапшық (Монохорионды-Моноамниотикалық)', 'health'),
  ('chorionicity_mcma', 'de', 'Gemeinsame Plazenta und gemeinsame Fruchtblase (Monochorial-Monoamniotisch)', 'health'),
  ('chorionicity_mcma', 'ar', 'مشيمة مشتركة وكيس مشترك (وحيدة المشيمة وحيدة السلى)', 'health'),
  ('chorionicity_help_dichorionic', 'az', 'Hər körpənin öz plasentası var — ən aşağı riskli növdür, əkiz doğuşların əksəriyyəti bu qrupdadır.', 'health'),
  ('chorionicity_help_dichorionic', 'en', 'Each baby has their own placenta — this is the lowest-risk type, and most twin pregnancies fall into this group.', 'health'),
  ('chorionicity_help_dichorionic', 'ru', 'У каждого ребёнка своя плацента — это наименее рискованный тип, к нему относится большинство двойней.', 'health'),
  ('chorionicity_help_dichorionic', 'tr', 'Her bebeğin kendi plasentası var — en düşük riskli türdür, ikiz gebeliklerin çoğu bu gruptadır.', 'health'),
  ('chorionicity_help_dichorionic', 'kk', 'Әр баланың өз плацентасы бар — бұл ең аз тәуекелді түр, егіз жүктіліктердің көпшілігі осы топқа жатады.', 'health'),
  ('chorionicity_help_dichorionic', 'de', 'Jedes Baby hat seine eigene Plazenta — dies ist der risikoärmste Typ, und die meisten Zwillingsschwangerschaften fallen in diese Gruppe.', 'health'),
  ('chorionicity_help_dichorionic', 'ar', 'لكل طفل مشيمته الخاصة — وهذا هو النوع الأقل خطورة، وتنتمي معظم حالات الحمل بتوأم إلى هذه المجموعة.', 'health'),
  ('chorionicity_help_mcda', 'az', 'Körpələr eyni plasentanı paylaşır (adətən eyniz əkizlərdə) — TTTS (əkiz-əkizə transfuziya sindromu) riskinə görə USM-lər daha tez-tez təyin olunur.', 'health'),
  ('chorionicity_help_mcda', 'en', 'The babies share the same placenta (usually in identical twins) — ultrasounds are scheduled more often due to the risk of TTTS (twin-to-twin transfusion syndrome).', 'health'),
  ('chorionicity_help_mcda', 'ru', 'Дети имеют общую плаценту (обычно у однояйцевых близнецов) — из-за риска СФФТ (синдром фето-фетальной трансфузии) УЗИ назначают чаще.', 'health'),
  ('chorionicity_help_mcda', 'tr', 'Bebekler aynı plasentayı paylaşır (genellikle tek yumurta ikizlerinde) — TTTS (ikizden ikize transfüzyon sendromu) riski nedeniyle USG daha sık planlanır.', 'health'),
  ('chorionicity_help_mcda', 'kk', 'Балалар бір плацентaны бөліседі (әдетте біржұмыртқалы егіздерде) — ТТТС (егізден егізге трансфузия синдромы) қаупіне байланысты УДЗ жиірек тағайындалады.', 'health'),
  ('chorionicity_help_mcda', 'de', 'Die Babys teilen sich dieselbe Plazenta (meist bei eineiigen Zwillingen) — wegen des TTTS-Risikos (Zwillings-Transfusionssyndrom) werden häufiger Ultraschalluntersuchungen angesetzt.', 'health'),
  ('chorionicity_help_mcda', 'ar', 'يتشارك الطفلان نفس المشيمة (عادة في التوائم المتماثلة) — يتم جدولة الموجات فوق الصوتية بشكل أكثر تكرارًا بسبب خطر متلازمة نقل الدم بين التوأمين (TTTS).', 'health'),
  ('chorionicity_help_mcma', 'az', 'Körpələr həm plasentanı, həm kisəni paylaşır — nadir haldır, ən yaxın izləmə tələb edir (göbək ciyəsi dolaşması riski də var).', 'health'),
  ('chorionicity_help_mcma', 'en', 'The babies share both the placenta and the sac — this is rare and requires the closest monitoring (there is also a risk of cord entanglement).', 'health'),
  ('chorionicity_help_mcma', 'ru', 'Дети имеют общую плаценту и общий мешок — это редкий случай, требующий самого тщательного наблюдения (также есть риск перекрута пуповин).', 'health'),
  ('chorionicity_help_mcma', 'tr', 'Bebekler hem plasentayı hem de keseyi paylaşır — nadir bir durumdur ve en yakın takibi gerektirir (göbek kordonu dolanma riski de vardır).', 'health'),
  ('chorionicity_help_mcma', 'kk', 'Балалар плацентaны да, қапшықты да бөліседі — бұл сирек кездеседі және ең жақын бақылауды талап етеді (кіндік бауының шатасу қаупі де бар).', 'health'),
  ('chorionicity_help_mcma', 'de', 'Die Babys teilen sich sowohl die Plazenta als auch die Fruchtblase — dies ist selten und erfordert die engmaschigste Überwachung (es besteht auch das Risiko einer Nabelschnurverschlingung).', 'health'),
  ('chorionicity_help_mcma', 'ar', 'يتشارك الطفلان المشيمة والكيس معًا — وهذا نادر ويتطلب أدق متابعة (كما يوجد خطر تشابك الحبل السري).', 'health'),
  ('chorionicity_help_unknown', 'az', 'Adətən 10-14-cü həftə USM-də (dating scan) müəyyən olunur — həkiminiz sizə deyəcək. Ortaq plasenta olduqda USM-lər daha tez-tez planlaşdırılır.', 'health'),
  ('chorionicity_help_unknown', 'en', 'This is usually determined at the 10–14 week (dating) ultrasound — your doctor will tell you. When the placenta is shared, ultrasounds are scheduled more often.', 'health'),
  ('chorionicity_help_unknown', 'ru', 'Обычно определяется на УЗИ в 10–14 недель — врач сообщит вам. При общей плаценте УЗИ назначают чаще.', 'health'),
  ('chorionicity_help_unknown', 'tr', 'Genellikle 10-14. hafta USG''sinde (tarihleme taraması) belirlenir — doktorunuz size söyleyecektir. Plasenta ortak olduğunda USG''ler daha sık planlanır.', 'health'),
  ('chorionicity_help_unknown', 'kk', 'Әдетте 10-14 апталық УДЗ-де (мерзімін анықтау) белгіленеді — дәрігеріңіз сізге айтады. Плацента ортақ болғанда УДЗ жиірек жоспарланады.', 'health'),
  ('chorionicity_help_unknown', 'de', 'Dies wird meist beim Ultraschall in der 10.–14. Woche (Datierungsscan) festgestellt — Ihr Arzt wird es Ihnen mitteilen. Bei gemeinsamer Plazenta werden Ultraschalluntersuchungen häufiger angesetzt.', 'health'),
  ('chorionicity_help_unknown', 'ar', 'عادة ما يتم تحديد ذلك في فحص الموجات فوق الصوتية في الأسبوع 10-14 — سيخبرك طبيبك بذلك. عندما تكون المشيمة مشتركة، يتم جدولة الموجات فوق الصوتية بشكل أكثر تكرارًا.', 'health'),
  ('rf_ttts_title', 'az', 'Əkizlərdə qeyri-bərabər böyümə əlamətləri (TTTS)', 'health'),
  ('rf_ttts_title', 'en', 'Signs of uneven growth in twins (TTTS)', 'health'),
  ('rf_ttts_title', 'ru', 'Признаки неравномерного роста у близнецов (СФФТ)', 'health'),
  ('rf_ttts_title', 'tr', 'İkizlerde eşitsiz büyüme belirtileri (TTTS)', 'health'),
  ('rf_ttts_title', 'kk', 'Егіздердегі теңсіз даму белгілері (ТТТС)', 'health'),
  ('rf_ttts_title', 'de', 'Anzeichen für ungleichmäßiges Wachstum bei Zwillingen (TTTS)', 'health'),
  ('rf_ttts_title', 'ar', 'علامات النمو غير المتساوي في التوائم (TTTS)', 'health'),
  ('rf_ttts_desc', 'az', 'Qarının gözlənilməzdən sürətli/qeyri-bərabər böyüməsi, nəfəs darlığının qəfil artması, ayaqlarda qəfil şişkinlik və ya bir körpənin hərəkətinin digərinə nisbətən azalması — ortaq plasentalı (monoxorionik) əkiz/üçüzlərdə TTTS (əkiz-əkizə transfuziya sindromu) əlaməti ola bilər. Bu, tez aşkarlanıb müalicə edildikdə yaxşı idarə oluna bilən, amma vaxtında həkimə çatdırılması vacib olan bir vəziyyətdir.', 'health'),
  ('rf_ttts_desc', 'en', 'Faster-than-expected or uneven belly growth, a sudden increase in shortness of breath, sudden swelling in the legs, or one baby moving noticeably less than the other — these can be signs of TTTS (twin-to-twin transfusion syndrome) in monochorionic (shared-placenta) twins/triplets. This is a condition that can be well managed when caught early, but it is important to reach your doctor promptly.', 'health'),
  ('rf_ttts_desc', 'ru', 'Неожиданно быстрый/неравномерный рост живота, резкое усиление одышки, внезапная отёчность ног или заметное снижение шевелений одного ребёнка по сравнению с другим — могут быть признаками СФФТ (синдром фето-фетальной трансфузии) у близнецов/тройни с общей плацентой (монохориальных). Это состояние хорошо поддаётся лечению при раннем выявлении, но важно вовремя обратиться к врачу.', 'health'),
  ('rf_ttts_desc', 'tr', 'Karnın beklenenden hızlı/eşitsiz büyümesi, nefes darlığında ani artış, bacaklarda ani şişlik veya bir bebeğin hareketinin diğerine göre azalması — ortak plasentalı (monokoryonik) ikiz/üçüzlerde TTTS (ikizden ikize transfüzyon sendromu) belirtisi olabilir. Bu, erken tespit edilip tedavi edildiğinde iyi yönetilebilen, ancak zamanında doktora ulaşılması önemli olan bir durumdur.', 'health'),
  ('rf_ttts_desc', 'kk', 'Іштің күтпеген жерден тез/теңсіз өсуі, тыныс тарылуының кенеттен күшеюі, аяқтардың кенеттен ісінуі немесе бір баланың қозғалысының екіншісіне қарағанда азаюы — ортақ плацентaлы (монохорионды) егіз/үшемдерде ТТТС (егізден егізге трансфузия синдромы) белгісі болуы мүмкін. Бұл, ерте анықталып емделгенде жақсы басқарылатын, бірақ уақытында дәрігерге жеткізу маңызды жағдай.', 'health'),
  ('rf_ttts_desc', 'de', 'Ein schneller-als-erwartetes oder ungleichmäßiges Wachstum des Bauches, eine plötzliche Zunahme von Atemnot, plötzliche Schwellungen der Beine oder ein Baby, das sich spürbar weniger bewegt als das andere — dies können Anzeichen für TTTS (Zwillings-Transfusionssyndrom) bei monochorialen (gemeinsame Plazenta) Zwillingen/Drillingen sein. Dieser Zustand lässt sich bei früher Erkennung gut behandeln, aber es ist wichtig, rechtzeitig Ihren Arzt zu erreichen.', 'health'),
  ('rf_ttts_desc', 'ar', 'نمو البطن بشكل أسرع من المتوقع أو غير متساوٍ، أو زيادة مفاجئة في ضيق التنفس، أو تورم مفاجئ في الساقين، أو حركة أحد الطفلين بشكل ملحوظ أقل من الآخر — يمكن أن تكون علامات على TTTS (متلازمة نقل الدم بين التوأمين) في التوائم/الثلاثة توائم أحادية المشيمة (المشيمة المشتركة). هذه حالة يمكن التحكم بها جيدًا عند اكتشافها مبكرًا، لكن من المهم الوصول إلى طبيبك على الفور.', 'health'),
  ('fetalgrowth_title', 'az', 'Fetal Böyümə İzləyicisi', 'tools'),
  ('fetalgrowth_title', 'en', 'Fetal Growth Tracker', 'tools'),
  ('fetalgrowth_title', 'ru', 'Трекер роста плода', 'tools'),
  ('fetalgrowth_title', 'tr', 'Fetal Büyüme Takipçisi', 'tools'),
  ('fetalgrowth_title', 'kk', 'Ұрық дамуын бақылаушы', 'tools'),
  ('fetalgrowth_title', 'de', 'Fetaler Wachstumstracker', 'tools'),
  ('fetalgrowth_title', 'ar', 'متتبع نمو الجنين', 'tools'),
  ('fetalgrowth_current_week', 'az', 'Cari həftə', 'tools'),
  ('fetalgrowth_current_week', 'en', 'Current week', 'tools'),
  ('fetalgrowth_current_week', 'ru', 'Текущая неделя', 'tools'),
  ('fetalgrowth_current_week', 'tr', 'Mevcut hafta', 'tools'),
  ('fetalgrowth_current_week', 'kk', 'Ағымдағы апта', 'tools'),
  ('fetalgrowth_current_week', 'de', 'Aktuelle Woche', 'tools'),
  ('fetalgrowth_current_week', 'ar', 'الأسبوع الحالي', 'tools'),
  ('fetalgrowth_scan_count', 'az', 'USM qeydi', 'tools'),
  ('fetalgrowth_scan_count', 'en', 'Ultrasound entries', 'tools'),
  ('fetalgrowth_scan_count', 'ru', 'Записи УЗИ', 'tools'),
  ('fetalgrowth_scan_count', 'tr', 'USG kaydı', 'tools'),
  ('fetalgrowth_scan_count', 'kk', 'УДЗ жазбасы', 'tools'),
  ('fetalgrowth_scan_count', 'de', 'Ultraschall-Einträge', 'tools'),
  ('fetalgrowth_scan_count', 'ar', 'سجلات الموجات فوق الصوتية', 'tools'),
  ('fetalgrowth_baby_count', 'az', 'Körpə sayı', 'tools'),
  ('fetalgrowth_baby_count', 'en', 'Number of babies', 'tools'),
  ('fetalgrowth_baby_count', 'ru', 'Количество детей', 'tools'),
  ('fetalgrowth_baby_count', 'tr', 'Bebek sayısı', 'tools'),
  ('fetalgrowth_baby_count', 'kk', 'Балалар саны', 'tools'),
  ('fetalgrowth_baby_count', 'de', 'Anzahl der Babys', 'tools'),
  ('fetalgrowth_baby_count', 'ar', 'عدد الأطفال', 'tools'),
  ('fetalgrowth_baby_label_n', 'az', 'Körpə {n}', 'tools'),
  ('fetalgrowth_baby_label_n', 'en', 'Baby {n}', 'tools'),
  ('fetalgrowth_baby_label_n', 'ru', 'Ребёнок {n}', 'tools'),
  ('fetalgrowth_baby_label_n', 'tr', 'Bebek {n}', 'tools'),
  ('fetalgrowth_baby_label_n', 'kk', '{n} бала', 'tools'),
  ('fetalgrowth_baby_label_n', 'de', 'Baby {n}', 'tools'),
  ('fetalgrowth_baby_label_n', 'ar', 'الطفل {n}', 'tools'),
  ('fetalgrowth_latest_efw', 'az', 'Son EFW', 'tools'),
  ('fetalgrowth_latest_efw', 'en', 'Latest EFW', 'tools'),
  ('fetalgrowth_latest_efw', 'ru', 'Последний ПВП', 'tools'),
  ('fetalgrowth_latest_efw', 'tr', 'Son tahmini ağırlık', 'tools'),
  ('fetalgrowth_latest_efw', 'kk', 'Соңғы болжамды салмақ', 'tools'),
  ('fetalgrowth_latest_efw', 'de', 'Letztes geschätztes Gewicht', 'tools'),
  ('fetalgrowth_latest_efw', 'ar', 'آخر وزن تقديري', 'tools'),
  ('fetalgrowth_discordance_title', 'az', 'Böyümə uyğunluğu', 'tools'),
  ('fetalgrowth_discordance_title', 'en', 'Growth consistency', 'tools'),
  ('fetalgrowth_discordance_title', 'ru', 'Согласованность роста', 'tools'),
  ('fetalgrowth_discordance_title', 'tr', 'Büyüme uyumu', 'tools'),
  ('fetalgrowth_discordance_title', 'kk', 'Даму сәйкестігі', 'tools'),
  ('fetalgrowth_discordance_title', 'de', 'Wachstumsübereinstimmung', 'tools'),
  ('fetalgrowth_discordance_title', 'ar', 'اتساق النمو', 'tools'),
  ('fetalgrowth_discordance_high', 'az', 'Əhəmiyyətli fərq — həkiminizlə müzakirə edin', 'tools'),
  ('fetalgrowth_discordance_high', 'en', 'Significant difference — discuss with your doctor', 'tools'),
  ('fetalgrowth_discordance_high', 'ru', 'Значительная разница — обсудите с врачом', 'tools'),
  ('fetalgrowth_discordance_high', 'tr', 'Önemli fark — doktorunuzla görüşün', 'tools'),
  ('fetalgrowth_discordance_high', 'kk', 'Айтарлықтай айырмашылық — дәрігеріңізбен талқылаңыз', 'tools'),
  ('fetalgrowth_discordance_high', 'de', 'Erheblicher Unterschied — besprechen Sie dies mit Ihrem Arzt', 'tools'),
  ('fetalgrowth_discordance_high', 'ar', 'فرق كبير — ناقشي ذلك مع طبيبك', 'tools'),
  ('fetalgrowth_discordance_watch', 'az', 'Yüngül fərq — izləməyə davam edin', 'tools'),
  ('fetalgrowth_discordance_watch', 'en', 'Mild difference — keep monitoring', 'tools'),
  ('fetalgrowth_discordance_watch', 'ru', 'Небольшая разница — продолжайте наблюдение', 'tools'),
  ('fetalgrowth_discordance_watch', 'tr', 'Hafif fark — izlemeye devam edin', 'tools'),
  ('fetalgrowth_discordance_watch', 'kk', 'Жеңіл айырмашылық — бақылауды жалғастырыңыз', 'tools'),
  ('fetalgrowth_discordance_watch', 'de', 'Leichter Unterschied — weiter beobachten', 'tools'),
  ('fetalgrowth_discordance_watch', 'ar', 'فرق طفيف — استمري في المراقبة', 'tools'),
  ('fetalgrowth_discordance_normal', 'az', 'Uyğun böyüyürlər', 'tools'),
  ('fetalgrowth_discordance_normal', 'en', 'Growing consistently', 'tools'),
  ('fetalgrowth_discordance_normal', 'ru', 'Растут согласованно', 'tools'),
  ('fetalgrowth_discordance_normal', 'tr', 'Uyumlu büyüyorlar', 'tools'),
  ('fetalgrowth_discordance_normal', 'kk', 'Сәйкес дамып жатыр', 'tools'),
  ('fetalgrowth_discordance_normal', 'de', 'Wachsen gleichmäßig', 'tools'),
  ('fetalgrowth_discordance_normal', 'ar', 'ينموان بشكل متسق', 'tools'),
  ('fetalgrowth_discordance_desc', 'az', 'Körpələr arasında çəki fərqi: {percent}%', 'tools'),
  ('fetalgrowth_discordance_desc', 'en', 'Weight difference between babies: {percent}%', 'tools'),
  ('fetalgrowth_discordance_desc', 'ru', 'Разница в весе между детьми: {percent}%', 'tools'),
  ('fetalgrowth_discordance_desc', 'tr', 'Bebekler arasındaki ağırlık farkı: %{percent}', 'tools'),
  ('fetalgrowth_discordance_desc', 'kk', 'Балалар арасындағы салмақ айырмашылығы: {percent}%', 'tools'),
  ('fetalgrowth_discordance_desc', 'de', 'Gewichtsunterschied zwischen den Babys: {percent}%', 'tools'),
  ('fetalgrowth_discordance_desc', 'ar', 'فرق الوزن بين الأطفال: {percent}%', 'tools'),
  ('fetalgrowth_chart_title', 'az', 'Böyümə qrafiki', 'tools'),
  ('fetalgrowth_chart_title', 'en', 'Growth chart', 'tools'),
  ('fetalgrowth_chart_title', 'ru', 'График роста', 'tools'),
  ('fetalgrowth_chart_title', 'tr', 'Büyüme grafiği', 'tools'),
  ('fetalgrowth_chart_title', 'kk', 'Даму графигі', 'tools'),
  ('fetalgrowth_chart_title', 'de', 'Wachstumsdiagramm', 'tools'),
  ('fetalgrowth_chart_title', 'ar', 'مخطط النمو', 'tools'),
  ('fetalgrowth_normal_range', 'az', 'Normal aralıq (P10–P90)', 'tools'),
  ('fetalgrowth_normal_range', 'en', 'Normal range (P10–P90)', 'tools'),
  ('fetalgrowth_normal_range', 'ru', 'Нормальный диапазон (П10–П90)', 'tools'),
  ('fetalgrowth_normal_range', 'tr', 'Normal aralık (P10–P90)', 'tools'),
  ('fetalgrowth_normal_range', 'kk', 'Қалыпты аралық (P10–P90)', 'tools'),
  ('fetalgrowth_normal_range', 'de', 'Normalbereich (P10–P90)', 'tools'),
  ('fetalgrowth_normal_range', 'ar', 'النطاق الطبيعي (P10–P90)', 'tools'),
  ('fetalgrowth_median_label', 'az', 'Median (P50)', 'tools'),
  ('fetalgrowth_median_label', 'en', 'Median (P50)', 'tools'),
  ('fetalgrowth_median_label', 'ru', 'Медиана (П50)', 'tools'),
  ('fetalgrowth_median_label', 'tr', 'Medyan (P50)', 'tools'),
  ('fetalgrowth_median_label', 'kk', 'Медиана (P50)', 'tools'),
  ('fetalgrowth_median_label', 'de', 'Median (P50)', 'tools'),
  ('fetalgrowth_median_label', 'ar', 'الوسيط (P50)', 'tools'),
  ('fetalgrowth_chart_legend', 'az', 'Yaşıl zolaq — normal aralıq (P10–P90), nöqtələr — sizin USM ölçmələriniz', 'tools'),
  ('fetalgrowth_chart_legend', 'en', 'Green band — normal range (P10–P90), dots — your ultrasound measurements', 'tools'),
  ('fetalgrowth_chart_legend', 'ru', 'Зелёная полоса — нормальный диапазон (П10–П90), точки — ваши измерения УЗИ', 'tools'),
  ('fetalgrowth_chart_legend', 'tr', 'Yeşil bant — normal aralık (P10–P90), noktalar — USG ölçümleriniz', 'tools'),
  ('fetalgrowth_chart_legend', 'kk', 'Жасыл жолақ — қалыпты аралық (P10–P90), нүктелер — сіздің УДЗ өлшемдеріңіз', 'tools'),
  ('fetalgrowth_chart_legend', 'de', 'Grünes Band — Normalbereich (P10–P90), Punkte — Ihre Ultraschallmessungen', 'tools'),
  ('fetalgrowth_chart_legend', 'ar', 'الشريط الأخضر — النطاق الطبيعي (P10–P90)، النقاط — قياسات الموجات فوق الصوتية الخاصة بك', 'tools'),
  ('fetalgrowth_history_title', 'az', 'USM Tarixçəsi', 'tools'),
  ('fetalgrowth_history_title', 'en', 'Ultrasound history', 'tools'),
  ('fetalgrowth_history_title', 'ru', 'История УЗИ', 'tools'),
  ('fetalgrowth_history_title', 'tr', 'USG Geçmişi', 'tools'),
  ('fetalgrowth_history_title', 'kk', 'УДЗ тарихы', 'tools'),
  ('fetalgrowth_history_title', 'de', 'Ultraschall-Verlauf', 'tools'),
  ('fetalgrowth_history_title', 'ar', 'سجل الموجات فوق الصوتية', 'tools'),
  ('fetalgrowth_no_scans_yet', 'az', 'Hələ USM qeydi yoxdur', 'tools'),
  ('fetalgrowth_no_scans_yet', 'en', 'No ultrasound entries yet', 'tools'),
  ('fetalgrowth_no_scans_yet', 'ru', 'Пока нет записей УЗИ', 'tools'),
  ('fetalgrowth_no_scans_yet', 'tr', 'Henüz USG kaydı yok', 'tools'),
  ('fetalgrowth_no_scans_yet', 'kk', 'Әзірге УДЗ жазбасы жоқ', 'tools'),
  ('fetalgrowth_no_scans_yet', 'de', 'Noch keine Ultraschall-Einträge', 'tools'),
  ('fetalgrowth_no_scans_yet', 'ar', 'لا توجد سجلات موجات فوق صوتية بعد', 'tools'),
  ('fetalgrowth_add_scan_hint', 'az', 'İlk USM ölçünüzü əlavə edin', 'tools'),
  ('fetalgrowth_add_scan_hint', 'en', 'Add your first ultrasound measurement', 'tools'),
  ('fetalgrowth_add_scan_hint', 'ru', 'Добавьте первое измерение УЗИ', 'tools'),
  ('fetalgrowth_add_scan_hint', 'tr', 'İlk USG ölçümünüzü ekleyin', 'tools'),
  ('fetalgrowth_add_scan_hint', 'kk', 'Алғашқы УДЗ өлшеміңізді қосыңыз', 'tools'),
  ('fetalgrowth_add_scan_hint', 'de', 'Fügen Sie Ihre erste Ultraschallmessung hinzu', 'tools'),
  ('fetalgrowth_add_scan_hint', 'ar', 'أضيفي أول قياس بالموجات فوق الصوتية', 'tools'),
  ('fetalgrowth_delete_confirm', 'az', 'Bu USM qeydini silmək istəyirsiniz?', 'tools'),
  ('fetalgrowth_delete_confirm', 'en', 'Do you want to delete this ultrasound entry?', 'tools'),
  ('fetalgrowth_delete_confirm', 'ru', 'Удалить эту запись УЗИ?', 'tools'),
  ('fetalgrowth_delete_confirm', 'tr', 'Bu USG kaydını silmek istiyor musunuz?', 'tools'),
  ('fetalgrowth_delete_confirm', 'kk', 'Осы УДЗ жазбасын жойғыңыз келе ме?', 'tools'),
  ('fetalgrowth_delete_confirm', 'de', 'Möchten Sie diesen Ultraschall-Eintrag löschen?', 'tools'),
  ('fetalgrowth_delete_confirm', 'ar', 'هل تريدين حذف سجل الموجات فوق الصوتية هذا؟', 'tools'),
  ('fetalgrowth_add_title', 'az', 'USM ölçüsü əlavə et', 'tools'),
  ('fetalgrowth_add_title', 'en', 'Add ultrasound measurement', 'tools'),
  ('fetalgrowth_add_title', 'ru', 'Добавить измерение УЗИ', 'tools'),
  ('fetalgrowth_add_title', 'tr', 'USG ölçümü ekle', 'tools'),
  ('fetalgrowth_add_title', 'kk', 'УДЗ өлшемін қосу', 'tools'),
  ('fetalgrowth_add_title', 'de', 'Ultraschallmessung hinzufügen', 'tools'),
  ('fetalgrowth_add_title', 'ar', 'إضافة قياس بالموجات فوق الصوتية', 'tools'),
  ('fetalgrowth_add_subtitle', 'az', 'Son USM-dəki təxmini çəkini daxil edin', 'tools'),
  ('fetalgrowth_add_subtitle', 'en', 'Enter the estimated weight from your latest ultrasound', 'tools'),
  ('fetalgrowth_add_subtitle', 'ru', 'Введите предполагаемый вес по последнему УЗИ', 'tools'),
  ('fetalgrowth_add_subtitle', 'tr', 'Son USG''deki tahmini ağırlığı girin', 'tools'),
  ('fetalgrowth_add_subtitle', 'kk', 'Соңғы УДЗ-дегі болжамды салмақты енгізіңіз', 'tools'),
  ('fetalgrowth_add_subtitle', 'de', 'Geben Sie das geschätzte Gewicht Ihres letzten Ultraschalls ein', 'tools'),
  ('fetalgrowth_add_subtitle', 'ar', 'أدخلي الوزن التقديري من آخر موجات فوق صوتية', 'tools'),
  ('fetalgrowth_which_baby', 'az', 'Hansı körpə?', 'tools'),
  ('fetalgrowth_which_baby', 'en', 'Which baby?', 'tools'),
  ('fetalgrowth_which_baby', 'ru', 'Какой ребёнок?', 'tools'),
  ('fetalgrowth_which_baby', 'tr', 'Hangi bebek?', 'tools'),
  ('fetalgrowth_which_baby', 'kk', 'Қай бала?', 'tools'),
  ('fetalgrowth_which_baby', 'de', 'Welches Baby?', 'tools'),
  ('fetalgrowth_which_baby', 'ar', 'أي طفل؟', 'tools'),
  ('fetalgrowth_scan_date_label', 'az', 'USM tarixi', 'tools'),
  ('fetalgrowth_scan_date_label', 'en', 'Ultrasound date', 'tools'),
  ('fetalgrowth_scan_date_label', 'ru', 'Дата УЗИ', 'tools'),
  ('fetalgrowth_scan_date_label', 'tr', 'USG tarihi', 'tools'),
  ('fetalgrowth_scan_date_label', 'kk', 'УДЗ күні', 'tools'),
  ('fetalgrowth_scan_date_label', 'de', 'Ultraschalldatum', 'tools'),
  ('fetalgrowth_scan_date_label', 'ar', 'تاريخ الموجات فوق الصوتية', 'tools'),
  ('fetalgrowth_efw_label', 'az', 'Təxmini çəki (qram)', 'tools'),
  ('fetalgrowth_efw_label', 'en', 'Estimated weight (grams)', 'tools'),
  ('fetalgrowth_efw_label', 'ru', 'Предполагаемый вес (грамм)', 'tools'),
  ('fetalgrowth_efw_label', 'tr', 'Tahmini ağırlık (gram)', 'tools'),
  ('fetalgrowth_efw_label', 'kk', 'Болжамды салмақ (грамм)', 'tools'),
  ('fetalgrowth_efw_label', 'de', 'Geschätztes Gewicht (Gramm)', 'tools'),
  ('fetalgrowth_efw_label', 'ar', 'الوزن التقديري (جرام)', 'tools'),
  ('fetalgrowth_scan_saved', 'az', 'USM qeydi yadda saxlandı! 🤰', 'tools'),
  ('fetalgrowth_scan_saved', 'en', 'Ultrasound entry saved! 🤰', 'tools'),
  ('fetalgrowth_scan_saved', 'ru', 'Запись УЗИ сохранена! 🤰', 'tools'),
  ('fetalgrowth_scan_saved', 'tr', 'USG kaydı kaydedildi! 🤰', 'tools'),
  ('fetalgrowth_scan_saved', 'kk', 'УДЗ жазбасы сақталды! 🤰', 'tools'),
  ('fetalgrowth_scan_saved', 'de', 'Ultraschall-Eintrag gespeichert! 🤰', 'tools'),
  ('fetalgrowth_scan_saved', 'ar', 'تم حفظ سجل الموجات فوق الصوتية! 🤰', 'tools'),
  ('fetalgrowth_error', 'az', 'Xəta baş verdi', 'tools'),
  ('fetalgrowth_error', 'en', 'An error occurred', 'tools'),
  ('fetalgrowth_error', 'ru', 'Произошла ошибка', 'tools'),
  ('fetalgrowth_error', 'tr', 'Bir hata oluştu', 'tools'),
  ('fetalgrowth_error', 'kk', 'Қате орын алды', 'tools'),
  ('fetalgrowth_error', 'de', 'Ein Fehler ist aufgetreten', 'tools'),
  ('fetalgrowth_error', 'ar', 'حدث خطأ', 'tools'),
  ('common_silindi', 'az', 'Silindi', 'common'),
  ('common_silindi', 'en', 'Deleted', 'common'),
  ('common_silindi', 'ru', 'Удалено', 'common'),
  ('common_silindi', 'tr', 'Silindi', 'common'),
  ('common_silindi', 'kk', 'Жойылды', 'common'),
  ('common_silindi', 'de', 'Gelöscht', 'common'),
  ('common_silindi', 'ar', 'تم الحذف', 'common')
ON CONFLICT (key, lang) DO UPDATE SET value = EXCLUDED.value;
