import { useEffect, useRef, useState } from 'react';
import { art, GROCERY_PRODUCTS, groceryCheckout, groceryTotal, laundryLoad, money, PANTRY_CAPACITY } from '../game/luzern';
import { t, text } from '../game/i18n';
import { copy as c } from '../game/copy';
import { audio } from '../game/audio';
import type { Activity, GameAction, GameState, Household } from '../game/types';
import { Icon } from './Icon';

export function HouseholdGame({ activity, state, dispatch, onFinish }: { activity: Activity; state: GameState; dispatch(action: GameAction): void; onFinish(score: number): void }) {
  switch (activity.mini) {
    case 'groceries': return <GroceriesGame state={state} dispatch={dispatch} onFinish={onFinish} />;
    case 'laundry': return <LaundryGame state={state} onFinish={onFinish} />;
    case 'cleaning': return <CleaningGame state={state} onFinish={onFinish} />;
    case 'coffeeRitual': return <CoffeeGame state={state} onFinish={onFinish} />;
    case 'lakeDiscovery': return <LakeGame state={state} onFinish={onFinish} />;
    default: return null;
  }
}

function GroceriesGame({ state, dispatch, onFinish }: { state: GameState; dispatch(action: GameAction): void; onFinish(score: number): void }) {
  const [basket, setBasket] = useState<Partial<Household['groceries']>>({}), [paid, setPaid] = useState(false), l = state.language;
  const paidRef = useRef(false), total = groceryTotal(basket), checkout = groceryCheckout(state.household, basket);
  const add = (id: keyof Household['groceries'], delta: number) => { if (paidRef.current) return; setBasket(previous => ({ ...previous, [id]: Math.max(0, Math.min(6, PANTRY_CAPACITY - state.household.groceries[id], (previous[id] ?? 0) + delta)) })); audio.tap(); };
  return <div className="groceries-game"><div className="household-game-hero"><img src={art('market')} alt="" /><span className="scene-location">LUZERN · QUARTIERMARKT</span></div><div className="household-game-heading"><span className="eyebrow">{t('familyBudget', l)} · CHF {money(state.household.cash, l)}</span><h3>{text(c('Bu gün evə nə aparaq?', 'What shall we bring home today?', 'Bugün eve ne götürelim?'), l)}</h3><p>{text(c('Siyahını ehtiyacına uyğun tamamla. Alış-veriş evdəki ərzaq ehtiyatına əlavə olunur.', 'Shop for what you need. Your purchase adds to the pantry at home.', 'İhtiyaçlarına göre alışveriş yap. Aldıkların evdeki gıda stoğuna eklenir.'), l)}</p></div>
    <div className="grocery-shelves">{GROCERY_PRODUCTS.map(p => <article key={p.id}><span className="grocery-art" style={{ '--grocery-colour': p.colour } as React.CSSProperties}><Icon name={p.icon} size={34} /></span><div><strong>{text(p.title, l)}</strong><small>CHF {money(p.price, l)} · {t('pantry', l)}: {state.household.groceries[p.id]}</small></div><div className="quantity-control"><button onClick={() => add(p.id, -1)} disabled={paid || !basket[p.id]} aria-label={`-${text(p.title, l)}`}><span>−</span></button><strong data-testid={`grocery-quantity-${p.id}`}>{basket[p.id] ?? 0}</strong><button onClick={() => add(p.id, 1)} disabled={paid || (basket[p.id] ?? 0) >= Math.min(6, PANTRY_CAPACITY - state.household.groceries[p.id])} data-testid={`grocery-plus-${p.id}`} aria-label={`+${text(p.title, l)}`}><Icon name="plus" size={14} /></button></div></article>)}</div>
    <div className="checkout-summary"><span>{t('shoppingTotal', l)}</span><strong data-testid="grocery-total">CHF {money(total, l)}</strong></div><button className="button primary large" disabled={paid || !checkout} onClick={() => { if (paidRef.current || !checkout) return; paidRef.current = true; setPaid(true); dispatch({ type: 'SHOP', basket }); onFinish(100); }} data-testid="grocery-checkout"><Icon name="bag" size={18} />{t('checkout', l)}</button>
  </div>;
}

function LaundryGame({ state, onFinish }: { state: GameState; onFinish(score: number): void }) {
  const load = useRef(laundryLoad(state.household)).current;
  const [stage, setStage] = useState(load.dirty ? 0 : 3), [selected, setSelected] = useState<number | null>(null), [sorted, setSorted] = useState<number[]>([]), [wash, setWash] = useState(0), [folds, setFolds] = useState(0), [wrong, setWrong] = useState(false);
  const [program, setProgram] = useState(30), [dried, setDried] = useState<number[]>([]), ended = useRef(false), wrongTimer = useRef<ReturnType<typeof setTimeout>>();
  const l = state.language, clothes = [0, 1, 0, 1, 1, 0].slice(0, load.dirty);
  useEffect(() => () => clearTimeout(wrongTimer.current), []);
  useEffect(() => { if (stage !== 2) return; const timer = setInterval(() => setWash(old => Math.min(100, old + 5)), 170); return () => clearInterval(timer); }, [stage]);
  useEffect(() => { if (stage === 2 && wash >= 100) { setStage(3); audio.sparkle(); } }, [wash, stage]);
  const sort = (basket: number) => { if (selected === null || sorted.includes(selected)) return; if (clothes[selected] !== basket) { setWrong(true); clearTimeout(wrongTimer.current); wrongTimer.current = setTimeout(() => setWrong(false), 350); return; } const next = [...sorted, selected]; setSorted(next); setSelected(null); audio.tap(); if (next.length === clothes.length) setStage(1); };
  return <div className="laundry-game" data-testid="laundry-game" data-stage={stage}><div className="household-game-heading"><span className="eyebrow">{t('household', l)} · 0{stage + 1}/05</span><h3>{text([c('Əvvəl rəngləri ayıraq', 'First, sort the colours', 'Önce renkleri ayıralım'), c('Yumşaq yuma proqramı', 'A gentle wash programme', 'Nazik yıkama programı'), c('Paltarlar yuyulur…', 'Laundry is washing…', 'Çamaşırlar yıkanıyor…'), c('Təmiz paltarları quruyaq', 'Dry the fresh clothes', 'Temiz giysileri kurutalım'), c('Təmiz paltarları qatlayaq', 'Fold the fresh clothes', 'Temiz giysileri katlayalım')][stage], l)}</h3><p>{text(c('Kiçik işləri öz ritminlə tamamla. Səbətdəki say oyunda dəyişir.', 'Finish the little chores at your pace. The basket count changes in the game.', 'Küçük işleri kendi ritminle tamamla. Sepetteki sayı oyunda değişir.'), l)}</p></div>
    {stage === 0 && <><div className={`laundry-baskets ${wrong ? 'shake' : ''}`}>{[0, 1].map(type => <button key={type} onClick={() => sort(type)} data-testid={`laundry-basket-${type}`} className={type === 0 ? 'light-clothes' : 'colour-clothes'}><div className="woven-basket"><Icon name="shirt" size={35} /></div><strong>{text(type === 0 ? c('Açıq rənglər', 'Light colours', 'Açık renkler') : c('Rəngli paltarlar', 'Colours', 'Renkli çamaşırlar'), l)}</strong><small>{sorted.filter(i => clothes[i] === type).length}</small></button>)}</div><div className="clothes-tray">{clothes.map((type, i) => <button className={`${type === 0 ? 'white' : 'sage'} ${selected === i ? 'selected' : ''} ${sorted.includes(i) ? 'done' : ''}`} onClick={() => setSelected(i)} key={i} disabled={sorted.includes(i)} data-testid={`laundry-cloth-${i}`}><Icon name={sorted.includes(i) ? 'check' : 'shirt'} size={28} /><span>{type === 0 ? '01' : '02'}</span></button>)}</div><small className="household-game-tip">{text(c('Paltarı seç, sonra uyğun səbətə toxun.', 'Choose a garment, then tap its matching basket.', 'Giysiyi seç, sonra uygun sepete dokun.'), l)}</small></>}
    {stage === 1 && <><div className="laundry-programs">{[30, 40].map(value => <button key={value} onClick={() => setProgram(value)} aria-pressed={program === value} className={program === value ? 'selected' : ''} data-testid={`laundry-program-${value}`}><Icon name={value === 30 ? 'leaf' : 'shirt'} size={24} /><strong>{value}°</strong><span>{text(value === 30 ? c('Yumşaq yuma', 'Gentle wash', 'Nazik yıkama') : c('Gündəlik yuma', 'Everyday wash', 'Günlük yıkama'), l)}</span></button>)}</div><button className="button primary large" onClick={() => setStage(2)} data-testid="laundry-start-wash"><Icon name="laundry" size={20} />{text(c('Yumağa başla', 'Start washing', 'Yıkamaya başla'), l)}</button></>}
    {stage === 2 && <div className="washing-stage"><div className="washing-machine"><div className="washing-controls"><span /><i /><b>{program}°</b></div><div className="washing-drum"><div><Icon name="shirt" size={39} /><Icon name="shirt" size={29} /></div><i /><i /></div></div><div className="wash-progress"><i style={{ width: `${wash}%` }} /></div><span>{wash}%</span></div>}
    {stage === 3 && <><div className="laundry-drying">{Array.from({ length: load.count }, (_, i) => <button key={i} className={dried.includes(i) ? 'done' : ''} disabled={dried.includes(i)} data-testid={`laundry-dry-${i}`} onClick={() => { const next = [...dried, i]; setDried(next); audio.tap(); if (next.length === load.count) setStage(4); }}><Icon name={dried.includes(i) ? 'check' : 'shirt'} size={40} /><span>{i + 1}</span></button>)}</div><p className="household-game-tip">{text(c('Paltarları asmaq üçün bir-bir toxun.', 'Tap each garment to hang it up to dry.', 'Giysileri asmak için tek tek dokun.'), l)}</p></>}
    {stage === 4 && <div className="folding-stage"><div className="folded-stack">{Array.from({ length: folds }, (_, i) => <i key={i} style={{ bottom: 10 + i * 13 }} />)}<button onClick={() => { if (ended.current) return; const n = folds + 1; setFolds(n); audio.tap(); if (n === load.count) { ended.current = true; onFinish(program === 30 ? 100 : 90); } }} data-testid="fold-cloth"><Icon name="shirt" size={65} /></button></div><p>{folds} / {load.count}</p><span>{text(c('Paltara toxunaraq qatla', 'Tap the garment to fold it', 'Giysiye dokunarak katla'), l)}</span></div>}
  </div>;
}

function CleaningGame({ state, onFinish }: { state: GameState; onFinish(score: number): void }) {
  const [cleaned, setCleaned] = useState<number[]>([]), [held, setHeld] = useState(false), l = state.language, zone = useRef<HTMLDivElement>(null);
  const spots = [[17, 30], [42, 54], [66, 39], [76, 74], [28, 79], [88, 23]];
  const wipe = (event: React.PointerEvent) => {
    if (!zone.current) return; const r = zone.current.getBoundingClientRect(), x = (event.clientX - r.left) / r.width * 100, y = (event.clientY - r.top) / r.height * 100;
    const next = [...cleaned]; spots.forEach(([sx, sy], i) => { if (Math.hypot(sx - x, sy - y) < 16 && !next.includes(i)) next.push(i); });
    if (next.length !== cleaned.length) { setCleaned(next); audio.tap(); if (next.length === spots.length) onFinish(100); }
  };
  return <div className="cleaning-game"><div className="household-game-heading"><span className="eyebrow">{t('household', l)}</span><h3>{text(c('Günəşli bir ev guşəsi', 'A sunny corner at home', 'Güneşli bir ev köşesi'), l)}</h3><p>{text(c('Barmağını səthdə sürüşdür. Tozlu guşələri sil, sonra rahatlığı gör.', 'Swipe across the surface. Wipe the dusty corners and see the difference.', 'Parmağını yüzeyde sürükle. Tozlu köşeleri sil ve farkı gör.'), l)}</p></div>
    <div className="cleaning-surface" ref={zone} onPointerDown={e => { e.currentTarget.setPointerCapture(e.pointerId); setHeld(true); wipe(e); }} onPointerMove={e => held && wipe(e)} onPointerUp={() => setHeld(false)} onPointerCancel={() => setHeld(false)} data-testid="cleaning-surface"><div className="surface-grain" />{spots.map(([x, y], i) => <button key={i} className={cleaned.includes(i) ? 'wiped' : ''} style={{ left: `${x}%`, top: `${y}%` }} onClick={() => { if (cleaned.includes(i)) return; const next = [...cleaned, i]; setCleaned(next); if (next.length === 6) onFinish(100); }} data-testid={`dust-${i}`} aria-label={`${t('cleanliness', l)} ${i + 1}`}><Icon name={cleaned.includes(i) ? 'sparkles' : 'cloud'} size={29} /></button>)}<span className="cleaning-cloth"><Icon name="clean" size={29} /></span></div><div className="cleaning-meter"><span>{t('cleanliness', l)}</span><div><i style={{ width: `${cleaned.length / 6 * 100}%` }} /></div><strong>{cleaned.length}/6</strong></div>
  </div>;
}

function CoffeeGame({ state, onFinish }: { state: GameState; onFinish(score: number): void }) {
  const [step, setStep] = useState(0), [fill, setFill] = useState(0), [holding, setHolding] = useState(false), l = state.language;
  useEffect(() => { if (!holding || step !== 1) return; const timer = setInterval(() => setFill(old => Math.min(100, old + 3)), 95); return () => clearInterval(timer); }, [holding, step]);
  return <div className="coffee-game"><div className="household-game-hero"><img src={art('cafe')} alt="" /></div><div className="household-game-heading"><span className="eyebrow">{t('calmMoment', l)}</span><h3>{text(c('Bir fincan, tələsmədən', 'One cup, no hurry', 'Bir fincan, acele etmeden'), l)}</h3></div><div className="coffee-cup-stage"><div className="coffee-saucer" /><div className="coffee-cup"><div className="coffee-liquid" style={{ height: `${fill * .6}%` }} /><Icon name="heart" size={22} /><i /></div><span className="coffee-steam" /></div>
    {step === 0 && <button className="button secondary large" onClick={() => { setStep(1); audio.tap(); }}><Icon name="coffee" size={20} />{text(c('Sevdiyim fincanı seç', 'Choose my favourite cup', 'Sevdiğim fincanı seç'), l)}</button>}
    {step === 1 && <><button className="coffee-pour" onPointerDown={e => { e.currentTarget.setPointerCapture(e.pointerId); setHolding(true); }} onPointerUp={() => { setHolding(false); if (fill >= 55) setStep(2); }} onPointerCancel={() => setHolding(false)} data-testid="coffee-pour"><Icon name="droplet" size={24} />{text(c('Doldurmaq üçün basıb saxla', 'Hold to pour', 'Doldurmak için basılı tut'), l)}</button><div className="coffee-fill-meter"><i style={{ width: `${fill}%` }} /></div><small>{text(c('Fincanı yarıdan bir az çox doldur', 'Pour a little over half a cup', 'Fincanı yarıdan biraz fazla doldur'), l)}</small></>}
    {step === 2 && <button className="button primary large" onClick={() => onFinish(Math.max(60, 100 - Math.abs(fill - 72)))} data-testid="coffee-finish"><Icon name="leaf" />{text(c('İndi bu anı yaşayım', 'Now enjoy this moment', 'Şimdi bu anı yaşayayım'), l)}</button>}
  </div>;
}

function LakeGame({ state, onFinish }: { state: GameState; onFinish(score: number): void }) {
  const [found, setFound] = useState<number[]>([]), l = state.language;
  return <div className="lake-game"><div className="household-game-heading"><span className="eyebrow">LUZERN · KAPELLBRÜCKE</span><h3>{text(c('Gəzintinin kiçik gözəllikləri', 'The little joys on your walk', 'Yürüyüşün küçük güzellikleri'), l)}</h3><p>{text(c('Körpünü, gölün işığını və yaşıl guşəni tap. Birlikdə mənzərəni kəşf edin.', 'Find the bridge, lake light, and greenery. Discover the view together.', 'Köprüyü, gölün ışığını ve yeşil köşeyi bul. Manzarayı birlikte keşfedin.'), l)}</p></div><div className="lake-discovery-view"><img src={art('lakeside-wide')} alt="Lake Lucerne" />{[[30, 37], [70, 63], [17, 77]].map(([x, y], i) => <button key={i} className={found.includes(i) ? 'found' : ''} style={{ left: `${x}%`, top: `${y}%` }} onClick={() => { if (found.includes(i)) return; const next = [...found, i]; setFound(next); audio.sparkle(); if (next.length === 3) onFinish(100); }} data-testid={`lake-find-${i}`} aria-label={`${t('milestones', l)} ${i + 1}`}><Icon name={found.includes(i) ? 'check' : ['home', 'waves', 'leaf'][i]} size={23} /></button>)}</div><div className="lake-found-counter"><Icon name="camera" size={17} />{found.length} / 3 · {text(c('mənzərə anı', 'scenic moments', 'manzara anı'), l)}</div></div>;
}
