import { art, dailyLifeGoals, LIFE_LOCATIONS, lifeDate, money } from '../game/luzern';
import { t, text } from '../game/i18n';
import { CHAPTERS } from '../game/content';
import { activityById, isBaby, levelFor } from '../game/engine';
import { currentStep, missionProgress, simulationWeek } from '../game/progression';
import type { Activity, GameState, Panel } from '../game/types';
import { Icon } from './Icon';
import { Needs } from './Needs';

export function LuzernHUD({ state, moving, onPanel, onMission, onPhoto, onPause, onSpeed, onCancel }: {
  state: GameState; moving: Activity | null; onPanel(p: Panel): void; onMission(): void; onPhoto(): void;
  onPause(): void; onSpeed(): void; onCancel(): void;
}) {
  const l = state.language, chapter = CHAPTERS[state.chapter], step = currentStep(state), progress = missionProgress(state), active = state.activity ? activityById(state.activity.id) : moving;
  const weather = state.household.weather, mood = state.household.moodlet === 'home' ? 'homeFeeling' : state.household.moodlet;
  return <div className="luzern-hud"><header className="luzern-top"><button className="luzern-wordmark" onClick={() => onPanel('journey')} aria-label={t('journey', l)} data-testid="nav-journey"><img src="/assets/mark.svg" alt="" /><div><strong>Mommy<span>Simulator</span></strong><small>LUZERN STORIES</small></div></button><div className="luzern-top-right"><button className="chf-wallet" onClick={() => onPanel('day')} aria-label={t('familyBudget', l)} data-testid="family-wallet" data-cash={state.household.cash}><Icon name="wallet" size={17} /><span><small>CHF</small><strong>{money(state.household.cash, l)}</strong></span></button><button className="luzern-settings" onClick={() => onPanel('settings')} aria-label={t('settings', l)}><Icon name="settings" size={19} /></button></div></header>
    <section className="luzern-daybar"><div><span>{lifeDate(state.day, l)}</span><strong>{Math.floor(state.time / 60).toString().padStart(2, '0')}<i>:</i>{Math.floor(state.time % 60).toString().padStart(2, '0')}</strong></div><button className="weather-pill" onClick={() => onPanel('day')}><Icon name={weather === 'sunny' ? 'sun' : weather === 'rain' ? 'rain' : 'cloud'} size={23} /><div><strong>{weather === 'rain' ? '12°' : weather === 'cloudy' ? '15°' : '18°'}</strong><small>{t(weather === 'rain' ? 'rainy' : weather, l)} · Luzern</small></div></button></section>
    <div className="luzern-edge-controls"><button onClick={onPhoto} aria-label={t('camera', l)} data-testid="photo-mode"><Icon name="camera" size={20} /></button><button onClick={() => onPanel('map')} aria-label={t('map', l)} data-testid="open-map"><Icon name="town" size={20} /></button><button onClick={() => onPanel('library')} aria-label={t('library', l)}><Icon name="book" size={19} /></button></div>
    <div className="luzern-dock"><div className="luzern-person-card"><button className="luzern-portrait" onClick={() => onPanel('family')} aria-label={t('family', l)}><img src={art(isBaby(state) ? 'feeding' : 'pregnancy')} alt="" /><i>{levelFor(state.xp)}</i></button><div className="luzern-person-info"><div><strong>{state.avatar.name}</strong><span><i />{t(mood, l)}</span></div><Needs state={state} compact />{isBaby(state) && <div className="luzern-baby-strip"><Icon name="baby" size={12} /><strong>{state.avatar.babyName}</strong><Needs state={state} baby compact /></div>}</div><div className="luzern-play-speed"><button onClick={onPause} aria-label={t(state.settings.speed === 0 ? 'resume' : 'pause', l)}><Icon name={state.settings.speed === 0 ? 'play' : 'pause'} size={15} /></button><button onClick={onSpeed} aria-label={t('speed', l)}>{state.settings.speed || 1}×</button></div></div>
      <button className={`luzern-next-story ${active ? 'playing' : ''}`} onClick={() => !active && onMission()} disabled={Boolean(active)} data-testid="mission-widget"><span className="luzern-next-icon"><Icon name={active?.icon ?? (step ? activityById(step.action).icon : 'trophy')} size={23} /></span><div><small>{active ? t('gameplay', l) : t('journeyContinue', l)} <i>{progress.completed}/{progress.total}</i></small><strong>{active ? text(active.title, l) : step ? text(step.title, l) : text(chapter.title, l)}</strong><div className="luzern-story-track"><i style={{ width: active ? moving ? '12%' : `${(state.activity?.elapsed ?? 0) / active.seconds * 100}%` : `${progress.percent}%` }} /></div><span>{isBaby(state) ? text(chapter.period, l) : `${t('week', l)} ${simulationWeek(state)}`} · {t('chapter', l)} {state.chapter + 1}</span></div><Icon name={active ? 'loading' : 'right'} size={19} className={active && !moving ? 'spin' : ''} /></button>
      {active && <button className="luzern-cancel" onClick={onCancel} aria-label={t('cancel', l)}><Icon name="close" size={15} /></button>}
      <nav className="luzern-navigation" aria-label="Luzern Life navigation">{(['day', 'tasks', 'map', 'decorate', 'album'] as Panel[]).map((panel, i) => <button key={panel} className={panel === 'day' ? 'active' : ''} onClick={() => onPanel(panel)} data-testid={`nav-${panel}`}><Icon name={['sun', 'bookheart', 'town', 'home', 'camera'][i]} size={21} /><span>{t(panel === 'day' ? 'lifeDay' : panel === 'tasks' ? 'journey' : panel, l)}</span>{panel === 'day' && <i>{dailyLifeGoals(state).filter(id => state.household.chores.includes(id)).length}</i>}</button>)}</nav>
    </div>
  </div>;
}
