import { activityById, availableActivities, chapterCanAdvance } from '../game/engine';
import { CHAPTERS } from '../game/content';
import { currentMission, currentStep, missionFinished, missionProgress, simulationWeek } from '../game/progression';
import { copy as c } from '../game/copy';
import { t, text } from '../game/i18n';
import type { ActivityId, GameAction, GameState } from '../game/types';
import { Icon } from './Icon';

export function MissionPanel({ state, dispatch, onActivity, onTravel, onClose }: { state: GameState; dispatch(action: GameAction): void; onActivity(id: ActivityId): void; onTravel(): void; onClose(): void }) {
  const l = state.language, mission = currentMission(state), next = currentStep(state), progress = missionProgress(state), complete = missionFinished(state), claimed = state.missions.rewards.includes(CHAPTERS[state.chapter].id);
  return <div className="mission-panel"><div className="mission-title-card"><div><span className="eyebrow">{t('mainMission', l)} · {state.chapter + 1}/14</span><h3>{text(mission.title, l)}</h3><p>{text(mission.description, l)}</p></div><span className="mission-emblem"><Icon name={CHAPTERS[state.chapter].icon} size={36} /></span><div className="mission-progress-track"><i style={{ width: `${progress.percent}%` }} /></div><small>{progress.completed} / {progress.total} {text(c('addım', 'steps', 'adım'), l)} <span>{t('week', l)} {simulationWeek(state)}</span></small></div>
    {complete && <div className="mission-finish-card"><Icon name="trophy" size={35} /><div><h3>{t('missionComplete', l)}</h3><p>+{mission.reward} <Icon name="coins" size={14} /> · +60 XP · +2 <Icon name="star" size={13} /></p></div><button className="button secondary" disabled={claimed} onClick={() => dispatch({ type: 'CLAIM_MISSION' })} data-testid="claim-mission">{t(claimed ? 'claimed' : 'missionClaim', l)}</button></div>}
    {chapterCanAdvance(state) && <button className="button primary large completed-chapter-next" onClick={() => { if (!claimed) dispatch({ type: 'CLAIM_MISSION' }); dispatch({ type: 'ADVANCE_CHAPTER' }); onClose(); }} data-testid="advance-chapter">{t('nextChapter', l)}<Icon name="arrow" /></button>}
    <div className="mission-step-list">{mission.steps.map((step, i) => {
      const done = state.missions.completed.includes(step.id), active = next?.id === step.id, wrongLocation = state.location !== step.location, a = activityById(step.action);
      return <article className={`mission-step ${done ? 'done' : active ? 'active' : 'locked'}`} key={step.id} data-testid={`mission-step-${step.id}`}><div className="mission-step-marker"><span>{done ? <Icon name="check" size={18} /> : i + 1}</span><i /></div><div className="mission-step-body"><div className="mission-step-kicker"><span>{t(step.location === 'clinic' ? 'clinic' : 'homeLocation', l)}</span>{step.interactive && <small><Icon name="play" size={11} />{t('interactive', l)}</small>}</div><h4>{text(step.title, l)}</h4><p>{text(step.description, l)}</p>{active && <button className="button primary" onClick={() => { if (step.action === 'travel' || wrongLocation) onTravel(); else onActivity(step.action); }} data-testid="mission-play"><Icon name={step.action === 'travel' || wrongLocation ? 'map' : a.icon} size={17} />{t(step.action === 'travel' || wrongLocation ? 'goThere' : step.interactive ? 'playScene' : 'doIt', l)}<Icon name="arrow" size={15} /></button>}{done && <span className="step-completed"><Icon name="check" size={12} />{t('completed', l)}</span>}</div></article>;
    })}</div>
    <div className="mission-secondary"><h4>{text(c('Sərbəst ailə həyatı', 'Free-play family life', 'Serbest aile hayatı'), l)}</h4><p>{text(c('Səhnələr arasında öz gününü yaşa. Ehtiyaclarını bərpa et, yaradıcılığını artır.', 'Live your day between scenes. Restore your needs and grow your creativity.', 'Sahneler arasında kendi gününü yaşa. İhtiyaçlarını yenile, yaratıcılığını artır.'), l)}</p><div className="freeplay-actions">{availableActivities(state).slice(0, 16).map(a => <button onClick={() => onActivity(a.id)} key={a.id} disabled={Boolean(state.activity)} data-testid={`activity-${a.id}`}><Icon name={a.icon} size={18} /><span>{text(a.title, l)}</span></button>)}</div></div>
    <div className="sleep-card"><Icon name="moon" size={25} /><div><strong>{t('sleep', l)}</strong><small>{t(state.dailyActions < 3 ? 'finishSome' : 'sleepHint', l)}</small></div><button className="icon-button" disabled={state.dailyActions < 3 || Boolean(state.activity)} onClick={() => { dispatch({ type: 'SLEEP' }); onClose(); }} aria-label={t('sleep', l)} data-testid="finish-day"><Icon name="arrow" /></button></div>
  </div>;
}

export function TownMap({ state, onTravel }: { state: GameState; onTravel(location: GameState['location']): void }) {
  const l = state.language;
  return <div className="town-map-panel"><span className="eyebrow">{t('route', l)} · ANACAN VALLEY</span><h3>{text(c('Ailənizin balaca şəhəri', 'Your family’s little town', 'Ailenizin küçük şehri'), l)}</h3><p>{text(c('Evin gündəlik həyatı və klinikadakı vacib görüşlər bir hekayənin hissələridir.', 'Everyday life at home and special clinic visits belong to one story.', 'Evdeki günlük hayat ve klinikteki önemli buluşmalar aynı hikâyenin parçaları.'), l)}</p>
    <div className="town-map-art"><svg viewBox="0 0 500 340" aria-hidden="true"><rect width="500" height="340" rx="24" fill="#dce3d5" /><path d="M-20 250Q150 130 240 180T520 70" fill="none" stroke="#bfced3" strokeWidth="32" /><path d="M50 330Q80 180 220 170T430-20" fill="none" stroke="#f1ead9" strokeWidth="39" /><path d="M60 70Q180 100 230 165T490 255" fill="none" stroke="#f1ead9" strokeWidth="29" /><path d="M50 330Q80 180 220 170T430-20" fill="none" stroke="#d2c7b1" strokeWidth="1" strokeDasharray="7 12" />{[[75, 35], [420, 310], [455, 35], [60, 280], [300, 270], [350, 50]].map(([x, y], i) => <g key={i}><circle cx={x} cy={y} r="20" fill="#a8bb9c" /><circle cx={x - 7} cy={y - 6} r="16" fill="#bcc9a9" /></g>)}<rect x="96" y="89" width="92" height="74" rx="8" fill="#d9c4a7" /><path d="m91 98 53-32 49 32" fill="#a38a71" /><rect x="119" y="112" width="21" height="24" rx="3" fill="#afc5c7" /><rect x="152" y="117" width="22" height="46" rx="3" fill="#b2a07e" /><rect x="314" y="160" width="102" height="78" rx="7" fill="#ece8d9" /><rect x="308" y="147" width="114" height="20" rx="4" fill="#9ab2a7" />{[328, 355, 382].map(x => <rect key={x} x={x} y="180" width="18" height="20" rx="3" fill="#b8ced0" />)}<path d="M358 212h20v26h-20" fill="#a9bdb0" /><path d="M360 152h14m-7-7v14" stroke="#f5eedf" strokeWidth="4" /></svg>
      <button className={`map-pin home ${state.location === 'home' ? 'here' : ''}`} onClick={() => onTravel('home')}><Icon name="home" size={24} /><span>{t('homeLocation', l)}</span></button><button className={`map-pin clinic ${state.location === 'clinic' ? 'here' : ''}`} onClick={() => onTravel('clinic')}><Icon name="doctor" size={24} /><span>{t('clinic', l)}</span></button></div>
    <div className="map-location-cards">{(['home', 'clinic'] as const).map(location => <button key={location} className={state.location === location ? 'current' : ''} onClick={() => onTravel(location)} disabled={state.location === location || Boolean(state.activity)} data-testid={`travel-${location}`}><span className="map-card-icon"><Icon name={location === 'home' ? 'home' : 'doctor'} size={25} /></span><div><strong>{t(location === 'home' ? 'homeLocation' : 'clinic', l)}</strong><small>{location === 'home' ? 'Willow House · 01' : 'Anacan Family Clinic'}</small></div><span>{t(state.location === location ? 'current' : 'travel', l)}<Icon name={state.location === location ? 'check' : 'arrow'} size={15} /></span></button>)}</div>
  </div>;
}
