import { chromium, devices } from '@playwright/test';
import { access, mkdir } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import path from 'node:path';

const root = fileURLToPath(new URL('../', import.meta.url));
await access(root);
const output = path.join(root, 'artifacts/screenshots');
await mkdir(output, { recursive: true });
const browser = await chromium.launch();
const page = await browser.newPage({ ...devices['iPhone 13'] });
await page.goto('http://127.0.0.1:5188/?e2e=1');
await page.evaluate(() => document.fonts.ready);
await page.locator('.arena-preview-phaser.ready').waitFor();
await page.waitForTimeout(400);
await page.screenshot({ path: path.join(output, 'mobile-home.png'), fullPage: true });
await page.getByTestId('play').click();
await page.screenshot({ path: path.join(output, 'mobile-tutorial.png') });
await page.getByTestId('tutorial-start').click();
await page.getByTestId('pause').waitFor();
await page.waitForFunction(() => (window.__startupio?.metrics().frames ?? 0) > 4);
await page.screenshot({ path: path.join(output, 'mobile-arena.png') });
await page.getByTestId('pause').click();
await page.setViewportSize({ width: 844, height: 390 });
await page.getByTestId('resume').click();
await page.waitForTimeout(500);
await page.screenshot({ path: path.join(output, 'mobile-landscape.png') });
await page.goto('http://127.0.0.1:5188/');
await page.setViewportSize({ width: 390, height: 844 });
await page.getByTestId('nav-marketplace').click();
await page.screenshot({ path: path.join(output, 'marketplace.png') });
await page.getByTestId('nav-customize').click();
await page.screenshot({ path: path.join(output, 'customize.png') });
await browser.close();
console.log('Captured startup.io lobby, tutorial, arena, landscape, marketplace and studio.');
