-- ============================================================
-- OzbekFix5 — baby_names_db: özbək adları dəsti (lang='uz')
-- PROBLEM: uz dilində ad siyahısı YOX idi — UZ istifadəçilər ya AZ
-- adlarını (köhnə build) ya da boş siyahı görürdü.
-- Format tr/ru seed ilə eynidir: WHERE NOT EXISTS (name+lang) — idempotent.
-- 80 ad: 40 qız + 40 oğlan, mənalar özbək dilində.
-- ============================================================

-- ── Qız adları (40) ──
INSERT INTO public.baby_names_db (name, gender, origin, meaning, origin_uz, meaning_uz, popularity, is_active, lang) SELECT 'Madina', 'girl', 'Arabcha', 'Muqaddas shahar nomidan; aziz va mo''tabar', 'Arabcha', 'Muqaddas shahar nomidan; aziz va mo''tabar', 98, true, 'uz' WHERE NOT EXISTS (SELECT 1 FROM public.baby_names_db WHERE name = 'Madina' AND lang = 'uz');
INSERT INTO public.baby_names_db (name, gender, origin, meaning, origin_uz, meaning_uz, popularity, is_active, lang) SELECT 'Sevinch', 'girl', 'O''zbekcha', 'Quvonch, shodlik', 'O''zbekcha', 'Quvonch, shodlik', 97, true, 'uz' WHERE NOT EXISTS (SELECT 1 FROM public.baby_names_db WHERE name = 'Sevinch' AND lang = 'uz');
INSERT INTO public.baby_names_db (name, gender, origin, meaning, origin_uz, meaning_uz, popularity, is_active, lang) SELECT 'Dilnoza', 'girl', 'Forscha', 'Nozik dilli, nafis va dilbar', 'Forscha', 'Nozik dilli, nafis va dilbar', 96, true, 'uz' WHERE NOT EXISTS (SELECT 1 FROM public.baby_names_db WHERE name = 'Dilnoza' AND lang = 'uz');
INSERT INTO public.baby_names_db (name, gender, origin, meaning, origin_uz, meaning_uz, popularity, is_active, lang) SELECT 'Zilola', 'girl', 'Forscha', 'Nilufar guli; pokiza va nozik', 'Forscha', 'Nilufar guli; pokiza va nozik', 94, true, 'uz' WHERE NOT EXISTS (SELECT 1 FROM public.baby_names_db WHERE name = 'Zilola' AND lang = 'uz');
INSERT INTO public.baby_names_db (name, gender, origin, meaning, origin_uz, meaning_uz, popularity, is_active, lang) SELECT 'Nilufar', 'girl', 'Forscha', 'Suv nilufari guli; go''zallik ramzi', 'Forscha', 'Suv nilufari guli; go''zallik ramzi', 93, true, 'uz' WHERE NOT EXISTS (SELECT 1 FROM public.baby_names_db WHERE name = 'Nilufar' AND lang = 'uz');
INSERT INTO public.baby_names_db (name, gender, origin, meaning, origin_uz, meaning_uz, popularity, is_active, lang) SELECT 'Gulnora', 'girl', 'Forscha', 'Anor guli; go''zal va yorqin', 'Forscha', 'Anor guli; go''zal va yorqin', 90, true, 'uz' WHERE NOT EXISTS (SELECT 1 FROM public.baby_names_db WHERE name = 'Gulnora' AND lang = 'uz');
INSERT INTO public.baby_names_db (name, gender, origin, meaning, origin_uz, meaning_uz, popularity, is_active, lang) SELECT 'Zarina', 'girl', 'Forscha', 'Oltin, zarrin; qimmatli', 'Forscha', 'Oltin, zarrin; qimmatli', 91, true, 'uz' WHERE NOT EXISTS (SELECT 1 FROM public.baby_names_db WHERE name = 'Zarina' AND lang = 'uz');
INSERT INTO public.baby_names_db (name, gender, origin, meaning, origin_uz, meaning_uz, popularity, is_active, lang) SELECT 'Kamola', 'girl', 'Arabcha', 'Komillik, yetuklik; barkamol', 'Arabcha', 'Komillik, yetuklik; barkamol', 89, true, 'uz' WHERE NOT EXISTS (SELECT 1 FROM public.baby_names_db WHERE name = 'Kamola' AND lang = 'uz');
INSERT INTO public.baby_names_db (name, gender, origin, meaning, origin_uz, meaning_uz, popularity, is_active, lang) SELECT 'Malika', 'girl', 'Arabcha', 'Qirolicha, xonim; ulug''vor', 'Arabcha', 'Qirolicha, xonim; ulug''vor', 92, true, 'uz' WHERE NOT EXISTS (SELECT 1 FROM public.baby_names_db WHERE name = 'Malika' AND lang = 'uz');
INSERT INTO public.baby_names_db (name, gender, origin, meaning, origin_uz, meaning_uz, popularity, is_active, lang) SELECT 'Nodira', 'girl', 'Arabcha', 'Noyob, tengsiz; nodir', 'Arabcha', 'Noyob, tengsiz; nodir', 88, true, 'uz' WHERE NOT EXISTS (SELECT 1 FROM public.baby_names_db WHERE name = 'Nodira' AND lang = 'uz');
INSERT INTO public.baby_names_db (name, gender, origin, meaning, origin_uz, meaning_uz, popularity, is_active, lang) SELECT 'Ruxshona', 'girl', 'Forscha', 'Yorug'' yuzli, nurli chehra', 'Forscha', 'Yorug'' yuzli, nurli chehra', 85, true, 'uz' WHERE NOT EXISTS (SELECT 1 FROM public.baby_names_db WHERE name = 'Ruxshona' AND lang = 'uz');
INSERT INTO public.baby_names_db (name, gender, origin, meaning, origin_uz, meaning_uz, popularity, is_active, lang) SELECT 'Sitora', 'girl', 'Forscha', 'Yulduz; porloq', 'Forscha', 'Yulduz; porloq', 87, true, 'uz' WHERE NOT EXISTS (SELECT 1 FROM public.baby_names_db WHERE name = 'Sitora' AND lang = 'uz');
INSERT INTO public.baby_names_db (name, gender, origin, meaning, origin_uz, meaning_uz, popularity, is_active, lang) SELECT 'Shahzoda', 'girl', 'Forscha', 'Shoh farzandi; malika', 'Forscha', 'Shoh farzandi; malika', 86, true, 'uz' WHERE NOT EXISTS (SELECT 1 FROM public.baby_names_db WHERE name = 'Shahzoda' AND lang = 'uz');
INSERT INTO public.baby_names_db (name, gender, origin, meaning, origin_uz, meaning_uz, popularity, is_active, lang) SELECT 'Mohira', 'girl', 'Arabcha', 'Mohir, iste''dodli, chevar', 'Arabcha', 'Mohir, iste''dodli, chevar', 80, true, 'uz' WHERE NOT EXISTS (SELECT 1 FROM public.baby_names_db WHERE name = 'Mohira' AND lang = 'uz');
INSERT INTO public.baby_names_db (name, gender, origin, meaning, origin_uz, meaning_uz, popularity, is_active, lang) SELECT 'Durdona', 'girl', 'Forscha', 'Dur donasi; qimmatbaho, yagona', 'Forscha', 'Dur donasi; qimmatbaho, yagona', 84, true, 'uz' WHERE NOT EXISTS (SELECT 1 FROM public.baby_names_db WHERE name = 'Durdona' AND lang = 'uz');
INSERT INTO public.baby_names_db (name, gender, origin, meaning, origin_uz, meaning_uz, popularity, is_active, lang) SELECT 'Laylo', 'girl', 'Arabcha', 'Tun; tun go''zali', 'Arabcha', 'Tun; tun go''zali', 83, true, 'uz' WHERE NOT EXISTS (SELECT 1 FROM public.baby_names_db WHERE name = 'Laylo' AND lang = 'uz');
INSERT INTO public.baby_names_db (name, gender, origin, meaning, origin_uz, meaning_uz, popularity, is_active, lang) SELECT 'Feruza', 'girl', 'Forscha', 'Feruza toshi; baxt va omad ramzi', 'Forscha', 'Feruza toshi; baxt va omad ramzi', 82, true, 'uz' WHERE NOT EXISTS (SELECT 1 FROM public.baby_names_db WHERE name = 'Feruza' AND lang = 'uz');
INSERT INTO public.baby_names_db (name, gender, origin, meaning, origin_uz, meaning_uz, popularity, is_active, lang) SELECT 'Gavhar', 'girl', 'Forscha', 'Javohir, qimmatbaho tosh', 'Forscha', 'Javohir, qimmatbaho tosh', 78, true, 'uz' WHERE NOT EXISTS (SELECT 1 FROM public.baby_names_db WHERE name = 'Gavhar' AND lang = 'uz');
INSERT INTO public.baby_names_db (name, gender, origin, meaning, origin_uz, meaning_uz, popularity, is_active, lang) SELECT 'Dildora', 'girl', 'Forscha', 'Ko''ngli yaqin, mehribon', 'Forscha', 'Ko''ngli yaqin, mehribon', 79, true, 'uz' WHERE NOT EXISTS (SELECT 1 FROM public.baby_names_db WHERE name = 'Dildora' AND lang = 'uz');
INSERT INTO public.baby_names_db (name, gender, origin, meaning, origin_uz, meaning_uz, popularity, is_active, lang) SELECT 'Shirin', 'girl', 'Forscha', 'Shirin, yoqimli; afsonaviy go''zal', 'Forscha', 'Shirin, yoqimli; afsonaviy go''zal', 77, true, 'uz' WHERE NOT EXISTS (SELECT 1 FROM public.baby_names_db WHERE name = 'Shirin' AND lang = 'uz');
INSERT INTO public.baby_names_db (name, gender, origin, meaning, origin_uz, meaning_uz, popularity, is_active, lang) SELECT 'Umida', 'girl', 'O''zbekcha', 'Umid, ishonch; kelajakka umid', 'O''zbekcha', 'Umid, ishonch; kelajakka umid', 81, true, 'uz' WHERE NOT EXISTS (SELECT 1 FROM public.baby_names_db WHERE name = 'Umida' AND lang = 'uz');
INSERT INTO public.baby_names_db (name, gender, origin, meaning, origin_uz, meaning_uz, popularity, is_active, lang) SELECT 'Zebo', 'girl', 'Forscha', 'Go''zal, chiroyli', 'Forscha', 'Go''zal, chiroyli', 76, true, 'uz' WHERE NOT EXISTS (SELECT 1 FROM public.baby_names_db WHERE name = 'Zebo' AND lang = 'uz');
INSERT INTO public.baby_names_db (name, gender, origin, meaning, origin_uz, meaning_uz, popularity, is_active, lang) SELECT 'Oydin', 'girl', 'O''zbekcha', 'Oy nuri; yorug'', munavvar', 'O''zbekcha', 'Oy nuri; yorug'', munavvar', 75, true, 'uz' WHERE NOT EXISTS (SELECT 1 FROM public.baby_names_db WHERE name = 'Oydin' AND lang = 'uz');
INSERT INTO public.baby_names_db (name, gender, origin, meaning, origin_uz, meaning_uz, popularity, is_active, lang) SELECT 'Mavluda', 'girl', 'Arabcha', 'Tug''ilgan, dunyoga kelgan', 'Arabcha', 'Tug''ilgan, dunyoga kelgan', 72, true, 'uz' WHERE NOT EXISTS (SELECT 1 FROM public.baby_names_db WHERE name = 'Mavluda' AND lang = 'uz');
INSERT INTO public.baby_names_db (name, gender, origin, meaning, origin_uz, meaning_uz, popularity, is_active, lang) SELECT 'Muslima', 'girl', 'Arabcha', 'Islom diniga e''tiqodli', 'Arabcha', 'Islom diniga e''tiqodli', 74, true, 'uz' WHERE NOT EXISTS (SELECT 1 FROM public.baby_names_db WHERE name = 'Muslima' AND lang = 'uz');
INSERT INTO public.baby_names_db (name, gender, origin, meaning, origin_uz, meaning_uz, popularity, is_active, lang) SELECT 'Robiya', 'girl', 'Arabcha', 'To''rtinchi; oilaning to''rtinchi farzandi', 'Arabcha', 'To''rtinchi; oilaning to''rtinchi farzandi', 70, true, 'uz' WHERE NOT EXISTS (SELECT 1 FROM public.baby_names_db WHERE name = 'Robiya' AND lang = 'uz');
INSERT INTO public.baby_names_db (name, gender, origin, meaning, origin_uz, meaning_uz, popularity, is_active, lang) SELECT 'Xadicha', 'girl', 'Arabcha', 'Payg''ambarimiz turmush o''rtog''i nomi; mo''tabar', 'Arabcha', 'Payg''ambarimiz turmush o''rtog''i nomi; mo''tabar', 85, true, 'uz' WHERE NOT EXISTS (SELECT 1 FROM public.baby_names_db WHERE name = 'Xadicha' AND lang = 'uz');
INSERT INTO public.baby_names_db (name, gender, origin, meaning, origin_uz, meaning_uz, popularity, is_active, lang) SELECT 'Oysha', 'girl', 'Arabcha', 'Yashovchi, hayotga to''la', 'Arabcha', 'Yashovchi, hayotga to''la', 84, true, 'uz' WHERE NOT EXISTS (SELECT 1 FROM public.baby_names_db WHERE name = 'Oysha' AND lang = 'uz');
INSERT INTO public.baby_names_db (name, gender, origin, meaning, origin_uz, meaning_uz, popularity, is_active, lang) SELECT 'Fotima', 'girl', 'Arabcha', 'Payg''ambarimiz qizlari nomi; ulug'' va aziz', 'Arabcha', 'Payg''ambarimiz qizlari nomi; ulug'' va aziz', 90, true, 'uz' WHERE NOT EXISTS (SELECT 1 FROM public.baby_names_db WHERE name = 'Fotima' AND lang = 'uz');
INSERT INTO public.baby_names_db (name, gender, origin, meaning, origin_uz, meaning_uz, popularity, is_active, lang) SELECT 'Zaynab', 'girl', 'Arabcha', 'Xushbo''y daraxt nomi; go''zal', 'Arabcha', 'Xushbo''y daraxt nomi; go''zal', 83, true, 'uz' WHERE NOT EXISTS (SELECT 1 FROM public.baby_names_db WHERE name = 'Zaynab' AND lang = 'uz');
INSERT INTO public.baby_names_db (name, gender, origin, meaning, origin_uz, meaning_uz, popularity, is_active, lang) SELECT 'Maryam', 'girl', 'Ibroniycha', 'Pokiza ayol; Iso payg''ambar onasi nomi', 'Ibroniycha', 'Pokiza ayol; Iso payg''ambar onasi nomi', 82, true, 'uz' WHERE NOT EXISTS (SELECT 1 FROM public.baby_names_db WHERE name = 'Maryam' AND lang = 'uz');
INSERT INTO public.baby_names_db (name, gender, origin, meaning, origin_uz, meaning_uz, popularity, is_active, lang) SELECT 'Iroda', 'girl', 'Arabcha', 'Iroda, qat''iyat; kuchli xarakter', 'Arabcha', 'Iroda, qat''iyat; kuchli xarakter', 73, true, 'uz' WHERE NOT EXISTS (SELECT 1 FROM public.baby_names_db WHERE name = 'Iroda' AND lang = 'uz');
INSERT INTO public.baby_names_db (name, gender, origin, meaning, origin_uz, meaning_uz, popularity, is_active, lang) SELECT 'Nafisa', 'girl', 'Arabcha', 'Nafis, nozik; qimmatli', 'Arabcha', 'Nafis, nozik; qimmatli', 79, true, 'uz' WHERE NOT EXISTS (SELECT 1 FROM public.baby_names_db WHERE name = 'Nafisa' AND lang = 'uz');
INSERT INTO public.baby_names_db (name, gender, origin, meaning, origin_uz, meaning_uz, popularity, is_active, lang) SELECT 'Munisa', 'girl', 'Arabcha', 'Do''st, hamdam, munis', 'Arabcha', 'Do''st, hamdam, munis', 78, true, 'uz' WHERE NOT EXISTS (SELECT 1 FROM public.baby_names_db WHERE name = 'Munisa' AND lang = 'uz');
INSERT INTO public.baby_names_db (name, gender, origin, meaning, origin_uz, meaning_uz, popularity, is_active, lang) SELECT 'Charos', 'girl', 'O''zbekcha', 'Uzum navi; qora ko''zli go''zal', 'O''zbekcha', 'Uzum navi; qora ko''zli go''zal', 77, true, 'uz' WHERE NOT EXISTS (SELECT 1 FROM public.baby_names_db WHERE name = 'Charos' AND lang = 'uz');
INSERT INTO public.baby_names_db (name, gender, origin, meaning, origin_uz, meaning_uz, popularity, is_active, lang) SELECT 'Lobar', 'girl', 'Forscha', 'Go''zal, latofatli, dilbar', 'Forscha', 'Go''zal, latofatli, dilbar', 71, true, 'uz' WHERE NOT EXISTS (SELECT 1 FROM public.baby_names_db WHERE name = 'Lobar' AND lang = 'uz');
INSERT INTO public.baby_names_db (name, gender, origin, meaning, origin_uz, meaning_uz, popularity, is_active, lang) SELECT 'Yulduz', 'girl', 'O''zbekcha', 'Yulduz; porloq va yorqin', 'O''zbekcha', 'Yulduz; porloq va yorqin', 80, true, 'uz' WHERE NOT EXISTS (SELECT 1 FROM public.baby_names_db WHERE name = 'Yulduz' AND lang = 'uz');
INSERT INTO public.baby_names_db (name, gender, origin, meaning, origin_uz, meaning_uz, popularity, is_active, lang) SELECT 'Ezoza', 'girl', 'Arabcha', 'E''zozlangan, aziz va hurmatli', 'Arabcha', 'E''zozlangan, aziz va hurmatli', 76, true, 'uz' WHERE NOT EXISTS (SELECT 1 FROM public.baby_names_db WHERE name = 'Ezoza' AND lang = 'uz');
INSERT INTO public.baby_names_db (name, gender, origin, meaning, origin_uz, meaning_uz, popularity, is_active, lang) SELECT 'Rayhona', 'girl', 'Arabcha', 'Rayhon guli; xushbo''y', 'Arabcha', 'Rayhon guli; xushbo''y', 75, true, 'uz' WHERE NOT EXISTS (SELECT 1 FROM public.baby_names_db WHERE name = 'Rayhona' AND lang = 'uz');
INSERT INTO public.baby_names_db (name, gender, origin, meaning, origin_uz, meaning_uz, popularity, is_active, lang) SELECT 'Asal', 'girl', 'Arabcha', 'Asal; shirin va yoqimli', 'Arabcha', 'Asal; shirin va yoqimli', 86, true, 'uz' WHERE NOT EXISTS (SELECT 1 FROM public.baby_names_db WHERE name = 'Asal' AND lang = 'uz');

-- ── Oğlan adları (40) ──
INSERT INTO public.baby_names_db (name, gender, origin, meaning, origin_uz, meaning_uz, popularity, is_active, lang) SELECT 'Muhammadali', 'boy', 'Arabcha', 'Muhammad va Ali nomlari birikmasi; maqtovga loyiq va yuksak', 'Arabcha', 'Muhammad va Ali nomlari birikmasi; maqtovga loyiq va yuksak', 99, true, 'uz' WHERE NOT EXISTS (SELECT 1 FROM public.baby_names_db WHERE name = 'Muhammadali' AND lang = 'uz');
INSERT INTO public.baby_names_db (name, gender, origin, meaning, origin_uz, meaning_uz, popularity, is_active, lang) SELECT 'Abdulloh', 'boy', 'Arabcha', 'Allohning bandasi', 'Arabcha', 'Allohning bandasi', 97, true, 'uz' WHERE NOT EXISTS (SELECT 1 FROM public.baby_names_db WHERE name = 'Abdulloh' AND lang = 'uz');
INSERT INTO public.baby_names_db (name, gender, origin, meaning, origin_uz, meaning_uz, popularity, is_active, lang) SELECT 'Aziz', 'boy', 'Arabcha', 'Aziz, qadrli, hurmatli', 'Arabcha', 'Aziz, qadrli, hurmatli', 92, true, 'uz' WHERE NOT EXISTS (SELECT 1 FROM public.baby_names_db WHERE name = 'Aziz' AND lang = 'uz');
INSERT INTO public.baby_names_db (name, gender, origin, meaning, origin_uz, meaning_uz, popularity, is_active, lang) SELECT 'Jasur', 'boy', 'Arabcha', 'Jasur, botir, qo''rqmas', 'Arabcha', 'Jasur, botir, qo''rqmas', 93, true, 'uz' WHERE NOT EXISTS (SELECT 1 FROM public.baby_names_db WHERE name = 'Jasur' AND lang = 'uz');
INSERT INTO public.baby_names_db (name, gender, origin, meaning, origin_uz, meaning_uz, popularity, is_active, lang) SELECT 'Bobur', 'boy', 'Forscha', 'Sher, yo''lbars; Bobur Mirzo nomidan', 'Forscha', 'Sher, yo''lbars; Bobur Mirzo nomidan', 90, true, 'uz' WHERE NOT EXISTS (SELECT 1 FROM public.baby_names_db WHERE name = 'Bobur' AND lang = 'uz');
INSERT INTO public.baby_names_db (name, gender, origin, meaning, origin_uz, meaning_uz, popularity, is_active, lang) SELECT 'Temur', 'boy', 'Turkiycha', 'Temir; mustahkam, matonatli; Amir Temur nomidan', 'Turkiycha', 'Temir; mustahkam, matonatli; Amir Temur nomidan', 94, true, 'uz' WHERE NOT EXISTS (SELECT 1 FROM public.baby_names_db WHERE name = 'Temur' AND lang = 'uz');
INSERT INTO public.baby_names_db (name, gender, origin, meaning, origin_uz, meaning_uz, popularity, is_active, lang) SELECT 'Ulug''bek', 'boy', 'Turkiycha', 'Ulug'' bek; Mirzo Ulug''bek nomidan', 'Turkiycha', 'Ulug'' bek; Mirzo Ulug''bek nomidan', 89, true, 'uz' WHERE NOT EXISTS (SELECT 1 FROM public.baby_names_db WHERE name = 'Ulug''bek' AND lang = 'uz');
INSERT INTO public.baby_names_db (name, gender, origin, meaning, origin_uz, meaning_uz, popularity, is_active, lang) SELECT 'Sardor', 'boy', 'Forscha', 'Yo''lboshchi, sarkarda', 'Forscha', 'Yo''lboshchi, sarkarda', 91, true, 'uz' WHERE NOT EXISTS (SELECT 1 FROM public.baby_names_db WHERE name = 'Sardor' AND lang = 'uz');
INSERT INTO public.baby_names_db (name, gender, origin, meaning, origin_uz, meaning_uz, popularity, is_active, lang) SELECT 'Shohruh', 'boy', 'Forscha', 'Shoh ruhi; Shohruh Mirzo nomidan', 'Forscha', 'Shoh ruhi; Shohruh Mirzo nomidan', 87, true, 'uz' WHERE NOT EXISTS (SELECT 1 FROM public.baby_names_db WHERE name = 'Shohruh' AND lang = 'uz');
INSERT INTO public.baby_names_db (name, gender, origin, meaning, origin_uz, meaning_uz, popularity, is_active, lang) SELECT 'Otabek', 'boy', 'Turkiycha', 'Ota kabi g''amxo''r bek; "O''tkan kunlar" qahramoni', 'Turkiycha', 'Ota kabi g''amxo''r bek; "O''tkan kunlar" qahramoni', 88, true, 'uz' WHERE NOT EXISTS (SELECT 1 FROM public.baby_names_db WHERE name = 'Otabek' AND lang = 'uz');
INSERT INTO public.baby_names_db (name, gender, origin, meaning, origin_uz, meaning_uz, popularity, is_active, lang) SELECT 'Doston', 'boy', 'Forscha', 'Doston; qahramonlik qissasi', 'Forscha', 'Doston; qahramonlik qissasi', 85, true, 'uz' WHERE NOT EXISTS (SELECT 1 FROM public.baby_names_db WHERE name = 'Doston' AND lang = 'uz');
INSERT INTO public.baby_names_db (name, gender, origin, meaning, origin_uz, meaning_uz, popularity, is_active, lang) SELECT 'Javohir', 'boy', 'Arabcha', 'Javohir, qimmatbaho tosh', 'Arabcha', 'Javohir, qimmatbaho tosh', 86, true, 'uz' WHERE NOT EXISTS (SELECT 1 FROM public.baby_names_db WHERE name = 'Javohir' AND lang = 'uz');
INSERT INTO public.baby_names_db (name, gender, origin, meaning, origin_uz, meaning_uz, popularity, is_active, lang) SELECT 'Ibrohim', 'boy', 'Arabcha', 'Payg''ambar nomi; xalqlar otasi', 'Arabcha', 'Payg''ambar nomi; xalqlar otasi', 84, true, 'uz' WHERE NOT EXISTS (SELECT 1 FROM public.baby_names_db WHERE name = 'Ibrohim' AND lang = 'uz');
INSERT INTO public.baby_names_db (name, gender, origin, meaning, origin_uz, meaning_uz, popularity, is_active, lang) SELECT 'Yusuf', 'boy', 'Arabcha', 'Payg''ambar nomi; go''zallik ramzi', 'Arabcha', 'Payg''ambar nomi; go''zallik ramzi', 90, true, 'uz' WHERE NOT EXISTS (SELECT 1 FROM public.baby_names_db WHERE name = 'Yusuf' AND lang = 'uz');
INSERT INTO public.baby_names_db (name, gender, origin, meaning, origin_uz, meaning_uz, popularity, is_active, lang) SELECT 'Umar', 'boy', 'Arabcha', 'Hayot, uzoq umr', 'Arabcha', 'Hayot, uzoq umr', 83, true, 'uz' WHERE NOT EXISTS (SELECT 1 FROM public.baby_names_db WHERE name = 'Umar' AND lang = 'uz');
INSERT INTO public.baby_names_db (name, gender, origin, meaning, origin_uz, meaning_uz, popularity, is_active, lang) SELECT 'Islom', 'boy', 'Arabcha', 'Islom; itoat va tinchlik', 'Arabcha', 'Islom; itoat va tinchlik', 82, true, 'uz' WHERE NOT EXISTS (SELECT 1 FROM public.baby_names_db WHERE name = 'Islom' AND lang = 'uz');
INSERT INTO public.baby_names_db (name, gender, origin, meaning, origin_uz, meaning_uz, popularity, is_active, lang) SELECT 'Amir', 'boy', 'Arabcha', 'Amir, boshliq, hukmdor', 'Arabcha', 'Amir, boshliq, hukmdor', 85, true, 'uz' WHERE NOT EXISTS (SELECT 1 FROM public.baby_names_db WHERE name = 'Amir' AND lang = 'uz');
INSERT INTO public.baby_names_db (name, gender, origin, meaning, origin_uz, meaning_uz, popularity, is_active, lang) SELECT 'Akbar', 'boy', 'Arabcha', 'Eng ulug'', buyuk', 'Arabcha', 'Eng ulug'', buyuk', 78, true, 'uz' WHERE NOT EXISTS (SELECT 1 FROM public.baby_names_db WHERE name = 'Akbar' AND lang = 'uz');
INSERT INTO public.baby_names_db (name, gender, origin, meaning, origin_uz, meaning_uz, popularity, is_active, lang) SELECT 'Alisher', 'boy', 'Forscha', 'Ali sheri; Alisher Navoiy nomidan', 'Forscha', 'Ali sheri; Alisher Navoiy nomidan', 89, true, 'uz' WHERE NOT EXISTS (SELECT 1 FROM public.baby_names_db WHERE name = 'Alisher' AND lang = 'uz');
INSERT INTO public.baby_names_db (name, gender, origin, meaning, origin_uz, meaning_uz, popularity, is_active, lang) SELECT 'Farrux', 'boy', 'Forscha', 'Baxtli, qutlug'', muborak', 'Forscha', 'Baxtli, qutlug'', muborak', 80, true, 'uz' WHERE NOT EXISTS (SELECT 1 FROM public.baby_names_db WHERE name = 'Farrux' AND lang = 'uz');
INSERT INTO public.baby_names_db (name, gender, origin, meaning, origin_uz, meaning_uz, popularity, is_active, lang) SELECT 'Firdavs', 'boy', 'Forscha', 'Jannat bog''i', 'Forscha', 'Jannat bog''i', 76, true, 'uz' WHERE NOT EXISTS (SELECT 1 FROM public.baby_names_db WHERE name = 'Firdavs' AND lang = 'uz');
INSERT INTO public.baby_names_db (name, gender, origin, meaning, origin_uz, meaning_uz, popularity, is_active, lang) SELECT 'G''ayrat', 'boy', 'Arabcha', 'G''ayrat, shijoat, kuch', 'Arabcha', 'G''ayrat, shijoat, kuch', 74, true, 'uz' WHERE NOT EXISTS (SELECT 1 FROM public.baby_names_db WHERE name = 'G''ayrat' AND lang = 'uz');
INSERT INTO public.baby_names_db (name, gender, origin, meaning, origin_uz, meaning_uz, popularity, is_active, lang) SELECT 'Hasan', 'boy', 'Arabcha', 'Go''zal, yaxshi', 'Arabcha', 'Go''zal, yaxshi', 81, true, 'uz' WHERE NOT EXISTS (SELECT 1 FROM public.baby_names_db WHERE name = 'Hasan' AND lang = 'uz');
INSERT INTO public.baby_names_db (name, gender, origin, meaning, origin_uz, meaning_uz, popularity, is_active, lang) SELECT 'Husan', 'boy', 'Arabcha', 'Go''zallik; Hasanning egizi', 'Arabcha', 'Go''zallik; Hasanning egizi', 80, true, 'uz' WHERE NOT EXISTS (SELECT 1 FROM public.baby_names_db WHERE name = 'Husan' AND lang = 'uz');
INSERT INTO public.baby_names_db (name, gender, origin, meaning, origin_uz, meaning_uz, popularity, is_active, lang) SELECT 'Kamron', 'boy', 'Forscha', 'Baxtli, muvaffaqiyatli', 'Forscha', 'Baxtli, muvaffaqiyatli', 79, true, 'uz' WHERE NOT EXISTS (SELECT 1 FROM public.baby_names_db WHERE name = 'Kamron' AND lang = 'uz');
INSERT INTO public.baby_names_db (name, gender, origin, meaning, origin_uz, meaning_uz, popularity, is_active, lang) SELECT 'Mirzo', 'boy', 'Forscha', 'Shahzoda; o''qimishli, ziyoli', 'Forscha', 'Shahzoda; o''qimishli, ziyoli', 75, true, 'uz' WHERE NOT EXISTS (SELECT 1 FROM public.baby_names_db WHERE name = 'Mirzo' AND lang = 'uz');
INSERT INTO public.baby_names_db (name, gender, origin, meaning, origin_uz, meaning_uz, popularity, is_active, lang) SELECT 'Muslim', 'boy', 'Arabcha', 'Islomga e''tiqodli', 'Arabcha', 'Islomga e''tiqodli', 73, true, 'uz' WHERE NOT EXISTS (SELECT 1 FROM public.baby_names_db WHERE name = 'Muslim' AND lang = 'uz');
INSERT INTO public.baby_names_db (name, gender, origin, meaning, origin_uz, meaning_uz, popularity, is_active, lang) SELECT 'Nodir', 'boy', 'Arabcha', 'Noyob, kamyob', 'Arabcha', 'Noyob, kamyob', 77, true, 'uz' WHERE NOT EXISTS (SELECT 1 FROM public.baby_names_db WHERE name = 'Nodir' AND lang = 'uz');
INSERT INTO public.baby_names_db (name, gender, origin, meaning, origin_uz, meaning_uz, popularity, is_active, lang) SELECT 'Ozod', 'boy', 'Forscha', 'Erkin, ozod', 'Forscha', 'Erkin, ozod', 76, true, 'uz' WHERE NOT EXISTS (SELECT 1 FROM public.baby_names_db WHERE name = 'Ozod' AND lang = 'uz');
INSERT INTO public.baby_names_db (name, gender, origin, meaning, origin_uz, meaning_uz, popularity, is_active, lang) SELECT 'Rustam', 'boy', 'Forscha', 'Qahramon, pahlavon; "Shohnoma" qahramoni', 'Forscha', 'Qahramon, pahlavon; "Shohnoma" qahramoni', 84, true, 'uz' WHERE NOT EXISTS (SELECT 1 FROM public.baby_names_db WHERE name = 'Rustam' AND lang = 'uz');
INSERT INTO public.baby_names_db (name, gender, origin, meaning, origin_uz, meaning_uz, popularity, is_active, lang) SELECT 'Sanjar', 'boy', 'Turkiycha', 'Shiddatli; Sulton Sanjar nomidan', 'Turkiycha', 'Shiddatli; Sulton Sanjar nomidan', 78, true, 'uz' WHERE NOT EXISTS (SELECT 1 FROM public.baby_names_db WHERE name = 'Sanjar' AND lang = 'uz');
INSERT INTO public.baby_names_db (name, gender, origin, meaning, origin_uz, meaning_uz, popularity, is_active, lang) SELECT 'Shavkat', 'boy', 'Arabcha', 'Shon-shavkat, qudrat', 'Arabcha', 'Shon-shavkat, qudrat', 75, true, 'uz' WHERE NOT EXISTS (SELECT 1 FROM public.baby_names_db WHERE name = 'Shavkat' AND lang = 'uz');
INSERT INTO public.baby_names_db (name, gender, origin, meaning, origin_uz, meaning_uz, popularity, is_active, lang) SELECT 'Sherzod', 'boy', 'Forscha', 'Sher o''g''li; botir', 'Forscha', 'Sher o''g''li; botir', 86, true, 'uz' WHERE NOT EXISTS (SELECT 1 FROM public.baby_names_db WHERE name = 'Sherzod' AND lang = 'uz');
INSERT INTO public.baby_names_db (name, gender, origin, meaning, origin_uz, meaning_uz, popularity, is_active, lang) SELECT 'Shukur', 'boy', 'Arabcha', 'Shukr, minnatdorlik', 'Arabcha', 'Shukr, minnatdorlik', 72, true, 'uz' WHERE NOT EXISTS (SELECT 1 FROM public.baby_names_db WHERE name = 'Shukur' AND lang = 'uz');
INSERT INTO public.baby_names_db (name, gender, origin, meaning, origin_uz, meaning_uz, popularity, is_active, lang) SELECT 'Suhrob', 'boy', 'Forscha', 'Yorqin yulduz; "Shohnoma" qahramoni', 'Forscha', 'Yorqin yulduz; "Shohnoma" qahramoni', 74, true, 'uz' WHERE NOT EXISTS (SELECT 1 FROM public.baby_names_db WHERE name = 'Suhrob' AND lang = 'uz');
INSERT INTO public.baby_names_db (name, gender, origin, meaning, origin_uz, meaning_uz, popularity, is_active, lang) SELECT 'Tohir', 'boy', 'Arabcha', 'Pok, toza', 'Arabcha', 'Pok, toza', 73, true, 'uz' WHERE NOT EXISTS (SELECT 1 FROM public.baby_names_db WHERE name = 'Tohir' AND lang = 'uz');
INSERT INTO public.baby_names_db (name, gender, origin, meaning, origin_uz, meaning_uz, popularity, is_active, lang) SELECT 'Zafar', 'boy', 'Arabcha', 'G''alaba, zafar', 'Arabcha', 'G''alaba, zafar', 79, true, 'uz' WHERE NOT EXISTS (SELECT 1 FROM public.baby_names_db WHERE name = 'Zafar' AND lang = 'uz');
INSERT INTO public.baby_names_db (name, gender, origin, meaning, origin_uz, meaning_uz, popularity, is_active, lang) SELECT 'Zohid', 'boy', 'Arabcha', 'Taqvodor, parhezkor', 'Arabcha', 'Taqvodor, parhezkor', 70, true, 'uz' WHERE NOT EXISTS (SELECT 1 FROM public.baby_names_db WHERE name = 'Zohid' AND lang = 'uz');
INSERT INTO public.baby_names_db (name, gender, origin, meaning, origin_uz, meaning_uz, popularity, is_active, lang) SELECT 'Diyor', 'boy', 'Forscha', 'Vatan, yurt', 'Forscha', 'Vatan, yurt', 77, true, 'uz' WHERE NOT EXISTS (SELECT 1 FROM public.baby_names_db WHERE name = 'Diyor' AND lang = 'uz');
INSERT INTO public.baby_names_db (name, gender, origin, meaning, origin_uz, meaning_uz, popularity, is_active, lang) SELECT 'Bekzod', 'boy', 'Forscha', 'Bek avlodi, asilzoda', 'Forscha', 'Bek avlodi, asilzoda', 81, true, 'uz' WHERE NOT EXISTS (SELECT 1 FROM public.baby_names_db WHERE name = 'Bekzod' AND lang = 'uz');
