-- ============================================================
-- Ereb5 — EPDS cavab variantlarına text_ar əlavə olunur
-- QEYD: Alman5-dən SONRA işlədin (mövcud text_ru/tr/kk/de qorunur).
-- ============================================================


UPDATE public.epds_questions SET options = '[{"text":"As much as I always could","value":0,"text_az":"Həmişəki kimi","text_de":"So wie immer","text_kk":"Әдеттегідей","text_ru":"Как всегда","text_tr":"Her zamanki kadar","text_ar":"كما هي عادتي دائمًا"},{"text":"Not quite so much now","value":1,"text_az":"İndi o qədər də yox","text_de":"Jetzt nicht mehr ganz so sehr","text_kk":"Қазір онша емес","text_ru":"Сейчас уже не так","text_tr":"Şimdi eskisi kadar değil","text_ar":"ليس بالقدر نفسه الآن"},{"text":"Definitely not so much now","value":2,"text_az":"Əlbəttə ki, indi o qədər yox","text_de":"Jetzt eindeutig nicht mehr so sehr","text_kk":"Әрине, қазір бұрынғыдай емес","text_ru":"Определённо, сейчас уже не так","text_tr":"Kesinlikle artık eskisi kadar değil","text_ar":"بالتأكيد أقل بكثير الآن"},{"text":"Not at all","value":3,"text_az":"Heç","text_de":"Überhaupt nicht","text_kk":"Мүлде жоқ","text_ru":"Совсем нет","text_tr":"Hiç","text_ar":"إطلاقًا"}]'::jsonb WHERE id = '277c938a-fb4a-486c-b34d-e552dd72625e';

UPDATE public.epds_questions SET options = '[{"text":"As much as I ever did","value":0,"text_az":"Həmişəki kimi","text_de":"So wie immer","text_kk":"Әдеттегідей","text_ru":"Как всегда","text_tr":"Her zamanki kadar","text_ar":"كما هي عادتي دائمًا"},{"text":"Rather less than I used to","value":1,"text_az":"Əvvəlkindən az","text_de":"Weniger als früher","text_kk":"Бұрынғыдан азырақ","text_ru":"Меньше, чем раньше","text_tr":"Eskisinden daha az","text_ar":"أقل من السابق"},{"text":"Definitely less than I used to","value":2,"text_az":"Əvvəlkindən xeyli az","text_de":"Deutlich weniger als früher","text_kk":"Бұрынғыдан әлдеқайда аз","text_ru":"Значительно меньше, чем раньше","text_tr":"Eskisinden çok daha az","text_ar":"أقل بكثير من السابق"},{"text":"Hardly at all","value":3,"text_az":"Demək olar ki, heç","text_de":"Fast überhaupt nicht","text_kk":"Мүлде дерлік жоқ","text_ru":"Почти никогда","text_tr":"Neredeyse hiç","text_ar":"تقريبًا أبدًا"}]'::jsonb WHERE id = '4a420fda-2d8d-426c-a5e1-f7df0bf3d4c7';

UPDATE public.epds_questions SET options = '[{"text":"Yes, most of the time","value":3,"text_az":"Bəli, çox vaxt","text_de":"Ja, meistens","text_kk":"Иә, көбінесе","text_ru":"Да, большую часть времени","text_tr":"Evet, çoğu zaman","text_ar":"نعم، معظم الوقت"},{"text":"Yes, some of the time","value":2,"text_az":"Bəli, bəzən","text_de":"Ja, manchmal","text_kk":"Иә, кейде","text_ru":"Да, иногда","text_tr":"Evet, bazen","text_ar":"نعم، أحيانًا"},{"text":"Not very often","value":1,"text_az":"Çox tez-tez yox","text_de":"Nicht sehr oft","text_kk":"Онша жиі емес","text_ru":"Не очень часто","text_tr":"Çok sık değil","text_ar":"ليس كثيرًا"},{"text":"No, never","value":0,"text_az":"Xeyr, heç vaxt","text_de":"Nein, niemals","text_kk":"Жоқ, ешқашан","text_ru":"Нет, никогда","text_tr":"Hayır, hiçbir zaman","text_ar":"لا، أبدًا"}]'::jsonb WHERE id = '617495b6-4b22-4a30-add7-080988a6d0af';

UPDATE public.epds_questions SET options = '[{"text":"No, not at all","value":0,"text_az":"Xeyr, heç","text_de":"Nein, überhaupt nicht","text_kk":"Жоқ, мүлде жоқ","text_ru":"Нет, совсем нет","text_tr":"Hayır, hiç","text_ar":"لا، إطلاقًا"},{"text":"Hardly ever","value":1,"text_az":"Demək olar ki, heç","text_de":"Fast überhaupt nicht","text_kk":"Мүлде дерлік жоқ","text_ru":"Почти никогда","text_tr":"Neredeyse hiç","text_ar":"تقريبًا أبدًا"},{"text":"Yes, sometimes","value":2,"text_az":"Bəli, bəzən","text_de":"Ja, manchmal","text_kk":"Иә, кейде","text_ru":"Да, иногда","text_tr":"Evet, bazen","text_ar":"نعم، أحيانًا"},{"text":"Yes, very often","value":3,"text_az":"Bəli, çox tez-tez","text_de":"Ja, sehr oft","text_kk":"Иә, өте жиі","text_ru":"Да, очень часто","text_tr":"Evet, çok sık","text_ar":"نعم، كثيرًا جدًا"}]'::jsonb WHERE id = '507845db-fd7f-4a9f-b4cc-6c3ff4bb0535';

UPDATE public.epds_questions SET options = '[{"text":"Yes, quite a lot","value":3,"text_az":"Bəli, kifayət qədər çox","text_de":"Ja, ziemlich oft","text_kk":"Иә, айтарлықтай жиі","text_ru":"Да, довольно часто","text_tr":"Evet, oldukça sık","text_ar":"نعم، كثيرًا إلى حدّ ما"},{"text":"Yes, sometimes","value":2,"text_az":"Bəli, bəzən","text_de":"Ja, manchmal","text_kk":"Иә, кейде","text_ru":"Да, иногда","text_tr":"Evet, bazen","text_ar":"نعم، أحيانًا"},{"text":"No, not much","value":1,"text_az":"Xeyr, çox yox","text_de":"Nein, nicht sehr","text_kk":"Жоқ, онша емес","text_ru":"Нет, не очень часто","text_tr":"Hayır, pek değil","text_ar":"لا، ليس كثيرًا"},{"text":"No, not at all","value":0,"text_az":"Xeyr, heç","text_de":"Nein, überhaupt nicht","text_kk":"Жоқ, мүлде жоқ","text_ru":"Нет, совсем нет","text_tr":"Hayır, hiç","text_ar":"لا، إطلاقًا"}]'::jsonb WHERE id = '1084fc38-0a22-4825-9661-8e3a8cce0a12';

UPDATE public.epds_questions SET options = '[{"text":"Yes, most of the time I haven''t been able to cope at all","value":3,"text_az":"Bəli, çox vaxt heç bacarmırdım","text_de":"Ja, meistens kam ich überhaupt nicht zurecht","text_kk":"Иә, көбінесе мүлде жеңе алмадым","text_ru":"Да, большую часть времени совсем не удавалось справляться","text_tr":"Evet, çoğu zaman hiç başa çıkamıyordum","text_ar":"نعم، في معظم الأوقات لم أكن قادرة على التأقلم إطلاقًا"},{"text":"Yes, sometimes I haven''t been coping as well as usual","value":2,"text_az":"Bəli, bəzən həmişəki kimi bacarırdım","text_de":"Ja, manchmal kam ich nicht so gut zurecht wie sonst","text_kk":"Иә, кейде әдеттегідей жеңе алдым","text_ru":"Да, иногда удавалось справляться как обычно","text_tr":"Evet, bazen her zamanki gibi başa çıkabiliyordum","text_ar":"نعم، أحيانًا لم أكن قادرة على التأقلم كعادتي"},{"text":"No, most of the time I have coped quite well","value":1,"text_az":"Xeyr, çox vaxt yaxşı bacarırdım","text_de":"Nein, meistens kam ich recht gut zurecht","text_kk":"Жоқ, көбінесе жақсы жеңе алдым","text_ru":"Нет, большую часть времени удавалось справляться довольно хорошо","text_tr":"Hayır, çoğu zaman iyi başa çıkabiliyordum","text_ar":"لا، كنت قادرة على التأقلم جيدًا معظم الوقت"},{"text":"No, I have been coping as well as ever","value":0,"text_az":"Xeyr, həmişəki kimi bacarırdım","text_de":"Nein, ich kam so gut zurecht wie immer","text_kk":"Жоқ, әдеттегідей жеңе алдым","text_ru":"Нет, удавалось справляться как обычно","text_tr":"Hayır, her zamanki gibi başa çıkabiliyordum","text_ar":"لا، كنت قادرة على التأقلم كعادتي دائمًا"}]'::jsonb WHERE id = 'd51a6901-6595-4091-afb1-5ec4059046c2';

UPDATE public.epds_questions SET options = '[{"text":"Yes, most of the time","value":3,"text_az":"Bəli, çox vaxt","text_de":"Ja, meistens","text_kk":"Иә, көбінесе","text_ru":"Да, большую часть времени","text_tr":"Evet, çoğu zaman","text_ar":"نعم، معظم الوقت"},{"text":"Yes, sometimes","value":2,"text_az":"Bəli, bəzən","text_de":"Ja, manchmal","text_kk":"Иә, кейде","text_ru":"Да, иногда","text_tr":"Evet, bazen","text_ar":"نعم، أحيانًا"},{"text":"Not very often","value":1,"text_az":"Çox tez-tez yox","text_de":"Nicht sehr oft","text_kk":"Онша жиі емес","text_ru":"Не очень часто","text_tr":"Çok sık değil","text_ar":"ليس كثيرًا"},{"text":"No, not at all","value":0,"text_az":"Xeyr, heç","text_de":"Nein, überhaupt nicht","text_kk":"Жоқ, мүлде жоқ","text_ru":"Нет, совсем нет","text_tr":"Hayır, hiç","text_ar":"لا، إطلاقًا"}]'::jsonb WHERE id = '251f439e-2a72-48b6-aac2-cc3886ff44da';

UPDATE public.epds_questions SET options = '[{"text":"Yes, most of the time","value":3,"text_az":"Bəli, çox vaxt","text_de":"Ja, meistens","text_kk":"Иә, көбінесе","text_ru":"Да, большую часть времени","text_tr":"Evet, çoğu zaman","text_ar":"نعم، معظم الوقت"},{"text":"Yes, quite often","value":2,"text_az":"Bəli, tez-tez","text_de":"Ja, oft","text_kk":"Иә, жиі","text_ru":"Да, часто","text_tr":"Evet, sık sık","text_ar":"نعم، غالبًا"},{"text":"Not very often","value":1,"text_az":"Çox tez-tez yox","text_de":"Nicht sehr oft","text_kk":"Онша жиі емес","text_ru":"Не очень часто","text_tr":"Çok sık değil","text_ar":"ليس كثيرًا"},{"text":"No, not at all","value":0,"text_az":"Xeyr, heç","text_de":"Nein, überhaupt nicht","text_kk":"Жоқ, мүлде жоқ","text_ru":"Нет, совсем нет","text_tr":"Hayır, hiç","text_ar":"لا، إطلاقًا"}]'::jsonb WHERE id = '87b54c96-ffd4-48de-bb2f-98ac41ec65e3';

UPDATE public.epds_questions SET options = '[{"text":"Yes, most of the time","value":3,"text_az":"Bəli, çox vaxt","text_de":"Ja, meistens","text_kk":"Иә, көбінесе","text_ru":"Да, большую часть времени","text_tr":"Evet, çoğu zaman","text_ar":"نعم، معظم الوقت"},{"text":"Yes, quite often","value":2,"text_az":"Bəli, tez-tez","text_de":"Ja, oft","text_kk":"Иә, жиі","text_ru":"Да, часто","text_tr":"Evet, sık sık","text_ar":"نعم، غالبًا"},{"text":"Only occasionally","value":1,"text_az":"Yalnız bəzən","text_de":"Nur manchmal","text_kk":"Тек кейде","text_ru":"Только иногда","text_tr":"Yalnızca bazen","text_ar":"في بعض الأحيان فقط"},{"text":"No, never","value":0,"text_az":"Xeyr, heç vaxt","text_de":"Nein, niemals","text_kk":"Жоқ, ешқашан","text_ru":"Нет, никогда","text_tr":"Hayır, hiçbir zaman","text_ar":"لا، أبدًا"}]'::jsonb WHERE id = '7bf201c9-c37f-422f-b61b-02b1c6fac4c0';

UPDATE public.epds_questions SET options = '[{"text":"Yes, quite often","value":3,"text_az":"Bəli, tez-tez","text_de":"Ja, oft","text_kk":"Иә, жиі","text_ru":"Да, часто","text_tr":"Evet, sık sık","text_ar":"نعم، غالبًا"},{"text":"Sometimes","value":2,"text_az":"Bəzən","text_de":"Manchmal","text_kk":"Кейде","text_ru":"Иногда","text_tr":"Bazen","text_ar":"أحيانًا"},{"text":"Hardly ever","value":1,"text_az":"Demək olar ki, heç","text_de":"Fast überhaupt nicht","text_kk":"Мүлде дерлік жоқ","text_ru":"Почти никогда","text_tr":"Neredeyse hiç","text_ar":"تقريبًا أبدًا"},{"text":"Never","value":0,"text_az":"Heç vaxt","text_de":"Niemals","text_kk":"Ешқашан","text_ru":"Никогда","text_tr":"Hiçbir zaman","text_ar":"أبدًا"}]'::jsonb WHERE id = '1ef9070f-81ad-4cee-bf09-cb4b156af990';
