-- Funnel/paywall/ölkə seçici/AI kalori açarları — idempotent
INSERT INTO public.translations (key, lang, value, namespace) VALUES
  ('funnel_month_stats', 'ru', 'мес. — 82% мам с малышом этого возраста сталкиваются с похожими трудностями.', 'common'),
  ('funnel_month_stats', 'tr', 'aylık bebeği olan annelerin %82’si benzer zorluklarla karşılaşıyor.', 'common'),
  ('funnel_month_stats', 'en', 'months old — 82% of moms with a baby this age face similar challenges.', 'common'),
  ('funnel_cycle_stats', 'ru', 'дн. цикл — мы подготовили персональный анализ на его основе.', 'common'),
  ('funnel_cycle_stats', 'tr', 'günlük döngünüze göre kişisel analiz hazırladık.', 'common'),
  ('funnel_cycle_stats', 'en', 'day cycle — we prepared a personal analysis based on it.', 'common'),
  ('funneldata_ay_1', 'ru', 'Месяц 1', 'common'),
  ('funneldata_ay_1', 'tr', 'Ay 1', 'common'),
  ('funneldata_ay_1', 'en', 'Month 1', 'common'),
  ('funneldata_ay_3', 'ru', 'Месяц 3', 'common'),
  ('funneldata_ay_3', 'tr', 'Ay 3', 'common'),
  ('funneldata_ay_3', 'en', 'Month 3', 'common'),
  ('revtrial_context_bump', 'ru', '{week}-я неделя, {tri}-й триместр', 'common'),
  ('revtrial_context_bump', 'tr', '{week}. hafta, {tri}. trimester', 'common'),
  ('revtrial_context_bump', 'en', 'Week {week}, trimester {tri}', 'common'),
  ('revtrial_context_mommy', 'ru', '{name} — {months} мес.', 'common'),
  ('revtrial_context_mommy', 'tr', '{name} — {months} aylık', 'common'),
  ('revtrial_context_mommy', 'en', '{name} — {months} months old', 'common'),
  ('howapphelps_stat_tools', 'ru', 'Инструментов', 'common'),
  ('howapphelps_stat_tools', 'tr', 'Profesyonel araç', 'common'),
  ('howapphelps_stat_tools', 'en', 'Expert tools', 'common'),
  ('howapphelps_stat_moms', 'ru', 'Мам в сообществе', 'common'),
  ('howapphelps_stat_moms', 'tr', 'Toplulukta anne', 'common'),
  ('howapphelps_stat_moms', 'en', 'Moms in community', 'common'),
  ('howapphelps_stat_langs', 'ru', 'Языка', 'common'),
  ('howapphelps_stat_langs', 'tr', 'Dil desteği', 'common'),
  ('howapphelps_stat_langs', 'en', 'Languages', 'common'),
  ('howapphelps_trust_line', 'ru', 'Контент проверяется врачами · Ваши данные защищены', 'common'),
  ('howapphelps_trust_line', 'tr', 'İçerik doktor onaylı · Verileriniz korunur', 'common'),
  ('howapphelps_trust_line', 'en', 'Content is doctor-reviewed · Your data is protected', 'common'),
  ('nutrition_ai_kalori_axtarir', 'ru', 'AI определяет...', 'common'),
  ('nutrition_ai_kalori_axtarir', 'tr', 'AI belirliyor...', 'common'),
  ('nutrition_ai_kalori_axtarir', 'en', 'AI is estimating...', 'common'),
  ('countryselect_olke_secin', 'ru', 'Выберите страну', 'common'),
  ('countryselect_olke_secin', 'tr', 'Ülke seçin', 'common'),
  ('countryselect_olke_secin', 'en', 'Select country', 'common'),
  ('countryselect_axtar', 'ru', 'Поиск...', 'common'),
  ('countryselect_axtar', 'tr', 'Ara...', 'common'),
  ('countryselect_axtar', 'en', 'Search...', 'common'),
  ('countryselect_tapilmadi', 'ru', 'Страна не найдена', 'common'),
  ('countryselect_tapilmadi', 'tr', 'Ülke bulunamadı', 'common'),
  ('countryselect_tapilmadi', 'en', 'No countries found', 'common'),
  ('paywallstep_3_gunluk_pulsuz_dovrunuz_basladi_d84d42', 'ru', 'Ваш 3-дневный бесплатный период начался', 'common'),
  ('paywallstep_3_gunluk_pulsuz_dovrunuz_basladi_d84d42', 'tr', '3 günlük ücretsiz döneminiz başladı', 'common'),
  ('paywallstep_3_gunluk_pulsuz_dovrunuz_basladi_d84d42', 'en', 'Your 3-day free trial has started', 'common'),
  ('paywallstep_alis_ugursuz_ffb098', 'ru', 'Покупка не удалась', 'common'),
  ('paywallstep_alis_ugursuz_ffb098', 'tr', 'Satın alma başarısız', 'common'),
  ('paywallstep_alis_ugursuz_ffb098', 'en', 'Purchase failed', 'common'),
  ('paywallstep_ayliq_6f265e', 'ru', 'Месячный', 'common'),
  ('paywallstep_ayliq_6f265e', 'tr', 'Aylık', 'common'),
  ('paywallstep_ayliq_6f265e', 'en', 'Monthly', 'common'),
  ('paywallstep_butun_aletlere_sinirsiz_giris_2d0db2', 'ru', 'Безлимитный доступ ко всем инструментам', 'common'),
  ('paywallstep_butun_aletlere_sinirsiz_giris_2d0db2', 'tr', 'Tüm araçlara sınırsız erişim', 'common'),
  ('paywallstep_butun_aletlere_sinirsiz_giris_2d0db2', 'en', 'Unlimited access to all tools', 'common'),
  ('paywallstep_en_serfeli_056ce6', 'ru', 'Самый выгодный ·', 'common'),
  ('paywallstep_en_serfeli_056ce6', 'tr', 'En avantajlı ·', 'common'),
  ('paywallstep_en_serfeli_056ce6', 'en', 'The most affordable', 'common'),
  ('paywallstep_ferdi_heftelik_hesabatlar_4ab67b', 'ru', 'Персональные недельные отчёты', 'common'),
  ('paywallstep_ferdi_heftelik_hesabatlar_4ab67b', 'tr', 'Kişisel haftalık raporlar', 'common'),
  ('paywallstep_ferdi_heftelik_hesabatlar_4ab67b', 'en', 'Individual weekly reports', 'common'),
  ('paywallstep_gun_pulsuz_sinaq_0787ff', 'ru', 'ДНЕЙ БЕСПЛАТНО', 'common'),
  ('paywallstep_gun_pulsuz_sinaq_0787ff', 'tr', 'GÜN ÜCRETSİZ DENEME', 'common'),
  ('paywallstep_gun_pulsuz_sinaq_0787ff', 'en', 'DAY FREE TRIAL', 'common'),
  ('paywallstep_illik_4a3cef', 'ru', 'Годовой', 'common'),
  ('paywallstep_illik_4a3cef', 'tr', 'Yıllık', 'common'),
  ('paywallstep_illik_4a3cef', 'en', 'Annual', 'common'),
  ('paywallstep_istediyin_an_legv_et_zemanetli_c95beb', 'ru', 'Отменяйте в любой момент · С гарантией', 'common'),
  ('paywallstep_istediyin_an_legv_et_zemanetli_c95beb', 'tr', 'İstediğin an iptal et · Garantili', 'common'),
  ('paywallstep_istediyin_an_legv_et_zemanetli_c95beb', 'en', 'Cancel anytime · Guaranteed', 'common'),
  ('paywallstep_premium_a_kec_2e8b0e', 'ru', 'Перейти на Premium', 'common'),
  ('paywallstep_premium_a_kec_2e8b0e', 'tr', 'Premium''a Geç', 'common'),
  ('paywallstep_premium_a_kec_2e8b0e', 'en', 'Go Premium', 'common'),
  ('paywallstep_premium_aktivlesdi_67ea32', 'ru', 'Premium активирован 🎉', 'common'),
  ('paywallstep_premium_aktivlesdi_67ea32', 'tr', 'Premium etkinleşti 🎉', 'common'),
  ('paywallstep_premium_aktivlesdi_67ea32', 'en', 'Premium activated 🎉', 'common'),
  ('paywallstep_qenaet_ea8b53', 'ru', '% экономии', 'common'),
  ('paywallstep_qenaet_ea8b53', 'tr', '% tasarruf', 'common'),
  ('paywallstep_qenaet_ea8b53', 'en', '% savings', 'common'),
  ('paywallstep_qiymetler_yuklenir_15aa82', 'ru', 'Цены загружаются...', 'common'),
  ('paywallstep_qiymetler_yuklenir_15aa82', 'tr', 'Fiyatlar yükleniyor...', 'common'),
  ('paywallstep_qiymetler_yuklenir_15aa82', 'en', 'Prices loading...', 'common'),
  ('paywallstep_reklamsiz_tecrube_2e4fa4', 'ru', 'Без рекламы', 'common'),
  ('paywallstep_reklamsiz_tecrube_2e4fa4', 'tr', 'Reklamsız deneyim', 'common'),
  ('paywallstep_reklamsiz_tecrube_2e4fa4', 'en', 'An ad-free experience', 'common'),
  ('paywallstep_tam_imkanlardan_yararlanin_4b72fb', 'ru', 'Используйте все возможности', 'common'),
  ('paywallstep_tam_imkanlardan_yararlanin_4b72fb', 'tr', 'Tüm imkanlardan yararlanın', 'common'),
  ('paywallstep_tam_imkanlardan_yararlanin_4b72fb', 'en', 'Enjoy full features', 'common'),
  ('paywallstep_yuxu_sesleri_meditasiya_fb635f', 'ru', 'Звуки сна и медитация', 'common'),
  ('paywallstep_yuxu_sesleri_meditasiya_fb635f', 'tr', 'Uyku Sesleri & Meditasyon', 'common'),
  ('paywallstep_yuxu_sesleri_meditasiya_fb635f', 'en', 'Sleep Sounds & Meditation', 'common'),
  ('funneldata_ciddi_yuxusuzluq_painpoint', 'ru', 'Серьёзная бессонница', 'common'),
  ('funneldata_ciddi_yuxusuzluq_painpoint', 'tr', 'Ciddi uykusuzluk', 'common'),
  ('funneldata_ciddi_yuxusuzluq_painpoint', 'en', 'Severe sleeplessness', 'common'),
  ('funneldata_yuxusuzluq_painpoint', 'ru', 'Бессонница', 'common'),
  ('funneldata_yuxusuzluq_painpoint', 'tr', 'Uykusuzluk', 'common'),
  ('funneldata_yuxusuzluq_painpoint', 'en', 'Sleeplessness', 'common')
ON CONFLICT (key, lang) DO NOTHING;
