import type { Activity, Chapter, Copy, Furniture } from './types';
import { copy } from './copy';
import { SIM_CHAPTERS } from './scenario';
import { SIM_ACTIVITIES } from './sim-activities';
import { DAILY_LIFE_ACTIVITIES } from './luzern';
export { copy } from './copy';
export const CHAPTERS: Chapter[] = SIM_CHAPTERS;

export const ACTIVITIES: Activity[] = [
  ...SIM_ACTIVITIES,
  ...DAILY_LIFE_ACTIVITIES,
  { id: 'rest', title: copy('Bir az dincəl', 'A little rest', 'Biraz dinlen'), description: copy('Yumşaq divan, sakit bir an. Bu vaxt sənindir.', 'A soft sofa and a quiet moment. This time is yours.', 'Yumuşacık kanepe ve sakin bir an. Bu zaman senin.'), result: copy('Bir az yavaşlamaq yaxşı gəldi.', 'Slowing down felt good.', 'Biraz yavaşlamak iyi geldi.'), icon: 'moon', room: 'living', target: 'sofa', seconds: 7, minutes: 60, effect: { energy: 30, mood: 8 }, skill: 'balance', xp: 12, coins: 8 },
  { id: 'water', title: copy('Sərin su fasiləsi', 'A refreshing pause', 'Serin bir su molası'), description: copy('Mətbəxdə kiçik, təravətli fasilə.', 'A little refreshing pause in the kitchen.', 'Mutfakta küçük, ferahlatıcı bir mola.'), result: copy('Balaca fasilə, yeni enerji!', 'A small pause, fresh energy!', 'Küçük bir mola, yeni enerji!'), icon: 'droplet', room: 'kitchen', target: 'counter', seconds: 3, minutes: 15, effect: { energy: 5, food: 8, mood: 4 }, skill: 'balance', xp: 8, coins: 6 },
  { id: 'cook', title: copy('Sevgi ilə bişir', 'Cook with love', 'Sevgiyle pişir'), description: copy('Anacan reseptlərindən birini seç və rəngli süfrə hazırla.', 'Choose an Anacan recipe and make a colourful meal.', 'Anacan tariflerinden birini seç ve renkli bir sofra hazırla.'), result: copy('Mətbəxdən gələn qoxu bütün evi isidir.', 'The kitchen smells like home.', 'Mutfaktan gelen koku bütün evi ısıtıyor.'), icon: 'cooking', room: 'kitchen', target: 'counter', seconds: 8, minutes: 45, effect: { food: 32, mood: 10, energy: -6 }, skill: 'cooking', xp: 20, coins: 18, mini: 'cooking' },
  { id: 'read', title: copy('Bir nağıl vaxtı', 'A little story time', 'Bir masal zamanı'), description: copy('Ən sevdiyin guşədə bir nağıl, bir isti səs.', 'A story and a warm voice in your favourite corner.', 'En sevdiğin köşede bir masal, sıcacık bir ses.'), result: copy('Bu səs, bu an, bu yaxınlıq…', 'This voice, this moment, this closeness…', 'Bu ses, bu an, bu yakınlık…'), icon: 'book', room: 'living', target: 'sofa', seconds: 7, minutes: 30, effect: { mood: 12, bond: 12, energy: -3 }, skill: 'creativity', xp: 16, coins: 12 },
  { id: 'breathe', title: copy('Nəfəs al, gülümsə', 'Breathe and smile', 'Nefes al, gülümse'), description: copy('Dörd sakit nəfəs. Çiyinlərini rahatlat və özünü dinlə.', 'Four calm breaths. Relax your shoulders and listen to yourself.', 'Dört sakin nefes. Omuzlarını gevşet ve kendini dinle.'), result: copy('İndi bir az daha yüngülsən.', 'You feel a little lighter now.', 'Şimdi biraz daha hafifsin.'), icon: 'wind', room: 'garden', target: 'bench', seconds: 8, minutes: 20, effect: { mood: 20, energy: 10 }, skill: 'balance', xp: 14, coins: 10 },
  { id: 'walk', title: copy('Bağda bir gəzinti', 'A garden stroll', 'Bahçede bir yürüyüş'), description: copy('Günəş, yarpaqlar və tələsmədən atılan addımlar.', 'Sunshine, leaves, and unhurried steps.', 'Güneş, yapraklar ve acele etmeden atılan adımlar.'), result: copy('Bağın havası gününə rəng qatdı.', 'The garden brightened your day.', 'Bahçe gününe renk kattı.'), icon: 'leaf', room: 'garden', target: 'bench', seconds: 8, minutes: 35, effect: { mood: 18, energy: -6, bond: 5 }, skill: 'balance', xp: 16, coins: 12 },
  { id: 'plant', title: copy('Bir çiçək ək', 'Plant a little flower', 'Bir çiçek ek'), description: copy('Balaca toxum, böyük sevinc. Bağında bir rəng də artsın.', 'A tiny seed, a big joy. Add another colour to your garden.', 'Küçük bir tohum, büyük bir sevinç. Bahçene bir renk daha ekle.'), result: copy('Bu çiçək sənin qayğınla böyüyəcək.', 'This flower will grow with your care.', 'Bu çiçek senin ilginle büyüyecek.'), icon: 'flower', room: 'garden', target: 'planter', seconds: 6, minutes: 30, effect: { mood: 14, energy: -4 }, skill: 'creativity', xp: 18, coins: 16 },
  { id: 'talk', title: copy('Birlikdə bir an', 'A moment together', 'Birlikte bir an'), description: copy('Gününüzdən danışın, xəyallarınızı paylaşın.', 'Talk about your day and share your dreams.', 'Gününüzü anlatın, hayallerinizi paylaşın.'), result: copy('Birlikdə hər şey daha gözəldir.', 'Everything is lovelier together.', 'Birlikte her şey daha güzel.'), icon: 'heart', room: 'living', target: 'partner', seconds: 7, minutes: 30, effect: { mood: 18, bond: 12 }, skill: 'care', xp: 16, coins: 12 },
  { id: 'help', title: copy('Dəstəyi paylaş', 'Share the care', 'Desteği paylaş'), description: copy('Ailə dəstəyi ilə özünə kiçik bir fasilə ver.', 'Let your family help while you take a small break.', 'Ailenin desteğiyle kendine küçük bir mola ver.'), result: copy('Qayğı paylaşdıqca çoxalır.', 'Care grows when it is shared.', 'Bakım paylaştıkça çoğalır.'), icon: 'hands', room: 'living', target: 'partner', seconds: 6, minutes: 30, effect: { energy: 18, comfort: 12, mood: 10, babySleep: 10 }, skill: 'care', xp: 18, coins: 14 },
  { id: 'pack', title: copy('Doğum çantam', 'My hospital bag', 'Doğum çantam'), description: copy('Anacan siyahısından balaca çantanı hazırlayaq.', 'Pack your little bag with the Anacan checklist.', 'Anacan listesiyle küçük çantanı hazırlayalım.'), result: copy('Hazırlıq tamam, ürəyin daha rahatdır.', 'All packed, a little more peace of mind.', 'Hazırlık tamam, için daha rahat.'), icon: 'bag', room: 'nursery', target: 'dresser', seconds: 7, minutes: 40, effect: { mood: 14, energy: -3 }, skill: 'care', xp: 22, coins: 18, pregnancyOnly: true, mini: 'packing' },
  { id: 'feed', title: copy('Balacamın yemək vaxtı', 'Little one’s feeding time', 'Bebeğimin beslenme zamanı'), description: copy('Rahat kreslo, isti qucaq və tələsmədən qayğı.', 'A cosy chair, a warm cuddle, and unhurried care.', 'Rahat bir koltuk, sıcacık bir kucak ve sakin bir bakım.'), result: copy('Balacan rahatlandı, sənə daha da yaxınlaşdı.', 'Your little one feels content and close to you.', 'Bebeğin rahatladı, sana biraz daha yakınlaştı.'), icon: 'bottle', room: 'nursery', target: 'chair', seconds: 8, minutes: 30, effect: { babyFood: 34, comfort: 10, bond: 10, energy: -6 }, skill: 'care', xp: 22, coins: 16, babyOnly: true },
  { id: 'diaper', title: copy('Təmiz, rahat, xoşbəxt', 'Fresh, cosy, happy', 'Temiz, rahat, mutlu'), description: copy('Balacanın bezini dəyiş və yumşaq bir qucaq ver.', 'A fresh nappy and a soft cuddle.', 'Bebeğinin bezini değiştir ve yumuşacık sarıl.'), result: copy('Balaca ayaqlar xoşbəxtlikdən tərpənir!', 'Tiny feet wiggle with happiness!', 'Minik ayaklar mutluluktan kıpırdıyor!'), icon: 'sparkles', room: 'nursery', target: 'dresser', seconds: 6, minutes: 20, effect: { comfort: 32, mood: 5, energy: -4 }, skill: 'care', xp: 18, coins: 14, babyOnly: true },
  { id: 'lullaby', title: copy('Şirin yuxular', 'Sweet dreams', 'Tatlı rüyalar'), description: copy('Laylanın ritmini tap, balacan sakitcə yuxuya getsin.', 'Find the lullaby rhythm and help your little one drift off.', 'Ninninin ritmini bul, bebeğin usulca uykuya dalsın.'), result: copy('Şşş… evdə şirin bir sakitlik var.', 'Shhh… a sweet quiet fills the house.', 'Şşş… evde tatlı bir sessizlik var.'), icon: 'music', room: 'nursery', target: 'crib', seconds: 8, minutes: 45, effect: { babySleep: 34, comfort: 10, bond: 8, energy: -4 }, skill: 'care', xp: 20, coins: 16, babyOnly: true, mini: 'lullaby' },
  { id: 'play', title: copy('Kəşf edək, gülək!', 'Discover and giggle!', 'Keşfedelim, gülelim!'), description: copy('Rəngli oyuncaqlar, balaca kəşflər, böyük gülüşlər.', 'Colourful toys, tiny discoveries, great big giggles.', 'Renkli oyuncaklar, küçük keşifler, kocaman kahkahalar.'), result: copy('Bu gülüş günün ən gözəl səsidir.', 'That giggle is the best sound of the day.', 'Bu kahkaha günün en güzel sesi.'), icon: 'blocks', room: 'nursery', target: 'playmat', seconds: 8, minutes: 30, effect: { bond: 18, comfort: 14, mood: 14, babySleep: -8, energy: -6 }, skill: 'creativity', xp: 24, coins: 18, babyOnly: true, mini: 'discovery' },
  { id: 'bath', title: copy('Köpüklü fasilə', 'A bubbly little pause', 'Köpüklü bir mola'), description: copy('İsti rənglər, yumşaq dəsmal və sakit bir axşam.', 'Warm colours, a soft towel, and a peaceful evening.', 'Sıcak renkler, yumuşacık havlu ve sakin bir akşam.'), result: copy('Təmizlik və rahatlıq — günün yumşaq sonu.', 'Fresh and relaxed — a soft end to the day.', 'Temizlik ve rahatlık — günün yumuşak sonu.'), icon: 'bath', room: 'bathroom', target: 'bath', seconds: 7, minutes: 30, effect: { comfort: 22, mood: 14, energy: 6 }, skill: 'balance', xp: 16, coins: 12 },
  { id: 'journal', title: copy('Xatirə dəftərim', 'My memory journal', 'Anı defterim'), description: copy('Bu günün bir gözəl anını yadda saxla.', 'Keep one lovely moment from today.', 'Bugünün güzel bir anını sakla.'), result: copy('Balaca anlar ən qiymətli xatirələrdir.', 'Little moments make the most precious memories.', 'Küçük anlar en değerli anılardır.'), icon: 'pen', room: 'living', target: 'desk', seconds: 6, minutes: 20, effect: { mood: 14, bond: 6 }, skill: 'creativity', xp: 18, coins: 14 },
  { id: 'checkup', title: copy('Anacan guşəsi', 'The Anacan corner', 'Anacan köşesi'), description: copy('Bu fəslə aid məlumatı kəşf et və gününə kiçik bir ilham götür.', 'Discover this chapter’s notes and a little inspiration for your day.', 'Bu bölüme ait bilgileri keşfet ve gününe küçük bir ilham al.'), result: copy('Biliklə böyüyür, sevgi ilə irəliləyirsən.', 'Growing with knowledge, moving with love.', 'Bilgiyle büyüyor, sevgiyle ilerliyorsun.'), icon: 'bookheart', room: 'living', target: 'desk', seconds: 5, minutes: 20, effect: { mood: 10 }, skill: 'care', xp: 16, coins: 10 },
  { id: 'tidy', title: copy('Yuvama kiçik qayğı', 'A little love for home', 'Yuvama küçük bir ilgi'), description: copy('Oyuncaqlar yerinə, yastıqlar guşəsinə. Sonra bir fasilə!', 'Toys in place, cushions fluffed. Then a break!', 'Oyuncaklar yerine, yastıklar köşesine. Sonra bir mola!'), result: copy('İsti, səliqəli bir yuva.', 'A warm, cosy little nest.', 'Sıcak, düzenli bir yuva.'), icon: 'home', room: 'nursery', target: 'dresser', seconds: 6, minutes: 30, effect: { mood: 12, comfort: 8, energy: -6 }, skill: 'balance', xp: 16, coins: 16 },
];

export const FURNITURE: Furniture[] = [
  { id: 'cloud-rug', title: copy('Bulud xalça', 'Cloud rug', 'Bulut halı'), description: copy('Balaca ayaqlar üçün yumşaq bir bulud.', 'A soft cloud for tiny feet.', 'Minik ayaklar için yumuşacık bir bulut.'), kind: 'rug', price: 65, level: 1, colour: '#e1d9ee', icon: 'cloud', room: 'nursery' },
  { id: 'olive-plant', title: copy('Zeytun ağacı', 'Little olive tree', 'Minik zeytin ağacı'), description: copy('Evinə bir az təbiət gətir.', 'Bring a little nature home.', 'Evine biraz doğa getir.'), kind: 'plant', price: 45, level: 1, colour: '#98b8a0', icon: 'leaf', room: 'living' },
  { id: 'moon-lamp', title: copy('Ay işığı', 'Moon lamp', 'Ay ışığı'), description: copy('Layla vaxtının yumşaq işığı.', 'A gentle glow for lullaby time.', 'Ninni zamanının yumuşak ışığı.'), kind: 'lamp', price: 80, level: 1, colour: '#f8dda7', icon: 'moon', room: 'nursery' },
  { id: 'rose-ottoman', title: copy('Çəhrayı puf', 'Rose pouf', 'Pembe puf'), description: copy('Dincəlmək üçün balaca rahatlıq.', 'A little comfort for resting.', 'Dinlenmek için küçük bir rahatlık.'), kind: 'ottoman', price: 75, level: 2, colour: '#dfb0b9', icon: 'sofa', room: 'living' },
  { id: 'rainbow-toy', title: copy('Taxta göy qurşağı', 'Wooden rainbow', 'Ahşap gökkuşağı'), description: copy('Rənglər, formalar və balaca kəşflər.', 'Colours, shapes, and little discoveries.', 'Renkler, şekiller ve küçük keşifler.'), kind: 'toy', price: 55, level: 1, colour: '#dda889', icon: 'rainbow', room: 'nursery' },
  { id: 'wildflowers', title: copy('Çöl çiçəkləri', 'Wildflowers', 'Kır çiçekleri'), description: copy('Hər günə bir az bahar.', 'A little spring in every day.', 'Her güne biraz bahar.'), kind: 'flowers', price: 40, level: 1, colour: '#c5a1ca', icon: 'flower', room: 'garden' },
  { id: 'story-shelf', title: copy('Nağıl rəfi', 'Story shelf', 'Masal rafı'), description: copy('İçində yüz balaca macəra var.', 'A hundred tiny adventures inside.', 'İçinde yüz küçük macera var.'), kind: 'shelf', price: 110, level: 3, colour: '#d0b49b', icon: 'book', room: 'living' },
  { id: 'sage-rug', title: copy('Bağ rəngli xalça', 'Sage garden rug', 'Bahçe renkli halı'), description: copy('Evin ortasında sakit bir guşə.', 'A peaceful corner in the heart of home.', 'Evin ortasında sakin bir köşe.'), kind: 'rug', price: 85, level: 2, colour: '#abc7b7', icon: 'leaf', room: 'living' },
];

export const SKINS = ['#f4cbae', '#e3ae87', '#bd8059', '#8c573f', '#623e30'];
export const HAIRS = ['#53372e', '#241e25', '#966349', '#d5a66b', '#b96550'];
export const OUTFITS = ['#ad94cd', '#dc9fac', '#8cb8a3', '#d6a377', '#82a8bd'];
export const ROOM_LABELS: Record<string, Copy> = {
  living: copy('Qonaq otağı', 'Living room', 'Oturma odası'), kitchen: copy('Mətbəx', 'Kitchen', 'Mutfak'),
  nursery: copy('Körpə otağı', 'Nursery', 'Bebek odası'), garden: copy('Bağ', 'Garden', 'Bahçe'),
  bathroom: copy('Hamam', 'Bathroom', 'Banyo'), clinic: copy('Klinika', 'Clinic', 'Klinik'), bedroom: copy('Yataq otağı', 'Bedroom', 'Yatak odası'),
  lakeside: copy('Luzern gölü', 'Lake Lucerne', 'Luzern Gölü'), market: copy('Market', 'Market', 'Market'), cafe: copy('Kafe', 'Café', 'Kafe'),
};

for (const activity of ACTIVITIES) {
  if (['feed', 'diaper', 'sterilise'].includes(activity.id)) activity.mini = 'babyCare';
  if (activity.id === 'breathe') activity.mini = 'breathing';
}

export const STORIES = [
  { id: 'little-secret', chapter: 0, day: 1, icon: 'heart', title: copy('Şirin sirrimizi paylaşaq?', 'Shall we share our sweet secret?', 'Tatlı sırrımızı paylaşalım mı?'),
    body: copy('Axşam günəşi pəncərəyə düşür. Yanındakı sevdiyin insan “Bu gün gözlərində ayrı bir işıq var” deyir.', 'The evening sun touches the window. Your loved one says, “There is a special sparkle in your eyes today.”', 'Akşam güneşi pencereye vuruyor. Sevdiğin insan “Bugün gözlerinde başka bir ışık var” diyor.'),
    choices: [copy('Balaca bir sürpriz hazırla', 'Make a little surprise', 'Küçük bir sürpriz hazırla'), copy('İsti bir qucaqla de', 'Tell them with a warm hug', 'Sıcak bir sarılmayla söyle')] },
  { id: 'nursery-dream', chapter: 2, day: 1, icon: 'home', title: copy('Balaca otağın böyük xəyalı', 'Big dreams for a little room', 'Küçük odanın büyük hayali'),
    body: copy('Boş bir guşə gözləyir. Burada hansı xatirələr yaranacaq? Birlikdə körpənin gələcək otağını xəyal edirsiniz.', 'An empty corner is waiting. What memories will live here? You dream up your little one’s room together.', 'Boş bir köşe bekliyor. Burada hangi anılar oluşacak? Bebeğinizin odasını birlikte hayal ediyorsunuz.'),
    choices: [copy('Ulduzlu bir gecə mövzusu', 'A starry-night theme', 'Yıldızlı gece teması'), copy('Təbiət və yumşaq rənglər', 'Nature and gentle colours', 'Doğa ve yumuşak renkler')] },
  { id: 'welcome', chapter: 4, day: 1, icon: 'baby', title: copy('Evin yeni səsi', 'A new sound at home', 'Evin yeni sesi'),
    body: copy('Balacan qucağında sakitləşir. Bu, ailənizin ilk birlikdə axşamıdır. Mükəmməl olmasına ehtiyac yoxdur, sizin olmasına yetər.', 'Your little one settles in your arms. It is your family’s first evening together. It only needs to be yours.', 'Bebeğin kucağında sakinleşiyor. Ailenizin ilk birlikte akşamı. Size ait olması yeter.'),
    choices: [copy('İlk ailə şəklimizi çəkək', 'Our first family picture', 'İlk aile fotoğrafımızı çekelim'), copy('Sakitcə bu anı yaşayaq', 'Simply enjoy this moment', 'Sakince bu anı yaşayalım')] },
  { id: 'smile', chapter: 5, day: 1, icon: 'smile', title: copy('Bir təbəssüm sənə hədiyyə', 'A smile, just for you', 'Bir gülümseme sana hediye'),
    body: copy('Səsini eşidəndə balacanın üzü işıqlanır. Bu balaca gülüş bütün yorğunluğu bir anlıq unutturur.', 'Your little one lights up at your voice. That tiny giggle makes the whole day feel softer.', 'Sesini duyunca bebeğinin yüzü aydınlanıyor. Bu minik kahkaha bütün günü yumuşatıyor.'),
    choices: [copy('Alboma yaz', 'Save it in the album', 'Albüme yaz'), copy('Birlikdə gülək!', 'Let’s giggle together!', 'Birlikte gülelim!')] },
  { id: 'birthday', chapter: 7, day: 1, icon: 'party', title: copy('Bir yaş, min xatirə', 'One year, a thousand memories', 'Bir yaş, bin anı'),
    body: copy('Bir şam, balaca bir tort və evinizi dolduran sevgi. İlk gündən bu günə qədər nə çox şey yaşamısınız!', 'One candle, a tiny cake, and a home full of love. So many lovely moments since the very first day!', 'Bir mum, küçük bir pasta ve evinizi dolduran sevgi. İlk günden bugüne ne çok şey yaşadınız!'),
    choices: [copy('Bağda balaca şənlik', 'A little garden party', 'Bahçede küçük bir kutlama'), copy('Ailəmlə isti bir axşam', 'A cosy family evening', 'Ailemle sıcak bir akşam')] },
];

const storyChapterMap: Record<string, number> = { 'little-secret': 0, 'nursery-dream': 6, welcome: 10, smile: 11, birthday: 13 };
for (const story of STORIES) story.chapter = storyChapterMap[story.id];
