import { copy as c } from './copy';
import type { Activity, Copy } from './types';

const a = (id: Activity['id'], title: Copy, description: Copy,
  icon: string, room: Activity['room'], target: string, mini?: Activity['mini'], extra: Partial<Activity> = {}): Activity =>
  ({ id, title, description, result: description, icon, room, target, seconds: 5, minutes: 25,
    effect: { mood: 12, bond: 8 }, skill: 'care', xp: 25, coins: 18, ...(mini ? { mini } : {}), ...extra });

export const SIM_ACTIVITIES: Activity[] = [
  a('test', c('Hamiləlik testi', 'Pregnancy test', 'Hamilelik testi'), c('Bir səhər, kiçik bir test və iki xəttin dəyişdirdiyi həyat.', 'One morning, a small test, and a life changed by two lines.', 'Bir sabah, küçük bir test ve iki çizginin değiştirdiği hayat.'), 'test', 'bathroom', 'bath', 'pregnancyTest', { pregnancyOnly: true }),
  a('appointment', c('Müayinəni planla', 'Plan an appointment', 'Muayeneyi planla'), c('Ailə təqvimi, sənə uyğun bir saat və yanında bir dəstək.', 'Your calendar, a time that fits, and support beside you.', 'Aile takvimi, uygun bir saat ve yanında destek.'), 'calendar', 'living', 'desk', 'appointment', { pregnancyOnly: true }),
  a('scan', c('Ultrasəs müayinəsi', 'Ultrasound visit', 'Ultrason muayenesi'), c('Probu idarə et, aydın görüntünü tap və balacanın şəklini saxla.', 'Control the probe, find the clear picture, and save the scan.', 'Probu yönet, net görüntüyü bul ve bebeğinin resmini kaydet.'), 'scan', 'clinic', 'scanner', 'scan', { pregnancyOnly: true, location: 'clinic', xp: 35, coins: 24 }),
  a('stretch', c('Yüngül hərəkət', 'Gentle movement', 'Hafif hareket'), c('Nəfəs, rahatlıq və bədəninin yumşaq ritmi.', 'Breath, comfort, and your body’s gentle rhythm.', 'Nefes, rahatlık ve bedeninin yumuşak ritmi.'), 'stretch', 'garden', 'bench', 'breathing', { effect: { mood: 16, energy: 10 }, skill: 'balance' }),
  a('name', c('Bir adın hekayəsi', 'The story of a name', 'Bir ismin hikâyesi'), c('İsim sadəcə bir söz deyil. Balacanın ilk hədiyyəsidir.', 'A name is the first gift in your little one’s story.', 'İsim yalnızca bir kelime değil. Bebeğinin ilk hediyesi.'), 'baby', 'living', 'desk', 'names', { pregnancyOnly: true, skill: 'creativity' }),
  a('kick', c('Balaca hərəkətlər', 'Little movements', 'Minik hareketler'), c('Sakit guşədə balacanın ritmini kəşf et.', 'Discover your little one’s rhythm in a quiet corner.', 'Sakin köşede bebeğinin ritmini keşfet.'), 'heart', 'living', 'sofa', 'breathing', { pregnancyOnly: true, effect: { mood: 16, bond: 14 } }),
  a('assemble', c('Beşiyi birləşdir', 'Assemble the crib', 'Beşiği birleştir'), c('Hissələri döndər, doğru yuvaya sürüşdür və balaca dünyanı qur.', 'Rotate the pieces, slide them into place, and build a little world.', 'Parçaları döndür, doğru yuvaya sürükle ve küçük dünyayı kur.'), 'hammer', 'nursery', 'crib', 'nesting', { seconds: 7, minutes: 55, effect: { mood: 16, energy: -12 }, skill: 'creativity', xp: 35, coins: 26 }),
  a('birthplan', c('Mənim doğuş planım', 'My birth plan', 'Doğum planım'), c('Hekayənin doğuş yolunu, dəstəyini və rahatlıq seçimlərini hazırla.', 'Prepare the birth path, support, and comfort choices for your story.', 'Hikâyenin doğum yolunu, desteğini ve rahatlık tercihlerini hazırla.'), 'clipboard', 'living', 'desk', 'birthPlan', { pregnancyOnly: true, xp: 28, coins: 22 }),
  a('contractions', c('Dalğaların ritmi', 'The rhythm of the waves', 'Dalgaların ritmi'), c('Oyundakı dalğaların başlanğıcını və sonunu qeyd et.', 'Record the game’s wave starts and ends.', 'Oyundaki dalgaların başlangıcını ve sonunu kaydet.'), 'waves', 'living', 'sofa', 'contractions', { pregnancyOnly: true, skill: 'balance', xp: 30, coins: 22 }),
  a('call', c('Dəstəyimi çağır', 'Call my support', 'Desteğimi çağır'), c('Həyat yoldaşına və klinikadakı komandaya xəbər ver.', 'Let your partner and the clinic team know.', 'Eşine ve klinikteki ekibe haber ver.'), 'phone', 'living', 'partner', undefined, { pregnancyOnly: true, effect: { mood: 18, energy: 12 } }),
  a('birth', c('Balacamla görüş', 'Meet my baby', 'Bebeğimle buluş'), c('Doğuş komandanla səhnələri keç. Nəfəsdən ilk qucağa.', 'Move through the birth scenes. From breathing to the first embrace.', 'Doğum ekibinle sahneleri geç. Nefesten ilk kucağa.'), 'heartpulse', 'clinic', 'birthbed', 'birth', { pregnancyOnly: true, location: 'clinic', seconds: 6, minutes: 90, effect: { mood: 30, energy: -10, bond: 28 }, xp: 65, coins: 50 }),
  a('skin', c('İlk yaxınlıq', 'The first closeness', 'İlk yakınlık'), c('İsti qucaq, sənin səsin və yeni ailə bağınız.', 'Warm arms, your voice, and a new family bond.', 'Sıcak bir kucak, sesin ve yeni aile bağınız.'), 'heart', 'clinic', 'birthbed', undefined, { babyOnly: true, seconds: 8, effect: { comfort: 22, bond: 24, mood: 15 } }),
  a('carseat', c('İlk yolculuq', 'The first ride', 'İlk yolculuk'), c('Oyundakı oturacaq hissələrini və tokalarını birləşdir.', 'Connect the game’s seat parts and buckles.', 'Oyundaki koltuk parçalarını ve tokalarını birleştir.'), 'car', 'clinic', 'reception', 'carseat', { babyOnly: true, location: 'clinic', effect: { mood: 14, comfort: 12 } }),
  a('sterilise', c('Qayğı guşəsini hazırla', 'Prepare the care corner', 'Bakım köşesini hazırla'), c('Təmiz əşyaları oyun trayına yerləşdir və qayğını planla.', 'Place fresh items on the game’s tray and plan the care.', 'Temiz eşyaları oyun tepsisine yerleştir ve bakımı planla.'), 'sparkles', 'kitchen', 'counter', 'babyCare', { babyOnly: true, effect: { comfort: 14, mood: 8 } }),
  a('soothe', c('Qucağın sakit ritmi', 'The gentle rhythm of a cuddle', 'Kucağın sakin ritmi'), c('Sakit hərəkətlə balacanı qucağında rahatlat.', 'Settle your baby with a gentle rocking rhythm.', 'Sakin hareketlerle bebeğini kucağında rahatlat.'), 'hands', 'nursery', 'chair', 'breathing', { babyOnly: true, seconds: 7, effect: { comfort: 24, babySleep: 14, bond: 16 } }),
  a('routine', c('Ailəmizin ritmi', 'Our family rhythm', 'Ailemizin ritmi'), c('Qida, oyun, yuxu və ananın fasiləsini günlük plana yerləşdir.', 'Plan feeds, play, sleep, and a break for mum.', 'Beslenme, oyun, uyku ve annenin molasını günlük plana yerleştir.'), 'clock', 'living', 'desk', 'routine', { babyOnly: true, effect: { mood: 16, energy: 12, babySleep: 10 }, skill: 'balance' }),
  a('travel', c('Yola düş', 'Travel', 'Yola çık'), c('Ailənizin xəritəsində yeni səhnəyə keç.', 'Move to a new scene on your family map.', 'Aile haritanda yeni sahneye geç.'), 'map', 'living', 'desk', undefined, { seconds: 1, effect: {}, coins: 0 }),
];
