-- ============================================================
-- Qazax9 — Community dinamik açarları (BÜTÜN dillər üçün kök düzəliş)
-- 1) community_header_{bump,flow,trying,mommy} → en/ru/tr/kk
--    (yalnız en var idi — ru/tr istifadəçilər də AZ görürdü!)
-- 2) Hazırkı 25 qrupun group_name_*/group_desc_* açarları → en/ru/tr/kk
--    (heç bir dildə yox idi — köhnə açarlar köhnəlmiş qrup adlarına aid idi)
-- 3) Köhnə 4 qrup açarı → ru/tr/kk. İdempotent (DO NOTHING).
-- ============================================================

INSERT INTO public.translations (key, lang, value, namespace) VALUES
  ('community_header_bump', 'ru', 'Общайтесь с другими беременными', 'common'),
  ('community_header_bump', 'tr', 'Diğer hamile annelerle bağlantı kurun', 'common'),
  ('community_header_bump', 'kk', 'Басқа жүкті аналармен байланыста болыңыз', 'common'),
  ('community_header_mommy', 'ru', 'Общайтесь с другими мамами', 'common'),
  ('community_header_mommy', 'tr', 'Diğer annelerle bağlantı kurun', 'common'),
  ('community_header_mommy', 'kk', 'Басқа аналармен байланыста болыңыз', 'common'),
  ('community_header_mommy', 'en', 'Connect with other moms', 'common'),
  ('group_name_1._ay_hamiləlik', 'ru', '1-й месяц беременности', 'common'),
  ('group_name_1._ay_hamiləlik', 'tr', 'Hamileliğin 1. Ayı', 'common'),
  ('group_name_1._ay_hamiləlik', 'kk', 'Жүктіліктің 1-айы', 'common'),
  ('group_name_1._ay_hamiləlik', 'en', '1st Month of Pregnancy', 'common'),
  ('group_desc_1._ay_hamiləlik', 'ru', 'Беременные на первом месяце', 'common'),
  ('group_desc_1._ay_hamiləlik', 'tr', 'Hamileliğinin ilk ayında olanlar', 'common'),
  ('group_desc_1._ay_hamiləlik', 'kk', 'Жүктіліктің бірінші айындағы әйелдер', 'common'),
  ('group_desc_1._ay_hamiləlik', 'en', 'Moms in their first month of pregnancy', 'common'),
  ('group_name_2._ay_hamiləlik', 'ru', '2-й месяц беременности', 'common'),
  ('group_name_2._ay_hamiləlik', 'tr', 'Hamileliğin 2. Ayı', 'common'),
  ('group_name_2._ay_hamiləlik', 'kk', 'Жүктіліктің 2-айы', 'common'),
  ('group_name_2._ay_hamiləlik', 'en', '2nd Month of Pregnancy', 'common'),
  ('group_desc_2._ay_hamiləlik', 'ru', 'Беременные на втором месяце', 'common'),
  ('group_desc_2._ay_hamiləlik', 'tr', 'Hamileliğinin ikinci ayında olanlar', 'common'),
  ('group_desc_2._ay_hamiləlik', 'kk', 'Жүктіліктің екінші айындағы әйелдер', 'common'),
  ('group_desc_2._ay_hamiləlik', 'en', 'Moms in their second month of pregnancy', 'common'),
  ('group_name_2026_aprel_anaları', 'ru', 'Мамы апреля 2026', 'common'),
  ('group_name_2026_aprel_anaları', 'tr', '2026 Nisan Anneleri', 'common'),
  ('group_name_2026_aprel_anaları', 'kk', '2026 Сәуір аналары', 'common'),
  ('group_name_2026_aprel_anaları', 'en', 'April 2026 Moms', 'common'),
  ('group_desc_2026_aprel_anaları', 'ru', 'Мамы, родившие в ноябре 2025 года', 'common'),
  ('group_desc_2026_aprel_anaları', 'tr', 'Kasım 2025''te doğum yapan anneler', 'common'),
  ('group_desc_2026_aprel_anaları', 'kk', '2025 жылдың қарашасында босанған аналар', 'common'),
  ('group_desc_2026_aprel_anaları', 'en', 'Moms due in November 2025', 'common'),
  ('group_name_2026_fevral_anaları', 'ru', 'Мамы февраля 2026', 'common'),
  ('group_name_2026_fevral_anaları', 'tr', '2026 Şubat Anneleri', 'common'),
  ('group_name_2026_fevral_anaları', 'kk', '2026 Ақпан аналары', 'common'),
  ('group_name_2026_fevral_anaları', 'en', 'February 2026 Moms', 'common'),
  ('group_desc_2026_fevral_anaları', 'ru', 'Мамы, родившие в феврале 2026 года', 'common'),
  ('group_desc_2026_fevral_anaları', 'tr', 'Şubat 2026''da doğum yapan anneler', 'common'),
  ('group_desc_2026_fevral_anaları', 'kk', '2026 жылдың ақпанында босанған аналар', 'common'),
  ('group_desc_2026_fevral_anaları', 'en', 'Moms due in February 2026', 'common'),
  ('group_name_2026_i̇yun_anaları', 'ru', 'Мамы июня 2026', 'common'),
  ('group_name_2026_i̇yun_anaları', 'tr', '2026 Haziran Anneleri', 'common'),
  ('group_name_2026_i̇yun_anaları', 'kk', '2026 Маусым аналары', 'common'),
  ('group_name_2026_i̇yun_anaları', 'en', 'June 2026 Moms', 'common'),
  ('group_desc_2026_i̇yun_anaları', 'ru', 'Мамы, родившие в октябре 2025 года', 'common'),
  ('group_desc_2026_i̇yun_anaları', 'tr', 'Ekim 2025''te doğum yapan anneler', 'common'),
  ('group_desc_2026_i̇yun_anaları', 'kk', '2025 жылдың қазанында босанған аналар', 'common'),
  ('group_desc_2026_i̇yun_anaları', 'en', 'Moms due in October 2025', 'common'),
  ('group_name_2026_mart_anaları', 'ru', 'Мамы марта 2026', 'common'),
  ('group_name_2026_mart_anaları', 'tr', '2026 Mart Anneleri', 'common'),
  ('group_name_2026_mart_anaları', 'kk', '2026 Наурыз аналары', 'common'),
  ('group_name_2026_mart_anaları', 'en', 'March 2026 Moms', 'common'),
  ('group_desc_2026_mart_anaları', 'ru', 'Мамы, родившие в марте 2026 года', 'common'),
  ('group_desc_2026_mart_anaları', 'tr', 'Mart 2026''da doğum yapan anneler', 'common'),
  ('group_desc_2026_mart_anaları', 'kk', '2026 жылдың наурызында босанған аналар', 'common'),
  ('group_desc_2026_mart_anaları', 'en', 'Moms due in March 2026', 'common'),
  ('group_name_2026_may_anaları', 'ru', 'Мамы мая 2026', 'common'),
  ('group_name_2026_may_anaları', 'tr', '2026 Mayıs Anneleri', 'common'),
  ('group_name_2026_may_anaları', 'kk', '2026 Мамыр аналары', 'common'),
  ('group_name_2026_may_anaları', 'en', 'May 2026 Moms', 'common'),
  ('group_desc_2026_may_anaları', 'ru', 'Мамы, родившие в декабре 2025 года', 'common'),
  ('group_desc_2026_may_anaları', 'tr', 'Aralık 2025''te doğum yapan anneler', 'common'),
  ('group_desc_2026_may_anaları', 'kk', '2025 жылдың желтоқсанында босанған аналар', 'common'),
  ('group_desc_2026_may_anaları', 'en', 'Moms due in December 2025', 'common'),
  ('group_name_2026_yanvar_anaları', 'ru', 'Мамы января 2026', 'common'),
  ('group_name_2026_yanvar_anaları', 'tr', '2026 Ocak Anneleri', 'common'),
  ('group_name_2026_yanvar_anaları', 'kk', '2026 Қаңтар аналары', 'common'),
  ('group_name_2026_yanvar_anaları', 'en', 'January 2026 Moms', 'common'),
  ('group_desc_2026_yanvar_anaları', 'ru', 'Мамы, родившие в январе 2026 года', 'common'),
  ('group_desc_2026_yanvar_anaları', 'tr', 'Ocak 2026''da doğum yapan anneler', 'common'),
  ('group_desc_2026_yanvar_anaları', 'kk', '2026 жылдың қаңтарында босанған аналар', 'common'),
  ('group_desc_2026_yanvar_anaları', 'en', 'Moms due in January 2026', 'common'),
  ('group_name_3._ay_hamiləlik', 'ru', '3-й месяц беременности', 'common'),
  ('group_name_3._ay_hamiləlik', 'tr', 'Hamileliğin 3. Ayı', 'common'),
  ('group_name_3._ay_hamiləlik', 'kk', 'Жүктіліктің 3-айы', 'common'),
  ('group_name_3._ay_hamiləlik', 'en', '3rd Month of Pregnancy', 'common'),
  ('group_desc_3._ay_hamiləlik', 'ru', 'Беременные на третьем месяце', 'common'),
  ('group_desc_3._ay_hamiləlik', 'tr', 'Hamileliğinin üçüncü ayında olanlar', 'common'),
  ('group_desc_3._ay_hamiləlik', 'kk', 'Жүктіліктің үшінші айындағы әйелдер', 'common'),
  ('group_desc_3._ay_hamiləlik', 'en', 'Moms in their third month of pregnancy', 'common'),
  ('group_name_4._ay_hamiləlik', 'ru', '4-й месяц беременности', 'common'),
  ('group_name_4._ay_hamiləlik', 'tr', 'Hamileliğin 4. Ayı', 'common'),
  ('group_name_4._ay_hamiləlik', 'kk', 'Жүктіліктің 4-айы', 'common'),
  ('group_name_4._ay_hamiləlik', 'en', '4th Month of Pregnancy', 'common'),
  ('group_desc_4._ay_hamiləlik', 'ru', 'Беременные на четвёртом месяце', 'common'),
  ('group_desc_4._ay_hamiləlik', 'tr', 'Hamileliğinin dördüncü ayında olanlar', 'common'),
  ('group_desc_4._ay_hamiləlik', 'kk', 'Жүктіліктің төртінші айындағы әйелдер', 'common'),
  ('group_desc_4._ay_hamiləlik', 'en', 'Moms in their fourth month of pregnancy', 'common'),
  ('group_name_5._ay_hamiləlik', 'ru', '5-й месяц беременности', 'common'),
  ('group_name_5._ay_hamiləlik', 'tr', 'Hamileliğin 5. Ayı', 'common'),
  ('group_name_5._ay_hamiləlik', 'kk', 'Жүктіліктің 5-айы', 'common'),
  ('group_name_5._ay_hamiləlik', 'en', '5th Month of Pregnancy', 'common'),
  ('group_desc_5._ay_hamiləlik', 'ru', 'Беременные на пятом месяце', 'common'),
  ('group_desc_5._ay_hamiləlik', 'tr', 'Hamileliğinin beşinci ayında olanlar', 'common'),
  ('group_desc_5._ay_hamiləlik', 'kk', 'Жүктіліктің бесінші айындағы әйелдер', 'common'),
  ('group_desc_5._ay_hamiləlik', 'en', 'Moms in their fifth month of pregnancy', 'common'),
  ('group_name_6._ay_hamiləlik', 'ru', '6-й месяц беременности', 'common'),
  ('group_name_6._ay_hamiləlik', 'tr', 'Hamileliğin 6. Ayı', 'common'),
  ('group_name_6._ay_hamiləlik', 'kk', 'Жүктіліктің 6-айы', 'common'),
  ('group_name_6._ay_hamiləlik', 'en', '6th Month of Pregnancy', 'common'),
  ('group_desc_6._ay_hamiləlik', 'ru', 'Беременные на шестом месяце', 'common'),
  ('group_desc_6._ay_hamiləlik', 'tr', 'Hamileliğinin altıncı ayında olanlar', 'common'),
  ('group_desc_6._ay_hamiləlik', 'kk', 'Жүктіліктің алтыншы айындағы әйелдер', 'common'),
  ('group_desc_6._ay_hamiləlik', 'en', 'Moms in their sixth month of pregnancy', 'common'),
  ('group_name_7._ay_hamiləlik', 'ru', '7-й месяц беременности', 'common'),
  ('group_name_7._ay_hamiləlik', 'tr', 'Hamileliğin 7. Ayı', 'common'),
  ('group_name_7._ay_hamiləlik', 'kk', 'Жүктіліктің 7-айы', 'common'),
  ('group_name_7._ay_hamiləlik', 'en', '7th Month of Pregnancy', 'common'),
  ('group_desc_7._ay_hamiləlik', 'ru', 'Беременные на седьмом месяце', 'common'),
  ('group_desc_7._ay_hamiləlik', 'tr', 'Hamileliğinin yedinci ayında olanlar', 'common'),
  ('group_desc_7._ay_hamiləlik', 'kk', 'Жүктіліктің жетінші айындағы әйелдер', 'common'),
  ('group_desc_7._ay_hamiləlik', 'en', 'Moms in their seventh month of pregnancy', 'common'),
  ('group_name_8._ay_hamiləlik', 'ru', '8-й месяц беременности', 'common'),
  ('group_name_8._ay_hamiləlik', 'tr', 'Hamileliğin 8. Ayı', 'common'),
  ('group_name_8._ay_hamiləlik', 'kk', 'Жүктіліктің 8-айы', 'common'),
  ('group_name_8._ay_hamiləlik', 'en', '8th Month of Pregnancy', 'common'),
  ('group_desc_8._ay_hamiləlik', 'ru', 'Беременные на восьмом месяце', 'common'),
  ('group_desc_8._ay_hamiləlik', 'tr', 'Hamileliğinin sekizinci ayında olanlar', 'common'),
  ('group_desc_8._ay_hamiləlik', 'kk', 'Жүктіліктің сегізінші айындағы әйелдер', 'common'),
  ('group_desc_8._ay_hamiləlik', 'en', 'Moms in their eighth month of pregnancy', 'common'),
  ('group_name_9._ay_hamiləlik', 'ru', '9-й месяц беременности', 'common'),
  ('group_name_9._ay_hamiləlik', 'tr', 'Hamileliğin 9. Ayı', 'common'),
  ('group_name_9._ay_hamiləlik', 'kk', 'Жүктіліктің 9-айы', 'common'),
  ('group_name_9._ay_hamiləlik', 'en', '9th Month of Pregnancy', 'common'),
  ('group_desc_9._ay_hamiləlik', 'ru', 'Беременные на девятом месяце', 'common'),
  ('group_desc_9._ay_hamiləlik', 'tr', 'Hamileliğinin dokuzuncu ayında olanlar', 'common'),
  ('group_desc_9._ay_hamiləlik', 'kk', 'Жүктіліктің тоғызыншы айындағы әйелдер', 'common'),
  ('group_desc_9._ay_hamiləlik', 'en', 'Moms in their ninth month of pregnancy', 'common'),
  ('group_name_dördüz_anaları', 'ru', 'Мамы четверняшек', 'common'),
  ('group_name_dördüz_anaları', 'tr', 'Dördüz Anneleri', 'common'),
  ('group_name_dördüz_anaları', 'kk', 'Төртемнің аналары', 'common'),
  ('group_name_dördüz_anaları', 'en', 'Moms of Quadruplets', 'common'),
  ('group_desc_dördüz_anaları', 'ru', 'Группа для мам четверняшек', 'common'),
  ('group_desc_dördüz_anaları', 'tr', 'Dördüz anneleri için grup', 'common'),
  ('group_desc_dördüz_anaları', 'kk', 'Төртемі бар аналарға арналған топ', 'common'),
  ('group_desc_dördüz_anaları', 'en', 'A group for moms of quadruplets', 'common'),
  ('group_name_əkiz_anaları', 'ru', 'Мамы двойняшек', 'common'),
  ('group_name_əkiz_anaları', 'tr', 'İkiz Anneleri', 'common'),
  ('group_name_əkiz_anaları', 'kk', 'Егіздердің аналары', 'common'),
  ('group_name_əkiz_anaları', 'en', 'Moms of Twins', 'common'),
  ('group_desc_əkiz_anaları', 'ru', 'Группа для мам двойняшек', 'common'),
  ('group_desc_əkiz_anaları', 'tr', 'İkiz anneleri için grup', 'common'),
  ('group_desc_əkiz_anaları', 'kk', 'Егіздері бар аналарға арналған топ', 'common'),
  ('group_desc_əkiz_anaları', 'en', 'A group for moms of twins', 'common'),
  ('group_name_hamilə_qadınlar', 'ru', 'Беременные женщины', 'common'),
  ('group_name_hamilə_qadınlar', 'tr', 'Hamile Kadınlar', 'common'),
  ('group_name_hamilə_qadınlar', 'kk', 'Жүкті әйелдер', 'common'),
  ('group_name_hamilə_qadınlar', 'en', 'Pregnant Women', 'common'),
  ('group_desc_hamilə_qadınlar', 'ru', 'Общая группа для всех беременных', 'common'),
  ('group_desc_hamilə_qadınlar', 'tr', 'Tüm hamile kadınlar için genel grup', 'common'),
  ('group_desc_hamilə_qadınlar', 'kk', 'Барлық жүкті әйелдерге арналған ортақ топ', 'common'),
  ('group_desc_hamilə_qadınlar', 'en', 'A general group for all pregnant women', 'common'),
  ('group_name_oğlan_uşağı_anaları', 'ru', 'Мамы мальчиков', 'common'),
  ('group_name_oğlan_uşağı_anaları', 'tr', 'Erkek Çocuk Anneleri', 'common'),
  ('group_name_oğlan_uşağı_anaları', 'kk', 'Ұлдардың аналары', 'common'),
  ('group_name_oğlan_uşağı_anaları', 'en', 'Moms of Boys', 'common'),
  ('group_desc_oğlan_uşağı_anaları', 'ru', 'Группа для мам мальчиков', 'common'),
  ('group_desc_oğlan_uşağı_anaları', 'tr', 'Erkek çocuk anneleri için grup', 'common'),
  ('group_desc_oğlan_uşağı_anaları', 'kk', 'Ұлдары бар аналарға арналған топ', 'common'),
  ('group_desc_oğlan_uşağı_anaları', 'en', 'A group for moms of boys', 'common'),
  ('group_name_psixoloji_dəstək', 'ru', 'Психологическая поддержка', 'common'),
  ('group_name_psixoloji_dəstək', 'tr', 'Psikolojik Destek', 'common'),
  ('group_name_psixoloji_dəstək', 'kk', 'Психологиялық қолдау', 'common'),
  ('group_name_psixoloji_dəstək', 'en', 'Emotional Support', 'common'),
  ('group_desc_psixoloji_dəstək', 'ru', 'Эмоциональная поддержка и общение', 'common'),
  ('group_desc_psixoloji_dəstək', 'tr', 'Duygusal destek ve sohbet', 'common'),
  ('group_desc_psixoloji_dəstək', 'kk', 'Эмоциялық қолдау және әңгімелесу', 'common'),
  ('group_desc_psixoloji_dəstək', 'en', 'Emotional support and conversation', 'common'),
  ('group_name_qadınlar_klubu', 'ru', 'Женский клуб', 'common'),
  ('group_name_qadınlar_klubu', 'tr', 'Kadınlar Kulübü', 'common'),
  ('group_name_qadınlar_klubu', 'kk', 'Әйелдер клубы', 'common'),
  ('group_name_qadınlar_klubu', 'en', 'Women''s Club', 'common'),
  ('group_desc_qadınlar_klubu', 'ru', 'Общая группа для общения женщин', 'common'),
  ('group_desc_qadınlar_klubu', 'tr', 'Tüm kadınlar için genel sohbet grubu', 'common'),
  ('group_desc_qadınlar_klubu', 'kk', 'Барлық әйелдерге арналған ортақ әңгімелесу тобы', 'common'),
  ('group_desc_qadınlar_klubu', 'en', 'A general chat group for all women', 'common'),
  ('group_name_qız_uşağı_anaları', 'ru', 'Мамы девочек', 'common'),
  ('group_name_qız_uşağı_anaları', 'tr', 'Kız Çocuk Anneleri', 'common'),
  ('group_name_qız_uşağı_anaları', 'kk', 'Қыздардың аналары', 'common'),
  ('group_name_qız_uşağı_anaları', 'en', 'Moms of Girls', 'common'),
  ('group_desc_qız_uşağı_anaları', 'ru', 'Группа для мам девочек', 'common'),
  ('group_desc_qız_uşağı_anaları', 'tr', 'Kız çocuk anneleri için grup', 'common'),
  ('group_desc_qız_uşağı_anaları', 'kk', 'Қыздары бар аналарға арналған топ', 'common'),
  ('group_desc_qız_uşağı_anaları', 'en', 'A group for moms of girls', 'common'),
  ('group_name_reseptlər_və_qidalanma', 'ru', 'Рецепты и питание', 'common'),
  ('group_name_reseptlər_və_qidalanma', 'tr', 'Tarifler ve Beslenme', 'common'),
  ('group_name_reseptlər_və_qidalanma', 'kk', 'Рецепттер және тамақтану', 'common'),
  ('group_name_reseptlər_və_qidalanma', 'en', 'Recipes & Nutrition', 'common'),
  ('group_desc_reseptlər_və_qidalanma', 'ru', 'Здоровые блюда и питание', 'common'),
  ('group_desc_reseptlər_və_qidalanma', 'tr', 'Sağlıklı yemekler ve beslenme', 'common'),
  ('group_desc_reseptlər_və_qidalanma', 'kk', 'Пайдалы тағамдар мен дұрыс тамақтану', 'common'),
  ('group_desc_reseptlər_və_qidalanma', 'en', 'Healthy meals and nutrition', 'common'),
  ('group_name_sağlamlıq_tövsiyələri', 'ru', 'Советы по здоровью', 'common'),
  ('group_name_sağlamlıq_tövsiyələri', 'tr', 'Sağlık Önerileri', 'common'),
  ('group_name_sağlamlıq_tövsiyələri', 'kk', 'Денсаулық кеңестері', 'common'),
  ('group_name_sağlamlıq_tövsiyələri', 'en', 'Health Tips', 'common'),
  ('group_desc_sağlamlıq_tövsiyələri', 'ru', 'Советы о здоровье и уходе', 'common'),
  ('group_desc_sağlamlıq_tövsiyələri', 'tr', 'Sağlık ve bakım önerileri', 'common'),
  ('group_desc_sağlamlıq_tövsiyələri', 'kk', 'Денсаулық пен күтім туралы кеңестер', 'common'),
  ('group_desc_sağlamlıq_tövsiyələri', 'en', 'Health and care advice', 'common'),
  ('group_name_üçüz_anaları', 'ru', 'Мамы тройняшек', 'common'),
  ('group_name_üçüz_anaları', 'tr', 'Üçüz Anneleri', 'common'),
  ('group_name_üçüz_anaları', 'kk', 'Үшемдердің аналары', 'common'),
  ('group_name_üçüz_anaları', 'en', 'Moms of Triplets', 'common'),
  ('group_desc_üçüz_anaları', 'ru', 'Группа для мам тройняшек', 'common'),
  ('group_desc_üçüz_anaları', 'tr', 'Üçüz anneleri için grup', 'common'),
  ('group_desc_üçüz_anaları', 'kk', 'Үшемдері бар аналарға арналған топ', 'common'),
  ('group_desc_üçüz_anaları', 'en', 'A group for moms of triplets', 'common'),
  ('community_header_flow', 'ru', 'Общайтесь с теми, кто планирует беременность', 'common'),
  ('community_header_flow', 'tr', 'Hamile kalmaya çalışanlarla bağlantı kur', 'common'),
  ('community_header_flow', 'kk', 'Бала сүюді жоспарлап жүргендермен байланысыңыз', 'common'),
  ('community_header_trying', 'ru', 'Общайтесь с теми, кто планирует беременность', 'common'),
  ('community_header_trying', 'tr', 'Hamile kalmaya çalışanlarla bağlantı kur', 'common'),
  ('community_header_trying', 'kk', 'Бала сүюді жоспарлап жүргендермен байланысыңыз', 'common'),
  ('group_name_hamiləlik', 'ru', 'Беременность', 'common'),
  ('group_name_hamiləlik', 'tr', 'Hamilelik', 'common'),
  ('group_name_hamiləlik', 'kk', 'Жүктілік', 'common'),
  ('group_desc_hamiləlik', 'ru', 'Общайтесь с другими будущими мамами', 'common'),
  ('group_desc_hamiləlik', 'tr', 'Diğer anne adaylarıyla bağlantı kur', 'common'),
  ('group_desc_hamiləlik', 'kk', 'Басқа болашақ аналармен байланысыңыз', 'common'),
  ('group_name_məsləhət', 'ru', 'Советы', 'common'),
  ('group_name_məsləhət', 'tr', 'Tavsiyeler', 'common'),
  ('group_name_məsləhət', 'kk', 'Кеңес', 'common'),
  ('group_desc_məsləhət', 'ru', 'Задавайте вопросы и получайте советы от мам', 'common'),
  ('group_desc_məsləhət', 'tr', 'Sorularını sor, annelerden tavsiye al', 'common'),
  ('group_desc_məsləhət', 'kk', 'Сұрақ қойып, аналардан кеңес алыңыз', 'common'),
  ('group_name_təcrübəli_analar', 'ru', 'Опытные мамы', 'common'),
  ('group_name_təcrübəli_analar', 'tr', 'Deneyimli Anneler', 'common'),
  ('group_name_təcrübəli_analar', 'kk', 'Тәжірибелі аналар', 'common'),
  ('group_desc_təcrübəli_analar', 'ru', 'Делитесь советами и опытом', 'common'),
  ('group_desc_təcrübəli_analar', 'tr', 'Tavsiye ve deneyimlerini paylaş', 'common'),
  ('group_desc_təcrübəli_analar', 'kk', 'Кеңес пен тәжірибе бөлісіңіз', 'common'),
  ('group_name_yeni_analar', 'ru', 'Молодые мамы', 'common'),
  ('group_name_yeni_analar', 'tr', 'Yeni Anneler', 'common'),
  ('group_name_yeni_analar', 'kk', 'Жаңа босанған аналар', 'common'),
  ('group_desc_yeni_analar', 'ru', 'Делитесь опытом ухода за новорождёнными', 'common'),
  ('group_desc_yeni_analar', 'tr', 'Yenidoğan bakımı deneyimlerini paylaş', 'common'),
  ('group_desc_yeni_analar', 'kk', 'Нәресте күтімі туралы тәжірибе бөлісіңіз', 'common')
ON CONFLICT (key, lang) DO NOTHING;
