-- ============================================================
-- Qazax7 — 83 canlı açarın EN dəyəri (kk auditi zamanı aşkarlanan köhnə EN boşluğu)
-- billingscreen_* və s. — EN istifadəçilər inline AZ default görürdü.
-- en.json-a da əlavə olunub (yeni buildlər); bu SQL köhnə buildlər üçündür. İdempotent.
-- ============================================================

INSERT INTO public.translations (key, lang, value, namespace) VALUES
  ('billingscreen_annual_premium', 'en', 'Annual Premium', 'common'),
  ('billingscreen_auto_renewal', 'en', 'Auto Renewal', 'common'),
  ('billingscreen_cancel_appstore', 'en', 'You will be redirected to the App Store / Google Play subscription management page to cancel your subscription.', 'common'),
  ('billingscreen_cancel_confirm', 'en', 'Are you sure you want to cancel your subscription? You will continue to have Premium access until the end of the current period.', 'common'),
  ('billingscreen_cancel_error', 'en', 'Failed to cancel subscription.', 'common'),
  ('billingscreen_cancel_success', 'en', 'Subscription Cancelled', 'common'),
  ('billingscreen_cancel_success_desc', 'en', 'You can use Premium until the end of the current period.', 'common'),
  ('billingscreen_error', 'en', 'Error', 'common'),
  ('billingscreen_first_purchase', 'en', 'First Purchase', 'common'),
  ('billingscreen_monthly_premium', 'en', 'Monthly Premium', 'common'),
  ('billingscreen_need_help', 'en', 'Need help?', 'common'),
  ('billingscreen_next_renewal', 'en', 'Next Renewal', 'common'),
  ('billingscreen_open_in_store', 'en', 'View in App Store', 'common'),
  ('billingscreen_premium_features', 'en', 'Premium Features', 'common'),
  ('billingscreen_refresh', 'en', 'Refresh', 'common'),
  ('billingscreen_restore_error', 'en', 'Failed to restore subscription.', 'common'),
  ('billingscreen_restore_success', 'en', 'Subscription Restored', 'common'),
  ('billingscreen_restore_success_desc', 'en', 'Your Premium subscription is active again.', 'common'),
  ('billingscreen_scheduled', 'en', 'Scheduled', 'common'),
  ('billingscreen_status_free', 'en', 'Current Status: Free', 'common'),
  ('billingscreen_title', 'en', 'My Subscription', 'common'),
  ('billingscreen_upgrade', 'en', 'Upgrade', 'common'),
  ('billingscreen_upgrade_btn', 'en', 'Upgrade to Premium', 'common'),
  ('common_initial_i', 'en', 'I', 'common'),
  ('common_parametrler', 'en', 'Settings', 'common'),
  ('dashboard_diaper_change', 'en', 'Diaper changes:', 'common'),
  ('dashboard_h', 'en', 'h', 'common'),
  ('dashboard_kick', 'en', 'kick', 'common'),
  ('dashboard_m', 'en', 'min', 'common'),
  ('dashboard_sec', 'en', 'sec', 'common'),
  ('dashboard_today', 'en', 'Today', 'common'),
  ('dashboard_week_baby', 'en', 'week-old baby', 'common'),
  ('funnel_week_stats', 'en', '78% of pregnant women experience certain discomforts during this week.', 'common'),
  ('aichat_welcome_bump_1', 'en', 'Hello', 'common'),
  ('aichat_welcome_bump_2', 'en', 'I''m Anacan.AI.', 'common'),
  ('aichat_welcome_bump_3', 'en', 'You are currently {0} weeks pregnant, and your baby is approximately the size of a {1}. ', 'common'),
  ('aichat_welcome_bump_4', 'en', 'You can ask me any questions about pregnancy.', 'common'),
  ('aichat_welcome_default_1', 'en', 'Hello', 'common'),
  ('aichat_welcome_default_2', 'en', 'I''m Anacan.AI. How can I help you?', 'common'),
  ('aichat_welcome_flow_1', 'en', 'Hello', 'common'),
  ('aichat_welcome_flow_2', 'en', 'I''m Anacan.AI. I''m ready to provide professional answers to your questions about menstrual cycles, symptoms, and general health.', 'common'),
  ('aichat_welcome_mommy_1', 'en', 'Hello', 'common'),
  ('aichat_welcome_mommy_2', 'en', 'I''m Anacan.AI. I''m here to support you with questions about baby care, breastfeeding, sleep routines, and postpartum recovery.', 'common'),
  ('appearancescreen_fon', 'en', 'Background', 'common'),
  ('appearancescreen_seth', 'en', 'Surface', 'common'),
  ('appearancescreen_vurgu', 'en', 'Accent', 'common'),
  ('calendarscreen_evvelki_ay', 'en', 'Previous month', 'common'),
  ('calendarscreen_novbeti_ay', 'en', 'Next month', 'common'),
  ('community_file_upload_failed', 'en', 'File upload failed:', 'common'),
  ('community_is_typing', 'en', 'is typing...', 'common'),
  ('community_people_are_typing', 'en', 'people are typing...', 'common'),
  ('directmessagescreen_send', 'en', 'Send', 'common'),
  ('directmessagescreen_stop', 'en', 'Stop', 'common'),
  ('flow_period_delay_1', 'en', 'Your period is', 'common'),
  ('flow_period_delay_2', 'en', 'days late. Consider taking a pregnancy test or asking Dr.Anacan.', 'common'),
  ('flow_period_delay_prompt_1', 'en', 'My period is', 'common'),
  ('flow_period_delay_prompt_2', 'en', 'days late. What should I do?', 'common'),
  ('profile_child_added', 'en', 'added', 'common'),
  ('profile_download_app', 'en', 'Download the app:', 'common'),
  ('profile_share_partner_text', 'en', 'Join the Anacan app and support me on our pregnancy journey! My partner code:', 'common'),
  ('cake_confirm_order', 'en', 'Confirm Order', 'common'),
  ('cake_pay_and_order', 'en', 'Pay and Order', 'common'),
  ('cake_payment', 'en', 'payment', 'common'),
  ('cake_send_order', 'en', 'Submit Order', 'common'),
  ('cycletrendchart_tsikl_count', 'en', '{count} cycles', 'common'),
  ('dateutils_stress', 'en', 'Stress', 'common'),
  ('doctorshospitals_maraq_saheleri', 'en', 'Areas of Interest', 'common'),
  ('doctorshospitals_xidmetler', 'en', 'Services', 'common'),
  ('horoscopecompatibility_neticeniz_d14591', 'en', 'Your Result', 'common'),
  ('medical_disclaimer_text', 'en', 'This information is for educational purposes only and is NOT a substitute for medical advice, diagnosis, or treatment. Always consult your doctor or a qualified healthcare professional before making any medical decisions. In an emergency, call 103.', 'common'),
  ('rc_bundle_version', 'en', 'Bundle version:', 'common'),
  ('toolshub_featured_title', 'en', 'Featured', 'common'),
  ('toolshub_minigames_title', 'en', 'Mini Games', 'common'),
  ('untranslated_analiz_edilir_hf0m1t', 'en', 'Analyzing...', 'common'),
  ('untranslated_qeyd_edilir_df7cba', 'en', 'Saving...', 'common'),
  ('untranslated_silindi_u8c6ca', 'en', 'Deleted!', 'common'),
  ('untranslated_silinir_u86cva', 'en', 'Deleting...', 'common'),
  ('usedevicetoken_bildiris_izah', 'en', 'Allow the app to send notifications in your device settings to receive important updates and reminders.', 'common'),
  ('usedevicetoken_bildirislere_icaze_verin', 'en', 'Allow Notifications', 'common'),
  ('usementalhealthdata_normal_e041c7', 'en', 'Normal', 'common'),
  ('usementalhealthdata_pis_e041c6', 'en', 'Poor', 'common'),
  ('bp_systolic_hint', 'en', '(upper)', 'common'),
  ('bp_diastolic_hint', 'en', '(lower)', 'common')
ON CONFLICT (key, lang) DO NOTHING;
