-- ============================================================
-- Qazax6 — EPDS cavab variantlarının i18n düzəlişi (ru + tr + kk birdən)
-- options jsonb-yə text_ru/text_tr/text_kk əlavə olunur.
-- QEYD: ru/tr üçün də köhnə boşluq idi — depressiya testinin variantları
-- bütün dillərdə az görünürdü. İdempotent (mövcud dəyərlər qorunur).
-- ============================================================


UPDATE public.epds_questions SET options = '[{"text":"As much as I always could","value":0,"text_az":"Həmişəki kimi","text_ru":"Как всегда","text_tr":"Her zamanki kadar","text_kk":"Әдеттегідей"},{"text":"Not quite so much now","value":1,"text_az":"İndi o qədər də yox","text_ru":"Сейчас уже не так","text_tr":"Şimdi eskisi kadar değil","text_kk":"Қазір онша емес"},{"text":"Definitely not so much now","value":2,"text_az":"Əlbəttə ki, indi o qədər yox","text_ru":"Определённо, сейчас уже не так","text_tr":"Kesinlikle artık eskisi kadar değil","text_kk":"Әрине, қазір бұрынғыдай емес"},{"text":"Not at all","value":3,"text_az":"Heç","text_ru":"Совсем нет","text_tr":"Hiç","text_kk":"Мүлде жоқ"}]'::jsonb WHERE id = '277c938a-fb4a-486c-b34d-e552dd72625e';

UPDATE public.epds_questions SET options = '[{"text":"As much as I ever did","value":0,"text_az":"Həmişəki kimi","text_ru":"Как всегда","text_tr":"Her zamanki kadar","text_kk":"Әдеттегідей"},{"text":"Rather less than I used to","value":1,"text_az":"Əvvəlkindən az","text_ru":"Меньше, чем раньше","text_tr":"Eskisinden daha az","text_kk":"Бұрынғыдан азырақ"},{"text":"Definitely less than I used to","value":2,"text_az":"Əvvəlkindən xeyli az","text_ru":"Значительно меньше, чем раньше","text_tr":"Eskisinden çok daha az","text_kk":"Бұрынғыдан әлдеқайда аз"},{"text":"Hardly at all","value":3,"text_az":"Demək olar ki, heç","text_ru":"Почти никогда","text_tr":"Neredeyse hiç","text_kk":"Мүлде дерлік жоқ"}]'::jsonb WHERE id = '4a420fda-2d8d-426c-a5e1-f7df0bf3d4c7';

UPDATE public.epds_questions SET options = '[{"text":"Yes, most of the time","value":3,"text_az":"Bəli, çox vaxt","text_ru":"Да, большую часть времени","text_tr":"Evet, çoğu zaman","text_kk":"Иә, көбінесе"},{"text":"Yes, some of the time","value":2,"text_az":"Bəli, bəzən","text_ru":"Да, иногда","text_tr":"Evet, bazen","text_kk":"Иә, кейде"},{"text":"Not very often","value":1,"text_az":"Çox tez-tez yox","text_ru":"Не очень часто","text_tr":"Çok sık değil","text_kk":"Онша жиі емес"},{"text":"No, never","value":0,"text_az":"Xeyr, heç vaxt","text_ru":"Нет, никогда","text_tr":"Hayır, hiçbir zaman","text_kk":"Жоқ, ешқашан"}]'::jsonb WHERE id = '617495b6-4b22-4a30-add7-080988a6d0af';

UPDATE public.epds_questions SET options = '[{"text":"No, not at all","value":0,"text_az":"Xeyr, heç","text_ru":"Нет, совсем нет","text_tr":"Hayır, hiç","text_kk":"Жоқ, мүлде жоқ"},{"text":"Hardly ever","value":1,"text_az":"Demək olar ki, heç","text_ru":"Почти никогда","text_tr":"Neredeyse hiç","text_kk":"Мүлде дерлік жоқ"},{"text":"Yes, sometimes","value":2,"text_az":"Bəli, bəzən","text_ru":"Да, иногда","text_tr":"Evet, bazen","text_kk":"Иә, кейде"},{"text":"Yes, very often","value":3,"text_az":"Bəli, çox tez-tez","text_ru":"Да, очень часто","text_tr":"Evet, çok sık","text_kk":"Иә, өте жиі"}]'::jsonb WHERE id = '507845db-fd7f-4a9f-b4cc-6c3ff4bb0535';

UPDATE public.epds_questions SET options = '[{"text":"Yes, quite a lot","value":3,"text_az":"Bəli, kifayət qədər çox","text_ru":"Да, довольно часто","text_tr":"Evet, oldukça sık","text_kk":"Иә, айтарлықтай жиі"},{"text":"Yes, sometimes","value":2,"text_az":"Bəli, bəzən","text_ru":"Да, иногда","text_tr":"Evet, bazen","text_kk":"Иә, кейде"},{"text":"No, not much","value":1,"text_az":"Xeyr, çox yox","text_ru":"Нет, не очень часто","text_tr":"Hayır, pek değil","text_kk":"Жоқ, онша емес"},{"text":"No, not at all","value":0,"text_az":"Xeyr, heç","text_ru":"Нет, совсем нет","text_tr":"Hayır, hiç","text_kk":"Жоқ, мүлде жоқ"}]'::jsonb WHERE id = '1084fc38-0a22-4825-9661-8e3a8cce0a12';

UPDATE public.epds_questions SET options = '[{"text":"Yes, most of the time I haven''t been able to cope at all","value":3,"text_az":"Bəli, çox vaxt heç bacarmırdım","text_ru":"Да, большую часть времени совсем не удавалось справляться","text_tr":"Evet, çoğu zaman hiç başa çıkamıyordum","text_kk":"Иә, көбінесе мүлде жеңе алмадым"},{"text":"Yes, sometimes I haven''t been coping as well as usual","value":2,"text_az":"Bəli, bəzən həmişəki kimi bacarırdım","text_ru":"Да, иногда удавалось справляться как обычно","text_tr":"Evet, bazen her zamanki gibi başa çıkabiliyordum","text_kk":"Иә, кейде әдеттегідей жеңе алдым"},{"text":"No, most of the time I have coped quite well","value":1,"text_az":"Xeyr, çox vaxt yaxşı bacarırdım","text_ru":"Нет, большую часть времени удавалось справляться довольно хорошо","text_tr":"Hayır, çoğu zaman iyi başa çıkabiliyordum","text_kk":"Жоқ, көбінесе жақсы жеңе алдым"},{"text":"No, I have been coping as well as ever","value":0,"text_az":"Xeyr, həmişəki kimi bacarırdım","text_ru":"Нет, удавалось справляться как обычно","text_tr":"Hayır, her zamanki gibi başa çıkabiliyordum","text_kk":"Жоқ, әдеттегідей жеңе алдым"}]'::jsonb WHERE id = 'd51a6901-6595-4091-afb1-5ec4059046c2';

UPDATE public.epds_questions SET options = '[{"text":"Yes, most of the time","value":3,"text_az":"Bəli, çox vaxt","text_ru":"Да, большую часть времени","text_tr":"Evet, çoğu zaman","text_kk":"Иә, көбінесе"},{"text":"Yes, sometimes","value":2,"text_az":"Bəli, bəzən","text_ru":"Да, иногда","text_tr":"Evet, bazen","text_kk":"Иә, кейде"},{"text":"Not very often","value":1,"text_az":"Çox tez-tez yox","text_ru":"Не очень часто","text_tr":"Çok sık değil","text_kk":"Онша жиі емес"},{"text":"No, not at all","value":0,"text_az":"Xeyr, heç","text_ru":"Нет, совсем нет","text_tr":"Hayır, hiç","text_kk":"Жоқ, мүлде жоқ"}]'::jsonb WHERE id = '251f439e-2a72-48b6-aac2-cc3886ff44da';

UPDATE public.epds_questions SET options = '[{"text":"Yes, most of the time","value":3,"text_az":"Bəli, çox vaxt","text_ru":"Да, большую часть времени","text_tr":"Evet, çoğu zaman","text_kk":"Иә, көбінесе"},{"text":"Yes, quite often","value":2,"text_az":"Bəli, tez-tez","text_ru":"Да, часто","text_tr":"Evet, sık sık","text_kk":"Иә, жиі"},{"text":"Not very often","value":1,"text_az":"Çox tez-tez yox","text_ru":"Не очень часто","text_tr":"Çok sık değil","text_kk":"Онша жиі емес"},{"text":"No, not at all","value":0,"text_az":"Xeyr, heç","text_ru":"Нет, совсем нет","text_tr":"Hayır, hiç","text_kk":"Жоқ, мүлде жоқ"}]'::jsonb WHERE id = '87b54c96-ffd4-48de-bb2f-98ac41ec65e3';

UPDATE public.epds_questions SET options = '[{"text":"Yes, most of the time","value":3,"text_az":"Bəli, çox vaxt","text_ru":"Да, большую часть времени","text_tr":"Evet, çoğu zaman","text_kk":"Иә, көбінесе"},{"text":"Yes, quite often","value":2,"text_az":"Bəli, tez-tez","text_ru":"Да, часто","text_tr":"Evet, sık sık","text_kk":"Иә, жиі"},{"text":"Only occasionally","value":1,"text_az":"Yalnız bəzən","text_ru":"Только иногда","text_tr":"Yalnızca bazen","text_kk":"Тек кейде"},{"text":"No, never","value":0,"text_az":"Xeyr, heç vaxt","text_ru":"Нет, никогда","text_tr":"Hayır, hiçbir zaman","text_kk":"Жоқ, ешқашан"}]'::jsonb WHERE id = '7bf201c9-c37f-422f-b61b-02b1c6fac4c0';

UPDATE public.epds_questions SET options = '[{"text":"Yes, quite often","value":3,"text_az":"Bəli, tez-tez","text_ru":"Да, часто","text_tr":"Evet, sık sık","text_kk":"Иә, жиі"},{"text":"Sometimes","value":2,"text_az":"Bəzən","text_ru":"Иногда","text_tr":"Bazen","text_kk":"Кейде"},{"text":"Hardly ever","value":1,"text_az":"Demək olar ki, heç","text_ru":"Почти никогда","text_tr":"Neredeyse hiç","text_kk":"Мүлде дерлік жоқ"},{"text":"Never","value":0,"text_az":"Heç vaxt","text_ru":"Никогда","text_tr":"Hiçbir zaman","text_kk":"Ешқашан"}]'::jsonb WHERE id = '1ef9070f-81ad-4cee-bf09-cb4b156af990';
