-- Premium limit/gate UI açarları (ru/tr/en) — idempotent
INSERT INTO public.translations (key, lang, value, namespace) VALUES
  ('aichat_limit_warn_title', 'ru', 'Бесплатный лимит заканчивается', 'common'),
  ('aichat_limit_warn_title', 'tr', 'Ücretsiz limit azalıyor', 'common'),
  ('aichat_limit_warn_title', 'en', 'Free limit running low', 'common'),
  ('aichat_limit_warn_desc', 'ru', 'Сегодня осталось {n} бесплатных вопросов. С Premium — без лимита.', 'common'),
  ('aichat_limit_warn_desc', 'tr', 'Bugün {n} ücretsiz sorunuz kaldı. Premium''la sınırsız.', 'common'),
  ('aichat_limit_warn_desc', 'en', 'You have {n} free questions left today. Unlimited with Premium.', 'common'),
  ('babyai_limit_cta', 'ru', 'Дневной бесплатный анализ исчерпан — с Premium без лимита', 'common'),
  ('babyai_limit_cta', 'tr', 'Günlük ücretsiz analiz bitti — Premium''la sınırsız', 'common'),
  ('babyai_limit_cta', 'en', 'Daily free analyses used — unlimited with Premium', 'common'),
  ('pm_feat_tool', 'ru', 'Этот инструмент', 'common'),
  ('pm_feat_tool', 'tr', 'Bu araç', 'common'),
  ('pm_feat_tool', 'en', 'This tool', 'common'),
  ('pm_feat_ai_chat', 'ru', 'Безлимитный AI-чат', 'common'),
  ('pm_feat_ai_chat', 'tr', 'Sınırsız AI sohbeti', 'common'),
  ('pm_feat_ai_chat', 'en', 'Unlimited AI chat', 'common'),
  ('pm_feat_doctor_report', 'ru', 'PDF-отчёт для врача', 'common'),
  ('pm_feat_doctor_report', 'tr', 'Doktor PDF raporu', 'common'),
  ('pm_feat_doctor_report', 'en', 'Doctor PDF report', 'common'),
  ('pm_feat_baby_insight', 'ru', 'AI-анализ трекеров', 'common'),
  ('pm_feat_baby_insight', 'tr', 'AI takip analizi', 'common'),
  ('pm_feat_baby_insight', 'en', 'AI tracker analysis', 'common'),
  ('pm_feat_cry', 'ru', 'Переводчик плача', 'common'),
  ('pm_feat_cry', 'tr', 'Ağlama çevirmeni', 'common'),
  ('pm_feat_cry', 'en', 'Cry translator', 'common'),
  ('pm_feat_poop', 'ru', 'Анализ подгузника', 'common'),
  ('pm_feat_poop', 'tr', 'Bez analizi', 'common'),
  ('pm_feat_poop', 'en', 'Diaper analysis', 'common'),
  ('pm_feat_fairy', 'ru', 'AI-сказки', 'common'),
  ('pm_feat_fairy', 'tr', 'AI masallar', 'common'),
  ('pm_feat_fairy', 'en', 'AI fairy tales', 'common'),
  ('pm_feat_horoscope', 'ru', 'Астрологический анализ', 'common'),
  ('pm_feat_horoscope', 'tr', 'Burç analizi', 'common'),
  ('pm_feat_horoscope', 'en', 'Horoscope analysis', 'common'),
  ('pm_feat_weekly', 'ru', 'Недельная статистика', 'common'),
  ('pm_feat_weekly', 'tr', 'Haftalık istatistik', 'common'),
  ('pm_feat_weekly', 'en', 'Weekly stats', 'common'),
  ('pm_feat_teething', 'ru', 'Трекер зубов', 'common'),
  ('pm_feat_teething', 'tr', 'Diş takibi', 'common'),
  ('pm_feat_teething', 'en', 'Teething tracker', 'common'),
  ('pm_feat_growth', 'ru', 'Трекер роста', 'common'),
  ('pm_feat_growth', 'tr', 'Büyüme takibi', 'common'),
  ('pm_feat_growth', 'en', 'Growth tracker', 'common'),
  ('pm_feat_pregdays', 'ru', 'Просмотр всех дней', 'common'),
  ('pm_feat_pregdays', 'tr', 'Tüm günleri görüntüleme', 'common'),
  ('pm_feat_pregdays', 'en', 'View all days', 'common'),
  ('pm_feat_whitenoise', 'ru', 'Безлимитный белый шум', 'common'),
  ('pm_feat_whitenoise', 'tr', 'Sınırsız beyaz gürültü', 'common'),
  ('pm_feat_whitenoise', 'en', 'Unlimited white noise', 'common'),
  ('pm_feat_winback', 'ru', 'Premium', 'common'),
  ('pm_feat_winback', 'tr', 'Premium', 'common'),
  ('pm_feat_winback', 'en', 'Premium', 'common'),
  ('pm_feat_general', 'ru', 'Premium', 'common'),
  ('pm_feat_general', 'tr', 'Premium', 'common'),
  ('pm_feat_general', 'en', 'Premium', 'common'),
  ('pm_feat_flow_logger', 'ru', 'Ежедневные записи', 'common'),
  ('pm_feat_flow_logger', 'tr', 'Günlük kayıtlar', 'common'),
  ('pm_feat_flow_logger', 'en', 'Daily logging', 'common'),
  ('pm_feat_flow_mood', 'ru', 'График настроения', 'common'),
  ('pm_feat_flow_mood', 'tr', 'Ruh hali grafiği', 'common'),
  ('pm_feat_flow_mood', 'en', 'Mood chart', 'common'),
  ('pm_feat_flow_stats', 'ru', 'Статистика цикла', 'common'),
  ('pm_feat_flow_stats', 'tr', 'Döngü istatistikleri', 'common'),
  ('pm_feat_flow_stats', 'en', 'Cycle stats', 'common'),
  ('pm_feat_flow_trend', 'ru', 'График трендов', 'common'),
  ('pm_feat_flow_trend', 'tr', 'Trend grafiği', 'common'),
  ('pm_feat_flow_trend', 'en', 'Trend chart', 'common'),
  ('pm_feat_flow_symptom', 'ru', 'Отчёт о симптомах', 'common'),
  ('pm_feat_flow_symptom', 'tr', 'Semptom raporu', 'common'),
  ('pm_feat_flow_symptom', 'en', 'Symptom report', 'common'),
  ('pm_feat_flow_reminders', 'ru', 'Напоминания', 'common'),
  ('pm_feat_flow_reminders', 'tr', 'Hatırlatmalar', 'common'),
  ('pm_feat_flow_reminders', 'en', 'Reminders', 'common')
ON CONFLICT (key, lang) DO NOTHING;
