-- Həkim PDF hesabatı + Tracker AI analiz UI açarları (ru/tr/en) — idempotent
INSERT INTO public.translations (key, lang, value, namespace) VALUES
  ('profilescreen_hekim_hesabati', 'ru', 'Отчёт для врача (PDF)', 'common'),
  ('profilescreen_hekim_hesabati', 'tr', 'Doktor Raporu (PDF)', 'common'),
  ('profilescreen_hekim_hesabati', 'en', 'Doctor Report (PDF)', 'common'),
  ('dash_pdf_report', 'ru', 'Отчёт для врача (PDF)', 'common'),
  ('dash_pdf_report', 'tr', 'Doktor raporu (PDF)', 'common'),
  ('dash_pdf_report', 'en', 'Doctor report (PDF)', 'common'),
  ('pdf_section_babycare', 'ru', 'Уход за малышом (за период)', 'common'),
  ('pdf_section_babycare', 'tr', 'Bebek Bakımı (dönem boyunca)', 'common'),
  ('pdf_section_babycare', 'en', 'Baby Care (over period)', 'common'),
  ('pdf_bc_sleep_avg', 'ru', 'Сон (в среднем/день)', 'common'),
  ('pdf_bc_sleep_avg', 'tr', 'Uyku (ort./gün)', 'common'),
  ('pdf_bc_sleep_avg', 'en', 'Sleep (avg/day)', 'common'),
  ('pdf_bc_feeds_avg', 'ru', 'Кормление (в среднем/день)', 'common'),
  ('pdf_bc_feeds_avg', 'tr', 'Beslenme (ort./gün)', 'common'),
  ('pdf_bc_feeds_avg', 'en', 'Feeding (avg/day)', 'common'),
  ('pdf_bc_breast', 'ru', 'Грудное (всего)', 'common'),
  ('pdf_bc_breast', 'tr', 'Anne sütü (toplam)', 'common'),
  ('pdf_bc_breast', 'en', 'Breast (total)', 'common'),
  ('pdf_bc_formula', 'ru', 'Смесь (всего)', 'common'),
  ('pdf_bc_formula', 'tr', 'Mama (toplam)', 'common'),
  ('pdf_bc_formula', 'en', 'Formula (total)', 'common'),
  ('pdf_bc_solid', 'ru', 'Прикорм (всего)', 'common'),
  ('pdf_bc_solid', 'tr', 'Ek gıda (toplam)', 'common'),
  ('pdf_bc_solid', 'en', 'Solids (total)', 'common'),
  ('pdf_bc_diapers_avg', 'ru', 'Подгузники (в среднем/день)', 'common'),
  ('pdf_bc_diapers_avg', 'tr', 'Bez (ort./gün)', 'common'),
  ('pdf_bc_diapers_avg', 'en', 'Diapers (avg/day)', 'common'),
  ('pdf_bc_wet_dirty', 'ru', 'Мокрые / Грязные (всего)', 'common'),
  ('pdf_bc_wet_dirty', 'tr', 'Islak / Kirli (toplam)', 'common'),
  ('pdf_bc_wet_dirty', 'en', 'Wet / Dirty (total)', 'common'),
  ('pdf_bc_total', 'ru', 'Всего записей', 'common'),
  ('pdf_bc_total', 'tr', 'Toplam kayıt', 'common'),
  ('pdf_bc_total', 'en', 'Total logs', 'common'),
  ('babyai_title', 'ru', 'AI-анализ', 'common'),
  ('babyai_title', 'tr', 'AI Analizi', 'common'),
  ('babyai_title', 'en', 'AI Analysis', 'common'),
  ('babyai_check', 'ru', 'Проверить с AI — эти показатели в норме?', 'common'),
  ('babyai_check', 'tr', 'AI ile kontrol et — bu değerler normal mi?', 'common'),
  ('babyai_check', 'en', 'Check with AI — are these numbers normal?', 'common'),
  ('babyai_loading', 'ru', 'AI анализирует...', 'common'),
  ('babyai_loading', 'tr', 'AI analiz ediyor...', 'common'),
  ('babyai_loading', 'en', 'AI is analyzing...', 'common'),
  ('babyai_error_retry', 'ru', 'AI-анализ не удался — попробуйте ещё раз', 'common'),
  ('babyai_error_retry', 'tr', 'AI analizi başarısız — tekrar deneyin', 'common'),
  ('babyai_error_retry', 'en', 'AI analysis failed — tap to retry', 'common'),
  ('babyai_refresh', 'ru', 'Обновить', 'common'),
  ('babyai_refresh', 'tr', 'Yenile', 'common'),
  ('babyai_refresh', 'en', 'Refresh', 'common'),
  ('babyai_status_normal', 'ru', 'Норма', 'common'),
  ('babyai_status_normal', 'tr', 'Normal', 'common'),
  ('babyai_status_normal', 'en', 'Normal', 'common'),
  ('babyai_status_low', 'ru', 'Мало', 'common'),
  ('babyai_status_low', 'tr', 'Az', 'common'),
  ('babyai_status_low', 'en', 'Low', 'common'),
  ('babyai_status_high', 'ru', 'Много', 'common'),
  ('babyai_status_high', 'tr', 'Çok', 'common'),
  ('babyai_status_high', 'en', 'High', 'common'),
  ('babyai_status_watch', 'ru', 'Внимание', 'common'),
  ('babyai_status_watch', 'tr', 'Dikkat', 'common'),
  ('babyai_status_watch', 'en', 'Watch', 'common')
ON CONFLICT (key, lang) DO NOTHING;
