-- ============================================================
-- Son23: 1) blog_posts ölkə hədəfləməsi (admin include/exclude)
--        2) mini oyun açarlarının tərcümələri (59 açar — DB-yə heç düşməmişdi)
-- ============================================================

ALTER TABLE public.blog_posts
  ADD COLUMN IF NOT EXISTS countries_include text[],
  ADD COLUMN IF NOT EXISTS countries_exclude text[];

COMMENT ON COLUMN public.blog_posts.countries_include IS 'Boş deyilsə: yalnız bu ISO ölkə kodlarına görünür';
COMMENT ON COLUMN public.blog_posts.countries_exclude IS 'Bu ölkələrdə gizlənir';

-- Mini oyun UI açarları (idempotent)
INSERT INTO public.translations (key, lang, value, namespace) VALUES
  ('birlesdir_best_score_label', 'ru', 'Ваш лучший результат', 'common'),
  ('birlesdir_best_score_label', 'tr', 'En iyi puanınız', 'common'),
  ('birlesdir_best_score_label', 'en', 'Best score', 'common'),
  ('birlesdir_choose_level', 'ru', 'Выберите уровень', 'common'),
  ('birlesdir_choose_level', 'tr', 'Seviye seçin', 'common'),
  ('birlesdir_choose_level', 'en', 'Choose a level', 'common'),
  ('birlesdir_intro_desc', 'ru', 'Собери 3 или больше одинаковых предметов в ряд и открой бонусы «Минута спокойствия» и «Супермама»!', 'common'),
  ('birlesdir_intro_desc', 'tr', '3 veya daha fazla aynı öğeyi yan yana getir, “Sakinlik Anı” ve “Süper Anne” bonuslarını aç!', 'common'),
  ('birlesdir_intro_desc', 'en', 'Line up 3 or more matching items to unlock the "Calm Moment" and "Super Mom" bonuses!', 'common'),
  ('birlesdir_level_complete_title', 'ru', 'Уровень пройден!', 'common'),
  ('birlesdir_level_complete_title', 'tr', 'Seviye tamamlandı!', 'common'),
  ('birlesdir_level_complete_title', 'en', 'Level complete!', 'common'),
  ('birlesdir_level_label', 'ru', 'Уровень', 'common'),
  ('birlesdir_level_label', 'tr', 'Seviye', 'common'),
  ('birlesdir_level_label', 'en', 'Level', 'common'),
  ('birlesdir_levels_unlocked_prefix', 'ru', 'Открытые уровни', 'common'),
  ('birlesdir_levels_unlocked_prefix', 'tr', 'Açılan seviyeler', 'common'),
  ('birlesdir_levels_unlocked_prefix', 'en', 'Levels unlocked', 'common'),
  ('birlesdir_menu_button', 'ru', 'Меню', 'common'),
  ('birlesdir_menu_button', 'tr', 'Menü', 'common'),
  ('birlesdir_menu_button', 'en', 'Menu', 'common'),
  ('birlesdir_move_bonus_label', 'ru', 'бонус за ходы', 'common'),
  ('birlesdir_move_bonus_label', 'tr', 'hamle bonusu', 'common'),
  ('birlesdir_move_bonus_label', 'en', 'move bonus', 'common'),
  ('birlesdir_moves_short', 'ru', 'ходов', 'common'),
  ('birlesdir_moves_short', 'tr', 'hamle', 'common'),
  ('birlesdir_moves_short', 'en', 'moves', 'common'),
  ('birlesdir_next_level_button', 'ru', 'Следующий уровень', 'common'),
  ('birlesdir_next_level_button', 'tr', 'Sonraki seviye', 'common'),
  ('birlesdir_next_level_button', 'en', 'Next level', 'common'),
  ('birlesdir_out_of_moves_title', 'ru', 'Ходы закончились!', 'common'),
  ('birlesdir_out_of_moves_title', 'tr', 'Hamleler bitti!', 'common'),
  ('birlesdir_out_of_moves_title', 'en', 'Out of moves!', 'common'),
  ('birlesdir_paused_title', 'ru', 'Пауза', 'common'),
  ('birlesdir_paused_title', 'tr', 'Mola', 'common'),
  ('birlesdir_paused_title', 'en', 'Paused', 'common'),
  ('birlesdir_points_short', 'ru', 'очк.', 'common'),
  ('birlesdir_points_short', 'tr', 'puan', 'common'),
  ('birlesdir_points_short', 'en', 'pts', 'common'),
  ('birlesdir_replay_button', 'ru', 'Играть снова', 'common'),
  ('birlesdir_replay_button', 'tr', 'Tekrar oyna', 'common'),
  ('birlesdir_replay_button', 'en', 'Play again', 'common'),
  ('birlesdir_restart_button', 'ru', 'Начать заново', 'common'),
  ('birlesdir_restart_button', 'tr', 'Yeniden başla', 'common'),
  ('birlesdir_restart_button', 'en', 'Restart', 'common'),
  ('birlesdir_resume_button', 'ru', 'Продолжить', 'common'),
  ('birlesdir_resume_button', 'tr', 'Devam et', 'common'),
  ('birlesdir_resume_button', 'en', 'Resume', 'common'),
  ('birlesdir_retry_button', 'ru', 'Попробовать ещё раз', 'common'),
  ('birlesdir_retry_button', 'tr', 'Tekrar dene', 'common'),
  ('birlesdir_retry_button', 'en', 'Try again', 'common'),
  ('birlesdir_shuffle_notice', 'ru', 'Поле перемешано 🔄', 'common'),
  ('birlesdir_shuffle_notice', 'tr', 'Tahta karıştırıldı 🔄', 'common'),
  ('birlesdir_shuffle_notice', 'en', 'Board reshuffled 🔄', 'common'),
  ('birlesdir_start_button', 'ru', 'Начать', 'common'),
  ('birlesdir_start_button', 'tr', 'Başla', 'common'),
  ('birlesdir_start_button', 'en', 'Start', 'common'),
  ('birlesdir_target_prefix', 'ru', 'Цель', 'common'),
  ('birlesdir_target_prefix', 'tr', 'Hedef', 'common'),
  ('birlesdir_target_prefix', 'en', 'Target', 'common'),
  ('birlesdir_title', 'ru', 'Объедини', 'common'),
  ('birlesdir_title', 'tr', 'Birleştir', 'common'),
  ('birlesdir_title', 'en', 'Match Up', 'common'),
  ('birlesdir_your_score_prefix', 'ru', 'Ваши очки', 'common'),
  ('birlesdir_your_score_prefix', 'tr', 'Puanınız', 'common'),
  ('birlesdir_your_score_prefix', 'en', 'Your score', 'common'),
  ('minigames_badge_new', 'ru', 'Новое', 'common'),
  ('minigames_badge_new', 'tr', 'Yeni', 'common'),
  ('minigames_badge_new', 'en', 'New', 'common'),
  ('minigames_hub_subtitle', 'ru', 'Сбросьте стресс, играйте, расслабляйтесь', 'common'),
  ('minigames_hub_subtitle', 'tr', 'Stres at, oyna, rahatla', 'common'),
  ('minigames_hub_subtitle', 'en', 'Unwind, play, relax', 'common'),
  ('minigames_hub_title', 'ru', 'Мини-игры', 'common'),
  ('minigames_hub_title', 'tr', 'Mini Oyunlar', 'common'),
  ('minigames_hub_title', 'en', 'Mini Games', 'common'),
  ('minigames_leaderboard_empty_desc', 'ru', 'Станьте первым игроком! Завершите игру, и ваши очки попадут в глобальный рейтинг.', 'common'),
  ('minigames_leaderboard_empty_desc', 'tr', 'İlk oyuncu siz olun! Oyunu bitirin, puanınız küresel sıralamaya girsin.', 'common'),
  ('minigames_leaderboard_empty_desc', 'en', 'Be the first! Finish a round and your score will join the global leaderboard.', 'common'),
  ('minigames_leaderboard_empty_title', 'ru', 'Рейтинг пока пуст', 'common'),
  ('minigames_leaderboard_empty_title', 'tr', 'Sıralama henüz boş', 'common'),
  ('minigames_leaderboard_empty_title', 'en', 'The leaderboard is empty', 'common'),
  ('minigames_levels_short', 'ru', 'уровней', 'common'),
  ('minigames_levels_short', 'tr', 'seviye', 'common'),
  ('minigames_levels_short', 'en', 'levels', 'common'),
  ('minigames_more_soon_desc', 'ru', 'В раздел мини-игр скоро добавятся новые игры', 'common'),
  ('minigames_more_soon_desc', 'tr', 'Mini Oyunlar bölümüne yakında yeni oyunlar eklenecek', 'common'),
  ('minigames_more_soon_desc', 'en', 'New games will be added to the Mini Games section soon', 'common'),
  ('minigames_more_soon_title', 'ru', 'Скоро новые игры', 'common'),
  ('minigames_more_soon_title', 'tr', 'Yeni oyunlar yakında', 'common'),
  ('minigames_more_soon_title', 'en', 'New games coming soon', 'common'),
  ('minigames_points_label', 'ru', 'очк.', 'common'),
  ('minigames_points_label', 'tr', 'puan', 'common'),
  ('minigames_points_label', 'en', 'pts', 'common'),
  ('minigames_tab_games', 'ru', 'Игры', 'common'),
  ('minigames_tab_games', 'tr', 'Oyunlar', 'common'),
  ('minigames_tab_games', 'en', 'Games', 'common'),
  ('minigames_tab_leaderboard', 'ru', 'Рейтинг', 'common'),
  ('minigames_tab_leaderboard', 'tr', 'Sıralama', 'common'),
  ('minigames_tab_leaderboard', 'en', 'Leaderboard', 'common'),
  ('minigames_unlocked_short', 'ru', 'открыто', 'common'),
  ('minigames_unlocked_short', 'tr', 'açık', 'common'),
  ('minigames_unlocked_short', 'en', 'unlocked', 'common'),
  ('minigames_you_label', 'ru', 'Вы', 'common'),
  ('minigames_you_label', 'tr', 'Siz', 'common'),
  ('minigames_you_label', 'en', 'You', 'common'),
  ('minigames_your_best_score', 'ru', 'Ваш лучший результат', 'common'),
  ('minigames_your_best_score', 'tr', 'En iyi puanınız', 'common'),
  ('minigames_your_best_score', 'en', 'Your best score', 'common'),
  ('saglamsebet_best_score_label', 'ru', 'Ваш лучший результат', 'common'),
  ('saglamsebet_best_score_label', 'tr', 'En iyi puanınız', 'common'),
  ('saglamsebet_best_score_label', 'en', 'Best score', 'common'),
  ('saglamsebet_choose_level', 'ru', 'Выберите уровень', 'common'),
  ('saglamsebet_choose_level', 'tr', 'Seviye seçin', 'common'),
  ('saglamsebet_choose_level', 'en', 'Choose a level', 'common'),
  ('saglamsebet_go_text', 'ru', 'Начали!', 'common'),
  ('saglamsebet_go_text', 'tr', 'Başla!', 'common'),
  ('saglamsebet_go_text', 'en', 'Go!', 'common'),
  ('saglamsebet_intro_desc', 'ru', 'Ловите полезные продукты в корзину, уклоняйтесь от вредной еды и облаков стресса!', 'common'),
  ('saglamsebet_intro_desc', 'tr', 'Sağlıklı yiyecekleri sepete yakala, zararlı yiyeceklerden ve stres bulutlarından kaç!', 'common'),
  ('saglamsebet_intro_desc', 'en', 'Catch the healthy foods in your basket — dodge junk food and stress clouds!', 'common'),
  ('saglamsebet_level_complete_title', 'ru', 'Уровень пройден!', 'common'),
  ('saglamsebet_level_complete_title', 'tr', 'Seviye tamamlandı!', 'common'),
  ('saglamsebet_level_complete_title', 'en', 'Level complete!', 'common'),
  ('saglamsebet_level_label', 'ru', 'Уровень', 'common'),
  ('saglamsebet_level_label', 'tr', 'Seviye', 'common'),
  ('saglamsebet_level_label', 'en', 'Level', 'common'),
  ('saglamsebet_levels_unlocked_prefix', 'ru', 'Открытые уровни', 'common'),
  ('saglamsebet_levels_unlocked_prefix', 'tr', 'Açılan seviyeler', 'common'),
  ('saglamsebet_levels_unlocked_prefix', 'en', 'Levels unlocked', 'common'),
  ('saglamsebet_life_lost_text', 'ru', '-1 ❤️', 'common'),
  ('saglamsebet_life_lost_text', 'tr', '-1 ❤️', 'common'),
  ('saglamsebet_life_lost_text', 'en', '-1 ❤️', 'common'),
  ('saglamsebet_menu_button', 'ru', 'Меню', 'common'),
  ('saglamsebet_menu_button', 'tr', 'Menü', 'common'),
  ('saglamsebet_menu_button', 'en', 'Menu', 'common'),
  ('saglamsebet_next_level_button', 'ru', 'Следующий уровень', 'common'),
  ('saglamsebet_next_level_button', 'tr', 'Sonraki seviye', 'common'),
  ('saglamsebet_next_level_button', 'en', 'Next level', 'common'),
  ('saglamsebet_out_of_lives_title', 'ru', 'Жизни закончились!', 'common'),
  ('saglamsebet_out_of_lives_title', 'tr', 'Canlar bitti!', 'common'),
  ('saglamsebet_out_of_lives_title', 'en', 'Out of lives!', 'common'),
  ('saglamsebet_paused_title', 'ru', 'Пауза', 'common'),
  ('saglamsebet_paused_title', 'tr', 'Mola', 'common'),
  ('saglamsebet_paused_title', 'en', 'Paused', 'common'),
  ('saglamsebet_points_short', 'ru', 'очк.', 'common'),
  ('saglamsebet_points_short', 'tr', 'puan', 'common'),
  ('saglamsebet_points_short', 'en', 'pts', 'common'),
  ('saglamsebet_replay_button', 'ru', 'Играть снова', 'common'),
  ('saglamsebet_replay_button', 'tr', 'Tekrar oyna', 'common'),
  ('saglamsebet_replay_button', 'en', 'Play again', 'common'),
  ('saglamsebet_restart_button', 'ru', 'Начать заново', 'common'),
  ('saglamsebet_restart_button', 'tr', 'Yeniden başla', 'common'),
  ('saglamsebet_restart_button', 'en', 'Restart', 'common'),
  ('saglamsebet_resume_button', 'ru', 'Продолжить', 'common'),
  ('saglamsebet_resume_button', 'tr', 'Devam et', 'common'),
  ('saglamsebet_resume_button', 'en', 'Resume', 'common'),
  ('saglamsebet_retry_button', 'ru', 'Попробовать ещё раз', 'common'),
  ('saglamsebet_retry_button', 'tr', 'Tekrar dene', 'common'),
  ('saglamsebet_retry_button', 'en', 'Try again', 'common'),
  ('saglamsebet_start_button', 'ru', 'Начать', 'common'),
  ('saglamsebet_start_button', 'tr', 'Başla', 'common'),
  ('saglamsebet_start_button', 'en', 'Start', 'common'),
  ('saglamsebet_target_prefix', 'ru', 'Цель', 'common'),
  ('saglamsebet_target_prefix', 'tr', 'Hedef', 'common'),
  ('saglamsebet_target_prefix', 'en', 'Target', 'common'),
  ('saglamsebet_target_reached', 'ru', 'Цель достигнута!', 'common'),
  ('saglamsebet_target_reached', 'tr', 'Hedefe ulaşıldı!', 'common'),
  ('saglamsebet_target_reached', 'en', 'Target reached!', 'common'),
  ('saglamsebet_time_up_title', 'ru', 'Время вышло!', 'common'),
  ('saglamsebet_time_up_title', 'tr', 'Süre doldu!', 'common'),
  ('saglamsebet_time_up_title', 'en', 'Time''s up!', 'common'),
  ('saglamsebet_title', 'ru', 'Здоровая корзина', 'common'),
  ('saglamsebet_title', 'tr', 'Sağlıklı Sepet', 'common'),
  ('saglamsebet_title', 'en', 'Healthy Basket', 'common'),
  ('saglamsebet_your_score_prefix', 'ru', 'Ваши очки', 'common'),
  ('saglamsebet_your_score_prefix', 'tr', 'Puanınız', 'common'),
  ('saglamsebet_your_score_prefix', 'en', 'Your score', 'common')
ON CONFLICT (key, lang) DO NOTHING;
