-- Migration: Seed English Baby Names
-- Description: Inserts 150 popular English/Western baby names (50 Boys, 50 Girls, 50 Unisex) with detailed, localized meanings and origins.

-- First, clean up any existing English names to make this migration repeatable
DELETE FROM public.baby_names_db WHERE origin_en IS NOT NULL;

-- Batch insert the names
INSERT INTO public.baby_names_db (name, gender, origin, origin_en, meaning, meaning_az, meaning_en, popularity, is_active) VALUES
-- ==================== BOYS (50) ====================
('Liam', 'boy', 'İrland', 'Irish', 'Güclü iradəli döyüşçü, qoruyucu', 'Güclü iradəli döyüşçü, qoruyucu', 'Strong-willed warrior, protector', 100, true),
('Noah', 'boy', 'İbrani', 'Hebrew', 'Rahatlıq, təsəlli, sülh', 'Rahatlıq, təsəlli, sülh', 'Rest, comfort, peace', 99, true),
('Oliver', 'boy', 'Latın', 'Latin', 'Zeytun ağacı, sülh rəmzi', 'Zeytun ağacı, sülh rəmzi', 'Olive tree, symbol of peace', 98, true),
('Elijah', 'boy', 'İbrani', 'Hebrew', 'Rəbb mənim Allahımdır', 'Rəbb mənim Allahımdır', 'Yahweh is God', 97, true),
('James', 'boy', 'İbrani', 'Hebrew', 'Taxta çıxan, ardıcıl gələn', 'Taxta çıxan, ardıcıl gələn', 'Supplanter, one who follows', 96, true),
('William', 'boy', 'German', 'Germanic', 'Qətiyyətli qoruyucu, güclü dəbilqə', 'Qətiyyətli qoruyucu, güclü dəbilqə', 'Resolute protector, strong helmet', 95, true),
('Benjamin', 'boy', 'İbrani', 'Hebrew', 'Sağ əlin oğlu, sevimli oğul', 'Sağ əlin oğlu, sevimli oğul', 'Son of the right hand, favorite son', 94, true),
('Lucas', 'boy', 'Latın', 'Latin', 'İşıq gətirən, nurlu', 'İşıq gətirən, nurlu', 'Bringer of light, luminous', 93, true),
('Henry', 'boy', 'German', 'Germanic', 'Evin hökmdarı, mülk sahibi', 'Evin hökmdarı, mülk sahibi', 'Ruler of the home, estate ruler', 92, true),
('Theodore', 'boy', 'Yunan', 'Greek', 'Allahın töhfəsi, ilahi hədiyyə', 'Allahın töhfəsi, ilahi hədiyyə', 'Gift of God, divine gift', 91, true),
('Jack', 'boy', 'İngilis', 'English', 'Allah rəhmlidir', 'Allah rəhmlidir', 'God is gracious', 90, true),
('Levi', 'boy', 'İbrani', 'Hebrew', 'Birləşmiş, bağlı, vəfalı', 'Birləşmiş, bağlı, vəfalı', 'Joined, attached, united', 89, true),
('Alexander', 'boy', 'Yunan', 'Greek', 'İnsanların müdafiəçisi, qoruyucu', 'İnsanların müdafiəçisi, qoruyucu', 'Defender of men, protector', 88, true),
('Daniel', 'boy', 'İbrani', 'Hebrew', 'Allah mənim hakimiimdir', 'Allah mənim hakimiimdir', 'God is my judge', 87, true),
('Michael', 'boy', 'İbrani', 'Hebrew', 'Allah kimi olan kimdir?', 'Allah kimi olan kimdir?', 'Who is like God?', 86, true),
('Owen', 'boy', 'Uels', 'Welsh', 'Nəcabətli gənc döyüşçü, alicənab', 'Nəcabətli gənc döyüşçü, alicənab', 'Noble born, young warrior', 85, true),
('Sebastian', 'boy', 'Latın', 'Latin', 'Hörmətli, ehtirama layiq, müqəddəs', 'Hörmətli, ehtirama layiq, müqəddəs', 'Venerable, revered, respected', 84, true),
('Carter', 'boy', 'İngilis', 'English', 'Arabacı, yük daşıyan', 'Arabacı, yük daşıyan', 'Cart driver, transporter of goods', 83, true),
('Julian', 'boy', 'Latın', 'Latin', 'Gənc, gənclik dolu, güclü', 'Gənc, gənclik dolu, güclü', 'Youthful, downy-bearded', 82, true),
('Wyatt', 'boy', 'İngilis', 'English', 'Müharibədə cəsur, kiçik döyüşçü', 'Müharibədə cəsur, kiçik döyüşçü', 'Brave in war, little warrior', 81, true),
('Leo', 'boy', 'Latın', 'Latin', 'Şir, cəsur və güclü', 'Şir, cəsur və güclü', 'Lion, brave and strong', 80, true),
('Gabriel', 'boy', 'İbrani', 'Hebrew', 'Allah mənim gücümdür', 'Allah mənim gücümdür', 'God is my strength', 79, true),
('Lincoln', 'boy', 'İngilis', 'English', 'Göl koloniyası, göl kənarındakı şəhər', 'Göl koloniyası, göl kənarındakı şəhər', 'Lake colony, town by the pool', 78, true),
('Hudson', 'boy', 'İngilis', 'English', 'Hyu oğlu, zəka oğlu', 'Hyu oğlu, zəka oğlu', 'Son of Hugh, son of the mind', 77, true),
('Samuel', 'boy', 'İbrani', 'Hebrew', 'Allah eşitdi, Allahın adı', 'Allah eşitdi, Allahın adı', 'God has heard', 76, true),
('Maverick', 'boy', 'Amerika', 'American', 'Müstəqil, azad ruhlu, qaydalara uymayan', 'Müstəqil, azad ruhlu, qaydalara uymayan', 'Independent, free spirit', 75, true),
('Ezra', 'boy', 'İbrani', 'Hebrew', 'Kömək, köməkçi, güclü dayaq', 'Kömək, köməkçi, güclü dayaq', 'Help, helper, strong support', 74, true),
('Thomas', 'boy', 'Arami', 'Aramaic', 'Əkiz', 'Əkiz', 'Twin', 73, true),
('Charles', 'boy', 'German', 'Germanic', 'Azad insan, güclü, cəsur', 'Azad insan, güclü, cəsur', 'Free man, strong', 72, true),
('Christopher', 'boy', 'Yunan', 'Greek', 'Məsihin daşıyıcısı', 'Məsihin daşıyıcısı', 'Bearer of Christ', 71, true),
('Ethan', 'boy', 'İbrani', 'Hebrew', 'Güclü, möhkəm, uzunömürlü', 'Güclü, möhkəm, uzunömürlü', 'Strong, firm, long-lived', 70, true),
('Asher', 'boy', 'İbrani', 'Hebrew', 'Xoşbəxt, mübarək, bəxtiyar', 'Xoşbəxt, mübarək, bəxtiyar', 'Happy, blessed, fortunate', 70, true),
('Mason', 'boy', 'Fransız', 'French', 'Daşyonan, bənna, usta', 'Daşyonan, bənna, usta', 'Stone worker, builder', 70, true),
('Mateo', 'boy', 'İspan', 'Spanish', 'Allahın hədiyyəsi, töhfə', 'Allahın hədiyyəsi, töhfə', 'Gift of God', 70, true),
('Ryan', 'boy', 'İrland', 'Irish', 'Kiçik kral, şahzadə', 'Kiçik kral, şahzadə', 'Little king, royalty', 70, true),
('Nathan', 'boy', 'İbrani', 'Hebrew', 'O verdi, Allahın bəxşişi', 'O verdi, Allahın bəxşişi', 'He gave, gift of God', 70, true),
('Isaac', 'boy', 'İbrani', 'Hebrew', 'Güləcək, gülüş, sevinc', 'Güləcək, gülüş, sevinc', 'He will laugh, laughter', 70, true),
('Caleb', 'boy', 'İbrani', 'Hebrew', 'Sadiq, cəsur, ürəkdən bağlı', 'Sadiq, cəsur, ürəkdən bağlı', 'Faithful, whole-hearted, brave', 70, true),
('Christian', 'boy', 'Latın', 'Latin', 'Məsih ardıcılı, xristian', 'Məsih ardıcılı, xristian', 'Follower of Christ', 70, true),
('Dylan', 'boy', 'Uels', 'Welsh', 'Dəniz oğlu, böyük dalğa', 'Dəniz oğlu, böyük dalğa', 'Son of the sea, great wave', 70, true),
('Aaron', 'boy', 'İbrani', 'Hebrew', 'Uca dağ, şərəfli, ucaldılmış', 'Uca dağ, şərəfli, ucaldılmış', 'High mountain, exalted', 70, true),
('Jonathan', 'boy', 'İbrani', 'Hebrew', 'Allah bəxş etdi, töhfə', 'Allah bəxş etdi, töhfə', 'God has given', 70, true),
('Connor', 'boy', 'İrland', 'Irish', 'Ov itlərini sevən, arzu, istək', 'Ov itlərini sevən, arzu, istək', 'Lover of hounds, desire', 70, true),
('Adrian', 'boy', 'Latın', 'Latin', 'Hadriyadan olan, dəniz kənarından', 'Hadriyadan olan, dəniz kənarından', 'Man from Hadria, dark one', 70, true),
('Robert', 'boy', 'German', 'Germanic', 'Parlaq şöhrət, şanlı, tanınmış', 'Parlaq şöhrət, şanlı, tanınmış', 'Bright fame, shining glory', 70, true),
('Nicholas', 'boy', 'Yunan', 'Greek', 'Xalqın qələbəsi, qalib xalq', 'Xalqın qələbəsi, qalib xalq', 'Victory of the people', 70, true),
('Arthur', 'boy', 'Kelt', 'Celtic', 'Ayı kimi güclü, nəcabətli qəhrəman', 'Ayı kimi güclü, nəcabətli qəhrəman', 'Bear man, noble and courageous', 70, true),
('Edward', 'boy', 'İngilis', 'English', 'Zəngin qoruyucu, rifah keşikçisi', 'Zəngin qoruyucu, rifah keşikçisi', 'Wealthy guardian, protector of prosperity', 70, true),
('Gavin', 'boy', 'Kelt', 'Celtic', 'Ağ qırğı, döyüş quşu', 'Ağ qırğı, döyüş quşu', 'White hawk, battle bird', 70, true),
('Miles', 'boy', 'Latın', 'Latin', 'Əsgər, xeyirxah, rəhmli', 'Əsgər, xeyirxah, rəhmli', 'Soldier, merciful one', 70, true),

-- ==================== GIRLS (50) ====================
('Olivia', 'girl', 'Latın', 'Latin', 'Zeytun ağacı, sülh və bərəkət rəmzi', 'Zeytun ağacı, sülh və bərəkət rəmzi', 'Olive tree, symbol of peace and fertility', 100, true),
('Emma', 'girl', 'German', 'Germanic', 'Bütöv, universal, tam, güclü', 'Bütöv, universal, tam, güclü', 'Whole, universal, complete', 99, true),
('Charlotte', 'girl', 'Fransız', 'French', 'Azad insan, zərif və xanım-xatın', 'Azad insan, zərif və xanım-xatın', 'Free man, petite and feminine', 98, true),
('Amelia', 'girl', 'Latın', 'Latin', 'Çalışqan, zəhmətsevər, enerjili', 'Çalışqan, zəhmətsevər, enerjili', 'Industrious, striving, hardworking', 97, true),
('Sophia', 'girl', 'Yunan', 'Greek', 'Müdriklik, dərin zəka, bilik', 'Müdriklik, dərin zəka, bilik', 'Wisdom, intellectual ability', 96, true),
('Isabella', 'girl', 'İbrani', 'Hebrew', 'Allaha vəd edilmiş, sadiq, dindar', 'Allaha vəd edilmiş, sadiq, dindar', 'Pledged to God, devoted', 95, true),
('Mia', 'girl', 'İtalyan', 'Italian', 'Mənimki, sevimli və arzulanan uşaq', 'Mənimki, sevimli və arzulanan uşaq', 'Mine, beloved, wished-for child', 94, true),
('Evelyn', 'girl', 'İngilis', 'English', 'Arzulanan, gözəl quş, həyat mənbəyi', 'Arzulanan, gözəl quş, həyat mənbəyi', 'Desired, water source, beautiful bird', 93, true),
('Harper', 'girl', 'İngilis', 'English', 'Arfa chalan, musiqiçi, yaradıcı', 'Arfa chalan, musiqiçi, yaradıcı', 'Harp player, musician', 92, true),
('Luna', 'girl', 'Latın', 'Latin', 'Ay, parlayan, gecənin ilahəsi', 'Ay, parlayan, gecənin ilahəsi', 'Moon, glowing, celestial', 91, true),
('Camila', 'girl', 'Latın', 'Latin', 'Nəcib köməkçi, gənc mərasim xidmətçisi', 'Nəcib köməkçi, gənc mərasim xidmətçisi', 'Young ceremonial attendant, noble helper', 90, true),
('Gianna', 'girl', 'İtalyan', 'Italian', 'Allah rəhmlidir, ilahi lütf', 'Allah rəhmlidir, ilahi lütf', 'God is gracious, divine favor', 89, true),
('Elizabeth', 'girl', 'İbrani', 'Hebrew', 'Allahım mənim andımdır, bərəkətli', 'Allahım mənim andımdır, bərəkətli', 'My God is an oath, bountiful', 88, true),
('Eleanor', 'girl', 'Yunan', 'Greek', 'Parlaq, nurlu, işıq saçan', 'Parlaq, nurlu, işıq saçan', 'Bright, shining one, radiant', 87, true),
('Ella', 'girl', 'German', 'Germanic', 'Bütün, tam, pəri qız, gözəl', 'Bütün, tam, pəri qız, gözəl', 'All, completely, fairy maiden', 86, true),
('Aria', 'girl', 'İtalyan', 'Italian', 'Hava, nəğmə, melodiya, şir qızı', 'Hava, nəğmə, melodiya, şir qızı', 'Air, song, melody, lioness', 85, true),
('Scarlett', 'girl', 'İngilis', 'English', 'Al-qırmızı, nəfis parçalar satan', 'Al-qırmızı, nəfis parçalar satan', 'Bright red, seller of fine fabrics', 84, true),
('Emily', 'girl', 'Latın', 'Latin', 'Rəqib, həvəsli, çalışqan', 'Rəqib, həvəsli, çalışqan', 'Rival, eager, industrious', 83, true),
('Abigail', 'girl', 'İbrani', 'Hebrew', 'Atanın sevinci, sevinc mənbəyi', 'Atanın sevinci, sevinc mənbəyi', 'My father''s joy, source of joy', 82, true),
('Lily', 'girl', 'Latın', 'Latin', 'Zanbaq çiçəyi, paklıq və zəriflik rəmzi', 'Zanbaq çiçəyi, paklıq və zəriflik rəmzi', 'Lily flower, symbol of purity and innocence', 81, true),
('Chloe', 'girl', 'Yunan', 'Greek', 'Çiçəklənən, yaşıl cücərti, təzə bloom', 'Çiçəklənən, yaşıl cücərti, təzə bloom', 'Blooming, green shoot, fresh bloom', 80, true),
('Mila', 'girl', 'Slavyan', 'Slavic', 'Zərif, əziz, sevilən, mehriban', 'Zərif, əziz, sevilən, mehriban', 'Gracious, dear, loved by people', 79, true),
('Layla', 'girl', 'Ərəb', 'Arabic', 'Gecə, qaraşın gözəl, sirli', 'Gecə, qaraşın gözəl, sirli', 'Night, dark beauty', 78, true),
('Penelope', 'girl', 'Yunan', 'Greek', 'Toxucu, sadiq həyat yoldaşı', 'Toxucu, sadiq həyat yoldaşı', 'Weaver, faithful wife', 77, true),
('Grace', 'girl', 'Latın', 'Latin', 'Lütf, xeyir-dua, zəriflik, cazibə', 'Lütf, xeyir-dua, zəriflik, cazibə', 'Favor, blessing, effortless beauty', 76, true),
('Nora', 'girl', 'Latın', 'Latin', 'Şərəf, işıq, nur, alicənab', 'Şərəf, işıq, nur, alicənab', 'Honor, light, shining star', 75, true),
('Hazel', 'girl', 'İngilis', 'English', 'Fındıq ağacı, fındığı rəng, yaşıl-qonur', 'Fındıq ağacı, fındığı rəng, yaşıl-qonur', 'Hazelnut tree, greenish-brown color', 74, true),
('Aurora', 'girl', 'Latın', 'Latin', 'Şəfəq, dan ulduzu, sübh ilahəsi', 'Şəfəq, dan ulduzu, sübh ilahəsi', 'Dawn, morning goddess', 73, true),
('Audrey', 'girl', 'İngilis', 'English', 'Nəcib güc, alicənab qüvvət', 'Nəcib güc, alicənab qüvvət', 'Noble strength', 72, true),
('Stella', 'girl', 'Latın', 'Latin', 'Ulduz, səmavi işıq, dəniz ulduzu', 'Uduz, səmavi işıq, dəniz ulduzu', 'Star of the sea, celestial light', 71, true),
('Victoria', 'girl', 'Latın', 'Latin', 'Qələbə, qalib gələn, müzəffər', 'Qələbə, qalib gələn, müzəffər', 'Victory, conqueror', 70, true),
('Natalie', 'girl', 'Latın', 'Latin', 'Milad günü doğulmuş, mübarək doğum', 'Milad günü doğulmuş, mübarək doğum', 'Birthday of the Lord, Christmas', 70, true),
('Zoe', 'girl', 'Yunan', 'Greek', 'Həyat, canlılıq, parlaq enerji', 'Həyat, canlılıq, parlaq enerji', 'Life, vibrant energy', 70, true),
('Hannah', 'girl', 'İbrani', 'Hebrew', 'Lütf, mərhəmət, xeyirxahlıq, sevimli', 'Lütf, mərhəmət, xeyirxahlıq, sevimli', 'Favor, grace', 70, true),
('Lucy', 'girl', 'Latın', 'Latin', 'İşıq, parlaq, şəfəqdə doğulmuş', 'İşıq, parlaq, şəfəqdə doğulmuş', 'Light, shiny, born at dawn', 70, true),
('Violet', 'girl', 'Latın', 'Latin', 'Bənövşə, zərif çiçək, təvazökar gözəllik', 'Bənövşə, zərif çiçək, təvazökar gözəllik', 'Purple flower, modest beauty', 70, true),
('Claire', 'girl', 'Fransız', 'French', 'Aydın, parlaq, məşhur, təmiz', 'Aydın, parlaq, məşhur, təmiz', 'Clear, bright, famous', 70, true),
('Bella', 'girl', 'Latın', 'Latin', 'Gözəl, zərif, sevimli', 'Gözəl, zərif, sevimli', 'Beautiful, lovely', 70, true),
('Alice', 'girl', 'German', 'Germanic', 'Nəcib, alicənab, şərəfli', 'Nəcib, alicənab, şərəfli', 'Noble, honorable', 70, true),
('Samantha', 'girl', 'İbrani', 'Hebrew', 'Allahın buyurduğu, yaxşı dinləyici', 'Allahın buyurduğu, yaxşı dinləyici', 'Told by God, listener', 70, true),
('Caroline', 'girl', 'Fransız', 'French', 'Azad qadın, güclü, zərif', 'Azad qadın, güclü, zərif', 'Free woman, strong', 70, true),
('Genesis', 'girl', 'Yunan', 'Greek', 'Yaranış, mənşə, başlanğıc, doğuluş', 'Yaranış, mənşə, başlanğıc, doğuluş', 'Origin, birth, beginning', 70, true),
('Maya', 'girl', 'Yunan', 'Greek', 'Su, illüziya, sehr, möcüzə, ana', 'Su, illüziya, sehr, möcüzə, ana', 'Water, illusion, magic', 70, true),
('Madelyn', 'girl', 'Fransız', 'French', 'Uca qala, heyranedici, heyranedici məkan', 'Uca qala, heyranedici, heyranedici məkan', 'High tower, magnificent', 70, true),
('Sarah', 'girl', 'İbrani', 'Hebrew', 'Şahzadə, nəcabətli xanım, hökmdar', 'Şahzadə, nəcabətli xanım, hökmdar', 'Princess, noble lady', 70, true),
('Naomi', 'girl', 'İbrani', 'Hebrew', 'Xoşluq, şirinlik, gözəllik, lətafət', 'Xoşluq, şirinlik, gözəllik, lətafət', 'Pleasantness, sweetness', 70, true),
('Elena', 'girl', 'Yunan', 'Greek', 'Parlayan işıq, parlaq məşəl, nur', 'Parlayan işıq, parlaq məşəl, nur', 'Shining light, bright torch', 70, true),
('Ruby', 'girl', 'Latın', 'Latin', 'Yaqut, qiymətli qırmızı daş', 'Yaqut, qiymətli qırmızı daş', 'Red gemstone, precious jewel', 70, true),
('Hazel', 'girl', 'İngilis', 'English', 'Fındıq ağacı, fındığı rəng', 'Fındıq ağacı, fındığı rəng', 'Hazelnut tree, greenish-brown color', 70, true),
('Penelope', 'girl', 'Yunan', 'Greek', 'Sadiq və toxucu həyat yoldaşı', 'Sadiq və toxucu həyat yoldaşı', 'Weaver, faithful wife', 70, true),

-- ==================== UNISEX (50) ====================
('Avery', 'unisex', 'İngilis', 'English', 'Elflərin hökmdarı, müdrik məsləhətçi', 'Elflərin hökmdarı, müdrik məsləhətçi', 'Ruler of elves, wise advisor', 90, true),
('Riley', 'unisex', 'İrland', 'Irish', 'Cəsur, igid, qorxmaz, çəmənlik', 'Cəsur, igid, qorxmaz, çəmənlik', 'Courageous, valiant, clearing in the woods', 89, true),
('Jordan', 'unisex', 'İbrani', 'Hebrew', 'Aşağı axan, tarixi müqəddəs çay', 'Aşağı axan, tarixi müqəddəs çay', 'Flowing down, historical river', 88, true),
('Taylor', 'unisex', 'İngilis', 'English', 'Dərzi, parça kəsən, dəqiq', 'Dərzi, parça kəsən, dəqiq', 'Tailor, cutter of cloth', 87, true),
('Parker', 'unisex', 'İngilis', 'English', 'Park qoruyucusu, meşə gözətçisi', 'Park qoruyucusu, meşə gözətçisi', 'Park keeper, forest guardian', 86, true),
('Peyton', 'unisex', 'İngilis', 'English', 'Kral şəhəri, nəcib mülk, döyüşçü', 'Kral şəhəri, nəcib mülk, döyüşçü', 'Fighting man''s estate, royal town', 85, true),
('Quinn', 'unisex', 'İrland', 'Irish', 'Müdrik, ağıllı, lider, məsləhətçi', 'Müdrik, ağıllı, lider, məsləhətçi', 'Wise, intelligent, counsel, head', 84, true),
('Rowan', 'unisex', 'İrland', 'Irish', 'Qırmızısaç, quşarmudu ağacı, qorunma', 'Qırmızısaç, quşarmudu ağacı, qorunma', 'Red-haired, rowan tree, protection', 83, true),
('Logan', 'unisex', 'Şotland', 'Scottish', 'Kiçik dərə, dinc çəmənlik, sığınacaq', 'Kiçik dərə, dinc çəmənlik, sığınacaq', 'Little hollow, peaceful meadow', 82, true),
('Finley', 'unisex', 'Şotland', 'Scottish', 'Sarışın döyüşçü, qəhrəman lider, dürüst', 'Sarışın döyüşçü, qəhrəman lider, dürüst', 'Fair warrior, heroic leader', 81, true),
('Morgan', 'unisex', 'Uels', 'Welsh', 'Dəniz müdafiəçisi, dənizdən doğulmuş', 'Dəniz müdafiəçisi, dənizdən doğulmuş', 'Sea defender, born of the sea', 80, true),
('Alex', 'unisex', 'Yunan', 'Greek', 'İnsanların müdafiəçisi, köməkçi', 'İnsanların müdafiəçisi, köməkçi', 'Defender of men, helper', 79, true),
('Charlie', 'unisex', 'İngilis', 'English', 'Azad insan, səmimi, mehriban', 'Azad insan, səmimi, mehriban', 'Free man, friendly and cheerful', 78, true),
('Sam', 'unisex', 'İbrani', 'Hebrew', 'Allah eşitdi, yaxşı dinləyici', 'Allah eşitdi, yaxşı dinləyici', 'God has heard, listener', 77, true),
('Skyler', 'unisex', 'Holland', 'Dutch', 'Alim, qoruyucu sığınacaq, göy üzü', 'Alim, qoruyucu sığınacaq, göy üzü', 'Scholar, protective shelter, sky', 76, true),
('Sage', 'unisex', 'Latın', 'Latin', 'Müdrik insan, şəfalı ot, dinc', 'Müdrik insan, şəfalı ot, dinc', 'Wise one, healing herb', 75, true),
('River', 'unisex', 'İngilis', 'English', 'Axar su, çay, daimi yol, həyat', 'Axar su, çay, daimi yol, həyat', 'Flowing body of water, constant path', 74, true),
('Robin', 'unisex', 'İngilis', 'English', 'Parlaq şöhrət, şən quş, sevinc gətirən', 'Parlaq şöhrət, şən quş, sevinc gətirən', 'Bright fame, cheerful bird', 73, true),
('Reese', 'unisex', 'Uels', 'Welsh', 'Ehtiraslı, coşqun, alovlu, aktiv', 'Ehtiraslı, coşqun, alovlu, aktiv', 'Ardent, fiery, passionate', 72, true),
('Casey', 'unisex', 'İrland', 'Irish', 'Oyaq, cəsur, diqqətli, keşikçi', 'Oyaq, cəsur, diqqətli, keşikçi', 'Vigilant, brave, watchful', 71, true),
('Hayden', 'unisex', 'İngilis', 'English', 'Çəpərlənmiş dərə, ot sahəsi, sakit vadi', 'Çəpərlənmiş dərə, ot sahəsi, sakit vadi', 'Hedged valley, hay field', 70, true),
('Dakota', 'unisex', 'Yerli Amerika', 'Native American', 'Dost, müttəfiq, mehriban', 'Dost, müttəfiq, mehriban', 'Friendly, ally', 70, true),
('Phoenix', 'unisex', 'Yunan', 'Greek', 'Simurq quşu, yenidən doğulan, ölməz', 'Simurq quşu, yenidən doğulan, ölməz', 'Mythical bird, dark red, reborn', 70, true),
('Harley', 'unisex', 'İngilis', 'English', 'Dovşan çəmənliyi, geniş meşə, azad', 'Dovşan çəmənliyi, geniş meşə, azad', 'Hare''s meadow, spacious woods', 70, true),
('Dallas', 'unisex', 'Şotland', 'Scottish', 'Çəmənlikdəki yaşayış yerindən, dinc', 'Çəmənlikdəki yaşayış yerindən, dinc', 'From the meadow dwelling', 70, true),
('Emerson', 'unisex', 'German', 'Germanic', 'Emeri oğlu, çalışqan hökmdar, güclü', 'Emeri oğlu, çalışqan hökmdar, güclü', 'Son of Emery, industrious ruler', 70, true),
('Alexis', 'unisex', 'Yunan', 'Greek', 'Köməkçi, müdafiəçi, xilaskar', 'Köməkçi, müdafiəçi, xilaskar', 'Helper, defender', 70, true),
('Marley', 'unisex', 'İngilis', 'English', 'Dəniz kənarı xoş çəmənlik, fərəhli', 'Dəniz kənarı xoş çəmənlik, fərəhli', 'Pleasant seaside meadow', 70, true),
('Oakley', 'unisex', 'İngilis', 'English', 'Palıd ağacları çəmənliyi, möhkəm, dözümlü', 'Palıd ağacları çəmənliyi, möhkəm, dözümlü', 'Meadow of oak trees', 70, true),
('Remi', 'unisex', 'Fransız', 'French', 'Avarçəkən, dənizçi, səyyah', 'Avarçəkən, dənizçi, səyyah', 'Oarsman, rower', 70, true),
('Eden', 'unisex', 'İbrani', 'Hebrew', 'Həzz yeri, cənnət, sevinc məskəni', 'Həzz yeri, cənnət, sevinc məskəni', 'Place of pleasure, paradise', 70, true),
('Finley', 'unisex', 'İrland', 'Irish', 'Sarışın qəhrəman, cəsur döyüşçü', 'Sarışın qəhrəman, cəsur döyüşçü', 'Fair-haired hero', 70, true),
('Blake', 'unisex', 'İngilis', 'English', 'Sarışın və ya qaraşın, ziddiyyətli gözəllik', 'Sarışın və ya qaraşın, ziddiyyətli gözəllik', 'Fair-haired, dark, pale', 70, true),
('Sawyer', 'unisex', 'İngilis', 'English', 'Odunçu, mişarçı, zəhmətkeş', 'Odunçu, mişarçı, zəhmətkeş', 'Woodcutter, sawer of wood', 70, true),
('Jamie', 'unisex', 'Şotland', 'Scottish', 'Əvəzləyici, taxta çıxan, sadiq', 'Əvəzləyici, taxta çıxan, sadiq', 'Supplanter, replacement', 70, true),
('Shiloh', 'unisex', 'İbrani', 'Hebrew', 'Sakit, dinc, bol-bərəkətli, əmin-amanlıq', 'Sakit, dinc, bol-bərəkətli, əmin-amanlıq', 'Tranquil, peaceful, abundance', 70, true),
('Jesse', 'unisex', 'İbrani', 'Hebrew', 'Allahın hədiyyəsi, var-dövlət, töhfə', 'Allahın hədiyyəsi, var-dövlət, töhfə', 'God''s gift, wealth', 70, true),
('Rory', 'unisex', 'İrland', 'Irish', 'Qırmızı kral, coşqun lider, alovlu', 'Qırmızı kral, coşqun lider, alovlu', 'Red king, passionate leader', 70, true),
('Ellis', 'unisex', 'Uels', 'Welsh', 'Xeyirxah, rəhmli, mərhəmətli, nəcib', 'Xeyirxah, rəhmli, mərhəmətli, nəcib', 'Benevolent, kind, merciful', 70, true),
('Devon', 'unisex', 'Kelt', 'Celtic', 'Şair, dərin dərə sakini, yaradıcı', 'Şair, dərin dərə sakini, yaradıcı', 'Poet, deep valley dweller', 70, true),
('Aspen', 'unisex', 'İngilis', 'English', 'Titrək qovaq ağacı, təbiət, zərif', 'Titrək qovaq ağacı, təbiət, zərif', 'Quaking aspen tree, nature', 70, true),
('Kai', 'unisex', 'Havay', 'Hawaiian/Japanese', 'Dəniz, okean, balıqqulağı, azadlıq', 'Dəniz, okean, balıqqulağı, azadlıq', 'Sea, ocean, shell', 70, true),
('Milan', 'unisex', 'Slavyan', 'Slavic', 'Mehriban, sevən, nəcib, sevimli', 'Mehriban, sevən, nəcib, sevimli', 'Kind, loving, gracious', 70, true),
('Frankie', 'unisex', 'Latın', 'Latin', 'Azad, səmimi, doğruçu, azad insan', 'Azad, səmimi, doğruçu, azad insan', 'Free, truthful', 70, true),
('Tatum', 'unisex', 'İngilis', 'English', 'Şən, sevinc gətirən məskən, fərəhli', 'Şən, sevinc gətirən məskən, fərəhli', 'Tate''s homestead, cheerful bringer of joy', 70, true),
('Ariel', 'unisex', 'İbrani', 'Hebrew', 'Allahın aslanı, cəsur, güclü ruh', 'Allahın aslanı, cəsur, güclü ruh', 'Lion of God, courageous', 70, true),
('Brio', 'unisex', 'İtalyan', 'Italian', 'Canlılıq, coşqu, enerji, ruh yüksəkliyi', 'Canlılıq, coşqu, enerji, ruh yüksəkliyi', 'Vibrancy, vigor, high spirits', 70, true),
('Gale', 'unisex', 'İngilis', 'English', 'Şən, şənlik ruhu, fırtına, güc', 'Şən, şənlik ruhu, fırtına, güc', 'Cheerful, pleasant, strong wind', 70, true),
('Justice', 'unisex', 'Latın', 'Latin', 'Ədalət, dürüstlük, haqq', 'Ədalət, dürüstlük, haqq', 'Justice, fairness, righteousness', 70, true),
('Monroe', 'unisex', 'Kelt', 'Celtic', 'Rovanın ağzından, çay kənarı sakini', 'Rovanın ağzından, çay kənarı sakini', 'From the mouth of the Roe river', 70, true)
;
