-- Onboarding v2 (sual-əsaslı) UI açarları (ru/tr/en) — idempotent
INSERT INTO public.translations (key, lang, value, namespace) VALUES
  ('ponb2_subtitle', 'ru', 'Несколько коротких вопросов — всё будет настроено под вас', 'common'),
  ('ponb2_subtitle', 'tr', 'Birkaç kısa soru — her şey size göre kişiselleştirilecek', 'common'),
  ('ponb2_subtitle', 'en', 'A few quick questions — everything will be personalized for you', 'common'),
  ('ponb2_takes_minute', 'ru', 'Займёт всего 1 минуту', 'common'),
  ('ponb2_takes_minute', 'tr', 'Sadece 1 dakika sürer', 'common'),
  ('ponb2_takes_minute', 'en', 'Takes just 1 minute', 'common'),
  ('ponb2_multiples_title', 'ru', 'Сколько малышей вы ожидаете?', 'common'),
  ('ponb2_multiples_title', 'tr', 'Kaç bebek bekliyorsunuz?', 'common'),
  ('ponb2_multiples_title', 'en', 'How many babies are you expecting?', 'common'),
  ('ponb2_multiples_sub', 'ru', 'Гиды и группы сообщества подбираются соответственно', 'common'),
  ('ponb2_multiples_sub', 'tr', 'Rehberler ve topluluk grupları buna göre seçilir', 'common'),
  ('ponb2_multiples_sub', 'en', 'Guides and community groups are chosen accordingly', 'common'),
  ('ponb2_multiples_single', 'ru', 'Один малыш', 'common'),
  ('ponb2_multiples_single', 'tr', 'Tek bebek', 'common'),
  ('ponb2_multiples_single', 'en', 'One baby', 'common'),
  ('ponb2_multiples_twins', 'ru', 'Двойня', 'common'),
  ('ponb2_multiples_twins', 'tr', 'İkiz', 'common'),
  ('ponb2_multiples_twins', 'en', 'Twins', 'common'),
  ('ponb2_multiples_triplets', 'ru', 'Тройня или больше', 'common'),
  ('ponb2_multiples_triplets', 'tr', 'Üçüz veya daha fazla', 'common'),
  ('ponb2_multiples_triplets', 'en', 'Triplets or more', 'common'),
  ('ponb2_firstpreg_title', 'ru', 'Это ваша первая беременность?', 'common'),
  ('ponb2_firstpreg_title', 'tr', 'Bu ilk hamileliğiniz mi?', 'common'),
  ('ponb2_firstpreg_title', 'en', 'Is this your first pregnancy?', 'common'),
  ('ponb2_firstpreg_sub', 'ru', 'Контент адаптируется к вашему опыту', 'common'),
  ('ponb2_firstpreg_sub', 'tr', 'İçerik deneyiminize göre uyarlanır', 'common'),
  ('ponb2_firstpreg_sub', 'en', 'Content adapts to your experience', 'common'),
  ('ponb2_firstpreg_yes', 'ru', 'Да, впервые', 'common'),
  ('ponb2_firstpreg_yes', 'tr', 'Evet, ilk kez', 'common'),
  ('ponb2_firstpreg_yes', 'en', 'Yes, first time', 'common'),
  ('ponb2_firstpreg_no', 'ru', 'Нет, у меня есть опыт', 'common'),
  ('ponb2_firstpreg_no', 'tr', 'Hayır, deneyimim var', 'common'),
  ('ponb2_firstpreg_no', 'en', 'No, I have experience', 'common'),
  ('ponb2_feeding_title', 'ru', 'Как питается ваш малыш?', 'common'),
  ('ponb2_feeding_title', 'tr', 'Bebeğiniz nasıl besleniyor?', 'common'),
  ('ponb2_feeding_title', 'en', 'How is your baby fed?', 'common'),
  ('ponb2_feeding_sub', 'ru', 'Трекер кормления настраивается соответственно', 'common'),
  ('ponb2_feeding_sub', 'tr', 'Beslenme takibi buna göre kurulur', 'common'),
  ('ponb2_feeding_sub', 'en', 'The feeding tracker is set up accordingly', 'common'),
  ('ponb2_feeding_breast', 'ru', 'Грудное вскармливание', 'common'),
  ('ponb2_feeding_breast', 'tr', 'Anne sütü', 'common'),
  ('ponb2_feeding_breast', 'en', 'Breastfeeding', 'common'),
  ('ponb2_feeding_formula', 'ru', 'Смесь', 'common'),
  ('ponb2_feeding_formula', 'tr', 'Mama', 'common'),
  ('ponb2_feeding_formula', 'en', 'Formula', 'common'),
  ('ponb2_feeding_mixed', 'ru', 'Смешанное', 'common'),
  ('ponb2_feeding_mixed', 'tr', 'Karışık', 'common'),
  ('ponb2_feeding_mixed', 'en', 'Mixed', 'common'),
  ('ponb2_feeding_solid', 'ru', 'На прикорме', 'common'),
  ('ponb2_feeding_solid', 'tr', 'Ek gıdaya geçti', 'common'),
  ('ponb2_feeding_solid', 'en', 'On solids', 'common'),
  ('ponb2_nightwakes_title', 'ru', 'Как часто малыш просыпается ночью?', 'common'),
  ('ponb2_nightwakes_title', 'tr', 'Bebeğiniz gece kaç kez uyanıyor?', 'common'),
  ('ponb2_nightwakes_title', 'en', 'How often does your baby wake at night?', 'common'),
  ('ponb2_nightwakes_sub', 'ru', 'Советы по сну персонализируются соответственно', 'common'),
  ('ponb2_nightwakes_sub', 'tr', 'Uyku önerileri buna göre kişiselleştirilir', 'common'),
  ('ponb2_nightwakes_sub', 'en', 'Sleep advice is personalized accordingly', 'common'),
  ('ponb2_nightwakes_rare', 'ru', '0-1 раз', 'common'),
  ('ponb2_nightwakes_rare', 'tr', '0-1 kez', 'common'),
  ('ponb2_nightwakes_rare', 'en', '0-1 times', 'common'),
  ('ponb2_nightwakes_sometimes', 'ru', '2-3 раза', 'common'),
  ('ponb2_nightwakes_sometimes', 'tr', '2-3 kez', 'common'),
  ('ponb2_nightwakes_sometimes', 'en', '2-3 times', 'common'),
  ('ponb2_nightwakes_often', 'ru', '4+ раз', 'common'),
  ('ponb2_nightwakes_often', 'tr', '4+ kez', 'common'),
  ('ponb2_nightwakes_often', 'en', '4+ times', 'common'),
  ('ponb2_nightwakes_varies', 'ru', 'Каждую ночь по-разному', 'common'),
  ('ponb2_nightwakes_varies', 'tr', 'Her gece farklı', 'common'),
  ('ponb2_nightwakes_varies', 'en', 'Varies every night', 'common'),
  ('ponb2_goal_title', 'ru', 'Какова ваша главная цель?', 'common'),
  ('ponb2_goal_title', 'tr', 'Ana hedefiniz nedir?', 'common'),
  ('ponb2_goal_title', 'en', 'What is your main goal?', 'common'),
  ('ponb2_goal_sub', 'ru', 'Прогнозы и советы строятся соответственно', 'common'),
  ('ponb2_goal_sub', 'tr', 'Tahminler ve öneriler buna göre kurulur', 'common'),
  ('ponb2_goal_sub', 'en', 'Predictions and advice are built accordingly', 'common'),
  ('ponb2_goal_track', 'ru', 'Отслеживать менструацию', 'common'),
  ('ponb2_goal_track', 'tr', 'Reglimi takip etmek', 'common'),
  ('ponb2_goal_track', 'en', 'Track my period', 'common'),
  ('ponb2_goal_conceive', 'ru', 'Хочу забеременеть', 'common'),
  ('ponb2_goal_conceive', 'tr', 'Hamile kalmak istiyorum', 'common'),
  ('ponb2_goal_conceive', 'en', 'I want to get pregnant', 'common'),
  ('ponb2_goal_health', 'ru', 'Понять своё здоровье', 'common'),
  ('ponb2_goal_health', 'tr', 'Sağlığımı anlamak', 'common'),
  ('ponb2_goal_health', 'en', 'Understand my health', 'common'),
  ('ponb2_goal_symptoms', 'ru', 'Управлять симптомами', 'common'),
  ('ponb2_goal_symptoms', 'tr', 'Semptomlarımı yönetmek', 'common'),
  ('ponb2_goal_symptoms', 'en', 'Manage my symptoms', 'common'),
  ('ponb2_regularity_title', 'ru', 'Ваш цикл регулярный?', 'common'),
  ('ponb2_regularity_title', 'tr', 'Döngünüz düzenli mi?', 'common'),
  ('ponb2_regularity_title', 'en', 'Is your cycle regular?', 'common'),
  ('ponb2_regularity_sub', 'ru', 'Точность прогнозов настраивается соответственно', 'common'),
  ('ponb2_regularity_sub', 'tr', 'Tahmin doğruluğu buna göre ayarlanır', 'common'),
  ('ponb2_regularity_sub', 'en', 'Prediction accuracy is tuned accordingly', 'common'),
  ('ponb2_regularity_yes', 'ru', 'Да, регулярный', 'common'),
  ('ponb2_regularity_yes', 'tr', 'Evet, düzenli', 'common'),
  ('ponb2_regularity_yes', 'en', 'Yes, regular', 'common'),
  ('ponb2_regularity_no', 'ru', 'Нерегулярный', 'common'),
  ('ponb2_regularity_no', 'tr', 'Düzensiz', 'common'),
  ('ponb2_regularity_no', 'en', 'Irregular', 'common'),
  ('ponb2_regularity_unsure', 'ru', 'Не уверена', 'common'),
  ('ponb2_regularity_unsure', 'tr', 'Emin değilim', 'common'),
  ('ponb2_regularity_unsure', 'en', 'Not sure', 'common'),
  ('ponb2_bsymptoms_title', 'ru', 'Что вас беспокоит сейчас?', 'common'),
  ('ponb2_bsymptoms_title', 'tr', 'Şu anda sizi ne rahatsız ediyor?', 'common'),
  ('ponb2_bsymptoms_title', 'en', 'What bothers you right now?', 'common'),
  ('ponb2_bsymptoms_sub', 'ru', 'Можно выбрать несколько', 'common'),
  ('ponb2_bsymptoms_sub', 'tr', 'Birkaçını seçebilirsiniz', 'common'),
  ('ponb2_bsymptoms_sub', 'en', 'You can select several', 'common'),
  ('ponb2_bsym_nausea', 'ru', 'Тошнота', 'common'),
  ('ponb2_bsym_nausea', 'tr', 'Bulantı', 'common'),
  ('ponb2_bsym_nausea', 'en', 'Nausea', 'common'),
  ('ponb2_bsym_fatigue', 'ru', 'Усталость', 'common'),
  ('ponb2_bsym_fatigue', 'tr', 'Yorgunluk', 'common'),
  ('ponb2_bsym_fatigue', 'en', 'Fatigue', 'common'),
  ('ponb2_bsym_backpain', 'ru', 'Боль в спине', 'common'),
  ('ponb2_bsym_backpain', 'tr', 'Bel ağrısı', 'common'),
  ('ponb2_bsym_backpain', 'en', 'Back pain', 'common'),
  ('ponb2_bsym_insomnia', 'ru', 'Бессонница', 'common'),
  ('ponb2_bsym_insomnia', 'tr', 'Uykusuzluk', 'common'),
  ('ponb2_bsym_insomnia', 'en', 'Insomnia', 'common'),
  ('ponb2_bsym_heartburn', 'ru', 'Изжога', 'common'),
  ('ponb2_bsym_heartburn', 'tr', 'Mide yanması', 'common'),
  ('ponb2_bsym_heartburn', 'en', 'Heartburn', 'common'),
  ('ponb2_bsym_swelling', 'ru', 'Отёки', 'common'),
  ('ponb2_bsym_swelling', 'tr', 'Şişlik', 'common'),
  ('ponb2_bsym_swelling', 'en', 'Swelling', 'common'),
  ('ponb2_sym_none', 'ru', 'Ничего', 'common'),
  ('ponb2_sym_none', 'tr', 'Hiçbiri', 'common'),
  ('ponb2_sym_none', 'en', 'None', 'common'),
  ('ponb2_binterests_title', 'ru', 'Что вам интереснее всего?', 'common'),
  ('ponb2_binterests_title', 'tr', 'En çok ne ilginizi çekiyor?', 'common'),
  ('ponb2_binterests_title', 'en', 'What interests you most?', 'common'),
  ('ponb2_binterests_sub', 'ru', 'Ваш главный экран будет построен соответственно', 'common'),
  ('ponb2_binterests_sub', 'tr', 'Ana sayfanız buna göre kurulacak', 'common'),
  ('ponb2_binterests_sub', 'en', 'Your home screen will be built accordingly', 'common'),
  ('ponb2_bint_development', 'ru', 'Развитие малыша', 'common'),
  ('ponb2_bint_development', 'tr', 'Bebeğin gelişimi', 'common'),
  ('ponb2_bint_development', 'en', 'Baby''s development', 'common'),
  ('ponb2_bint_nutrition', 'ru', 'Питание', 'common'),
  ('ponb2_bint_nutrition', 'tr', 'Beslenme', 'common'),
  ('ponb2_bint_nutrition', 'en', 'Nutrition', 'common'),
  ('ponb2_bint_exercise', 'ru', 'Упражнения для беременных', 'common'),
  ('ponb2_bint_exercise', 'tr', 'Hamilelik egzersizleri', 'common'),
  ('ponb2_bint_exercise', 'en', 'Pregnancy exercises', 'common'),
  ('ponb2_bint_birthprep', 'ru', 'Подготовка к родам', 'common'),
  ('ponb2_bint_birthprep', 'tr', 'Doğuma hazırlık', 'common'),
  ('ponb2_bint_birthprep', 'en', 'Birth preparation', 'common'),
  ('ponb2_bint_names', 'ru', 'Имена для малыша', 'common'),
  ('ponb2_bint_names', 'tr', 'Bebek isimleri', 'common'),
  ('ponb2_bint_names', 'en', 'Baby names', 'common'),
  ('ponb2_bint_shopping', 'ru', 'Список покупок', 'common'),
  ('ponb2_bint_shopping', 'tr', 'Alışveriş listesi', 'common'),
  ('ponb2_bint_shopping', 'en', 'Shopping list', 'common'),
  ('ponb2_minterests_title', 'ru', 'Что вам нужнее всего?', 'common'),
  ('ponb2_minterests_title', 'tr', 'En çok neye ihtiyacınız var?', 'common'),
  ('ponb2_minterests_title', 'en', 'What do you need most?', 'common'),
  ('ponb2_minterests_sub', 'ru', 'Ваш главный экран будет построен соответственно', 'common'),
  ('ponb2_minterests_sub', 'tr', 'Ana sayfanız buna göre kurulacak', 'common'),
  ('ponb2_minterests_sub', 'en', 'Your home screen will be built accordingly', 'common'),
  ('ponb2_mint_sleep', 'ru', 'Режим сна', 'common'),
  ('ponb2_mint_sleep', 'tr', 'Uyku düzeni', 'common'),
  ('ponb2_mint_sleep', 'en', 'Sleep schedule', 'common'),
  ('ponb2_mint_feeding', 'ru', 'Трекер кормления', 'common'),
  ('ponb2_mint_feeding', 'tr', 'Beslenme takibi', 'common'),
  ('ponb2_mint_feeding', 'en', 'Feeding tracking', 'common'),
  ('ponb2_mint_milestones', 'ru', 'Этапы развития', 'common'),
  ('ponb2_mint_milestones', 'tr', 'Gelişim aşamaları', 'common'),
  ('ponb2_mint_milestones', 'en', 'Milestones', 'common'),
  ('ponb2_mint_vaccines', 'ru', 'Календарь прививок', 'common'),
  ('ponb2_mint_vaccines', 'tr', 'Aşı takvimi', 'common'),
  ('ponb2_mint_vaccines', 'en', 'Vaccine schedule', 'common'),
  ('ponb2_mint_teething', 'ru', 'Прорезывание зубов', 'common'),
  ('ponb2_mint_teething', 'tr', 'Diş çıkarma', 'common'),
  ('ponb2_mint_teething', 'en', 'Teething', 'common'),
  ('ponb2_mint_games', 'ru', 'Игры по возрасту', 'common'),
  ('ponb2_mint_games', 'tr', 'Yaşa uygun oyunlar', 'common'),
  ('ponb2_mint_games', 'en', 'Age-appropriate games', 'common'),
  ('ponb2_fsymptoms_title', 'ru', 'Что вы испытываете во время менструации?', 'common'),
  ('ponb2_fsymptoms_title', 'tr', 'Regl döneminde neler yaşıyorsunuz?', 'common'),
  ('ponb2_fsymptoms_title', 'en', 'What do you experience during your period?', 'common'),
  ('ponb2_fsymptoms_sub', 'ru', 'Можно выбрать несколько', 'common'),
  ('ponb2_fsymptoms_sub', 'tr', 'Birkaçını seçebilirsiniz', 'common'),
  ('ponb2_fsymptoms_sub', 'en', 'You can select several', 'common'),
  ('ponb2_fsym_cramps', 'ru', 'Спазмы / боль', 'common'),
  ('ponb2_fsym_cramps', 'tr', 'Kramp / ağrı', 'common'),
  ('ponb2_fsym_cramps', 'en', 'Cramps / pain', 'common'),
  ('ponb2_fsym_mood', 'ru', 'Перепады настроения', 'common'),
  ('ponb2_fsym_mood', 'tr', 'Ruh hali değişimi', 'common'),
  ('ponb2_fsym_mood', 'en', 'Mood changes', 'common'),
  ('ponb2_fsym_bloating', 'ru', 'Вздутие', 'common'),
  ('ponb2_fsym_bloating', 'tr', 'Şişkinlik', 'common'),
  ('ponb2_fsym_bloating', 'en', 'Bloating', 'common'),
  ('ponb2_fsym_headache', 'ru', 'Головная боль', 'common'),
  ('ponb2_fsym_headache', 'tr', 'Baş ağrısı', 'common'),
  ('ponb2_fsym_headache', 'en', 'Headache', 'common'),
  ('ponb2_fsym_acne', 'ru', 'Проблемы с кожей', 'common'),
  ('ponb2_fsym_acne', 'tr', 'Cilt sorunları', 'common'),
  ('ponb2_fsym_acne', 'en', 'Skin problems', 'common'),
  ('ponb2_name_title', 'ru', 'Как зовут вашего малыша?', 'common'),
  ('ponb2_name_title', 'tr', 'Bebeğinizin adı ne?', 'common'),
  ('ponb2_name_title', 'en', 'What is your baby''s name?', 'common'),
  ('ponb2_name_sub', 'ru', 'Весь гид будет обращаться по имени', 'common'),
  ('ponb2_name_sub', 'tr', 'Tüm rehber onun adıyla konuşacak', 'common'),
  ('ponb2_name_sub', 'en', 'The whole guide will speak using their name', 'common'),
  ('ponb2_gender_title', 'ru', '{name} — девочка или мальчик?', 'common'),
  ('ponb2_gender_title', 'tr', '{name} — kız mı, erkek mi?', 'common'),
  ('ponb2_gender_title', 'en', '{name} — girl or boy?', 'common'),
  ('ponb2_gender_title_noname', 'ru', 'Девочка или мальчик?', 'common'),
  ('ponb2_gender_title_noname', 'tr', 'Kız mı, erkek mi?', 'common'),
  ('ponb2_gender_title_noname', 'en', 'Girl or boy?', 'common'),
  ('ponb2_birth_title', 'ru', 'Когда родился(ась) {name}?', 'common'),
  ('ponb2_birth_title', 'tr', '{name} ne zaman doğdu?', 'common'),
  ('ponb2_birth_title', 'en', 'When was {name} born?', 'common'),
  ('ponb2_birth_baby', 'ru', 'Ваш малыш', 'common'),
  ('ponb2_birth_baby', 'tr', 'Bebeğiniz', 'common'),
  ('ponb2_birth_baby', 'en', 'Your baby', 'common'),
  ('ponb2_cycle_title', 'ru', 'Параметры вашего цикла', 'common'),
  ('ponb2_cycle_title', 'tr', 'Döngü ayarlarınız', 'common'),
  ('ponb2_cycle_title', 'en', 'Your cycle settings', 'common'),
  ('ponb2_cycle_sub', 'ru', 'Если не уверены, оставьте как есть — со временем уточнится', 'common'),
  ('ponb2_cycle_sub', 'tr', 'Emin değilseniz olduğu gibi bırakın — zamanla netleşecek', 'common'),
  ('ponb2_cycle_sub', 'en', 'If unsure, keep as is — it''ll refine over time', 'common'),
  ('ponb2_notif_title', 'ru', 'Ничего не пропустите', 'common'),
  ('ponb2_notif_title', 'tr', 'Hiçbir şeyi kaçırmayın', 'common'),
  ('ponb2_notif_title', 'en', 'Don''t miss anything', 'common'),
  ('ponb2_notif_sub_bump', 'ru', 'Еженедельные новости развития, напоминания о воде и витаминах', 'common'),
  ('ponb2_notif_sub_bump', 'tr', 'Haftalık gelişim haberleri, su ve vitamin hatırlatmaları', 'common'),
  ('ponb2_notif_sub_bump', 'en', 'Weekly development updates, water and vitamin reminders', 'common'),
  ('ponb2_notif_sub_mommy', 'ru', 'Ежедневные советы по развитию, напоминания о прививках и уходе', 'common'),
  ('ponb2_notif_sub_mommy', 'tr', 'Günlük gelişim önerileri, aşı ve bakım hatırlatmaları', 'common'),
  ('ponb2_notif_sub_mommy', 'en', 'Daily development tips, vaccine and care reminders', 'common'),
  ('ponb2_notif_sub_flow', 'ru', 'Оповещения о приближении менструации и днях овуляции', 'common'),
  ('ponb2_notif_sub_flow', 'tr', 'Regl yaklaşırken ve yumurtlama günlerinde uyarı', 'common'),
  ('ponb2_notif_sub_flow', 'en', 'Alerts when your period is near and on ovulation days', 'common'),
  ('ponb2_notif_b1', 'ru', 'Ежедневные персональные советы', 'common'),
  ('ponb2_notif_b1', 'tr', 'Günlük kişisel öneriler', 'common'),
  ('ponb2_notif_b1', 'en', 'Daily personalized tips', 'common'),
  ('ponb2_notif_b1_flow', 'ru', 'Оповещение за 2 дня до менструации', 'common'),
  ('ponb2_notif_b1_flow', 'tr', 'Regl 2 gün kala uyarı', 'common'),
  ('ponb2_notif_b1_flow', 'en', 'Alert 2 days before your period', 'common'),
  ('ponb2_notif_b2', 'ru', 'Напоминания о воде и витаминах', 'common'),
  ('ponb2_notif_b2', 'tr', 'Su ve vitamin hatırlatmaları', 'common'),
  ('ponb2_notif_b2', 'en', 'Water and vitamin reminders', 'common'),
  ('ponb2_notif_b3', 'ru', 'Уведомления о важных этапах', 'common'),
  ('ponb2_notif_b3', 'tr', 'Önemli aşama bildirimleri', 'common'),
  ('ponb2_notif_b3', 'en', 'Important milestone alerts', 'common'),
  ('ponb2_notif_allow', 'ru', 'Разрешить уведомления', 'common'),
  ('ponb2_notif_allow', 'tr', 'Bildirimlere izin ver', 'common'),
  ('ponb2_notif_allow', 'en', 'Allow notifications', 'common'),
  ('ponb2_notif_skip', 'ru', 'Не сейчас', 'common'),
  ('ponb2_notif_skip', 'tr', 'Şimdi değil', 'common'),
  ('ponb2_notif_skip', 'en', 'Not now', 'common')
ON CONFLICT (key, lang) DO NOTHING;
